### PR TITLE
HBASE-24148 Upgrade Thrift to 0.13.0: 0.12.0 has outstanding CVEs.

### PR DESCRIPTION
**Pull request by apurtell**
Backport for branch-1

### CODE REVIEW

**Comment by apurtell** [comment]
I need to add an exclusion to libthrift to fix an assembly enforcer error. Pushing an update in a sec.

**Comment by apurtell** [comment]
Local results FWIW

    [INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] Running org.apache.hadoop.hbase.thrift2.TestThriftHBaseServiceHandlerWithReadOnly
    [INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.724 s - in org.apache.hadoop.hbase.thrift2.TestThriftHBaseServiceHandlerWithReadOnly
    [INFO] Running org.apache.hadoop.hbase.thrift2.TestThriftHBaseServiceHandler
    [INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 48.375 s - in org.apache.hadoop.hbase.thrift2.TestThriftHBaseServiceHandler
    [INFO] Running org.apache.hadoop.hbase.thrift2.TestThriftHBaseServiceHandlerWithLabels
    [INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.408 s - in org.apache.hadoop.hbase.thrift2.TestThriftHBaseServiceHandlerWithLabels
    [INFO] Running org.apache.hadoop.hbase.thrift.TestCallQueue
    [INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.212 s - in org.apache.hadoop.hbase.thrift.TestCallQueue
    [INFO] Running org.apache.hadoop.hbase.thrift.TestThriftHttpServer
    [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.943 s - in org.apache.hadoop.hbase.thrift.TestThriftHttpServer
    [INFO] Running org.apache.hadoop.hbase.thrift.TestThriftServer
    [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 80.47 s - in org.apache.hadoop.hbase.thrift.TestThriftServer
    [INFO] Running org.apache.hadoop.hbase.thrift.TestThriftServerCmdLine
    [INFO] Tests run: 32, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 51.129 s - in org.apache.hadoop.hbase.thrift.TestThriftServerCmdLine
    [INFO] 
    [INFO] Results:
    [INFO] 
    [INFO] Tests run: 110, Failures: 0, Errors: 0, Skipped: 0

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 50s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 49s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 51s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 44s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  compile  |   1m 44s |  branch-1 passed with JDK v1.7.0_252  |
| +1 :green_heart: |  checkstyle  |   5m 39s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  3s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 39s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   5m 12s |  branch-1 passed with JDK v1.7.0_252  |
| +0 :ok: |  spotbugs  |   1m 30s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |  10m 39s |  root in branch-1 has 1 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 39s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javac  |   1m 39s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 44s |  the patch passed with JDK v1.7.0_252  |
| -1 :x: |  javac  |   1m 44s |  root-jdk1.7.0_252 with JDK v1.7.0_252 generated 116 new + 38 unchanged - 0 fixed = 154 total (was 38)  |
| +1 :green_heart: |  checkstyle  |   0m 30s |  hbase-thrift: The patch generated 0 new + 38 unchanged - 1 fixed = 38 total (was 39)  |
| +1 :green_heart: |  checkstyle  |   4m 56s |  root: The patch generated 0 new + 38 unchanged - 1 fixed = 38 total (was 39)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 2 ill-formed XML file(s).  |
| +1 :green_heart: |  shadedjars  |   2m 44s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 54s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   2m 30s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   5m 18s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  findbugs  |  12m 33s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 168m 12s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m  0s |  The patch does not generate ASF License warnings.  |
|  |   | 255m 24s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | hbase-thrift/pom.xml |
|   | pom.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1533 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile spotbugs findbugs hbaseanti checkstyle |
| uname | Linux a6f8a89504c4 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1533/out/precommit/personality/provided.sh |
| git revision | branch-1 / d4b64c2 |
| Default Java | 1.7.0_252 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_242 /usr/lib/jvm/zulu-7-amd64:1.7.0_252 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/1/artifact/out/branch-findbugs-root-warnings.html |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/1/artifact/out/diff-compile-javac-root-jdk1.7.0_252.txt |
| xml | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/1/artifact/out/xml.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/1/testReport/ |
| Max. process+thread count | 4289 (vs. ulimit of 10000) |
| modules | C: hbase-thrift . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 39s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m  3s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 26s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 39s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  compile  |   1m 45s |  branch-1 passed with JDK v1.7.0_252  |
| +1 :green_heart: |  checkstyle  |   5m 34s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   2m 54s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 37s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   5m  5s |  branch-1 passed with JDK v1.7.0_252  |
| +0 :ok: |  spotbugs  |   1m 28s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |  10m 36s |  root in branch-1 has 1 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 29s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 41s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javac  |   1m 41s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 41s |  the patch passed with JDK v1.7.0_252  |
| -1 :x: |  javac  |   1m 41s |  root-jdk1.7.0_252 with JDK v1.7.0_252 generated 116 new + 38 unchanged - 0 fixed = 154 total (was 38)  |
| +1 :green_heart: |  checkstyle  |   0m 29s |  hbase-thrift: The patch generated 0 new + 38 unchanged - 1 fixed = 38 total (was 39)  |
| +1 :green_heart: |  checkstyle  |   5m  9s |  root: The patch generated 0 new + 38 unchanged - 1 fixed = 38 total (was 39)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 4 line(s) with tabs.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 2 ill-formed XML file(s).  |
| +1 :green_heart: |  shadedjars  |   2m 49s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   5m  4s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   2m 31s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   5m 11s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  findbugs  |  12m 37s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 174m 25s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 54s |  The patch does not generate ASF License warnings.  |
|  |   | 261m 48s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | hbase-thrift/pom.xml |
|   | pom.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1533 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile spotbugs findbugs hbaseanti checkstyle |
| uname | Linux 3bdb84911ac4 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1533/out/precommit/personality/provided.sh |
| git revision | branch-1 / d4b64c2 |
| Default Java | 1.7.0_252 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_242 /usr/lib/jvm/zulu-7-amd64:1.7.0_252 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/2/artifact/out/branch-findbugs-root-warnings.html |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/2/artifact/out/diff-compile-javac-root-jdk1.7.0_252.txt |
| whitespace | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/2/artifact/out/whitespace-tabs.txt |
| xml | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/2/artifact/out/xml.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/2/testReport/ |
| Max. process+thread count | 4302 (vs. ulimit of 10000) |
| modules | C: hbase-thrift . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1533/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
