### PR TITLE
HBASE-8458 Support for batch version of checkAndPut() and checkAndDel…

### PR DESCRIPTION
**Pull request by guangxuCheng**
…ete()

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   2m  3s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| :blue_heart: |  prototool  |   0m  0s |  prototool was not available.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 35s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 13s |  master passed  |
| :green_heart: |  compile  |   2m  0s |  master passed  |
| :green_heart: |  checkstyle  |   2m  7s |  master passed  |
| :green_heart: |  shadedjars  |   4m 50s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   1m 15s |  master passed  |
| :blue_heart: |  spotbugs  |   4m 21s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   8m  6s |  master passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   4m 57s |  the patch passed  |
| :green_heart: |  compile  |   2m  1s |  the patch passed  |
| :green_heart: |  cc  |   2m  1s |  the patch passed  |
| :green_heart: |  javac  |   2m  1s |  the patch passed  |
| :broken_heart: |  checkstyle  |   0m 38s |  hbase-client: The patch generated 2 new + 305 unchanged - 0 fixed = 307 total (was 305)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   4m 33s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  16m  1s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  hbaseprotoc  |   1m 55s |  the patch passed  |
| :green_heart: |  javadoc  |   1m 13s |  the patch passed  |
| :broken_heart: |  findbugs  |   1m 16s |  hbase-client generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
||| _ Other Tests _ |
| :green_heart: |  unit  |   0m 40s |  hbase-protocol-shaded in the patch passed.  |
| :green_heart: |  unit  |   1m 59s |  hbase-client in the patch passed.  |
| :green_heart: |  unit  | 158m 53s |  hbase-server in the patch passed.  |
| :green_heart: |  asflicense  |   1m 37s |  The patch does not generate ASF License warnings.  |
|  |   | 237m 33s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-client |
|  |  org.apache.hadoop.hbase.client.CheckAndRowMutate defines compareTo(Object) and uses Object.equals()  At CheckAndRowMutate.java:Object.equals()  At CheckAndRowMutate.java:[line 30] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/765 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 5933afbe74f0 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-765/out/precommit/personality/provided.sh |
| git revision | master / d7deafa120 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/1/artifact/out/diff-checkstyle-hbase-client.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/1/artifact/out/new-findbugs-hbase-client.html |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/1/testReport/ |
| Max. process+thread count | 4857 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 35s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :blue_heart: |  prototool  |   0m  0s |  prototool was not available.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 36s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 12s |  master passed  |
| :green_heart: |  compile  |   2m  0s |  master passed  |
| :green_heart: |  checkstyle  |   2m 11s |  master passed  |
| :green_heart: |  shadedjars  |   4m 36s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   1m 13s |  master passed  |
| :blue_heart: |  spotbugs  |   4m  5s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   7m 48s |  master passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   4m 54s |  the patch passed  |
| :green_heart: |  compile  |   2m  1s |  the patch passed  |
| :green_heart: |  cc  |   2m  1s |  the patch passed  |
| :green_heart: |  javac  |   2m  1s |  the patch passed  |
| :broken_heart: |  checkstyle  |   0m 41s |  hbase-client: The patch generated 1 new + 305 unchanged - 0 fixed = 306 total (was 305)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   4m 34s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  15m 34s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  hbaseprotoc  |   1m 55s |  the patch passed  |
| :green_heart: |  javadoc  |   1m 13s |  the patch passed  |
| :green_heart: |  findbugs  |   8m  4s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  |   0m 41s |  hbase-protocol-shaded in the patch passed.  |
| :green_heart: |  unit  |   1m 59s |  hbase-client in the patch passed.  |
| :green_heart: |  unit  | 158m 57s |  hbase-server in the patch passed.  |
| :green_heart: |  asflicense  |   1m 38s |  The patch does not generate ASF License warnings.  |
|  |   | 235m  8s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/765 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 81b52603cc61 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-765/out/precommit/personality/provided.sh |
| git revision | master / 4c75485f11 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/2/artifact/out/diff-checkstyle-hbase-client.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/2/testReport/ |
| Max. process+thread count | 4804 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 33s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :blue_heart: |  prototool  |   0m  1s |  prototool was not available.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 36s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 16s |  master passed  |
| :green_heart: |  compile  |   1m 59s |  master passed  |
| :green_heart: |  checkstyle  |   2m 12s |  master passed  |
| :green_heart: |  shadedjars  |   4m 36s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   1m 14s |  master passed  |
| :blue_heart: |  spotbugs  |   3m 59s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   7m 31s |  master passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 14s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   4m 54s |  the patch passed  |
| :green_heart: |  compile  |   2m  0s |  the patch passed  |
| :green_heart: |  cc  |   2m  0s |  the patch passed  |
| :green_heart: |  javac  |   2m  0s |  the patch passed  |
| :green_heart: |  checkstyle  |   2m 11s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   4m 31s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  15m 49s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  hbaseprotoc  |   1m 55s |  the patch passed  |
| :green_heart: |  javadoc  |   1m 14s |  the patch passed  |
| :green_heart: |  findbugs  |   8m  2s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  |   0m 41s |  hbase-protocol-shaded in the patch passed.  |
| :green_heart: |  unit  |   1m 56s |  hbase-client in the patch passed.  |
| :broken_heart: |  unit  | 161m 47s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   1m 38s |  The patch does not generate ASF License warnings.  |
|  |   | 237m 47s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.TestOpenSeqNumUnexpectedIncrease |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/765 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 1d61cde40ce4 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-765/out/precommit/personality/provided.sh |
| git revision | master / a881678ef4 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/3/testReport/ |
| Max. process+thread count | 4836 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-765/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
@guangxuCheng Can you please resolve the conflict. Is #594 still needed if this one gets merged and backported?

**Pull request closed without merging**
