### PR TITLE
HBASE-24013 Bump branch-2 version to 2.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by ndimiduk**
Increment version in poms with

```
$ mvn org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=2.4.0-SNAPSHOT -DgenerateBackupPoms=false
```

Verified no dangling references with

```
$ find . -iname '*pom.xml' -exec grep -n '2.3.0-SNAPSHOT' {} +
```

Verified build with

```
$ JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home mvn clean package -DskipTests
$ JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home mvn clean package -DskipTests -Dhadoop.profile=3.0
```

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  6s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 21s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   6m  1s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 47s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 41s |  branch-2 passed  |
| +0 :ok: |  mvndep  |   6m  1s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 46s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 42s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m 51s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  hadoopcheck  |  17m 24s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   7m 12s |  The patch does not generate ASF License warnings.  |
|  |   |  62m  1s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1309 |
| Optional Tests | dupname asflicense hadoopcheck xml checkstyle |
| uname | Linux d4768514bd36 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 58a0ef0cfe |
| Max. process+thread count | 62 (vs. ulimit of 10000) |
| modules | C: hbase-checkstyle hbase-annotations hbase-build-configuration hbase-protocol-shaded hbase-common hbase-metrics-api hbase-hadoop-compat hbase-metrics hbase-hadoop2-compat hbase-protocol hbase-client hbase-zookeeper hbase-replication hbase-resource-bundle hbase-http hbase-procedure hbase-server hbase-mapreduce hbase-testing-util hbase-thrift hbase-rsgroup hbase-shell hbase-endpoint hbase-it hbase-rest hbase-examples hbase-shaded hbase-shaded/hbase-shaded-client hbase-shaded/hbase-shaded-client-byo-hadoop hbase-shaded/hbase-shaded-mapreduce hbase-external-blockcache hbase-hbtop hbase-assembly hbase-shaded/hbase-shaded-testing-util hbase-shaded/hbase-shaded-testing-util-tester hbase-shaded/hbase-shaded-check-invariants hbase-shaded/hbase-shaded-with-hadoop-check-invariants hbase-archetypes hbase-archetypes/hbase-client-project hbase-archetypes/hbase-shaded-client-project hbase-archetypes/hbase-archetype-builder . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/console |
| versions | git=2.17.1 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 41s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  7s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 10s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   4m 11s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   5m 46s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |  13m 45s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m 51s |  branch-2 passed  |
| +0 :ok: |  mvndep  |   7m 16s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   6m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 27s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 27s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 48s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |  12m 58s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  10m 19s |  root in the patch failed.  |
|  |   |  84m 53s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1309 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux fae7e77145ad 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 58a0ef0cfe |
| Default Java | 1.8.0_232 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/testReport/ |
| Max. process+thread count | 1180 (vs. ulimit of 10000) |
| modules | C: hbase-checkstyle hbase-annotations hbase-build-configuration hbase-protocol-shaded hbase-common hbase-metrics-api hbase-hadoop-compat hbase-metrics hbase-hadoop2-compat hbase-protocol hbase-client hbase-zookeeper hbase-replication hbase-resource-bundle hbase-http hbase-procedure hbase-server hbase-mapreduce hbase-testing-util hbase-thrift hbase-rsgroup hbase-shell hbase-endpoint hbase-it hbase-rest hbase-examples hbase-shaded hbase-shaded/hbase-shaded-client hbase-shaded/hbase-shaded-client-byo-hadoop hbase-shaded/hbase-shaded-mapreduce hbase-external-blockcache hbase-hbtop hbase-assembly hbase-shaded/hbase-shaded-testing-util hbase-shaded/hbase-shaded-testing-util-tester hbase-shaded/hbase-shaded-check-invariants hbase-shaded/hbase-shaded-with-hadoop-check-invariants hbase-archetypes hbase-archetypes/hbase-client-project hbase-archetypes/hbase-shaded-client-project hbase-archetypes/hbase-archetype-builder . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/console |
| versions | git=2.17.1 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 22s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   9m  7s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   4m 52s |  branch-2 passed  |
| -1 :x: |  shadedjars  |   0m  9s |  branch has 7 errors when building our shaded downstream artifacts.  |
| -0 :warning: |  javadoc  |   0m 20s |  root in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 17s |  hbase-archetypes in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 16s |  hbase-client-project in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 15s |  hbase-shaded-client-project in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 30s |  hbase-client in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 17s |  hbase-common in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 20s |  hbase-examples in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 15s |  hbase-external-blockcache in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 16s |  hbase-hadoop2-compat in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 18s |  hbase-hadoop-compat in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 16s |  hbase-hbtop in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 17s |  hbase-http in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 20s |  hbase-mapreduce in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 14s |  hbase-metrics in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 14s |  hbase-metrics-api in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 17s |  hbase-procedure in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 20s |  hbase-replication in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 28s |  hbase-rest in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 27s |  hbase-rsgroup in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 50s |  hbase-server in branch-2 failed.  |
| -0 :warning: |  javadoc  |   1m  7s |  hbase-thrift in branch-2 failed.  |
| -0 :warning: |  javadoc  |   0m 18s |  hbase-zookeeper in branch-2 failed.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   7m 19s |  branch-2 passed  |
| +0 :ok: |  mvndep  |   7m 45s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   7m  5s |  the patch passed  |
| +1 :green_heart: |  compile  |   4m 20s |  the patch passed  |
| +1 :green_heart: |  javac  |   4m 20s |  the patch passed  |
| -1 :x: |  shadedjars  |   0m  8s |  patch has 7 errors when building our shaded downstream artifacts.  |
| -0 :warning: |  javadoc  |   0m 16s |  hbase-common in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 14s |  hbase-metrics-api in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 17s |  hbase-hadoop-compat in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 14s |  hbase-metrics in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 17s |  hbase-hadoop2-compat in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 27s |  hbase-client in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 16s |  hbase-zookeeper in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 15s |  hbase-replication in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 16s |  hbase-http in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 16s |  hbase-procedure in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 41s |  hbase-server in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 19s |  hbase-mapreduce in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 56s |  hbase-thrift in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 20s |  hbase-rsgroup in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 22s |  hbase-rest in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 19s |  hbase-examples in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 14s |  hbase-external-blockcache in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 15s |  hbase-hbtop in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 15s |  hbase-archetypes in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 14s |  hbase-client-project in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 15s |  hbase-shaded-client-project in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 17s |  root in the patch failed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 152m 34s |  root in the patch passed.  |
|  |   | 220m 32s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1309 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 978177c95b1e 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 58a0ef0cfe |
| Default Java | 2020-01-14 |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-shadedjars.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-root.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-archetypes.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-archetypes_hbase-client-project.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-archetypes_hbase-shaded-client-project.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-client.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-common.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-examples.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-external-blockcache.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-hadoop2-compat.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-hadoop-compat.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-hbtop.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-http.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-mapreduce.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-metrics.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-metrics-api.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-procedure.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-replication.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-rest.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-rsgroup.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-server.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-thrift.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-zookeeper.txt |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-shadedjars.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-common.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-metrics-api.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-hadoop-compat.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-metrics.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-hadoop2-compat.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-client.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-zookeeper.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-replication.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-http.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-procedure.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-server.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-mapreduce.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-thrift.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-rsgroup.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-rest.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-examples.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-external-blockcache.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-hbtop.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-archetypes.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-archetypes_hbase-client-project.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-archetypes_hbase-shaded-client-project.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/testReport/ |
| Max. process+thread count | 6203 (vs. ulimit of 10000) |
| modules | C: hbase-checkstyle hbase-annotations hbase-build-configuration hbase-protocol-shaded hbase-common hbase-metrics-api hbase-hadoop-compat hbase-metrics hbase-hadoop2-compat hbase-protocol hbase-client hbase-zookeeper hbase-replication hbase-resource-bundle hbase-http hbase-procedure hbase-server hbase-mapreduce hbase-testing-util hbase-thrift hbase-rsgroup hbase-shell hbase-endpoint hbase-it hbase-rest hbase-examples hbase-shaded hbase-shaded/hbase-shaded-client hbase-shaded/hbase-shaded-client-byo-hadoop hbase-shaded/hbase-shaded-mapreduce hbase-external-blockcache hbase-hbtop hbase-assembly hbase-shaded/hbase-shaded-testing-util hbase-shaded/hbase-shaded-testing-util-tester hbase-shaded/hbase-shaded-check-invariants hbase-shaded/hbase-shaded-with-hadoop-check-invariants hbase-archetypes hbase-archetypes/hbase-client-project hbase-archetypes/hbase-shaded-client-project hbase-archetypes/hbase-archetype-builder . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1309/1/console |
| versions | git=2.17.1 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Thanks @HorizonNet !

**Pull request merged**
