### PR TITLE
HBASE-23357 Add 2.1.8 to download page

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache9** [comment]
Which url?

**Comment by infraio** [comment]
> Which url?

http://mirror-hk.koddos.net/apache/hbase/2.1.8/hbase-2.1.8-src.tar.gz

**Comment by Apache9** [comment]
https://dist.apache.org/repos/dist/release/hbase/2.1.8/

It is there. This should be the delay of the mirrors?

**Comment by busbey** [comment]
It can take a bit for the mirrors to all catch up. If you take a look at the list of all mirrors you can kind of see how things are going by spot checking.

http://www.apache.org/mirrors/

I usually just wait 24hrs from uploading to dist.a.o, since that's the SLA ASF infra talks about.

**Comment by infraio** [comment]
> It can take a bit for the mirrors to all catch up. If you take a look at the list of all mirrors you can kind of see how things are going by spot checking.
> 
> http://www.apache.org/mirrors/
> 
> I usually just wait 24hrs from uploading to dist.a.o, since that's the SLA ASF infra talks about.

Got it. Thanks.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 44s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m  8s |  master passed  |
| +1 :green_heart: |  mvnsite  |  20m 30s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 27s |  the patch passed  |
| +1 :green_heart: |  mvnsite  |  20m 36s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 18s |  The patch does not generate ASF License warnings.  |
|  |   |  56m  5s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-892/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/892 |
| Optional Tests | dupname asflicense mvnsite xml |
| uname | Linux 23a082a06e83 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-892/out/precommit/personality/provided.sh |
| git revision | master / 0f166edc3d |
| Max. process+thread count | 86 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-892/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
