### PR TITLE
HBASE-22910 Enable TestMultiVersionConcurrencyControl

### PR DESCRIPTION
**Pull request by jatsakthi**

### CODE REVIEW

**Comment by jatsakthi** [comment]
I think the pre-commit build was aborted due to HBASE-22913. Next run is in progress, Stack.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 73 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 417 | master passed |
| +1 | compile | 62 | master passed |
| +1 | checkstyle | 91 | master passed |
| +1 | shadedjars | 305 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 40 | master passed |
| 0 | spotbugs | 282 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 280 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 341 | the patch passed |
| +1 | compile | 67 | the patch passed |
| +1 | javac | 67 | the patch passed |
| +1 | checkstyle | 96 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 332 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1058 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 37 | the patch passed |
| +1 | findbugs | 284 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 15313 | hbase-server in the patch failed. |
| +1 | asflicense | 43 | The patch does not generate ASF License warnings. |
| | | 19266 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.namespace.TestNamespaceAuditor |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.master.TestAssignmentManagerMetrics |
|   | hadoop.hbase.client.TestAsyncTableGetMultiThreaded |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-531/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/531 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 2328d2016554 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-531@2/out/precommit/personality/provided.sh |
| git revision | master / 94155fe175 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-531/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-531/2/testReport/ |
| Max. process+thread count | 4909 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-531/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jatsakthi** [comment]
The test passed. Shall we get this in, @saintstack ?

**Comment by jatsakthi** [comment]
Thanks for your review, Stack.

**Pull request merged**
