### PR TITLE
HBASE-23176 delete_all_snapshot does not work with regex

### PR DESCRIPTION
**Pull request by karthikhw**
Delete_all_snapshot.rb is using deprecated method SnapshotDescription#getTable but this method is already removed in 3.0.x.

### CODE REVIEW

**Comment by karthikhw** [comment]
I am really not sure if we need testcase. I added general test case for this issue. Just realized, it already exists. Here, testcase will pass even without this fix.

The reason I could not add testcase because delete_all_snapshot.rb#command(regex) accept only one argument and second argument will get it from user ('y/n') at runtime, for confirming delete. 

But here I don't think I can't pass argument at runtime.

**Comment by karthikhw** [comment]
I tried passing args at runtime but test case hungs ever.  I don't think we need test case for init script.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   6m 29s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| :green_heart: |  mvninstall  |   6m 37s |  master passed  |
| :green_heart: |  javadoc  |   0m 15s |  master passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   6m  6s |  the patch passed  |
| :green_heart: |  rubocop  |   0m  9s |  There were no new rubocop issues.  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  javadoc  |   0m 15s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  |  13m 44s |  hbase-shell in the patch failed.  |
| :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  35m  6s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAdminShell |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/725 |
| Optional Tests | dupname asflicense javac javadoc unit rubocop |
| uname | Linux bf49f0f4e578 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-725/out/precommit/personality/provided.sh |
| git revision | master / 7924ba39e7 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/1/artifact/out/patch-unit-hbase-shell.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/1/testReport/ |
| Max. process+thread count | 2680 (vs. ulimit of 10000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) rubocop=0.75.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by karthikhw** [comment]
Removed this test-case, as similar functionality test exist already.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m  0s |  Docker mode activated.  |
| :broken_heart: |  docker  |   0m  1s |  Docker failed to build yetus/hbase:1cb4f687c1.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/725 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m  8s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| :green_heart: |  mvninstall  |   6m 11s |  master passed  |
| :green_heart: |  javadoc  |   0m 14s |  master passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   5m 34s |  the patch passed  |
| :green_heart: |  rubocop  |   0m  9s |  There were no new rubocop issues.  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  javadoc  |   0m 12s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  |  10m 23s |  hbase-shell in the patch passed.  |
| :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  25m  0s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.3 Server=19.03.3 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/725 |
| Optional Tests | dupname asflicense javac javadoc unit rubocop |
| uname | Linux b4b1bb25dfbe 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-725/out/precommit/personality/provided.sh |
| git revision | master / 7924ba39e7 |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/3/testReport/ |
| Max. process+thread count | 2630 (vs. ulimit of 10000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) rubocop=0.75.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by guangxuCheng** [comment]
https://github.com/apache/hbase/blob/fa05907b1b5ff3ac440a43937cae386b3638de5a/hbase-shell/src/main/ruby/shell/commands/delete_all_snapshot.rb#L57
Also need to be modified here

**Comment by karthikhw** [comment]
Thank you very much  @guangxuCheng for checking this. There are 3 commits here, the first commit changes for delete_all_snapshot.rb.

**Comment by guangxuCheng** [comment]
@karthikhw There are two places in delete_all_snapshot.rb that need to be modified, but you only modified one of them.

**Comment by karthikhw** [comment]
Thank you @guangxuCheng highlighting missing one. Sorry, I somehow missed it.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| :green_heart: |  mvninstall  |   6m 52s |  master passed  |
| :green_heart: |  javadoc  |   0m 14s |  master passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   5m 29s |  the patch passed  |
| :green_heart: |  rubocop  |   0m 10s |  There were no new rubocop issues.  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  javadoc  |   0m 13s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  |  10m 17s |  hbase-shell in the patch passed.  |
| :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  25m 35s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.3 Server=19.03.3 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/725 |
| Optional Tests | dupname asflicense javac javadoc unit rubocop |
| uname | Linux f34471f58eee 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-725/out/precommit/personality/provided.sh |
| git revision | master / 0043dfebc5 |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/4/testReport/ |
| Max. process+thread count | 2621 (vs. ulimit of 10000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-725/4/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) rubocop=0.75.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
