### PR TITLE
HBASE-28690 Aborting Active HMaster is not rejecting reportRegionStateTransition if procedure is initialised by next Active master

### PR DESCRIPTION
**Pull request by Umeshkumar9414**
Added masterActiveTime as fencing token for remote procedures

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  8s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  |  Patch does not have any anti-patterns.  |
|||| _ branch-2.5 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   4m 28s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   5m 21s |  |  branch-2.5 passed  |
| +1 :green_heart: |  checkstyle  |   1m 21s |  |  branch-2.5 passed  |
| +1 :green_heart: |  spotbugs  |   5m 58s |  |  branch-2.5 passed  |
| +1 :green_heart: |  spotless  |   1m  1s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 51s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   4m 55s |  |  the patch passed  |
| +1 :green_heart: |  cc  |   4m 55s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   4m 55s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 37s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   5m 13s |  |  the patch passed  |
| +1 :green_heart: |  hadoopcheck  |  30m  5s |  |  Patch does not cause any errors with Hadoop 2.10.2 or 3.2.4 3.3.6 3.4.0.  |
| +1 :green_heart: |  hbaseprotoc  |   2m 20s |  |  the patch passed  |
| +1 :green_heart: |  spotless  |   1m 13s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 54s |  |  The patch does not generate ASF License warnings.  |
|  |   |  72m 55s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6180 |
| Optional Tests | dupname asflicense javac spotbugs checkstyle codespell detsecrets compile hadoopcheck hbaseanti spotless cc buflint bufcompat hbaseprotoc |
| uname | Linux e6c6ebbddc48 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 7a9d381e3271b72a49dd52f947ced8035cfa2dfc |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| Max. process+thread count | 82 (vs. ulimit of 30000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-procedure hbase-server U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/console |
| versions | git=2.34.1 maven=3.9.8 spotbugs=4.7.3 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 44s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 54s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   1m 58s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   1m  6s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   5m 18s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 55s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 55s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m  3s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 17s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 30s |  |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   8m  5s |  |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 29s |  |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  | 186m 34s |  |  hbase-server in the patch passed.  |
|  |   | 224m 25s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6180 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 7192d2fd5c88 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 7a9d381e3271b72a49dd52f947ced8035cfa2dfc |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/testReport/ |
| Max. process+thread count | 4232 (vs. ulimit of 30000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-procedure hbase-server U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 10s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m 55s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   2m 11s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   1m 25s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   6m  9s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m  5s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  5s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m  5s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 34s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   6m 17s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 27s |  |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 18s |  |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 45s |  |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  | 198m 33s |  |  hbase-server in the patch passed.  |
|  |   | 242m 20s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6180 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 63f1701f37ff 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 7a9d381e3271b72a49dd52f947ced8035cfa2dfc |
| Default Java | Temurin-1.8.0_412-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/testReport/ |
| Max. process+thread count | 4104 (vs. ulimit of 30000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-procedure hbase-server U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 42s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m  0s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   2m  9s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   1m 14s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   5m 14s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 53s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  9s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m  9s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 15s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 11s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 35s |  |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 15s |  |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 26s |  |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  | 213m 27s |  |  hbase-server in the patch passed.  |
|  |   | 252m 54s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6180 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 73d4e6612b84 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 7a9d381e3271b72a49dd52f947ced8035cfa2dfc |
| Default Java | Eclipse Adoptium-11.0.23+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/testReport/ |
| Max. process+thread count | 4328 (vs. ulimit of 30000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-procedure hbase-server U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6180/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Review by Apache9 — APPROVED** [review]

**Pull request merged**
