### PR TITLE
[ADDENDUM] HBASE-28947 Backport "HBASE-27598 Upgrade mockito to 4.x" …

### PR DESCRIPTION
**Pull request by NihalJain**
…to branch-2.5
- Remove references to mockito-core.version in pom to fix site build
- Backports https://github.com/apache/hbase/commit/55b4bbc05785cc652b4425b9ac45f673b28597b4

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 42s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ branch-2.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 57s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   5m  0s |  |  branch-2.5 passed  |
| +1 :green_heart: |  spotless  |   0m 43s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 45s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   5m  0s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   5m  0s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  xmllint  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  hadoopcheck  |  19m 37s |  |  Patch does not cause any errors with Hadoop 2.10.2 or 3.2.4 3.3.6 3.4.0.  |
| +1 :green_heart: |  spotless  |   0m 42s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 14s |  |  The patch does not generate ASF License warnings.  |
|  |   |  39m 27s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6454 |
| Optional Tests | dupname asflicense javac codespell detsecrets xmllint hadoopcheck spotless compile |
| uname | Linux 6d5f2326d064 5.4.0-200-generic #220-Ubuntu SMP Fri Sep 27 13:19:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 46493a52a8cd32f8bc9aa5fadb51a6b1d92b1098 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| Max. process+thread count | 75 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/console |
| versions | git=2.34.1 maven=3.9.8 xmllint=20913 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 44s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m  2s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   2m  2s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   1m 52s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   5m  1s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 45s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  5s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m  5s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 49s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 57s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 260m 52s |  |  root in the patch passed.  |
|  |   | 291m 47s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6454 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 005763a20ce4 5.4.0-195-generic #215-Ubuntu SMP Fri Aug 2 18:28:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 46493a52a8cd32f8bc9aa5fadb51a6b1d92b1098 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/testReport/ |
| Max. process+thread count | 8036 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m  7s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  8s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  6s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   2m 53s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   2m 58s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   8m 48s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 33s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  9s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   3m  9s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   3m 35s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   8m  6s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 256m 30s |  |  root in the patch passed.  |
|  |   | 302m 13s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6454 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux e1e3c5b0a0fd 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 46493a52a8cd32f8bc9aa5fadb51a6b1d92b1098 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/testReport/ |
| Max. process+thread count | 7786 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 44s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 32s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   1m 36s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   1m 41s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   6m 21s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m  8s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 30s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 30s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m  3s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 41s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 402m  8s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   | 433m 41s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6454 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 56cc6f0e219d 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 46493a52a8cd32f8bc9aa5fadb51a6b1d92b1098 |
| Default Java | Temurin-1.8.0_412-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/testReport/ |
| Max. process+thread count | 4703 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6454/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by NihalJain** [comment]
Merging this as its a straight backport.

**Pull request merged**
