### PR TITLE
HBASE-22969 A new binary component comparator(BinaryComponentComparator) to perform comparison of arbitrary length and position

### PR DESCRIPTION
**Pull request by udaikashyap**
A new binary component comparator(BinaryComponentComparator) to perform comp
arison of arbitrary length and position

### CODE REVIEW

**Comment by meszibalu** [comment]
(Triggered jenkins manually.)

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 29s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  1s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 32s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 44s |  master passed  |
| +1 :green_heart: |  compile  |   3m 15s |  master passed  |
| +1 :green_heart: |  checkstyle  |   2m 54s |  master passed  |
| +0 :ok: |  refguide  |   6m 24s |  branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect.  |
| +1 :green_heart: |  shadedjars  |   4m 59s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   4m  7s |  master passed  |
| +0 :ok: |  spotbugs  |   3m 53s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |  24m  4s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 29s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 16s |  the patch passed  |
| +1 :green_heart: |  cc  |   3m 16s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 16s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 56s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +0 :ok: |  refguide  |   6m 42s |  patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect.  |
| +1 :green_heart: |  shadedjars  |   5m 28s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  17m 22s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  hbaseprotoc  |   7m 58s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   4m  8s |  the patch passed  |
| +1 :green_heart: |  findbugs  |  25m  3s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 176m  5s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   2m  3s |  The patch does not generate ASF License warnings.  |
|  |   | 317m  2s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-829/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/829 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool refguide |
| uname | Linux e964fe7ca721 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-829/out/precommit/personality/provided.sh |
| git revision | master / 67f9afc722 |
| Default Java | 1.8.0_181 |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-829/2/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-829/2/artifact/out/patch-site/book.html |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-829/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-829/2/testReport/ |
| Max. process+thread count | 4523 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-protocol hbase-client hbase-server . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-829/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by udaikashyap** [comment]
The unit test failure seems due to bad xml file /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-829/src/hbase-server/target/surefire-reports/TEST-org.apache.hadoop.hbase.regionserver.TestRegionReplicaFailover.xml 

I have no idea about how this file gets generated or used? @meszibalu can you give me some idea? What can be done to fix this?

**Comment by meszibalu** [comment]
The test failure is independent from your patch in my opinion.

**Pull request merged**
