### PR TITLE
HBASE-22199 Replaced UTF-8 String with StandardCharsets.UTF_8

### PR DESCRIPTION
**Pull request by HorizonNet**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 301 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 4 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 32 | Maven dependency ordering for branch |
| +1 | mvninstall | 346 | master passed |
| +1 | compile | 165 | master passed |
| +1 | checkstyle | 151 | master passed |
| +1 | shadedjars | 353 | branch has no errors when building our shaded downstream artifacts. |
| -1 | findbugs | 266 | hbase-server in master has 11 extant Findbugs warnings. |
| +1 | javadoc | 106 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| +1 | mvninstall | 313 | the patch passed |
| +1 | compile | 161 | the patch passed |
| +1 | javac | 161 | the patch passed |
| -1 | checkstyle | 23 | hbase-mapreduce: The patch generated 1 new + 45 unchanged - 0 fixed = 46 total (was 45) |
| -1 | checkstyle | 21 | hbase-examples: The patch generated 3 new + 245 unchanged - 0 fixed = 248 total (was 245) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 333 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 712 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 423 | the patch passed |
| +1 | javadoc | 106 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 18455 | hbase-server in the patch failed. |
| +1 | unit | 1606 | hbase-mapreduce in the patch passed. |
| +1 | unit | 536 | hbase-rest in the patch passed. |
| +1 | unit | 146 | hbase-examples in the patch passed. |
| +1 | asflicense | 147 | The patch does not generate ASF License warnings. |
| | | 25110 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.util.TestFromClientSide3WoUnsafe |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleWAL |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicasWithoutZKCoordinated |
|   | hadoop.hbase.replication.TestReplicationDisableInactivePeer |
|   | hadoop.hbase.replication.TestReplicationSmallTestsSync |
|   | hadoop.hbase.quotas.TestSpaceQuotas |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicas |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleAsyncWAL |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.client.TestFromClientSide3 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/136 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux a57bb368ab59 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 494a8efe5f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/1/artifact/out/branch-findbugs-hbase-server-warnings.html |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/1/artifact/out/diff-checkstyle-hbase-mapreduce.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/1/artifact/out/diff-checkstyle-hbase-examples.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/1/testReport/ |
| Max. process+thread count | 5600 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-rest hbase-examples U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 51 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 4 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 17 | Maven dependency ordering for branch |
| +1 | mvninstall | 276 | master passed |
| +1 | compile | 127 | master passed |
| +1 | checkstyle | 119 | master passed |
| +1 | shadedjars | 259 | branch has no errors when building our shaded downstream artifacts. |
| -1 | findbugs | 167 | hbase-server in master has 11 extant Findbugs warnings. |
| +1 | javadoc | 90 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| +1 | mvninstall | 240 | the patch passed |
| +1 | compile | 129 | the patch passed |
| +1 | javac | 129 | the patch passed |
| +1 | checkstyle | 119 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 268 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 527 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 311 | the patch passed |
| +1 | javadoc | 86 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 17153 | hbase-server in the patch failed. |
| +1 | unit | 1309 | hbase-mapreduce in the patch passed. |
| +1 | unit | 482 | hbase-rest in the patch passed. |
| +1 | unit | 134 | hbase-examples in the patch passed. |
| +1 | asflicense | 101 | The patch does not generate ASF License warnings. |
| | | 22227 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAsyncTableRegionReplicasGet |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleWAL |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.util.TestFromClientSide3WoUnsafe |
|   | hadoop.hbase.master.TestAssignmentManagerMetrics |
|   | hadoop.hbase.namespace.TestNamespaceAuditor |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestAdmin1 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/136 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 883b855ba3ab 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / fc6e3fc9d7 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/2/artifact/out/branch-findbugs-hbase-server-warnings.html |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/2/testReport/ |
| Max. process+thread count | 4698 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-rest hbase-examples U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 20 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 4 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 29 | Maven dependency ordering for branch |
| +1 | mvninstall | 264 | master passed |
| +1 | compile | 127 | master passed |
| +1 | checkstyle | 127 | master passed |
| +1 | shadedjars | 271 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 305 | master passed |
| +1 | javadoc | 84 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| +1 | mvninstall | 252 | the patch passed |
| +1 | compile | 127 | the patch passed |
| +1 | javac | 127 | the patch passed |
| +1 | checkstyle | 126 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 272 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 520 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 325 | the patch passed |
| +1 | javadoc | 85 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8366 | hbase-server in the patch passed. |
| +1 | unit | 910 | hbase-mapreduce in the patch passed. |
| +1 | unit | 264 | hbase-rest in the patch passed. |
| +1 | unit | 111 | hbase-examples in the patch passed. |
| +1 | asflicense | 102 | The patch does not generate ASF License warnings. |
| | | 12841 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/136 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 91ec9c637f7c 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / f77bde3722 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/3/testReport/ |
| Max. process+thread count | 5092 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-rest hbase-examples U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
Updated PR according to feedback from @petersomogyi on the Jira ticket.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 23 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 4 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 145 | Maven dependency ordering for branch |
| +1 | mvninstall | 251 | master passed |
| +1 | compile | 130 | master passed |
| +1 | checkstyle | 115 | master passed |
| +1 | shadedjars | 266 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 315 | master passed |
| +1 | javadoc | 88 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| +1 | mvninstall | 245 | the patch passed |
| +1 | compile | 128 | the patch passed |
| +1 | javac | 128 | the patch passed |
| -1 | checkstyle | 13 | hbase-examples: The patch generated 1 new + 8 unchanged - 0 fixed = 9 total (was 8) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 263 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 500 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 352 | the patch passed |
| +1 | javadoc | 87 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 7047 | hbase-server in the patch passed. |
| -1 | unit | 889 | hbase-mapreduce in the patch failed. |
| +1 | unit | 270 | hbase-rest in the patch passed. |
| +1 | unit | 107 | hbase-examples in the patch passed. |
| +1 | asflicense | 87 | The patch does not generate ASF License warnings. |
| | | 11574 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.snapshot.TestExportSnapshotNoCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/136 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 32fe8b027544 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 20f72f5e25 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/4/artifact/out/diff-checkstyle-hbase-examples.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/4/artifact/out/patch-unit-hbase-mapreduce.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/4/testReport/ |
| Max. process+thread count | 5401 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-rest hbase-examples U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
Updated the PR to fix the Checkstyle issue.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 273 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 4 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 32 | Maven dependency ordering for branch |
| +1 | mvninstall | 305 | master passed |
| +1 | compile | 162 | master passed |
| +1 | checkstyle | 146 | master passed |
| +1 | shadedjars | 338 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 390 | master passed |
| +1 | javadoc | 105 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| +1 | mvninstall | 299 | the patch passed |
| +1 | compile | 164 | the patch passed |
| +1 | javac | 164 | the patch passed |
| +1 | checkstyle | 135 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 332 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 660 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 422 | the patch passed |
| +1 | javadoc | 174 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 13636 | hbase-server in the patch passed. |
| +1 | unit | 1373 | hbase-mapreduce in the patch passed. |
| +1 | unit | 582 | hbase-rest in the patch passed. |
| +1 | unit | 143 | hbase-examples in the patch passed. |
| +1 | asflicense | 113 | The patch does not generate ASF License warnings. |
| | | 19978 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/136 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 94b82e2106b6 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 20f72f5e25 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/5/testReport/ |
| Max. process+thread count | 5526 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-rest hbase-examples U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-136/5/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
