### PR TITLE
HBASE-22771 [HBCK2] fixMeta method and server-side support; ADDENDUM

### PR DESCRIPTION
**Pull request by petersomogyi**
Remove HRegion.java.rej file

### CODE REVIEW

**Comment by petersomogyi** [comment]
The rejected hunk was correctly applied in the original commit, only the `HRegion.java.rej` file was added.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 47 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.1 Compile Tests _ |
| -1 | mvninstall | 123 | root in branch-2.1 failed. |
| +1 | javadoc | 30 | branch-2.1 passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 124 | root in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 30 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8016 | hbase-server in the patch failed. |
| +1 | asflicense | 23 | The patch does not generate ASF License warnings. |
| | | 8469 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.security.visibility.TestVisibilityLabelsReplication |
|   | hadoop.hbase.security.access.TestAccessController3 |
|   | hadoop.hbase.security.visibility.TestVisibilityLabelsWithDeletes |
|   | hadoop.hbase.quotas.TestSpaceQuotas |
|   | hadoop.hbase.security.visibility.TestDefaultScanLabelGeneratorStack |
|   | hadoop.hbase.security.access.TestWithDisabledAuthorization |
|   | hadoop.hbase.quotas.TestQuotaObserverChoreWithMiniCluster |
|   | hadoop.hbase.security.visibility.TestVisibilityLabelsWithDefaultVisLabelService |
|   | hadoop.hbase.security.visibility.TestVisibilityLabelsWithCustomVisLabService |
|   | hadoop.hbase.security.visibility.TestVisibilityWithCheckAuths |
|   | hadoop.hbase.security.access.TestNamespaceCommands |
|   | hadoop.hbase.security.visibility.TestVisibilityLabelsOnNewVersionBehaviorTable |
|   | hadoop.hbase.quotas.TestQuotaStatusRPCs |
|   | hadoop.hbase.security.visibility.TestVisibilityLabelsWithSLGStack |
|   | hadoop.hbase.security.access.TestCellACLWithMultipleVersions |
|   | hadoop.hbase.security.visibility.TestVisibilityLabelReplicationWithExpAsString |
|   | hadoop.hbase.security.visibility.TestVisibilityLabelsWithACL |
|   | hadoop.hbase.security.visibility.TestVisibilityLabelsOpWithDifferentUsersNoACL |
|   | hadoop.hbase.security.token.TestGenerateDelegationToken |
|   | hadoop.hbase.security.visibility.TestWithDisabledAuthorization |
|   | hadoop.hbase.security.access.TestRpcAccessChecks |
|   | hadoop.hbase.quotas.TestSpaceQuotasWithSnapshots |
|   | hadoop.hbase.security.visibility.TestVisibilityLablesWithGroups |
|   | hadoop.hbase.security.access.TestTablePermissions |
|   | hadoop.hbase.TestNamespace |
|   | hadoop.hbase.quotas.TestSnapshotQuotaObserverChore |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/457 |
| Optional Tests | dupname asflicense javac javadoc unit |
| uname | Linux 35d55a01ca5d 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-457/out/precommit/personality/provided.sh |
| git revision | branch-2.1 / 9a6494f02f |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/1/artifact/out/branch-mvninstall-root.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/1/artifact/out/patch-mvninstall-root.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/1/testReport/ |
| Max. process+thread count | 4799 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 46 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.1 Compile Tests _ |
| -1 | mvninstall | 128 | root in branch-2.1 failed. |
| +1 | javadoc | 29 | branch-2.1 passed |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 125 | root in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 30 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 1510 | hbase-server in the patch failed. |
| +1 | asflicense | 11 | The patch does not generate ASF License warnings. |
| | | 1955 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.ipc.TestRpcServerTraceLogging |
|   | hadoop.hbase.regionserver.TestHRegionInfo |
|   | hadoop.hbase.monitoring.TestTaskMonitor |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/457 |
| Optional Tests | dupname asflicense javac javadoc unit |
| uname | Linux 8a73d83e8f4b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-457@2/out/precommit/personality/provided.sh |
| git revision | branch-2.1 / 935d271f77 |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/2/artifact/out/branch-mvninstall-root.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/2/artifact/out/patch-mvninstall-root.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/2/testReport/ |
| Max. process+thread count | 702 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 65 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.1 Compile Tests _ |
| +1 | mvninstall | 297 | branch-2.1 passed |
| +1 | javadoc | 34 | branch-2.1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 282 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 35 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 7429 | hbase-server in the patch failed. |
| +1 | asflicense | 21 | The patch does not generate ASF License warnings. |
| | | 8242 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestTableOperationException |
|   | hadoop.hbase.regionserver.TestHRegionReplayEvents |
|   | hadoop.hbase.regionserver.TestMutateRowsRecovery |
|   | hadoop.hbase.filter.TestFuzzyRowAndColumnRangeFilter |
|   | hadoop.hbase.regionserver.TestScannerHeartbeatMessages |
|   | hadoop.hbase.client.TestAsyncSnapshotAdminApi |
|   | hadoop.hbase.client.TestAsyncProcedureAdminApi |
|   | hadoop.hbase.TestIOFencing |
|   | hadoop.hbase.regionserver.TestNewVersionBehaviorFromClientSide |
|   | hadoop.hbase.regionserver.TestRegionIncrement |
|   | hadoop.hbase.client.TestMultiParallel |
|   | hadoop.hbase.client.TestSizeFailures |
|   | hadoop.hbase.regionserver.TestRegionServerAbortTimeout |
|   | hadoop.hbase.client.TestAsyncSingleRequestRpcRetryingCaller |
|   | hadoop.hbase.regionserver.TestPerColumnFamilyFlush |
|   | hadoop.hbase.regionserver.TestCompactionState |
|   | hadoop.hbase.client.TestSeparateClientZKCluster |
|   | hadoop.hbase.regionserver.TestRegionReplicasWithModifyTable |
|   | hadoop.hbase.client.TestAsyncTableBatch |
|   | hadoop.hbase.client.TestAsyncQuotaAdminApi |
|   | hadoop.hbase.filter.TestFilterListOnMini |
|   | hadoop.hbase.filter.TestScanRowPrefix |
|   | hadoop.hbase.regionserver.throttle.TestCompactionWithThroughputController |
|   | hadoop.hbase.client.TestSnapshotCloneIndependence |
|   | hadoop.hbase.util.TestFSUtils |
|   | hadoop.hbase.regionserver.TestCompactingMemStore |
|   | hadoop.hbase.regionserver.TestRegionMergeTransactionOnCluster |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestRestoreSnapshotFromClientSimple |
|   | hadoop.hbase.client.TestTableSnapshotScanner |
|   | hadoop.hbase.client.TestAsyncReplicationAdminApi |
|   | hadoop.hbase.client.TestIncrementFromClientSideWithCoprocessor |
|   | hadoop.hbase.filter.TestMultiRowRangeFilter |
|   | hadoop.hbase.regionserver.TestRegionServerAbort |
|   | hadoop.hbase.util.TestMiniClusterLoadSequential |
|   | hadoop.hbase.filter.TestFilterWithScanLimits |
|   | hadoop.hbase.client.TestCheckAndMutate |
|   | hadoop.hbase.util.TestHBaseFsckReplication |
|   | hadoop.hbase.client.TestAsyncNonMetaRegionLocator |
|   | hadoop.hbase.client.TestCIGetRpcTimeout |
|   | hadoop.hbase.client.TestMobRestoreSnapshotFromClientSimple |
|   | hadoop.hbase.client.TestCIBadHostname |
|   | hadoop.hbase.regionserver.throttle.TestFlushWithThroughputController |
|   | hadoop.hbase.client.TestCISleep |
|   | hadoop.hbase.client.TestMobSnapshotCloneIndependence |
|   | hadoop.hbase.filter.TestFilterWrapper |
|   | hadoop.hbase.regionserver.TestRegionReplicasWithRestartScenarios |
|   | hadoop.hbase.client.TestPutWithDelete |
|   | hadoop.hbase.TestHBaseOnOtherDfsCluster |
|   | hadoop.hbase.filter.TestFilterListOrOperatorWithBlkCnt |
|   | hadoop.hbase.regionserver.TestRegionServerNoMaster |
|   | hadoop.hbase.regionserver.TestRegionMove |
|   | hadoop.hbase.client.TestAlwaysSetScannerId |
|   | hadoop.hbase.TestAcidGuaranteesWithBasicPolicy |
|   | hadoop.hbase.client.TestConnectionImplementation |
|   | hadoop.hbase.regionserver.TestFSErrorsExposed |
|   | hadoop.hbase.client.TestAsyncMetaRegionLocator |
|   | hadoop.hbase.regionserver.TestSplitTransactionOnCluster |
|   | hadoop.hbase.regionserver.TestCompoundBloomFilter |
|   | hadoop.hbase.TestAcidGuaranteesWithNoInMemCompaction |
|   | hadoop.hbase.TestHColumnDescriptorDefaultVersions |
|   | hadoop.hbase.regionserver.TestMultiLogThreshold |
|   | hadoop.hbase.client.TestAppendFromClientSide |
|   | hadoop.hbase.client.TestRestoreSnapshotFromClientAfterSplittingRegions |
|   | hadoop.hbase.filter.TestFuzzyRowFilterEndToEnd |
|   | hadoop.hbase.regionserver.TestMultiColumnScannerWithAlgoGZAndNoDataEncoding |
|   | hadoop.hbase.regionserver.TestWalAndCompactingMemStoreFlush |
|   | hadoop.hbase.client.TestHTableMultiplexerFlushCache |
|   | hadoop.hbase.client.TestCIIncrementRpcTimeout |
|   | hadoop.hbase.client.TestTableFavoredNodes |
|   | hadoop.hbase.client.TestAdmin2 |
|   | hadoop.hbase.client.TestAsyncReplicationAdminApiWithClusters |
|   | hadoop.hbase.regionserver.TestMajorCompaction |
|   | hadoop.hbase.filter.TestColumnRangeFilter |
|   | hadoop.hbase.regionserver.TestSecureBulkLoadManager |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | TEST-null |
|   | hadoop.hbase.util.compaction.TestMajorCompactor |
|   | hadoop.hbase.client.TestMobRestoreSnapshotFromClientAfterSplittingRegions |
|   | hadoop.hbase.TestJMXConnectorServer |
|   | hadoop.hbase.client.TestAsyncTableAdminApi2 |
|   | hadoop.hbase.TestClusterBootOrder |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/457 |
| Optional Tests | dupname asflicense javac javadoc unit |
| uname | Linux 025e09f45f3b 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-457/out/precommit/personality/provided.sh |
| git revision | branch-2.1 / 935d271f77 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/3/testReport/ |
| Max. process+thread count | 4859 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-457/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
