### PR TITLE
[HBASE-22597] : Upgrading commons-long to 3.9

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 6 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for branch |
| +1 | mvninstall | 242 | master passed |
| +1 | compile | 162 | master passed |
| +1 | checkstyle | 138 | master passed |
| +1 | shadedjars | 259 | branch has no errors when building our shaded downstream artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hbase-shaded . |
| +1 | findbugs | 200 | master passed |
| +1 | javadoc | 201 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for patch |
| +1 | mvninstall | 235 | the patch passed |
| +1 | compile | 159 | the patch passed |
| +1 | javac | 159 | the patch passed |
| +1 | checkstyle | 132 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 5 | The patch has no ill-formed XML file. |
| +1 | shadedjars | 262 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 719 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hbase-shaded . |
| +1 | findbugs | 197 | the patch passed |
| +1 | javadoc | 196 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 13352 | root in the patch passed. |
| +1 | asflicense | 116 | The patch does not generate ASF License warnings. |
| | | 16966 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/317 |
| JIRA Issue | HBASE-22597 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  shadedjars  hadoopcheck  xml  compile  findbugs  hbaseanti  checkstyle  |
| uname | Linux 7d16ac63b631 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 5da5deb59d |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/2/testReport/ |
| Max. process+thread count | 5664 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-shaded . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
Please review @apurtell

**Comment by virajjasani** [comment]
> commons-lang 3.9 is the current release and RandomStringUtils doesn't look deprecated to me:
> 
> https://commons.apache.org/proper/commons-lang/javadocs/api-3.9/org/apache/commons/lang3/RandomStringUtils.html
> 
> What's the reasoning behind replacing this use? Have you already checked to ensure none of our other dependencies already provide what we need? I would prefer we not add yet another third party dependency.

@busbey We are using commons-lang 3.6: https://github.com/apache/hbase/blob/master/pom.xml#L1448
RandomStringUtils is deprecated as of 3.6: https://commons.apache.org/proper/commons-lang/javadocs/api-3.6/org/apache/commons/lang3/RandomStringUtils.html

**Comment by busbey** [comment]
It was undeprecated in commons-lang 3.7 (ref [LANG-1346](https://issues.apache.org/jira/browse/LANG-1346)). please upgrade us to commons-lang 3.9 instead.

**Comment by virajjasani** [comment]
> It was undeprecated in commons-lang 3.7 (ref [LANG-1346](https://issues.apache.org/jira/browse/LANG-1346)). please upgrade us to commons-lang 3.9 instead.

Makes sense. Let's see if the build goes well with 3.7. 
Thanks @busbey for the suggestion

**Comment by virajjasani** [comment]
@busbey could you please kill https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/3/ ? 
Latest commit has already triggered recent build

**Comment by busbey** [comment]
I tried. we'll see if it takes. :)

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 264 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 401 | master passed |
| +1 | compile | 221 | master passed |
| +1 | shadedjars | 353 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 208 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 312 | the patch passed |
| +1 | compile | 217 | the patch passed |
| +1 | javac | 217 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedjars | 355 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 998 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 208 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 19263 | root in the patch failed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 23237 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.quotas.TestSpaceQuotas |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestAsyncClusterAdminApi2 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/317 |
| JIRA Issue | HBASE-22597 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  shadedjars  hadoopcheck  xml  compile  |
| uname | Linux 3026ad645863 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / e14b5f0edc |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/4/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/4/testReport/ |
| Max. process+thread count | 4858 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 19 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 266 | master passed |
| +1 | compile | 172 | master passed |
| +1 | shadedjars | 273 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 155 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 246 | the patch passed |
| +1 | compile | 169 | the patch passed |
| +1 | javac | 169 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedjars | 273 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 760 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 160 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 12576 | root in the patch passed. |
| +1 | asflicense | 37 | The patch does not generate ASF License warnings. |
| | | 15429 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/317 |
| JIRA Issue | HBASE-22597 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  shadedjars  hadoopcheck  xml  compile  |
| uname | Linux 39a3ee6d323c 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / c7c6140396 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/5/testReport/ |
| Max. process+thread count | 5317 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/5/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
Please review @busbey

**Comment by virajjasani** [comment]
@busbey Could you please let me know how this PR is closed automatically? Which setting/validation triggered this closure?

**Comment by busbey** [comment]
I pushed it to master. still working on backports and then I'll close the jira.

thanks for working on this!

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 51 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 335 | master passed |
| +1 | compile | 219 | master passed |
| +1 | shadedjars | 352 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 207 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 318 | the patch passed |
| +1 | compile | 226 | the patch passed |
| +1 | javac | 226 | the patch passed |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedjars | 340 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 949 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 203 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 19260 | root in the patch failed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 22876 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.client.TestFromClientSide |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/317 |
| JIRA Issue | HBASE-22597 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  shadedjars  hadoopcheck  xml  compile  |
| uname | Linux daa62b87d66e 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 6a068da4dc |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/6/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/6/testReport/ |
| Max. process+thread count | 4921 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-317/6/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
