### PR TITLE
Backport "HBASE-24200 Upgrade to Yetus 0.12.0" to branch-1.4

### PR DESCRIPTION
**Pull request by ndimiduk**
Signed-off-by: Sean Busbey <busbey@apache.org>
Signed-off-by: Duo Zhang <zhangduo@apache.org>

### CODE REVIEW

**Comment by Apache9** [comment]
Pre commit check failed?

**Comment by ndimiduk** [comment]
Indeed. Testing if PR works for branch-1.4, #2603 .

**Comment by ndimiduk** [comment]
Yeah, looks like it's broken on 1.4. Filed [HBASE-25231](https://issues.apache.org/jira/browse/HBASE-25231).

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 36s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ branch-1.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 21s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  9s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +0 :ok: |  asflicense  |   0m  0s |  ASF License check generated no output?  |
|  |   |   4m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2601/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2601 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 4227864d8471 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-agent/workspace/Base-PreCommit-GitHub-PR_PR-2601/out/precommit/personality/provided.sh |
| git revision | branch-1.4 / e34c0e3 |
| Max. process+thread count | 41 (vs. ulimit of 10000) |
| modules | C:  U:  |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2601/4/console |
| versions | git=1.9.1 maven=3.0.5 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
