### PR TITLE
HBASE-21257 misspelled words.[occured -> occurred]

### PR DESCRIPTION
**Pull request by gangxueZhang**
hi!
    This PR does not affect the program function. It only modifies the misspelled words in the exception information and changes "occured" to "occurred".
Found in [HBASE-21257](https://issues.apache.org/jira/browse/HBASE-21257)

### CODE REVIEW

**Comment by huanyuqianlun** [comment]
Hi!
     Sorry, there is no clear problem description before. This PR does not affect the program function. It only modifies the misspelled words in the comments and changes "occured" to "occurred".
    In this case, do I still need to filing a request in JIRA that describes the problem and proposed solution?

**Comment by huanyuqianlun** [comment]
hi!
This PR does not affect the program function. It only modifies the misspelled words in the exception information and changes "occured" to "occurred".
Found in jira :[HBASE-21257](https://issues.apache.org/jira/browse/HBASE-21257)

**Comment by Apache9** [comment]
Hey @gangxueZhang the GitHub integration for HBase has been set up, could you please update the PR since there are conflicts?

Thanks.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 6 | https://github.com/apache/hbase/pull/91 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/91 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-91/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
@gangxueZhang  Please combine your commits into one commit? Thanks.

**Comment by gangxueZhang** [comment]
@Apache9 Hello, I am not very familiar with github now. Can you guide me how to merge these two commits? I will operate here. Thank you.

**Comment by Apache9** [comment]
Just check out the newest master of hbase, and cherry-pick your old patch, resolve conflicts, then force push to your master, the PR here will be changed automatically.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 5 | https://github.com/apache/hbase/pull/91 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/91 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-91/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by gangxueZhang** [comment]
@Apache9 Hey, I have done what you said, but I don't know if it is right, help me confirm it,please.

**Comment by Apache9** [comment]
You have some merge commits in your own repo, which leads to conflicts. I suggest you record the commit id 'fcfa14e2f176d19e9ce984fe4687c3e1fd57e66f', and then reset to an earlier commit before the merge commits, and then sync with the master branch of apache/hbase again, and then cherry-pick the 'fcfa14e2f176d19e9ce984fe4687c3e1fd57e66f'. And last, do a force push your master branch.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 6 | https://github.com/apache/hbase/pull/91 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/91 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-91/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 5 | https://github.com/apache/hbase/pull/91 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/91 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-91/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by gangxueZhang** [comment]
@Apache9 Hi, is this OK？ if not, can I close this PR and submit a new PR based on the latest version?

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 6 | https://github.com/apache/hbase/pull/91 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/91 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-91/5/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Seems the robot is still not able to apply the patch.

@gangxueZhang Yes, you can close this one and open a new one, if it is easier for you.

Thanks.

**Comment by gangxueZhang** [comment]
@Apache9 Hey, this PR has been closed by me, and a new [PR#146](https://github.com/apache/hbase/pull/146) has been created to replace it. If there is no problem, please merge the changes in [PR#146](https://github.com/apache/hbase/pull/146).

**Pull request closed without merging**
