### PR TITLE
HBASE-23612: Add new profile to make hbase build success on ARM

### PR DESCRIPTION
**Pull request by bzhaoopenstack**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m  1s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 25s |  master passed  |
| +1 :green_heart: |  compile  |   3m  1s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 38s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 49s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 56s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 57s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 57s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedjars  |   4m 33s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  15m 35s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   2m 46s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 224m 42s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 46s |  The patch does not generate ASF License warnings.  |
|  |   | 280m 27s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.mapreduce.TestSyncTable |
|   | hadoop.hbase.snapshot.TestExportSnapshotNoCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-959/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/959 |
| JIRA Issue | HBASE-23612 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 7d4d9ee12e44 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-959/out/precommit/personality/provided.sh |
| git revision | master / 4b6ce0fcbf |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-959/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-959/1/testReport/ |
| Max. process+thread count | 5073 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-959/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by bzhaoopenstack** [comment]
Hi, @saintstack ,
This will enable silencely by the backend ARCH, or you can specific by a maven profile '-Paarch64'

**Comment by Apache9** [comment]
@bzhaoopenstack The patch LGTM. Do you guys try this patch on arm? What is the build result? Just wondering if this really works on arm.

Thanks.

**Comment by bzhaoopenstack** [comment]
mvn clean install assembly:single -f ./pom.xml -Dhadoop.profile=3.0 -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dspotbugs.skip=true -DskipTests 2>&1 | tee ~/hbase-results/hbase_build.log \
    && mvn clean test -P runAllTests -Dhadoop.profile=3.0 -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dspotbugs.skip=true -Dtest.exclude.pattern=**/security.access.TestSnapshotScannerHDFSAclController.java -fn | tee ~/hbase-results/hbase_all_test.log

**Comment by saintstack** [comment]
Thanks for pasting in the build result. Where does it fail? Ok we just commit this on master branch?

**Comment by bzhaoopenstack** [comment]
@saintstack @Apache9 Thanks guys. The post result is test result. ;-). We can success build hbase, but the test seems not stable(as I can run the failure test via -Dtest with maven, and all of them could get pass), and I guess it could be related with the Host which exec the test.

**Comment by bzhaoopenstack** [comment]
@saintstack And I think it's ready to go with you guys kind review. Thanks again. ;-)

**Comment by saintstack** [comment]
@bzhaoopenstack just apply to master? Thats enough? Thanks.

**Comment by bzhaoopenstack** [comment]
@saintstack Yeah, I test both on X86 and aarch64, this works. Thank you.

**Pull request merged**
