### PR TITLE
HBASE-22927 Upgrade mockito version for Java 11 compatibility

### PR DESCRIPTION
**Pull request by ravowlga123**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   3m 46s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :green_heart: |  mvninstall  |   6m 18s |  master passed  |
| :green_heart: |  compile  |   3m 20s |  master passed  |
| :green_heart: |  shadedjars  |   4m 48s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   2m 51s |  master passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   4m 56s |  the patch passed  |
| :green_heart: |  compile  |   2m 55s |  the patch passed  |
| :green_heart: |  javac  |   2m 55s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| :broken_heart: |  shadedjars  |   4m 27s |  patch has 10 errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  15m 29s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   2m 48s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 311m 11s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   0m 41s |  The patch does not generate ASF License warnings.  |
|  |   | 369m 43s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/584 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 742b07b3fcec 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-584/out/precommit/personality/provided.sh |
| git revision | master / 0d338a1820 |
| Default Java | 1.8.0_181 |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/1/artifact/out/patch-shadedjars.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/1/testReport/ |
| Max. process+thread count | 4921 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
> [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ hbase-shaded-check-invariants ---
> [INFO] Restricted to JDK 1.8 yet net.bytebuddy:byte-buddy:jar:1.9.0:provided contains module-info.class targeted to JDK 1.9
> [INFO] Restricted to JDK 1.8 yet net.bytebuddy:byte-buddy-agent:jar:1.9.0:provided contains module-info.class targeted to JDK 1.9
> [WARNING] Rule 1: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
> HBase has unsupported dependencies.
>   HBase requires that all dependencies be compiled with version 1.8 or earlier
>   of the JDK to properly build from source.  You appear to be using a newer dependency. You can use
>   either "mvn -version" or "mvn enforcer:display-info" to verify what version is active.
>   Non-release builds can temporarily build with a newer JDK version by setting the
>   'compileSource' property (eg. mvn -DcompileSource=1.8 clean package).
> Found Banned Dependency: net.bytebuddy:byte-buddy:jar:1.9.0
> Found Banned Dependency: net.bytebuddy:byte-buddy-agent:jar:1.9.0

So the new mockito just drops the support for java 8?

**Comment by ravowlga123** [comment]
Comment on the similar issue https://github.com/raphw/byte-buddy/issues/541#issuecomment-429649501. Work around for above can be to add module-info.class in <ignoreclass>. What do you think @Apache9

**Comment by Apache9** [comment]
Seems hadoop has already updated the mockito version to 2.23.4? And seems the UTs are fine so this maybe a too strict enforcer rule? @busbey PTAL.

And why not upgrade to 2.28.2? And also there is a 3.0.0 release now? What's is the difference 3.x and 2.x?

**Comment by busbey** [comment]
> Seems hadoop has already updated the mockito version to 2.23.4? And seems the UTs are fine so this maybe a too strict enforcer rule? @busbey PTAL.

This sounded familiar so I dug about. This came up with a JRuby update on [HBASE-20582](https://issues.apache.org/jira/browse/HBASE-20582) and is tracked in [MENFORCER-300](https://issues.apache.org/jira/browse/MENFORCER-300).

On HBASE-20582 we pinned our version of JRuby to avoid the issue (which is what it looks like the byte-buddy developer suggested as a workaround). Since then MENFORCER-300 has been updated to include an example of how to ignore the {{module-info}} class. We should probably do that. It might also be worth reopening MENFORCER-300 to discuss what that plugin should be doing about the class.

**Comment by busbey** [comment]
Hadoop updating shouldn't be taken as an indicator of anything, IMHO. They only ensure a certain minimum JDK is used at build time; they don't have any checks to make sure generated artifacts will work with any particular JDK version.

**Comment by ravowlga123** [comment]
Checked out both HBASE-20582 and MENFORCER-300. Will follow the example of MENFORCER-300 and add module-info in ignoreclass section.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :green_heart: |  mvninstall  |   5m 44s |  master passed  |
| :green_heart: |  compile  |   3m  7s |  master passed  |
| :green_heart: |  shadedjars  |   4m 52s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   2m 59s |  master passed  |
| :yellow_heart: |  patch  |   8m  1s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   5m  4s |  the patch passed  |
| :green_heart: |  compile  |   2m 55s |  the patch passed  |
| :green_heart: |  javac  |   2m 55s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| :broken_heart: |  shadedjars  |   0m  9s |  patch has 7 errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  15m 40s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   2m 55s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 240m 26s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   0m 49s |  The patch does not generate ASF License warnings.  |
|  |   | 291m 54s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.rsgroup.TestRSGroupsAdmin2 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/584 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux ff0541411fe9 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-584/out/precommit/personality/provided.sh |
| git revision | master / 0d338a1820 |
| Default Java | 1.8.0_181 |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/2/artifact/out/patch-shadedjars.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/2/testReport/ |
| Max. process+thread count | 5636 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-584/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
Still working on this @ravowlga123 ?

**Pull request closed without merging**
