### PR TITLE
HBASE-24742 Improve performance of SKIP vs SEEK logic.

### PR DESCRIPTION
**Pull request by lhofhansl**
In our testing of HBase 1.3 against the current tip of branch-1 we saw a 30% slowdown in scanning scenarios.

We tracked it back to HBASE-17958 and HBASE-19863.
Both add comparisons to one of the tightest HBase has.

The observation is that we do not need to guard against ROWCOL Bloomfilters fake keys if ROWCOL BFs are either not used or not setup for this Store.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   5m 27s |  Docker failed to build yetus/hbase:7cf97016b9.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/2075 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-2075/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by bharathv** [comment]
Looks like branch-1 pre-commit is broken. @Reidddddd has a patch at #2065. Let me take a look at that.

**Comment by virajjasani** [comment]
> lgtm. My quick test shows that this shaves off a compare for tables without ROWCOL bfs. Thats a nice speed up.

Just a question: The speed is inline with 1.3?

**Comment by bharathv** [comment]
> Just a question: The speed is inline with 1.3?

Its within 5-10% bounds based on my preliminary analysis (on my local box, **if this optimization kicks in**). Will have to do a detailed cluster based perf run to dig deeper. As discussed in the jira, there is scope for further optimization for general use cases (specifically when versions=1, arbitrary bloom filters types etc) but that might need a bigger refactor of code. My point being that we cannot generally compare with 1.3 until we fix those issues too.

**Comment by lhofhansl** [comment]
In unit tests StoreScanner.store might be null. Fixed.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   0m  9s |  Docker failed to build yetus/hbase:7cf97016b9.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/2075 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-2075/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 37s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   9m 46s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 39s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  compile  |   0m 44s |  branch-1 passed with JDK v1.7.0_262  |
| +1 :green_heart: |  checkstyle  |   1m 42s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  0s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 48s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 40s |  branch-1 passed with JDK v1.7.0_262  |
| +0 :ok: |  spotbugs  |   3m  3s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   3m  0s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 56s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 40s |  the patch passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javac  |   0m 40s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 43s |  the patch passed with JDK v1.7.0_262  |
| +1 :green_heart: |  javac  |   0m 43s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 30s |  hbase-server: The patch generated 1 new + 38 unchanged - 1 fixed = 39 total (was 39)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 47s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 43s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 31s |  the patch passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 41s |  the patch passed with JDK v1.7.0_262  |
| +1 :green_heart: |  findbugs  |   2m 50s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 134m 29s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  The patch does not generate ASF License warnings.  |
|  |   | 176m  2s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.12 Server=19.03.12 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-2075/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2075 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux af8ea015eb72 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-2075/out/precommit/personality/provided.sh |
| git revision | branch-1 / b249092 |
| Default Java | 1.7.0_262 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_252 /usr/lib/jvm/zulu-7-amd64:1.7.0_262 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-2075/3/artifact/out/diff-checkstyle-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-2075/3/testReport/ |
| Max. process+thread count | 4208 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-2075/3/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by lhofhansl** [comment]
Re: Checkstyle... The indentation of the entire block in StoreScanner.<init> is wrong (5 instead of 4) happy to fix the entire block, but it'd be unrelated make the patch larger.

**Comment by bharathv** [comment]
Agree that the indents can be fixed separately in the interest of keeping the patch smaller. +1 from my side on the patch.

**Comment by lhofhansl** [comment]
Alright going to merge in a few.

**Comment by lhofhansl** [comment]
Darn... It used the wrong (old) email in the commit. Oh well.

**Pull request merged**
