### PR TITLE
HBASE-22262 Removed deprecated methods from Filter class

### PR DESCRIPTION
**Pull request by HorizonNet**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 39 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for branch |
| -1 | mvninstall | 83 | root in master failed. |
| -1 | compile | 16 | hbase-client in master failed. |
| -1 | compile | 28 | hbase-server in master failed. |
| -1 | compile | 24 | hbase-rest in master failed. |
| +1 | checkstyle | 123 | master passed |
| +1 | shadedjars | 281 | branch has no errors when building our shaded downstream artifacts. |
| -1 | findbugs | 60 | hbase-client in master has 83 extant Findbugs warnings. |
| -1 | findbugs | 153 | hbase-server in master has 3 extant Findbugs warnings. |
| -1 | findbugs | 24 | hbase-rest in master failed. |
| -1 | javadoc | 14 | hbase-client in master failed. |
| -1 | javadoc | 18 | hbase-server in master failed. |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for patch |
| -1 | mvninstall | 78 | root in the patch failed. |
| -1 | compile | 15 | hbase-client in the patch failed. |
| -1 | compile | 28 | hbase-server in the patch failed. |
| -1 | compile | 24 | hbase-rest in the patch failed. |
| -1 | javac | 15 | hbase-client in the patch failed. |
| -1 | javac | 28 | hbase-server in the patch failed. |
| -1 | javac | 24 | hbase-rest in the patch failed. |
| +1 | checkstyle | 35 | hbase-client: The patch generated 0 new + 352 unchanged - 26 fixed = 352 total (was 378) |
| +1 | checkstyle | 74 | hbase-server: The patch generated 0 new + 42 unchanged - 2 fixed = 42 total (was 44) |
| +1 | checkstyle | 13 | The patch passed checkstyle in hbase-rest |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 279 | patch has no errors when building our shaded downstream artifacts. |
| -1 | hadoopcheck | 44 | The patch causes 10 errors with Hadoop v2.7.4. |
| -1 | hadoopcheck | 86 | The patch causes 10 errors with Hadoop v3.0.0. |
| -1 | findbugs | 26 | hbase-rest in the patch failed. |
| -1 | javadoc | 14 | hbase-client in the patch failed. |
| -1 | javadoc | 19 | hbase-server in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 16 | hbase-client in the patch failed. |
| -1 | unit | 28 | hbase-server in the patch failed. |
| -1 | unit | 25 | hbase-rest in the patch failed. |
| +1 | asflicense | 27 | The patch does not generate ASF License warnings. |
| | | 2076 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/162 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux e1202aa03048 4.4.0-141-generic #167~14.04.1-Ubuntu SMP Mon Dec 10 13:20:24 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 8ec93ea193 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-compile-hbase-client.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-compile-hbase-server.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-compile-hbase-rest.txt |
| findbugs | v3.1.11 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-findbugs-hbase-client-warnings.html |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-findbugs-hbase-server-warnings.html |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-findbugs-hbase-rest.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-javadoc-hbase-client.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/branch-javadoc-hbase-server.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-compile-hbase-client.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-compile-hbase-server.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-compile-hbase-rest.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-compile-hbase-client.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-compile-hbase-server.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-compile-hbase-rest.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-javac-2.7.4.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-javac-3.0.0.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-findbugs-hbase-rest.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-javadoc-hbase-client.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-javadoc-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-unit-hbase-client.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-unit-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/artifact/out/patch-unit-hbase-rest.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/testReport/ |
| Max. process+thread count | 83 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for branch |
| +1 | mvninstall | 276 | master passed |
| +1 | compile | 110 | master passed |
| +1 | checkstyle | 128 | master passed |
| +1 | shadedjars | 284 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 300 | master passed |
| +1 | javadoc | 84 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| +1 | mvninstall | 252 | the patch passed |
| +1 | compile | 106 | the patch passed |
| +1 | javac | 106 | the patch passed |
| +1 | checkstyle | 35 | hbase-client: The patch generated 0 new + 352 unchanged - 26 fixed = 352 total (was 378) |
| +1 | checkstyle | 70 | hbase-server: The patch generated 0 new + 42 unchanged - 2 fixed = 42 total (was 44) |
| +1 | checkstyle | 17 | The patch passed checkstyle in hbase-rest |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 271 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 559 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 335 | the patch passed |
| +1 | javadoc | 76 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 202 | hbase-client in the patch passed. |
| -1 | unit | 7563 | hbase-server in the patch failed. |
| +1 | unit | 266 | hbase-rest in the patch passed. |
| +1 | asflicense | 92 | The patch does not generate ASF License warnings. |
| | | 11199 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.security.token.TestZKSecretWatcher |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/162 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 9ce6db6b80b5 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 268bcce76f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/2/testReport/ |
| Max. process+thread count | 4685 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
The test failure seems to be unrelated to the actual change.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 23 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 29 | Maven dependency ordering for branch |
| +1 | mvninstall | 260 | master passed |
| +1 | compile | 109 | master passed |
| +1 | checkstyle | 121 | master passed |
| +1 | shadedjars | 269 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 284 | master passed |
| +1 | javadoc | 81 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 17 | Maven dependency ordering for patch |
| +1 | mvninstall | 244 | the patch passed |
| +1 | compile | 102 | the patch passed |
| +1 | javac | 102 | the patch passed |
| +1 | checkstyle | 33 | hbase-client: The patch generated 0 new + 352 unchanged - 26 fixed = 352 total (was 378) |
| +1 | checkstyle | 67 | hbase-server: The patch generated 0 new + 42 unchanged - 2 fixed = 42 total (was 44) |
| +1 | checkstyle | 16 | The patch passed checkstyle in hbase-rest |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 265 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 508 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 337 | the patch passed |
| +1 | javadoc | 77 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 199 | hbase-client in the patch passed. |
| +1 | unit | 7596 | hbase-server in the patch passed. |
| +1 | unit | 266 | hbase-rest in the patch passed. |
| +1 | asflicense | 90 | The patch does not generate ASF License warnings. |
| | | 11095 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/162 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 716c71e53a49 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / f30d6c958a |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/3/testReport/ |
| Max. process+thread count | 4726 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
> For sure deprecated for a whole major version? Deprecate in hbase 2.0.0 release? 

I think 'a whole major version' just means we can not remove deprecated stuff if it is first deprecated in the same major version? For example, it is OK to remove a class in 3.0.0 if it is deprecated in 2.1.0, but you can not remove it in 2.2.0.

**Comment by saintstack** [comment]
"An API needs to be deprecated for a major version before we will change/remove it."

... in "Client API compatibility" in http://hbase.apache.org/book.html#hbase.versioning.post10

**Comment by HorizonNet** [comment]
I had the same understanding as @Apache9. I know we had a discussion about this some time ago, but wasn't able to find it anymore. Probably the documentation needs some more details (an example would be good), because it is up to some kind of interpretation. I think if we deprecate something in 2.0.0 we can remove it in 3.0.0. But what about the minor versions? If we deprecated something in 2.3.0 and the next version to be released is 3.0.0 we don't really have a deprecation for a major version. Removing it in 3.3.0 also doesn't seem to be good. With that the next major version would be 4.0.0, so removing it after 1.5 major versions.

**Comment by saintstack** [comment]
My interpretation is that you have to wait at least a major version so as per your example, it'd be 4.0.0 if deprecation was added in anything after 2.0.0.

**Comment by Apache9** [comment]
> My interpretation is that you have to wait at least a major version so as per your example, it'd be 4.0.0 if deprecation was added in anything after 2.0.0.

That would be too tough? I think a major release is where we do breaking changes. And I found this in our ref guide

> Example: A user using a newly deprecated API does not need to modify application code with HBase API calls until the next major version. *

So I think it is OK to remove deprecated classes in a major release? We can leave it there for some reasons, but removing  it is also acceptable.

**Comment by saintstack** [comment]
Sounds like we need to get clarification here. I think the 'Example' sentence is open to various interpretation. ML?

**Comment by Apache9** [comment]
I have already done some removal of deprecated classes on master...

But I think your point on 'at lease a whole major release' is also valid. For example, we have deprecated something on 2.1.0, but users may upgrade to 3.0.0 from 2.0.0, so they will not see the deprecation and find out some APIs are gone...

So maybe we need a guide on rolling upgrading, for example, 2.x users must upgrade to, for example, 2.3.0 first, before upgrading to 3.0.0? And we must make sure that, all classes deprecated after 2.3.0 release, must be retained until we release 4.0.0.

What do you think?

**Comment by saintstack** [comment]
Lets discuss on ML. I think asking folks to rolling upgrade to the most minor version before going to next major may be an unfair expectation.

**Comment by Apache9** [comment]
Anyway we have already done lots of removal and it is not likely that we can add them back, so...

**Comment by HorizonNet** [comment]
Also agree to discuss it on the ML. Will create a thread later today. We definitely need to make the documentation more clear. Regarding this PR: The two methods in the ```Filter``` class were deprecated in 2.0.0, so we should be fine to remove them for 3.0.0.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 267 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for branch |
| +1 | mvninstall | 273 | master passed |
| +1 | compile | 109 | master passed |
| +1 | checkstyle | 121 | master passed |
| +1 | shadedjars | 262 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 293 | master passed |
| +1 | javadoc | 72 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for patch |
| +1 | mvninstall | 269 | the patch passed |
| +1 | compile | 106 | the patch passed |
| +1 | javac | 106 | the patch passed |
| +1 | checkstyle | 35 | hbase-client: The patch generated 0 new + 340 unchanged - 26 fixed = 340 total (was 366) |
| +1 | checkstyle | 69 | hbase-server: The patch generated 0 new + 42 unchanged - 2 fixed = 42 total (was 44) |
| +1 | checkstyle | 15 | The patch passed checkstyle in hbase-rest |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 269 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 545 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 336 | the patch passed |
| +1 | javadoc | 72 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 205 | hbase-client in the patch passed. |
| -1 | unit | 17532 | hbase-server in the patch failed. |
| +1 | unit | 490 | hbase-rest in the patch passed. |
| +1 | asflicense | 74 | The patch does not generate ASF License warnings. |
| | | 21583 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.procedure.TestSCPWithReplicas |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicasWithoutZKCoordinated |
|   | hadoop.hbase.client.TestConnectionImplementation |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.master.TestSplitWALManager |
|   | hadoop.hbase.client.replication.TestReplicationAdminWithClusters |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.client.TestHbck |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/162 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 4e273caea6f0 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 184568cadd |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/4/testReport/ |
| Max. process+thread count | 5138 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-162/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
So, we got clarification on the ML. How does it effect the patch? Thanks.

**Comment by HorizonNet** [comment]
@saintstack It shouldn't affect the patch, because the two methods were deprecated in 2.0.0 and with that can be removed in 3.0.0. In my opinion we're ready to merge.

**Comment by saintstack** [comment]
@HorizonNet Ok. +1 on commit sir.

**Pull request merged**
