### PR TITLE
HBASE-22893

### PR DESCRIPTION
**Pull request by ravowlga123**
In the section : http://hbase.apache.org/book.html#hbase.unittests , "Categorizing Tests" -> "Large Tests" updated to 13 mins

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 8 | https://github.com/apache/hbase/pull/552 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jatsakthi** [comment]
@ravowlga123 as the original commit wasn't reverted & the plan is to include this commit as addendum, the patch isn't applicable. Could you please just include the doc change in this patch, so that it's applicable?

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 7 | https://github.com/apache/hbase/pull/552 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 7 | https://github.com/apache/hbase/pull/552 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/3/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 7 | https://github.com/apache/hbase/pull/552 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/4/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by ravowlga123** [comment]
Hi @jatsakthi Do you want me to remove the commit with the change in HBaseClassTestRule.java and just keep the commit with documentation change??

**Comment by jatsakthi** [comment]
Yes, please.

**Comment by ravowlga123** [comment]
Hi @jatsakthi I have made the changes. Please do review it if they are okay and thank you for your patience.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 41 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 341 | master passed |
| 0 | refguide | 349 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 301 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 359 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 18 | The patch does not generate ASF License warnings. |
| | | 1472 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux ffed4e19f444 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-552/out/precommit/personality/provided.sh |
| git revision | master / 090c55f3ff |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/5/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/5/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/5/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 74 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 344 | master passed |
| 0 | refguide | 345 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 340 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 348 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 20 | The patch does not generate ASF License warnings. |
| | | 1548 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux 4514446c3091 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-552/out/precommit/personality/provided.sh |
| git revision | master / ee5cf0d209 |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/6/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/6/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/6/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 47 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 440 | master passed |
| 0 | refguide | 441 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 354 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 439 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 21 | The patch does not generate ASF License warnings. |
| | | 1831 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux f55516c45818 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-552/out/precommit/personality/provided.sh |
| git revision | master / b642ee0418 |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/7/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/7/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/7/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 32 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 359 | master passed |
| 0 | refguide | 395 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 345 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 386 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 19 | The patch does not generate ASF License warnings. |
| | | 1607 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux f07bdb4e483a 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-552/out/precommit/personality/provided.sh |
| git revision | master / 97fbaa658e |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/8/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/8/artifact/out/patch-site/book.html |
| Max. process+thread count | 86 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/8/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 332 | master passed |
| 0 | refguide | 334 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 287 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 335 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 18 | The patch does not generate ASF License warnings. |
| | | 1401 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux 8f1efd275d2c 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-552/out/precommit/personality/provided.sh |
| git revision | master / 345c21dbe7 |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/9/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/9/artifact/out/patch-site/book.html |
| Max. process+thread count | 76 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/9/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 44 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 412 | master passed |
| 0 | refguide | 474 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 380 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 432 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 19 | The patch does not generate ASF License warnings. |
| | | 1830 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/10/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux 26ed32931f3c 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-552/out/precommit/personality/provided.sh |
| git revision | master / a5ef6b287c |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/10/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/10/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/10/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 326 | master passed |
| 0 | refguide | 338 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 289 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 321 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 19 | The patch does not generate ASF License warnings. |
| | | 1391 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/11/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux d06b5d96541a 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-552/out/precommit/personality/provided.sh |
| git revision | master / d32bf8daed |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/11/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/11/artifact/out/patch-site/book.html |
| Max. process+thread count | 81 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/11/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 8 | https://github.com/apache/hbase/pull/552 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/552 |
| JIRA Issue | HBASE-22893 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-552/12/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
@jatsakthi As far as I can see the addendum was pushed to master. Can we close this PR?

**Comment by saintstack** [comment]
Resolving. Committed to Master (as per @HorizonNet note above).

**Pull request closed without merging**
