### PR TITLE
HBASE-22390 Backport HBASE-22190 to branch-1

### PR DESCRIPTION
**Pull request by z-york**
HBASE-22190 SnapshotFileCache may fail to load the correct snapshot file list when there is an on-going snapshot operation

### CODE REVIEW

**Comment by z-york** [comment]
@Apache9 @apurtell (for visibility since this fixes HBASE-21070)

**Comment by z-york** [comment]
Also please advise if I attributed this incorrectly, it's a little wonky with a PR.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1278 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | findbugs | 0 | Findbugs executables are not available. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 150 | branch-1 passed |
| +1 | compile | 38 | branch-1 passed with JDK v1.8.0_212 |
| +1 | compile | 48 | branch-1 passed with JDK v1.7.0_222 |
| +1 | checkstyle | 80 | branch-1 passed |
| +1 | shadedjars | 159 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 57 | branch-1 passed with JDK v1.8.0_212 |
| +1 | javadoc | 62 | branch-1 passed with JDK v1.7.0_222 |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 151 | the patch passed |
| +1 | compile | 62 | the patch passed with JDK v1.8.0_212 |
| +1 | javac | 62 | the patch passed |
| +1 | compile | 50 | the patch passed with JDK v1.7.0_222 |
| +1 | javac | 50 | the patch passed |
| -1 | checkstyle | 79 | hbase-server: The patch generated 4 new + 2 unchanged - 2 fixed = 6 total (was 4) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 155 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 109 | Patch does not cause any errors with Hadoop 2.7.4. |
| +1 | javadoc | 28 | the patch passed with JDK v1.8.0_212 |
| +1 | javadoc | 38 | the patch passed with JDK v1.7.0_222 |
||| _ Other Tests _ |
| -1 | unit | 8889 | hbase-server in the patch failed. |
| +1 | asflicense | 87 | The patch does not generate ASF License warnings. |
| | | 11603 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.wal.TestLogRolling |
|   | hadoop.hbase.regionserver.TestPerColumnFamilyFlush |
|   | hadoop.hbase.regionserver.TestEncryptionKeyRotation |
|   | hadoop.hbase.replication.TestReplicationSmallTests |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-230/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/230 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux b54248fbc097 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-1 / 56548fc |
| maven | version: Apache Maven 3.0.5 |
| Default Java | 1.7.0_222 |
| Multi-JDK versions |  /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_212 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_222 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-230/1/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-230/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-230/1/testReport/ |
| Max. process+thread count | 3812 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-230/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by z-york** [comment]
all these tests pass locally. Fixed checkstyle as well. Committing.

**Comment by z-york** [comment]
pushed to branch-1 and branch-1.4. closing.

**Pull request closed without merging**
