### PR TITLE
HBASE-22524 Refactor TestReplicationSyncUpTool

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 159 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 33 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for branch |
| +1 | mvninstall | 241 | master passed |
| +1 | compile | 105 | master passed |
| +1 | checkstyle | 101 | master passed |
| +1 | shadedjars | 279 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 245 | master passed |
| +1 | javadoc | 60 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 12 | Maven dependency ordering for patch |
| +1 | mvninstall | 285 | the patch passed |
| +1 | compile | 101 | the patch passed |
| +1 | javac | 101 | the patch passed |
| -1 | checkstyle | 63 | hbase-server: The patch generated 3 new + 6 unchanged - 3 fixed = 9 total (was 9) |
| -1 | checkstyle | 18 | hbase-mapreduce: The patch generated 2 new + 7 unchanged - 2 fixed = 9 total (was 9) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 281 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 796 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 295 | the patch passed |
| +1 | javadoc | 59 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 15511 | hbase-server in the patch failed. |
| -1 | unit | 1454 | hbase-mapreduce in the patch failed. |
| -1 | unit | 326 | hbase-endpoint in the patch failed. |
| +1 | asflicense | 102 | The patch does not generate ASF License warnings. |
| | | 20888 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.snapshot.TestExportSnapshotNoCluster |
|   | hadoop.hbase.replication.TestReplicationSyncUpToolWithBulkLoadedData |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/285 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 297849f09dff 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / b2b7811902 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/1/artifact/out/diff-checkstyle-hbase-server.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/1/artifact/out/diff-checkstyle-hbase-mapreduce.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/1/artifact/out/patch-unit-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/1/artifact/out/patch-unit-hbase-mapreduce.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/1/artifact/out/patch-unit-hbase-endpoint.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/1/testReport/ |
| Max. process+thread count | 5399 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-endpoint U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 62 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 34 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 24 | Maven dependency ordering for branch |
| +1 | mvninstall | 243 | master passed |
| +1 | compile | 102 | master passed |
| +1 | checkstyle | 99 | master passed |
| +1 | shadedjars | 265 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 272 | master passed |
| +1 | javadoc | 63 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for patch |
| +1 | mvninstall | 235 | the patch passed |
| +1 | compile | 102 | the patch passed |
| +1 | javac | 102 | the patch passed |
| -1 | checkstyle | 67 | hbase-server: The patch generated 3 new + 6 unchanged - 3 fixed = 9 total (was 9) |
| -1 | checkstyle | 17 | hbase-mapreduce: The patch generated 2 new + 7 unchanged - 2 fixed = 9 total (was 9) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 271 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 704 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 291 | the patch passed |
| +1 | javadoc | 57 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8244 | hbase-server in the patch failed. |
| +1 | unit | 1017 | hbase-mapreduce in the patch passed. |
| +1 | unit | 173 | hbase-endpoint in the patch passed. |
| +1 | asflicense | 83 | The patch does not generate ASF License warnings. |
| | | 12763 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |
|   | hadoop.hbase.replication.TestReplicationSyncUpToolWithBulkLoadedData |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/285 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 5644de7f357a 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / ab99e2486e |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/2/artifact/out/diff-checkstyle-hbase-server.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/2/artifact/out/diff-checkstyle-hbase-mapreduce.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/2/testReport/ |
| Max. process+thread count | 5619 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-endpoint U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Seems TestReplicationSyncUpToolWithBulkLoadedData is failing. Let me dig.

**Comment by Apache9** [comment]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 55.785 s <<< FAILURE! - in org.apache.hadoop.hbase.replication.TestReplicationSyncUpToolWithBulkLoadedData
[ERROR] testSyncUpTool(org.apache.hadoop.hbase.replication.TestReplicationSyncUpToolWithBulkLoadedData)  Time elapsed: 55.715 s  <<< FAILURE!
java.lang.AssertionError: t1_syncup has 103 rows on source, and 100 on slave1 expected:<100> but was:<0>
	at org.apache.hadoop.hbase.replication.TestReplicationSyncUpToolWithBulkLoadedData.wait(TestReplicationSyncUpToolWithBulkLoadedData.java:232)
	at org.apache.hadoop.hbase.replication.TestReplicationSyncUpToolWithBulkLoadedData.loadAndReplicateHFiles(TestReplicationSyncUpToolWithBulkLoadedData.java:199)
	at org.apache.hadoop.hbase.replication.TestReplicationSyncUpToolWithBulkLoadedData.testSyncUpTool(TestReplicationSyncUpToolWithBulkLoadedData.java:94)

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 34 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for branch |
| +1 | mvninstall | 229 | master passed |
| +1 | compile | 100 | master passed |
| +1 | checkstyle | 92 | master passed |
| +1 | shadedjars | 267 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 305 | master passed |
| +1 | javadoc | 64 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for patch |
| +1 | mvninstall | 252 | the patch passed |
| +1 | compile | 103 | the patch passed |
| +1 | javac | 103 | the patch passed |
| -1 | checkstyle | 69 | hbase-server: The patch generated 3 new + 6 unchanged - 3 fixed = 9 total (was 9) |
| -1 | checkstyle | 17 | hbase-mapreduce: The patch generated 2 new + 7 unchanged - 2 fixed = 9 total (was 9) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 276 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 786 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 327 | the patch passed |
| +1 | javadoc | 61 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8123 | hbase-server in the patch passed. |
| +1 | unit | 1007 | hbase-mapreduce in the patch passed. |
| +1 | unit | 171 | hbase-endpoint in the patch passed. |
| +1 | asflicense | 106 | The patch does not generate ASF License warnings. |
| | | 12784 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/285 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 269f2f0fe08f 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / ab99e2486e |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/3/artifact/out/diff-checkstyle-hbase-server.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/3/artifact/out/diff-checkstyle-hbase-mapreduce.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/3/testReport/ |
| Max. process+thread count | 5643 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-endpoint U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 27 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 34 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 28 | Maven dependency ordering for branch |
| +1 | mvninstall | 255 | master passed |
| +1 | compile | 109 | master passed |
| +1 | checkstyle | 101 | master passed |
| +1 | shadedjars | 269 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 254 | master passed |
| +1 | javadoc | 67 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for patch |
| +1 | mvninstall | 250 | the patch passed |
| +1 | compile | 106 | the patch passed |
| +1 | javac | 106 | the patch passed |
| +1 | checkstyle | 69 | hbase-server: The patch generated 0 new + 2 unchanged - 7 fixed = 2 total (was 9) |
| +1 | checkstyle | 19 | hbase-mapreduce: The patch generated 0 new + 3 unchanged - 6 fixed = 3 total (was 9) |
| +1 | checkstyle | 12 | The patch passed checkstyle in hbase-endpoint |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 270 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 746 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 307 | the patch passed |
| +1 | javadoc | 63 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8019 | hbase-server in the patch failed. |
| +1 | unit | 1016 | hbase-mapreduce in the patch passed. |
| +1 | unit | 162 | hbase-endpoint in the patch passed. |
| +1 | asflicense | 96 | The patch does not generate ASF License warnings. |
| | | 12626 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAsyncTableGetMultiThreaded |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/285 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 6d2da6e32045 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 51c49a1784 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/4/testReport/ |
| Max. process+thread count | 5421 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-mapreduce hbase-endpoint U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-285/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
