### PR TITLE
HBASE-17666 Removed remaining usage of SnapshotDescriptionUtils.SNAPSHOT_TIMEOUT_MILLIS_DEFAULT

### PR DESCRIPTION
**Pull request by HorizonNet**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 302 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 379 | master passed |
| +1 | compile | 68 | master passed |
| +1 | checkstyle | 93 | master passed |
| +1 | shadedjars | 357 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 191 | master passed |
| +1 | javadoc | 43 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 320 | the patch passed |
| +1 | compile | 69 | the patch passed |
| +1 | javac | 69 | the patch passed |
| +1 | checkstyle | 91 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 333 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 684 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 201 | the patch passed |
| +1 | javadoc | 42 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 17534 | hbase-server in the patch failed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 20806 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestSnapshotTemporaryDirectory |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.master.TestSplitWALManager |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-121/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/121 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux eab9ad775b83 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 11547b79f3 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-121/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-121/1/testReport/ |
| Max. process+thread count | 4921 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-121/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
These tests are easy to fail in pre commit due to a slow machine.

So how could we trigger the QA again here? On jira we could just upload the patch again...

**Comment by busbey** [comment]
I retriggered it by going to the build and telling Jenkins to rebuild

**Comment by busbey** [comment]
Peter has things set up on one of the other repos to build again when someone comments with a certain keyword.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 295 | master passed |
| +1 | compile | 67 | master passed |
| +1 | checkstyle | 87 | master passed |
| +1 | shadedjars | 323 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 191 | master passed |
| +1 | javadoc | 41 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 299 | the patch passed |
| +1 | compile | 69 | the patch passed |
| +1 | javac | 69 | the patch passed |
| +1 | checkstyle | 86 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 317 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 608 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 202 | the patch passed |
| +1 | javadoc | 40 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 16796 | hbase-server in the patch failed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 19598 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleWAL |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.master.TestAssignmentManagerMetrics |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.namespace.TestNamespaceAuditor |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-121/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/121 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 68e9b60a5944 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 11547b79f3 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-121/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-121/2/testReport/ |
| Max. process+thread count | 4976 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-121/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
It seems that always the same tests fail for all PRs.

**Comment by HorizonNet** [comment]
Closing this one, because it will be part of #124 (HBASE-22186).

**Pull request closed without merging**
