### PR TITLE
HBASE-23110 Backport HBASE-23054 "Remove synchronization block from MetaTableMetrics and fix LossyCounting algorithm" to branch-1

### PR DESCRIPTION
**Pull request by apurtell**

### CODE REVIEW

**Comment by apurtell** [comment]
[INFO] -------------------------------------------------------
    [INFO]  T E S T S
    [INFO] -------------------------------------------------------
    [INFO] Running org.apache.hadoop.hbase.util.TestLossyCounting
    [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.881 s - in org.apache.hadoop.hbase.util.TestLossyCounting
    [INFO] Running org.apache.hadoop.hbase.coprocessor.TestMetaTableMetrics
    [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.004 s - in org.apache.hadoop.hbase.coprocessor.TestMetaTableMetrics

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 20s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| :green_heart: |  mvninstall  |   8m 36s |  branch-1 passed  |
| :green_heart: |  compile  |   0m 40s |  branch-1 passed with JDK v1.8.0_222  |
| :green_heart: |  compile  |   0m 44s |  branch-1 passed with JDK v1.7.0_232  |
| :green_heart: |  checkstyle  |   1m 30s |  branch-1 passed  |
| :green_heart: |  shadedjars  |   2m 57s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 35s |  branch-1 passed with JDK v1.8.0_222  |
| :green_heart: |  javadoc  |   0m 41s |  branch-1 passed with JDK v1.7.0_232  |
| :blue_heart: |  spotbugs  |   2m 48s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   2m 46s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   2m  0s |  the patch passed  |
| :green_heart: |  compile  |   0m 40s |  the patch passed with JDK v1.8.0_222  |
| :green_heart: |  javac  |   0m 40s |  the patch passed  |
| :green_heart: |  compile  |   0m 45s |  the patch passed with JDK v1.7.0_232  |
| :green_heart: |  javac  |   0m 45s |  the patch passed  |
| :broken_heart: |  checkstyle  |   1m 29s |  hbase-server: The patch generated 1 new + 1 unchanged - 1 fixed = 2 total (was 2)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   2m 47s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |   5m  0s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| :green_heart: |  javadoc  |   0m 32s |  the patch passed with JDK v1.8.0_222  |
| :green_heart: |  javadoc  |   0m 41s |  the patch passed with JDK v1.7.0_232  |
| :broken_heart: |  findbugs  |   2m 51s |  hbase-server generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0)  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 156m 34s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   0m 38s |  The patch does not generate ASF License warnings.  |
|  |   | 197m 30s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-server |
|  |  Unread field:LossyCounting.java:[line 56] |
|  |  Unread field:LossyCounting.java:[line 57] |
| Failed junit tests | hadoop.hbase.regionserver.TestRegionServerHostname |
|   | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/683 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux bfca61c45b83 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-683/out/precommit/personality/provided.sh |
| git revision | branch-1 / 0ffbf9c |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_222 /usr/lib/jvm/zulu-7-amd64:1.7.0_232 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/1/artifact/out/diff-checkstyle-hbase-server.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/1/artifact/out/new-findbugs-hbase-server.html |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/1/testReport/ |
| Max. process+thread count | 4113 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
The unit test failures are not related but let me fix the findbugs

**Comment by apurtell** [comment]
Rebased with fixes for findbugs and checkstyle warnings

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 20s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| :green_heart: |  mvninstall  |   8m 33s |  branch-1 passed  |
| :green_heart: |  compile  |   0m 42s |  branch-1 passed with JDK v1.8.0_222  |
| :green_heart: |  compile  |   0m 46s |  branch-1 passed with JDK v1.7.0_232  |
| :green_heart: |  checkstyle  |   1m 47s |  branch-1 passed  |
| :green_heart: |  shadedjars  |   3m 22s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 40s |  branch-1 passed with JDK v1.8.0_222  |
| :green_heart: |  javadoc  |   0m 47s |  branch-1 passed with JDK v1.7.0_232  |
| :blue_heart: |  spotbugs  |   3m 17s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   3m 13s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   2m 25s |  the patch passed  |
| :green_heart: |  compile  |   0m 50s |  the patch passed with JDK v1.8.0_222  |
| :green_heart: |  javac  |   0m 50s |  the patch passed  |
| :green_heart: |  compile  |   0m 55s |  the patch passed with JDK v1.7.0_232  |
| :green_heart: |  javac  |   0m 55s |  the patch passed  |
| :broken_heart: |  checkstyle  |   1m 49s |  hbase-server: The patch generated 1 new + 0 unchanged - 2 fixed = 1 total (was 2)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   3m 48s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |   5m 51s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| :green_heart: |  javadoc  |   0m 32s |  the patch passed with JDK v1.8.0_222  |
| :green_heart: |  javadoc  |   0m 41s |  the patch passed with JDK v1.7.0_232  |
| :green_heart: |  findbugs  |   3m  7s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 143m 20s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   0m 30s |  The patch does not generate ASF License warnings.  |
|  |   | 189m  1s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/683 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux ff9a3dc98828 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-683/out/precommit/personality/provided.sh |
| git revision | branch-1 / c63b2f4 |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_222 /usr/lib/jvm/zulu-7-amd64:1.7.0_232 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/2/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/2/testReport/ |
| Max. process+thread count | 4882 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-683/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
