### PR TITLE
HBASE-28066 Drop duplicate test class TestShellRSGroups.java

### PR DESCRIPTION
**Pull request by NihalJain**

### CODE REVIEW

**Comment by NihalJain** [comment]
Just noticed that TestShellRSGroups.java is misplaced and also because of same misplacement spotless skipped this file. I am assuming this file must have been misplaced due to human error, hence raised this PR.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 34s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 44s |  master passed  |
| +1 :green_heart: |  compile  |   0m 15s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 39s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 13s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 36s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 39s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   7m  9s |  hbase-shell in the patch passed.  |
|  |   |  24m 25s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5387 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 28ee1072c977 5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 97d512be7c |
| Default Java | Eclipse Adoptium-11.0.17+8 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/1/testReport/ |
| Max. process+thread count | 1563 (vs. ulimit of 30000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by NihalJain** [comment]
Just found another class https://github.com/apache/hbase/blob/master/hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestRSGroupShell.java which seems to be same as https://github.com/apache/hbase/blob/master/hbase-shell/src/test/rsgroup/org/apache/hadoop/hbase/client/rsgroup/TestShellRSGroups.java
Not sure though, need to verify.

**Comment by NihalJain** [comment]
Also, running `Hbase::RSGroupShellTest` from [TestShellRSGroups.java#L98C7-L98C67](https://github.com/apache/hbase/blob/97d512be7c9802fbba7890a7ff34a0e882cd8a84/hbase-shell/src/test/rsgroup/org/apache/hadoop/hbase/client/rsgroup/TestShellRSGroups.java#L98C7-L98C67) should be same as running `rsgroup_shell_test.rb` in [TestRSGroupShell.java#L48C1-L50C4](https://github.com/apache/hbase/blob/97d512be7c9802fbba7890a7ff34a0e882cd8a84/hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestRSGroupShell.java#L48C1-L50C4). 
Hence, I am guessing TestShellRSGroups.java must be duplicate, will check the test run logs and update here.

**Comment by NihalJain** [comment]
Ran `mvn test -pl :hbase-shell -Dtest=TestShellRSGroups,TestRSGroupShell` and was able to verify both classes run same set of tests.

Also same tables were created in both cases:
```
➜  surefire-reports git:(HBASE-28066) ll
total 10104
-rw-r--r--  1 nihjain  staff   1.0M Sep  7 01:54 TEST-org.apache.hadoop.hbase.client.TestRSGroupShell.xml
-rw-r--r--  1 nihjain  staff   855K Sep  7 01:54 TEST-org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups.xml
-rw-r--r--  1 nihjain  staff   1.1M Sep  7 01:54 org.apache.hadoop.hbase.client.TestRSGroupShell-output.txt
-rw-r--r--  1 nihjain  staff   344B Sep  7 01:54 org.apache.hadoop.hbase.client.TestRSGroupShell.txt
-rw-r--r--  1 nihjain  staff   963K Sep  7 01:54 org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups-output.txt
-rw-r--r--  1 nihjain  staff   362B Sep  7 01:54 org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups.txt

➜  surefire-reports git:(HBASE-28066) grep "Created table test_table" *-output.txt
org.apache.hadoop.hbase.client.TestRSGroupShell-output.txt:Created table test_table
org.apache.hadoop.hbase.client.TestRSGroupShell-output.txt:Created table test_table
org.apache.hadoop.hbase.client.TestRSGroupShell-output.txt:Created table test_table
org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups-output.txt:Created table test_table
org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups-output.txt:Created table test_table
org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups-output.txt:Created table test_table

➜  surefire-reports git:(HBASE-28066) grep "Created table test_namespace:test_ns_table" *-output.txt
org.apache.hadoop.hbase.client.TestRSGroupShell-output.txt:Created table test_namespace:test_ns_table
org.apache.hadoop.hbase.client.TestRSGroupShell-output.txt:Created table test_namespace:test_ns_table2
org.apache.hadoop.hbase.client.TestRSGroupShell-output.txt:Created table test_namespace:test_ns_table
org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups-output.txt:Created table test_namespace:test_ns_table
org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups-output.txt:Created table test_namespace:test_ns_table2
org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups-output.txt:Created table test_namespace:test_ns_table

➜  surefire-reports git:(HBASE-28066) grep "Created table test_namespace:test_ns_table2" *-output.txt
org.apache.hadoop.hbase.client.TestRSGroupShell-output.txt:Created table test_namespace:test_ns_table2
org.apache.hadoop.hbase.client.rsgroup.TestShellRSGroups-output.txt:Created table test_namespace:test_ns_table2
```

Sample test run logs from [TestRSGroupShell](https://github.com/apache/hbase/blob/master/hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestRSGroupShell.java)
```
2023-09-07T01:54:15,611 INFO  [Listener at localhost/52752 {}] client.AbstractTestShell(93): Starting ruby tests. includes: rsgroup_shell_test.rb excludes: 
Skip formatter_test.rb because of not included
Skip list_tables_test.rb because of not included
Skip converter_test.rb because of not included
Skip list_locks_test.rb because of not included
Skip list_procedures_test.rb because of not included
Skip commands_test.rb because of not included
Skip noninteractive_test.rb because of not included
Skip sftchange_shell_test.rb because of not included
Skip shell_test.rb because of not included
Skip quotas_test.rb because of not included
Skip replication_admin_test.rb because of not included
Skip taskmonitor_test.rb because of not included
Skip hbase_test.rb because of not included
Skip admin_test.rb because of not included
Skip balancer_utils_test.rb because of not included
Skip admin2_test.rb because of not included
Skip table_test.rb because of not included
Skip security_admin_test.rb because of not included
Skip visibility_labels_admin_test.rb because of not included
Loaded suite src/test/ruby/tests_runner
Started
```

Sample test run logs from [TestShellRSGroups](https://github.com/apache/hbase/blob/97d512be7c9802fbba7890a7ff34a0e882cd8a84/hbase-shell/src/test/rsgroup/org/apache/hadoop/hbase/client/rsgroup/TestShellRSGroups.java)
```
2023-09-07T01:54:15,791 INFO  [Listener at localhost/52758 {}] hbase.ResourceChecker(147): before: client.rsgroup.TestShellRSGroups#testRunShellTests Thread=497, OpenFileDescriptor=812, MaxFileDescriptor=10240, SystemLoadAverage=1399, ProcessCount=556, AvailableMemoryMB=4310
loading test file 'formatter_test.rb'.
loading test file 'list_tables_test.rb'.
loading test file 'converter_test.rb'.
loading test file 'list_locks_test.rb'.
loading test file 'list_procedures_test.rb'.
loading test file 'commands_test.rb'.
loading test file 'noninteractive_test.rb'.
loading test file 'sftchange_shell_test.rb'.
loading test file 'shell_test.rb'.
loading test file 'quotas_test.rb'.
loading test file 'replication_admin_test.rb'.
loading test file 'taskmonitor_test.rb'.
loading test file 'hbase_test.rb'.
loading test file 'admin_test.rb'.
loading test file 'balancer_utils_test.rb'.
loading test file 'admin2_test.rb'.
src/test/ruby/hbase/admin2_test.rb:386: warning: `+' after local variable or literal is interpreted as binary operator
src/test/ruby/hbase/admin2_test.rb:386: warning: even though it seems like unary operator
loading test file 'table_test.rb'.
loading test file 'security_admin_test.rb'.
loading test file 'visibility_labels_admin_test.rb'.
Only running tests that match Hbase::RSGroupShellTest
Loaded suite src/test/ruby/tests_runner
Started
```
So TestShellRSGroups is redundant, will drop the class from codebase, if analysis looks good to others. Please run `mvn test -pl :hbase-shell -Dtest=TestShellRSGroups,TestRSGroupShell` to cross check (assuming code is already built).

**Comment by NihalJain** [comment]
Updated description to reflect change based on above analysis. @Apache9 Could you please take a look at this?

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 25s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m  9s |  master passed  |
| +1 :green_heart: |  compile  |   0m 12s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 51s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 15s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 11s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 11s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 52s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   7m 47s |  hbase-shell in the patch passed.  |
|  |   |  24m  4s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/2/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5387 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux caf93960c281 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 97d512be7c |
| Default Java | Temurin-1.8.0_352-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/2/testReport/ |
| Max. process+thread count | 1732 (vs. ulimit of 30000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/2/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 33s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 36s |  master passed  |
| +1 :green_heart: |  compile  |   0m 15s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 40s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 40s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 45s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 11s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   7m  8s |  hbase-shell in the patch passed.  |
|  |   |  24m 15s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/2/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5387 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 29e7301f06c6 5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 97d512be7c |
| Default Java | Eclipse Adoptium-11.0.17+8 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/2/testReport/ |
| Max. process+thread count | 1563 (vs. ulimit of 30000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/2/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 26s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 46s |  master passed  |
| +1 :green_heart: |  compile  |   0m 14s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  5s |  master passed  |
| +1 :green_heart: |  spotless  |   0m 41s |  branch has no errors when running spotless:check.  |
| +1 :green_heart: |  spotbugs  |   0m  0s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 42s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 14s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 14s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  hadoopcheck  |  10m 20s |  Patch does not cause any errors with Hadoop 3.2.4 3.3.5.  |
| +1 :green_heart: |  spotless  |   0m 42s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  spotbugs  |   0m  0s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m  7s |  The patch does not generate ASF License warnings.  |
|  |   |  24m 48s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5387 |
| Optional Tests | dupname asflicense javac spotbugs hadoopcheck hbaseanti spotless checkstyle compile |
| uname | Linux ee534e3b954e 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 97d512be7c |
| Default Java | Eclipse Adoptium-11.0.17+8 |
| Max. process+thread count | 79 (vs. ulimit of 30000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5387/2/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by Apache9 — APPROVED** [review]

**Pull request merged**
