### PR TITLE
[BACKPORT] HBASE-25859 Reference class incorrectly parses the protobuf magic marker

### PR DESCRIPTION
**Pull request by catalin-luca**

### CODE REVIEW

**Comment by catalin-luca** [comment]
This is a back port of: https://issues.apache.org/jira/browse/HBASE-25859

**Comment by catalin-luca** [comment]
@busbey Any idea how I can re-trigger the build? Current failure is un-related to the changes in the patch.

**Comment by saintstack** [comment]
I retriggered the build. Do you want to point this fix at 1.7 since 1.4 is EOL'd? Thanks.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   8m 48s |  Docker failed to build yetus/hbase:7ff737df0f.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/3369 |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3369/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by catalin-luca** [comment]
@saintstack Thanks for the build.
Still seems to be failing with docker issues, though.

Currently we are kind of locked on HBase 1.4 (with no plans to upgrade in the near future).
So, it would be nice if could get this patch in 1.4. Thanks!

**Comment by saintstack** [comment]
Closing. PR is against a branch that has been EOL'd and we won't be making any more releases from it.

**Pull request closed without merging**
