### PR TITLE
HBASE-22407 add an option to use Hadoop metrics tags for table metrics (and fix some issues in metrics)

### PR DESCRIPTION
**Pull request by sershe-ms**
Most of the changes are actually just refactoring, like moving code into overridable methods so it could be overridden

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 64 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for branch |
| +1 | mvninstall | 245 | master passed |
| +1 | compile | 84 | master passed |
| +1 | checkstyle | 93 | master passed |
| +1 | shadedjars | 255 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 267 | master passed |
| +1 | javadoc | 63 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for patch |
| +1 | mvninstall | 235 | the patch passed |
| +1 | compile | 81 | the patch passed |
| +1 | javac | 81 | the patch passed |
| -1 | checkstyle | 13 | hbase-hadoop2-compat: The patch generated 18 new + 0 unchanged - 0 fixed = 18 total (was 0) |
| -1 | checkstyle | 70 | hbase-server: The patch generated 5 new + 5 unchanged - 3 fixed = 10 total (was 8) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 261 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 490 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| -1 | findbugs | 37 | hbase-hadoop2-compat generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | javadoc | 65 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 30 | hbase-hadoop-compat in the patch passed. |
| -1 | unit | 34 | hbase-hadoop2-compat in the patch failed. |
| +1 | unit | 8303 | hbase-server in the patch passed. |
| +1 | asflicense | 68 | The patch does not generate ASF License warnings. |
| | | 11151 | |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-hadoop2-compat |
|  |  org.apache.hadoop.hbase.regionserver.MetricsTableSourceImplWithTags doesn't override MetricsTableSourceImpl.equals(Object)  At MetricsTableSourceImplWithTags.java:At MetricsTableSourceImplWithTags.java:[line 1] |
| Failed junit tests | hadoop.hbase.regionserver.TestMetricsRegionServerSourceImpl |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/236 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 68f443fd956d 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 0797243365 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/1/artifact/out/diff-checkstyle-hbase-hadoop2-compat.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/1/artifact/out/diff-checkstyle-hbase-server.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/1/artifact/out/new-findbugs-hbase-hadoop2-compat.html |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/1/artifact/out/patch-unit-hbase-hadoop2-compat.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/1/testReport/ |
| Max. process+thread count | 4683 (vs. ulimit of 10000) |
| modules | C: hbase-hadoop-compat hbase-hadoop2-compat hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 23 | Maven dependency ordering for branch |
| +1 | mvninstall | 256 | master passed |
| +1 | compile | 103 | master passed |
| +1 | checkstyle | 94 | master passed |
| +1 | shadedjars | 293 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 262 | master passed |
| +1 | javadoc | 79 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| +1 | mvninstall | 261 | the patch passed |
| +1 | compile | 80 | the patch passed |
| +1 | javac | 80 | the patch passed |
| -1 | checkstyle | 18 | hbase-hadoop2-compat: The patch generated 18 new + 0 unchanged - 0 fixed = 18 total (was 0) |
| -1 | checkstyle | 63 | hbase-server: The patch generated 5 new + 5 unchanged - 3 fixed = 10 total (was 8) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 268 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 714 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| -1 | findbugs | 34 | hbase-hadoop2-compat generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | javadoc | 71 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 33 | hbase-hadoop-compat in the patch passed. |
| -1 | unit | 32 | hbase-hadoop2-compat in the patch failed. |
| +1 | unit | 12755 | hbase-server in the patch passed. |
| +1 | asflicense | 101 | The patch does not generate ASF License warnings. |
| | | 16192 | |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-hadoop2-compat |
|  |  org.apache.hadoop.hbase.regionserver.MetricsTableSourceImplWithTags doesn't override MetricsTableSourceImpl.equals(Object)  At MetricsTableSourceImplWithTags.java:At MetricsTableSourceImplWithTags.java:[line 1] |
| Failed junit tests | hadoop.hbase.regionserver.TestMetricsRegionServerSourceImpl |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/236 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux b2327ea304e6 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / ada772a1d3 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/2/artifact/out/diff-checkstyle-hbase-hadoop2-compat.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/2/artifact/out/diff-checkstyle-hbase-server.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/2/artifact/out/new-findbugs-hbase-hadoop2-compat.html |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/2/artifact/out/patch-unit-hbase-hadoop2-compat.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/2/testReport/ |
| Max. process+thread count | 4083 (vs. ulimit of 10000) |
| modules | C: hbase-hadoop-compat hbase-hadoop2-compat hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-236/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
@sershe-ms Could you please look into the merge conflict?

**Comment by Apache9** [comment]
Close since the PR is stale and can not be merged. Feel free to reopen.

**Pull request closed without merging**
