### PR TITLE
HBASE-28921 Avoid bundling hbase-webapps folder in default jars

### PR DESCRIPTION
**Pull request by NihalJain**
- Backports #6388

### CODE REVIEW

**Comment by NihalJain** [comment]
Verified following on branch-2.6
- Built code and ran hbase-shell unit tests locally
- Started hbase master in standalone, did basic shell sanity
- Started hbase-rest in standalone, did basic rest sanity
- Started hbase-thrift in standalone, ran thrift examples

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 49s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ branch-2.6 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m  5s |  |  branch-2.6 passed  |
| +1 :green_heart: |  compile  |   7m 23s |  |  branch-2.6 passed  |
| +1 :green_heart: |  spotless  |   1m 25s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 34s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   5m 56s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   5m 56s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  xmllint  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  hadoopcheck  |  21m 16s |  |  Patch does not cause any errors with Hadoop 2.10.2 or 3.3.6 3.4.0.  |
| +1 :green_heart: |  spotless  |   1m 18s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 55s |  |  The patch does not generate ASF License warnings.  |
|  |   |  51m 36s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6431/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6431 |
| Optional Tests | dupname asflicense javac codespell detsecrets xmllint hadoopcheck spotless compile |
| uname | Linux 965879e17446 5.4.0-200-generic #220-Ubuntu SMP Fri Sep 27 13:19:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.6 / 315118c5aed600e966c93753c1de1fd244242792 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| Max. process+thread count | 85 (vs. ulimit of 30000) |
| modules | C: hbase-server hbase-thrift hbase-rest U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6431/1/console |
| versions | git=2.34.1 maven=3.9.8 xmllint=20913 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 46s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.6 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m  9s |  |  branch-2.6 passed  |
| +1 :green_heart: |  compile  |   2m  8s |  |  branch-2.6 passed  |
| +1 :green_heart: |  javadoc  |   1m 16s |  |  branch-2.6 passed  |
| +1 :green_heart: |  shadedjars  |   6m 32s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 50s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 28s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 28s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 53s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 46s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 215m 22s |  |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |   6m 47s |  |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 48s |  |  hbase-rest in the patch passed.  |
|  |   | 255m 28s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6431/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6431 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 2cef074e13e1 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.6 / 315118c5aed600e966c93753c1de1fd244242792 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6431/1/testReport/ |
| Max. process+thread count | 4256 (vs. ulimit of 30000) |
| modules | C: hbase-server hbase-thrift hbase-rest U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6431/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 59s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  7s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.6 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   4m 44s |  |  branch-2.6 passed  |
| +1 :green_heart: |  compile  |   2m 32s |  |  branch-2.6 passed  |
| +1 :green_heart: |  javadoc  |   1m 19s |  |  branch-2.6 passed  |
| +1 :green_heart: |  shadedjars  |   8m 31s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m  6s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 44s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 44s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 33s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   7m 16s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 283m 37s |  |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |  26m  4s |  |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   5m  0s |  |  hbase-rest in the patch passed.  |
|  |   | 356m 54s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6431/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6431 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 2719a38c45d0 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.6 / 315118c5aed600e966c93753c1de1fd244242792 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6431/1/testReport/ |
| Max. process+thread count | 4268 (vs. ulimit of 30000) |
| modules | C: hbase-server hbase-thrift hbase-rest U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6431/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
