### PR TITLE
HBASE-23661 Reduced number of Checkstyle violations in hbase-rest

### PR DESCRIPTION
**Pull request by HorizonNet**
Backport of #1000 to branch-2.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 34s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  1s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 23s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   0m 30s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   0m 19s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   4m 10s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 24s |  branch-2 passed  |
| +0 :ok: |  spotbugs  |   0m 56s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   0m 54s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 30s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 30s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 17s |  hbase-rest: The patch generated 0 new + 0 unchanged - 19 fixed = 0 total (was 19)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 17s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  15m 14s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   0m 22s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   0m 58s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  14m 49s |  hbase-rest in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 14s |  The patch does not generate ASF License warnings.  |
|  |   |  60m  4s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.rest.TestSecureRESTServer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1066/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1066 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 66663472f1a5 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1066/out/precommit/personality/provided.sh |
| git revision | branch-2 / 70c69ba765 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1066/1/artifact/out/patch-unit-hbase-rest.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1066/1/testReport/ |
| Max. process+thread count | 402 (vs. ulimit of 10000) |
| modules | C: hbase-rest U: hbase-rest |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1066/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
+1 unless the test failure is relevant

**Comment by HorizonNet** [comment]
@virajjasani Test failure is not directly related. For me this test also fails on branch-2. Let me open a Jira for this one, if there's none already.

**Comment by HorizonNet** [comment]
For reference: Opened [HBASE-23709](https://issues.apache.org/jira/browse/HBASE-23709) for tracking the test failure.

**Pull request merged**
