### PR TITLE
HBASE-7003 Moved backup examples into hbase-examples

### PR DESCRIPTION
**Pull request by HorizonNet**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 19 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 25 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for branch |
| +1 | mvninstall | 264 | master passed |
| +1 | compile | 88 | master passed |
| +1 | checkstyle | 144 | master passed |
| +1 | shadedjars | 277 | branch has no errors when building our shaded downstream artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hbase-checkstyle |
| +1 | findbugs | 225 | master passed |
| +1 | javadoc | 60 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| +1 | mvninstall | 252 | the patch passed |
| +1 | compile | 86 | the patch passed |
| +1 | cc | 86 | the patch passed |
| +1 | javac | 86 | the patch passed |
| +1 | checkstyle | 142 | root: The patch generated 0 new + 0 unchanged - 68 fixed = 0 total (was 68) |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedjars | 275 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 520 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | hbaseprotoc | 72 | the patch passed |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hbase-checkstyle |
| +1 | findbugs | 276 | the patch passed |
| +1 | javadoc | 61 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 11 | hbase-checkstyle in the patch passed. |
| +1 | unit | 7533 | hbase-server in the patch passed. |
| +1 | unit | 107 | hbase-examples in the patch passed. |
| +1 | asflicense | 68 | The patch does not generate ASF License warnings. |
| | | 10618 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-145/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/145 |
| Optional Tests |  dupname  asflicense  checkstyle  javac  javadoc  unit  xml  findbugs  shadedjars  hadoopcheck  hbaseanti  compile  cc  hbaseprotoc  |
| uname | Linux 8c422b1ce546 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / f30d6c958a |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-145/1/testReport/ |
| Max. process+thread count | 4627 (vs. ulimit of 10000) |
| modules | C: hbase-checkstyle hbase-server hbase-examples U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-145/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
I thought one of the consensus points for getting the backup/restore stuff into master was that it would be isolated in the one module. Maybe I'm misremembering though?

**Comment by HorizonNet** [comment]
Wasn't aware of it. Should I remove the changes to the backup/restore stuff from this patch?

**Comment by saintstack** [comment]
Yes, it was important that the backup be totally contained in a module. In fact, now we have alternatives, backup should be moved out of core to something like hbase-operator-tools. Can bring it up on dev lists.

That said, your patch here looks like good cleanup @HorizonNet .  You are fixing formatting, line lengths, over-imports. Is that the nature of this patch no? If so, lets get it in.

**Comment by HorizonNet** [comment]
Core of the patch is to move everything into `hbase-examples`, but I tried to ensure that we don't get any Checkstyle issues during the move.

**Comment by saintstack** [comment]
Could we have a patch that has your cleanup only? i.e. no move to hbase-examples? There is good stuff in here. Would be shame to throw away? Maybe a new issue? Kill this one?

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 26 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 24 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 25 | Maven dependency ordering for branch |
| +1 | mvninstall | 269 | master passed |
| +1 | compile | 95 | master passed |
| +1 | checkstyle | 136 | master passed |
| +1 | shadedjars | 275 | branch has no errors when building our shaded downstream artifacts. |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hbase-checkstyle |
| +1 | findbugs | 247 | master passed |
| +1 | javadoc | 60 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for patch |
| +1 | mvninstall | 252 | the patch passed |
| +1 | compile | 94 | the patch passed |
| +1 | cc | 94 | the patch passed |
| +1 | javac | 94 | the patch passed |
| +1 | checkstyle | 139 | root: The patch generated 0 new + 0 unchanged - 27 fixed = 0 total (was 27) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 2 | The patch has no ill-formed XML file. |
| +1 | shadedjars | 274 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 787 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | hbaseprotoc | 73 | the patch passed |
| 0 | findbugs | 0 | Skipped patched modules with no Java source: hbase-checkstyle |
| +1 | findbugs | 275 | the patch passed |
| +1 | javadoc | 63 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 10 | hbase-checkstyle in the patch passed. |
| -1 | unit | 8511 | hbase-server in the patch failed. |
| +1 | unit | 107 | hbase-examples in the patch passed. |
| +1 | asflicense | 88 | The patch does not generate ASF License warnings. |
| | | 12164 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-145/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/145 |
| Optional Tests |  dupname  asflicense  checkstyle  javac  javadoc  unit  xml  findbugs  shadedjars  hadoopcheck  hbaseanti  compile  cc  hbaseprotoc  |
| uname | Linux b4d19cb94b77 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / ada772a1d3 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-145/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-145/3/testReport/ |
| Max. process+thread count | 4717 (vs. ulimit of 10000) |
| modules | C: hbase-checkstyle hbase-server hbase-examples U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-145/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
Closing this one and will open a new ticket. @saintstack Should I also close the corresponding ticket?

**Pull request closed without merging**
