### PR TITLE
HBASE-26814 Addendum: Fix spotbugs warning and clarify intent

### PR DESCRIPTION
**Pull request by bbeaudreault**
See discussion in https://issues.apache.org/jira/browse/HBASE-26814

### CODE REVIEW

**Comment by bbeaudreault** [comment]
I can't seem to get spotbugs to run locally in a useful way to verify this fix. I've tried various different permutations of mvn spotbugs:spotbugs, spotbugs:check, etc. We'll see what precommit check shows, but it didn't catch the original. If someone has a one-liner I can run I'd be happy to give it a shot

**Comment by ndimiduk** [comment]
You can look in the BlueOcean output of the General Checks to find it. The incantation looks like

```
[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1105)[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1106)[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1107)[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1108)[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1109)[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1110)[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1111)[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1112)[](https://ci-hbase.apache.org/blue/organizations/jenkins/HBase-PreCommit-GitHub-PR/detail/PR-4196/1/#step-87-log-1113)[2022-03-10T13:54:26.637Z] ============================================================================
[2022-03-10T13:54:26.637Z] ============================================================================
[2022-03-10T13:54:26.637Z]                       spotbugs detection: branch-2.5
[2022-03-10T13:54:26.637Z] ============================================================================
[2022-03-10T13:54:26.637Z] ============================================================================
[2022-03-10T13:54:26.637Z] 
[2022-03-10T13:54:26.637Z] 
[2022-03-10T13:54:26.637Z] [Thu Mar 10 13:54:19 UTC 2022 INFO]: Personality: branch spotbugs
[2022-03-10T13:54:26.637Z] cd /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-4196/yetus-general-check/src/hbase-server
[2022-03-10T13:54:26.637Z] /opt/maven/bin/mvn --batch-mode -Dmaven.repo.local=/home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-4196/yetus-m2/hbase-branch-2.5-patch-1 --threads=2 -DHBasePatchProcess test-compile spotbugs:spotbugs -DskipTests=true > /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-4196/yetus-general-check/output/branch-spotbugs-hbase-server.txt 2>&1
```

**Review by ndimiduk — APPROVED** [review]
Looks alright to me.

**Comment by apurtell** [comment]
When we cherry pick obviously spotbugs doesn't run. I do run unit tests locally, but this will vary by individual. It is interesting that the settings might be different per branch.

**Review by apurtell — APPROVED** [review]

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  4s |  https://github.com/apache/hbase/pull/4201 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/4201 |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4201/1/console |
| versions | git=2.25.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  7s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  3s |  https://github.com/apache/hbase/pull/4201 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4201/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4201 |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4201/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  3s |  https://github.com/apache/hbase/pull/4201 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/4201 |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4201/1/console |
| versions | git=2.25.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
