### PR TITLE
HBASE-23572 In 'HBCK Report', distringush between live, dead, and unk…

### PR DESCRIPTION
**Pull request by saintstack**
…nown servers

Give the 'HBCK Report' an edit while we're in here filling in a bit more help text.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 31s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-2.2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 35s |  branch-2.2 passed  |
| +1 :green_heart: |  javadoc  |   0m 36s |  branch-2.2 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 10s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 33s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 221m 57s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   | 236m  3s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-938/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/938 |
| Optional Tests | dupname asflicense javac javadoc unit |
| uname | Linux 1aa02f310705 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-938/out/precommit/personality/provided.sh |
| git revision | branch-2.2 / 2e651fbc63 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-938/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-938/1/testReport/ |
| Max. process+thread count | 4385 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-938/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
Thanks for review @busbey . Trying it out on cluster first before committing in case I messed it up (hard to test...)

**Comment by saintstack** [comment]
Pushed fix for a spelling mistake. Looks like this is working. Just need a bit more confirmation. Will be back.

**Comment by saintstack** [comment]
Verified does right thing. Then merge it manually.

**Pull request closed without merging**
