### PR TITLE
HBASE-23825 Increment proto conversion is broken

### PR DESCRIPTION
**Pull request by abhishek-chouhan**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 48s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  1s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 26s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 33s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 10s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  compile  |   1m 16s |  branch-1 passed with JDK v1.7.0_252  |
| +1 :green_heart: |  checkstyle  |   4m  5s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   2m 55s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 49s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   0m 53s |  branch-1 passed with JDK v1.7.0_252  |
| +0 :ok: |  spotbugs  |   2m 41s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m 56s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   1m 13s |  root in the patch failed.  |
| +1 :green_heart: |  compile  |   1m  2s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javac  |   1m  2s |  the patch passed  |
| -1 :x: |  compile  |   0m 48s |  hbase-server in the patch failed with JDK v1.7.0_252.  |
| -1 :x: |  javac  |   0m 48s |  hbase-server in the patch failed with JDK v1.7.0_252.  |
| -1 :x: |  checkstyle  |   1m 29s |  hbase-server: The patch generated 1 new + 8 unchanged - 1 fixed = 9 total (was 9)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   1m 56s |  patch has 16 errors when building our shaded downstream artifacts.  |
| -1 :x: |  hadoopcheck  |   1m  8s |  The patch causes 16 errors with Hadoop v2.8.5.  |
| -1 :x: |  hadoopcheck  |   3m 12s |  The patch causes 16 errors with Hadoop v2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 41s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   0m 53s |  the patch passed with JDK v1.7.0_252  |
| -1 :x: |  findbugs  |   0m 42s |  hbase-server in the patch failed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  hbase-protocol in the patch passed.  |
| -1 :x: |  unit  |   0m 43s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 25s |  The patch does not generate ASF License warnings.  |
|  |   |  46m 46s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1161 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux e6f1128f058d 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1161/out/precommit/personality/provided.sh |
| git revision | branch-1 / 942bb77 |
| Default Java | 1.7.0_252 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_242 /usr/lib/jvm/zulu-7-amd64:1.7.0_252 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/patch-compile-hbase-server-jdk1.7.0_252.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/patch-compile-hbase-server-jdk1.7.0_252.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/diff-checkstyle-hbase-server.txt |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/patch-shadedjars.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/patch-javac-2.8.5.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/patch-javac-2.9.2.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/patch-findbugs-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/testReport/ |
| Max. process+thread count | 87 (vs. ulimit of 10000) |
| modules | C: hbase-protocol hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by abhishek-chouhan** [comment]
Fixing test to work with 1.7.

**Comment by apurtell** [comment]
Assuming the test passes with 7 now, good to merge

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  21m  8s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 21s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 27s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 13s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  compile  |   1m 15s |  branch-1 passed with JDK v1.7.0_252  |
| +1 :green_heart: |  checkstyle  |   4m 41s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m 10s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 48s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   0m 54s |  branch-1 passed with JDK v1.7.0_252  |
| +0 :ok: |  spotbugs  |   2m 55s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   5m 17s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  6s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  8s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javac  |   1m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 13s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  javac  |   1m 13s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 44s |  hbase-server: The patch generated 1 new + 8 unchanged - 1 fixed = 9 total (was 9)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   3m  4s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   5m 33s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 43s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   0m 54s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  findbugs  |   5m 49s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 30s |  hbase-protocol in the patch passed.  |
| -1 :x: |  unit  |  39m 47s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  The patch does not generate ASF License warnings.  |
|  |   | 117m 55s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.ipc.TestSimpleRpcScheduler |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1161 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 6a0dfe797c04 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1161/out/precommit/personality/provided.sh |
| git revision | branch-1 / 942bb77 |
| Default Java | 1.7.0_252 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_242 /usr/lib/jvm/zulu-7-amd64:1.7.0_252 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/2/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/2/testReport/ |
| Max. process+thread count | 711 (vs. ulimit of 10000) |
| modules | C: hbase-protocol hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by abhishek-chouhan** [comment]
Test failure looks unrelated and passes locally reliably. Fixing import order and letting qa run again.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 29s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 26s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 33s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 40s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  compile  |   1m 45s |  branch-1 passed with JDK v1.7.0_252  |
| +1 :green_heart: |  checkstyle  |   6m 15s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   4m 20s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  1s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   1m  8s |  branch-1 passed with JDK v1.7.0_252  |
| +0 :ok: |  spotbugs  |   4m 13s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   7m 20s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 21s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 36s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 46s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javac  |   1m 46s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 46s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  javac  |   1m 46s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   3m 36s |  The patch passed checkstyle in hbase-protocol  |
| +1 :green_heart: |  checkstyle  |   2m 21s |  hbase-server: The patch generated 0 new + 7 unchanged - 2 fixed = 7 total (was 9)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   3m 50s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   5m 35s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 41s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   0m 54s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  findbugs  |   5m 46s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 29s |  hbase-protocol in the patch passed.  |
| -1 :x: |  unit  | 156m 38s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  The patch does not generate ASF License warnings.  |
|  |   | 227m 40s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.mapreduce.TestLoadIncrementalHFilesUseSecurityEndPoint |
|   | hadoop.hbase.wal.TestWALSplitBoundedLogWriterCreation |
|   | hadoop.hbase.mapreduce.TestLoadIncrementalHFiles |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1161 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 15d59bf1e2c0 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1161/out/precommit/personality/provided.sh |
| git revision | branch-1 / 942bb77 |
| Default Java | 1.7.0_252 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_242 /usr/lib/jvm/zulu-7-amd64:1.7.0_252 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/3/testReport/ |
| Max. process+thread count | 4292 (vs. ulimit of 10000) |
| modules | C: hbase-protocol hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/3/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by abhishek-chouhan** [comment]
Bunch of tests timed out(which pass locally). Getting one more QA.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 26s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 26s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 22s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 40s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  compile  |   1m 50s |  branch-1 passed with JDK v1.7.0_252  |
| +1 :green_heart: |  checkstyle  |   6m 33s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   4m 29s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 11s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   1m 17s |  branch-1 passed with JDK v1.7.0_252  |
| +0 :ok: |  spotbugs  |   4m  5s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   7m 39s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m  1s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 44s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javac  |   1m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 38s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  javac  |   1m 38s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   3m 42s |  The patch passed checkstyle in hbase-protocol  |
| +1 :green_heart: |  checkstyle  |   2m 14s |  hbase-server: The patch generated 0 new + 7 unchanged - 2 fixed = 7 total (was 9)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m  9s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   6m 57s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   1m  6s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   1m 13s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  findbugs  |   6m 59s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 33s |  hbase-protocol in the patch passed.  |
| -1 :x: |  unit  | 160m  8s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  The patch does not generate ASF License warnings.  |
|  |   | 236m 53s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1161 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux e89ef3877e8c 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1161/out/precommit/personality/provided.sh |
| git revision | branch-1 / 942bb77 |
| Default Java | 1.7.0_252 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_242 /usr/lib/jvm/zulu-7-amd64:1.7.0_252 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/4/testReport/ |
| Max. process+thread count | 4290 (vs. ulimit of 10000) |
| modules | C: hbase-protocol hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1161/4/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
Better result, and TestRegionReplicaReplicationEndpoint seems unrelated.

**Comment by abhishek-chouhan** [comment]
As @apurtell pointed out, test failure is unrelated and due to a timeout. Will commit this later today, unless objections.

**Pull request merged**
