### PR TITLE
HBASE-21777 Only log compaction pressure throughput when changed or traced

### PR DESCRIPTION
**Pull request by taklwu**
address issue mentioned on https://issues.apache.org/jira/browse/HBASE-21777

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 819 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | findbugs | 0 | Findbugs executables are not available. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 123 | branch-1 passed |
| +1 | compile | 39 | branch-1 passed with JDK v1.8.0_212 |
| +1 | compile | 42 | branch-1 passed with JDK v1.7.0_222 |
| +1 | checkstyle | 83 | branch-1 passed |
| +1 | shadedjars | 171 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 34 | branch-1 passed with JDK v1.8.0_212 |
| +1 | javadoc | 38 | branch-1 passed with JDK v1.7.0_222 |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 101 | the patch passed |
| +1 | compile | 38 | the patch passed with JDK v1.8.0_212 |
| +1 | javac | 38 | the patch passed |
| +1 | compile | 41 | the patch passed with JDK v1.7.0_222 |
| +1 | javac | 41 | the patch passed |
| +1 | checkstyle | 81 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 166 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 98 | Patch does not cause any errors with Hadoop 2.7.4. |
| +1 | javadoc | 28 | the patch passed with JDK v1.8.0_212 |
| +1 | javadoc | 39 | the patch passed with JDK v1.7.0_222 |
||| _ Other Tests _ |
| +1 | unit | 5949 | hbase-server in the patch passed. |
| +1 | asflicense | 21 | The patch does not generate ASF License warnings. |
| | | 7991 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/216 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 726dedf115d5 4.4.0-137-generic #163~14.04.1-Ubuntu SMP Mon Sep 24 17:14:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-1 / 26b9e76 |
| maven | version: Apache Maven 3.0.5 |
| Default Java | 1.7.0_222 |
| Multi-JDK versions |  /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_212 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_222 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/1/testReport/ |
| Max. process+thread count | 3730 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by carp84** [comment]
Please check comments in HBASE-21777 and let me know your thoughts. Thanks.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | findbugs | 1 | Findbugs executables are not available. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 128 | branch-1 passed |
| +1 | compile | 44 | branch-1 passed with JDK v1.8.0_212 |
| +1 | compile | 41 | branch-1 passed with JDK v1.7.0_222 |
| +1 | checkstyle | 83 | branch-1 passed |
| +1 | shadedjars | 169 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 31 | branch-1 passed with JDK v1.8.0_212 |
| +1 | javadoc | 38 | branch-1 passed with JDK v1.7.0_222 |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 102 | the patch passed |
| +1 | compile | 39 | the patch passed with JDK v1.8.0_212 |
| +1 | javac | 39 | the patch passed |
| +1 | compile | 41 | the patch passed with JDK v1.7.0_222 |
| +1 | javac | 41 | the patch passed |
| +1 | checkstyle | 80 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 165 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 100 | Patch does not cause any errors with Hadoop 2.7.4. |
| +1 | javadoc | 28 | the patch passed with JDK v1.8.0_212 |
| +1 | javadoc | 38 | the patch passed with JDK v1.7.0_222 |
||| _ Other Tests _ |
| -1 | unit | 5989 | hbase-server in the patch failed. |
| +1 | asflicense | 21 | The patch does not generate ASF License warnings. |
| | | 7620 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.security.access.TestAccessController3 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/216 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux bb821c095bc2 4.4.0-137-generic #163~14.04.1-Ubuntu SMP Mon Sep 24 17:14:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-1 / 26b9e76 |
| maven | version: Apache Maven 3.0.5 |
| Default Java | 1.7.0_222 |
| Multi-JDK versions |  /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_212 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_222 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/2/testReport/ |
| Max. process+thread count | 4245 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by taklwu** [comment]
I ran the test `TestAccessController3` manually and didn't see this error, maybe I edit the commit message and rerun the autotest test ?

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.hbase.security.access.TestAccessController3
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.46 s - in org.apache.hadoop.hbase.security.access.TestAccessController3
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (secondPartTestsExecution) @ hbase-server ---
[INFO] Tests are skipped.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.925 s
[INFO] Finished at: 2019-05-06T21:38:52Z
[INFO] ------------------------------------------------------------------------

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 31 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | findbugs | 0 | Findbugs executables are not available. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 192 | branch-1 passed |
| +1 | compile | 37 | branch-1 passed with JDK v1.8.0_212 |
| +1 | compile | 42 | branch-1 passed with JDK v1.7.0_222 |
| +1 | checkstyle | 82 | branch-1 passed |
| +1 | shadedjars | 169 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 35 | branch-1 passed with JDK v1.8.0_212 |
| +1 | javadoc | 41 | branch-1 passed with JDK v1.7.0_222 |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 113 | the patch passed |
| +1 | compile | 40 | the patch passed with JDK v1.8.0_212 |
| +1 | javac | 40 | the patch passed |
| +1 | compile | 46 | the patch passed with JDK v1.7.0_222 |
| +1 | javac | 46 | the patch passed |
| +1 | checkstyle | 81 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 159 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 107 | Patch does not cause any errors with Hadoop 2.7.4. |
| +1 | javadoc | 30 | the patch passed with JDK v1.8.0_212 |
| +1 | javadoc | 41 | the patch passed with JDK v1.7.0_222 |
||| _ Other Tests _ |
| +1 | unit | 6031 | hbase-server in the patch passed. |
| +1 | asflicense | 23 | The patch does not generate ASF License warnings. |
| | | 7376 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/216 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux e603b6678234 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-1 / 26b9e76 |
| maven | version: Apache Maven 3.0.5 |
| Default Java | 1.7.0_222 |
| Multi-JDK versions |  /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_212 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_222 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/3/testReport/ |
| Max. process+thread count | 4349 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-216/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
