### PR TITLE
HBASE-8458 Support for batch version of checkAndPut() and checkAndDelete()

### PR DESCRIPTION
**Pull request by guangxuCheng**
batch checkAndxxx using existing batch method on Table.

detail see: https://issues.apache.org/jira/browse/HBASE-8458

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m  7s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :blue_heart: |  prototool  |   0m  0s |  prototool was not available.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 13s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 40s |  branch-2 passed  |
| :green_heart: |  compile  |   2m  4s |  branch-2 passed  |
| :green_heart: |  checkstyle  |   2m 24s |  branch-2 passed  |
| :green_heart: |  shadedjars  |   4m 31s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   1m 12s |  branch-2 passed  |
| :blue_heart: |  spotbugs  |   3m  7s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   6m 51s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   5m 13s |  the patch passed  |
| :green_heart: |  compile  |   2m  1s |  the patch passed  |
| :green_heart: |  cc  |   2m  1s |  the patch passed  |
| :green_heart: |  javac  |   2m  1s |  the patch passed  |
| :broken_heart: |  checkstyle  |   0m 43s |  hbase-client: The patch generated 3 new + 355 unchanged - 0 fixed = 358 total (was 355)  |
| :broken_heart: |  checkstyle  |   1m 31s |  hbase-server: The patch generated 9 new + 65 unchanged - 0 fixed = 74 total (was 65)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   4m 29s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  16m 42s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  hbaseprotoc  |   1m 52s |  the patch passed  |
| :green_heart: |  javadoc  |   1m 11s |  the patch passed  |
| :broken_heart: |  findbugs  |   1m 23s |  hbase-client generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
||| _ Other Tests _ |
| :green_heart: |  unit  |   0m 40s |  hbase-protocol-shaded in the patch passed.  |
| :green_heart: |  unit  |   3m 31s |  hbase-client in the patch passed.  |
| :broken_heart: |  unit  | 256m 28s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   1m 30s |  The patch does not generate ASF License warnings.  |
|  |   | 335m 17s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-client |
|  |  org.apache.hadoop.hbase.client.CheckAndRowMutate defines compareTo(Object) and uses Object.equals()  At CheckAndRowMutate.java:Object.equals()  At CheckAndRowMutate.java:[line 31] |
| Failed junit tests | hadoop.hbase.client.TestFromClientSideWithCoprocessor |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/594 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 866e6efb5853 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-594/out/precommit/personality/provided.sh |
| git revision | branch-2 / af86b7bd06 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/1/artifact/out/diff-checkstyle-hbase-client.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/1/artifact/out/diff-checkstyle-hbase-server.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/1/artifact/out/new-findbugs-hbase-client.html |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/1/testReport/ |
| Max. process+thread count | 4871 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 47s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :blue_heart: |  prototool  |   0m  0s |  prototool was not available.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 15s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 54s |  branch-2 passed  |
| :green_heart: |  compile  |   2m 17s |  branch-2 passed  |
| :green_heart: |  checkstyle  |   2m 31s |  branch-2 passed  |
| :green_heart: |  shadedjars  |   4m 14s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   1m 13s |  branch-2 passed  |
| :blue_heart: |  spotbugs  |   3m 16s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   6m 52s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   4m 44s |  the patch passed  |
| :green_heart: |  compile  |   2m  3s |  the patch passed  |
| :green_heart: |  cc  |   2m  3s |  the patch passed  |
| :green_heart: |  javac  |   2m  3s |  the patch passed  |
| :broken_heart: |  checkstyle  |   0m 44s |  hbase-client: The patch generated 2 new + 355 unchanged - 0 fixed = 357 total (was 355)  |
| :broken_heart: |  checkstyle  |   1m 19s |  hbase-server: The patch generated 1 new + 65 unchanged - 0 fixed = 66 total (was 65)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   4m 12s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  15m  0s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  hbaseprotoc  |   1m 53s |  the patch passed  |
| :green_heart: |  javadoc  |   1m 14s |  the patch passed  |
| :green_heart: |  findbugs  |   7m 10s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  |   0m 41s |  hbase-protocol-shaded in the patch passed.  |
| :green_heart: |  unit  |   3m 32s |  hbase-client in the patch passed.  |
| :green_heart: |  unit  | 151m 46s |  hbase-server in the patch passed.  |
| :green_heart: |  asflicense  |   1m 29s |  The patch does not generate ASF License warnings.  |
|  |   | 227m 27s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/594 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux d7d56ec52647 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-594/out/precommit/personality/provided.sh |
| git revision | branch-2 / d17cbe183c |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/2/artifact/out/diff-checkstyle-hbase-client.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/2/artifact/out/diff-checkstyle-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/2/testReport/ |
| Max. process+thread count | 4479 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 36s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| :blue_heart: |  prototool  |   0m  0s |  prototool was not available.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 15s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 57s |  branch-2 passed  |
| :green_heart: |  compile  |   2m  1s |  branch-2 passed  |
| :green_heart: |  checkstyle  |   2m 18s |  branch-2 passed  |
| :green_heart: |  shadedjars  |   4m 11s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   1m 17s |  branch-2 passed  |
| :blue_heart: |  spotbugs  |   3m  9s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   6m 55s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   5m  0s |  the patch passed  |
| :green_heart: |  compile  |   2m  3s |  the patch passed  |
| :green_heart: |  cc  |   2m  3s |  the patch passed  |
| :green_heart: |  javac  |   2m  3s |  the patch passed  |
| :green_heart: |  checkstyle  |   2m 20s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   4m 21s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  15m 47s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  hbaseprotoc  |   1m 55s |  the patch passed  |
| :green_heart: |  javadoc  |   1m 14s |  the patch passed  |
| :green_heart: |  findbugs  |   7m 45s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  |   0m 41s |  hbase-protocol-shaded in the patch passed.  |
| :green_heart: |  unit  |   3m 39s |  hbase-client in the patch passed.  |
| :broken_heart: |  unit  | 176m 44s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   1m 30s |  The patch does not generate ASF License warnings.  |
|  |   | 253m 51s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.regionserver.TestWALEntryStream |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/594 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux ef30042b166f 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-594/out/precommit/personality/provided.sh |
| git revision | branch-2 / 1568e05507 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/3/testReport/ |
| Max. process+thread count | 4796 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
Oh. Rerunning tests but patch has conflicts. Mind fixing please @guangxuCheng  ?

**Comment by guangxuCheng** [comment]
> Oh. Rerunning tests but patch has conflicts. Mind fixing please @guangxuCheng ?

@saintstack Thanks for review. Rebased to current branch-2, pending QA, Thanks

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 40s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :blue_heart: |  prototool  |   0m  0s |  prototool was not available.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 30s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 13s |  branch-2 passed  |
| :green_heart: |  compile  |   1m 59s |  branch-2 passed  |
| :green_heart: |  checkstyle  |   2m 16s |  branch-2 passed  |
| :green_heart: |  shadedjars  |   4m 12s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   1m 15s |  branch-2 passed  |
| :blue_heart: |  spotbugs  |   3m 21s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   6m 55s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   4m 46s |  the patch passed  |
| :green_heart: |  compile  |   1m 59s |  the patch passed  |
| :green_heart: |  cc  |   1m 59s |  the patch passed  |
| :green_heart: |  javac  |   1m 59s |  the patch passed  |
| :green_heart: |  checkstyle  |   2m 14s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   4m 13s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  15m 15s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  hbaseprotoc  |   1m 51s |  the patch passed  |
| :green_heart: |  javadoc  |   1m 12s |  the patch passed  |
| :green_heart: |  findbugs  |   7m 22s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  |   0m 42s |  hbase-protocol-shaded in the patch passed.  |
| :green_heart: |  unit  |   3m 38s |  hbase-client in the patch passed.  |
| :green_heart: |  unit  | 160m 42s |  hbase-server in the patch passed.  |
| :green_heart: |  asflicense  |   1m 35s |  The patch does not generate ASF License warnings.  |
|  |   | 235m 36s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.3 Server=19.03.3 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/594 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 9b7e52fd7b96 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-594/out/precommit/personality/provided.sh |
| git revision | branch-2 / 18ff188d9d |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/5/testReport/ |
| Max. process+thread count | 4061 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-594/5/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by guangxuCheng** [comment]
@saintstack @Apache9 can you take a look? Thanks

**Comment by Apache9** [comment]
Could you please upload a patch against master?

**Comment by guangxuCheng** [comment]
Thanks @Apache9 for review. Create a new PR for master. #765

**Pull request closed without merging**
