### PR TITLE
HBASE-27260 Set version as 1.7.2 in branch-1 in prep for first RC of …

### PR DESCRIPTION
**Pull request by Apache9**
…1.7.2

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   9m 56s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 25s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 25s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   1m 21s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   3m 12s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   2m  1s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 42s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 59s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 32s |  branch-1 passed  |
| +0 :ok: |  mvndep  |   1m 43s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 24s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 15s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   1m 15s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 17s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  javac  |   1m 17s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   3m 16s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  3s |  The patch has 35 ill-formed XML file(s).  |
| +1 :green_heart: |  shadedjars  |   2m  1s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   3m  6s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   1m 39s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 55s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 184m  2s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   0m 21s |  The patch generated 1 ASF License warnings.  |
|  |   | 229m 26s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | hbase-annotations/pom.xml |
|   | hbase-archetypes/hbase-archetype-builder/pom.xml |
|   | hbase-archetypes/hbase-client-project/pom.xml |
|   | hbase-archetypes/hbase-shaded-client-project/pom.xml |
|   | hbase-archetypes/pom.xml |
|   | hbase-assembly/pom.xml |
|   | hbase-checkstyle/pom.xml |
|   | hbase-client/pom.xml |
|   | hbase-common/pom.xml |
|   | hbase-error-prone/pom.xml |
|   | hbase-examples/pom.xml |
|   | hbase-external-blockcache/pom.xml |
|   | hbase-hadoop-compat/pom.xml |
|   | hbase-hadoop2-compat/pom.xml |
|   | hbase-hbtop/pom.xml |
|   | hbase-it/pom.xml |
|   | hbase-metrics-api/pom.xml |
|   | hbase-metrics/pom.xml |
|   | hbase-prefix-tree/pom.xml |
|   | hbase-procedure/pom.xml |
|   | hbase-protocol/pom.xml |
|   | hbase-resource-bundle/pom.xml |
|   | hbase-rest/pom.xml |
|   | hbase-rsgroup/pom.xml |
|   | hbase-server/pom.xml |
|   | hbase-shaded/hbase-shaded-check-invariants/pom.xml |
|   | hbase-shaded/hbase-shaded-client/pom.xml |
|   | hbase-shaded/hbase-shaded-server/pom.xml |
|   | hbase-shaded/hbase-shaded-testing-util-tester/pom.xml |
|   | hbase-shaded/hbase-shaded-testing-util/pom.xml |
|   | hbase-shaded/pom.xml |
|   | hbase-shell/pom.xml |
|   | hbase-testing-util/pom.xml |
|   | hbase-thrift/pom.xml |
|   | pom.xml |
| Failed junit tests | hadoop.hbase.mapreduce.TestLoadIncrementalHFiles |
|   | hadoop.hbase.replication.TestReplicationKillSlaveRS |
|   | hadoop.hbase.snapshot.TestExportSnapshot |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.replication.TestReplicationEndpoint |
|   | hadoop.hbase.mapreduce.TestLoadIncrementalHFilesUseSecurityEndPoint |
|   | hadoop.hbase.master.TestMasterBalanceThrottling |
|   | hadoop.hbase.snapshot.TestExportSnapshotWithTemporaryDirectory |
|   | hadoop.hbase.mapreduce.TestSecureLoadIncrementalHFiles |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4671/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4671 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile checkstyle |
| uname | Linux fcb009b74904 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-4671/out/precommit/personality/provided.sh |
| git revision | branch-1 / d4b9fcec1b |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| xml | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4671/1/artifact/out/xml.txt |
| unit | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4671/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4671/1/testReport/ |
| asflicense | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4671/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 4238 (vs. ulimit of 10000) |
| modules | C: . hbase-annotations hbase-archetypes hbase-archetypes/hbase-archetype-builder hbase-archetypes/hbase-client-project hbase-archetypes/hbase-shaded-client-project hbase-assembly hbase-checkstyle hbase-client hbase-common hbase-error-prone hbase-examples hbase-external-blockcache hbase-hadoop-compat hbase-hadoop2-compat hbase-hbtop hbase-it hbase-metrics hbase-metrics-api hbase-prefix-tree hbase-procedure hbase-protocol hbase-resource-bundle hbase-rest hbase-rsgroup hbase-server hbase-shaded hbase-shaded/hbase-shaded-check-invariants hbase-shaded/hbase-shaded-client hbase-shaded/hbase-shaded-server hbase-shaded/hbase-shaded-testing-util hbase-shaded/hbase-shaded-testing-util-tester hbase-shell hbase-testing-util hbase-thrift U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4671/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Run rat check locally, no problem.

```
Summary
-------
Generated at: 2022-07-31T16:34:25+00:00

Notes: 9
Binaries: 94
Archives: 0
Standards: 194

Apache Licensed: 193
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

1 Unknown Licenses

*****************************************************

Files with unapproved licenses:

  excludes
```

https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4671/1/artifact/out/patch-asflicense.txt

Seems to be an environment problem, the excludes file is not in our repo. Maybe we download it when running pre commit...

**Comment by Apache9** [comment]
Ran UTs locally and filtered the output

These are the failed UTs
```
[ERROR]   TestAdmin1.testRegionStateCleanupFromAMMemoryAfterRegionSplitAndMerge:1283 expected:<1> but was:<3>
[ERROR]   TestBlockReorderMultiBlocks.testHBaseCluster:214->testFromDFS:260 expected:<[zhangduo-VirtualBox]> but was:<[host1]>
[ERROR]   TestSlowLogAccessor.testHigherSlowLogs:227 Waiting timed out after [11,000] msec
[ERROR]   TestHRegion.testBatchPut_whileNoRowLocksHeld:1475 Metrics Counters should be equal expected:<158> but was:<157>
```

These are the crashed UTs
```
[ERROR] org.apache.hadoop.hbase.client.TestSnapshotCloneIndependence
[ERROR] org.apache.hadoop.hbase.client.TestFromClientSideNoCodec
[ERROR] org.apache.hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory
[ERROR] org.apache.hadoop.hbase.replication.TestMasterReplication
[ERROR] org.apache.hadoop.hbase.replication.regionserver.TestWALEntryStream
[ERROR] org.apache.hadoop.hbase.replication.regionserver.TestReplicationSink
[ERROR] org.apache.hadoop.hbase.client.TestSnapshotCloneIndependence
[ERROR] org.apache.hadoop.hbase.client.TestFromClientSideNoCodec
[ERROR] org.apache.hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory
[ERROR] org.apache.hadoop.hbase.replication.TestMasterReplication
[ERROR] org.apache.hadoop.hbase.replication.regionserver.TestWALEntryStream
[ERROR] org.apache.hadoop.hbase.replication.regionserver.TestReplicationSink
```

Let me try them separately.

**Comment by Apache9** [comment]
On the failed UTs, TestAdmin1 and TestSlowLogAccessor can pass locally, TestBlockReorderMultiBlocks passed in the pre commit build so it should be my environment. TestHRegion, TestRSGroupsAdmin2, TestRSGroupsBalance are still failing. Let me check whether they are OK in 1.7.1.

**Comment by Apache9** [comment]
OK, they are both fine on 1.7.1.

Let me take a look.

**Comment by Apache9** [comment]
Ah, tried again, they all passed for me locally. Should be flaky...

Let me check the crashed one.

https://nightlies.apache.org/hbase/HBase-Find-Flaky-Tests/branch-1/706/output/dashboard.html

This is the flaky list for branch-1.

**Review by GeorryHuang — APPROVED** [review]
+1

**Review by ddupg — APPROVED** [review]
+1

**Pull request merged**
