### PR TITLE
HBASE-23246 Fix error prone warning in TestMetricsUserSourceImpl

### PR DESCRIPTION
**Pull request by apurtell**
The self comparison check in TestMetricsUserSourceImpl triggers error-prone and is of little value, remove it.

### CODE REVIEW

**Comment by apurtell** [comment]
Thanks for reporting this @busbey

**Comment by apurtell** [comment]
The error-prone result is:

    TestMetricsUserSourceImpl.java:[50,29] [SelfComparison] An object is compared to itself

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| :green_heart: |  mvninstall  |   8m 29s |  branch-1 passed  |
| :green_heart: |  compile  |   0m 14s |  branch-1 passed with JDK v1.8.0_232  |
| :green_heart: |  compile  |   0m 17s |  branch-1 passed with JDK v1.7.0_242  |
| :green_heart: |  checkstyle  |   0m 18s |  branch-1 passed  |
| :green_heart: |  shadedjars  |   3m 10s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 19s |  branch-1 passed with JDK v1.8.0_232  |
| :green_heart: |  javadoc  |   0m 16s |  branch-1 passed with JDK v1.7.0_242  |
| :blue_heart: |  spotbugs  |   0m 50s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   0m 46s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   2m  5s |  the patch passed  |
| :green_heart: |  compile  |   0m 14s |  the patch passed with JDK v1.8.0_232  |
| :green_heart: |  javac  |   0m 14s |  the patch passed  |
| :green_heart: |  compile  |   0m 17s |  the patch passed with JDK v1.7.0_242  |
| :green_heart: |  javac  |   0m 17s |  the patch passed  |
| :green_heart: |  checkstyle  |   0m 14s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   3m  5s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |   5m 15s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| :green_heart: |  javadoc  |   0m 13s |  the patch passed with JDK v1.8.0_232  |
| :green_heart: |  javadoc  |   0m 17s |  the patch passed with JDK v1.7.0_242  |
| :green_heart: |  findbugs  |   0m 50s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  |   0m 35s |  hbase-hadoop2-compat in the patch passed.  |
| :green_heart: |  asflicense  |   0m 15s |  The patch does not generate ASF License warnings.  |
|  |   |  31m 26s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-789/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/789 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 7b06f8a753de 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-789/out/precommit/personality/provided.sh |
| git revision | branch-1 / 2451023 |
| Default Java | 1.7.0_242 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_232 /usr/lib/jvm/zulu-7-amd64:1.7.0_242 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-789/1/testReport/ |
| Max. process+thread count | 77 (vs. ulimit of 10000) |
| modules | C: hbase-hadoop2-compat U: hbase-hadoop2-compat |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-789/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
Thanks for the reviews!

**Pull request merged**
