### PR TITLE
HBASE-23921 Findbugs is OOM on master

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache9** [comment]
OK we have override the MAVEN_OPTS in personality script...

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 36s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  shellcheck  |   0m  3s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +0 :ok: |  asflicense  |   0m  0s |  ASF License check generated no output?  |
|  |   |   2m 18s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1235/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1235 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 13288f3ad2a8 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1235/out/precommit/personality/provided.sh |
| git revision | master / f411e395d3 |
| Max. process+thread count | 50 (vs. ulimit of 10000) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1235/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
How? And I think we only need to increase it for hbase-server module...

**Comment by busbey** [comment]
I think in the personality module function where we do our other plugin specific changing of how we handle maven we could set the the higher memory limit if we detect findbugs is going to run and the hbase-server module or root is in the changed set.

**Comment by ndimiduk** [comment]
Nightly downloads the personality file from master, so this is now enabled for all branches :(

**Pull request merged**
