### PR TITLE
HBASE-22922 Lock all regions to be merged in case of multi region merge (2.2)

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 40 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.2 Compile Tests _ |
| +1 | mvninstall | 306 | branch-2.2 passed |
| +1 | compile | 53 | branch-2.2 passed |
| +1 | checkstyle | 77 | branch-2.2 passed |
| +1 | shadedjars | 242 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 36 | branch-2.2 passed |
| 0 | spotbugs | 174 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 171 | branch-2.2 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 283 | the patch passed |
| +1 | compile | 52 | the patch passed |
| +1 | javac | 52 | the patch passed |
| +1 | checkstyle | 77 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 241 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 888 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 33 | the patch passed |
| +1 | findbugs | 182 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 9706 | hbase-server in the patch failed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 12797 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAsyncRegionAdminApi2 |
|   | hadoop.hbase.master.assignment.TestMasterAbortWhileMergingTable |
|   | hadoop.hbase.master.normalizer.TestSimpleRegionNormalizerOnCluster |
|   | hadoop.hbase.master.procedure.TestIgnoreUnknownFamily |
|   | hadoop.hbase.snapshot.TestMobFlushSnapshotFromClient |
|   | hadoop.hbase.master.assignment.TestModifyTableWhileMerging |
|   | hadoop.hbase.snapshot.TestFlushSnapshotFromClient |
|   | hadoop.hbase.client.TestTableFavoredNodes |
|   | hadoop.hbase.master.TestMergeTableRegionsWhileRSCrash |
|   | hadoop.hbase.client.TestSplitOrMergeAtTableLevel |
|   | hadoop.hbase.TestJMXListener |
|   | hadoop.hbase.replication.TestSerialReplication |
|   | hadoop.hbase.TestSequenceIdMonotonicallyIncreasing |
|   | hadoop.hbase.TestSplitMerge |
|   | hadoop.hbase.regionserver.TestRegionMergeTransactionOnCluster |
|   | hadoop.hbase.snapshot.TestConcurrentFlushSnapshotFromClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/543 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux a49867d77281 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-543/out/precommit/personality/provided.sh |
| git revision | branch-2.2 / 1d939c7944 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/1/testReport/ |
| Max. process+thread count | 4019 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 243 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.2 Compile Tests _ |
| +1 | mvninstall | 382 | branch-2.2 passed |
| +1 | compile | 56 | branch-2.2 passed |
| +1 | checkstyle | 89 | branch-2.2 passed |
| +1 | shadedjars | 283 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 38 | branch-2.2 passed |
| 0 | spotbugs | 207 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 205 | branch-2.2 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 331 | the patch passed |
| +1 | compile | 55 | the patch passed |
| +1 | javac | 55 | the patch passed |
| +1 | checkstyle | 90 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 260 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 992 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 36 | the patch passed |
| +1 | findbugs | 187 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 12266 | hbase-server in the patch failed. |
| +1 | asflicense | 25 | The patch does not generate ASF License warnings. |
| | | 15950 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/543 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux e6a432821236 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-543/out/precommit/personality/provided.sh |
| git revision | branch-2.2 / 1d939c7944 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/2/testReport/ |
| Max. process+thread count | 4589 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 38 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.2 Compile Tests _ |
| +1 | mvninstall | 371 | branch-2.2 passed |
| +1 | compile | 54 | branch-2.2 passed |
| +1 | checkstyle | 78 | branch-2.2 passed |
| +1 | shadedjars | 245 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 36 | branch-2.2 passed |
| 0 | spotbugs | 182 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 181 | branch-2.2 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 286 | the patch passed |
| +1 | compile | 55 | the patch passed |
| +1 | javac | 55 | the patch passed |
| +1 | checkstyle | 78 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 239 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 928 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 35 | the patch passed |
| +1 | findbugs | 172 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 9292 | hbase-server in the patch passed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 12508 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/543 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 7a02cfc90610 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-543/out/precommit/personality/provided.sh |
| git revision | branch-2.2 / 1d939c7944 |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/3/testReport/ |
| Max. process+thread count | 4217 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
Redundant, already merged from master PR to 2.2

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 75 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.2 Compile Tests _ |
| +1 | mvninstall | 314 | branch-2.2 passed |
| +1 | compile | 54 | branch-2.2 passed |
| +1 | checkstyle | 79 | branch-2.2 passed |
| +1 | shadedjars | 241 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 37 | branch-2.2 passed |
| 0 | spotbugs | 181 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 179 | branch-2.2 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 284 | the patch passed |
| +1 | compile | 52 | the patch passed |
| +1 | javac | 52 | the patch passed |
| +1 | checkstyle | 74 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 237 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 880 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 34 | the patch passed |
| +1 | findbugs | 167 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 14206 | hbase-server in the patch failed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 17324 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/543 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux d69c87f23498 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-543/out/precommit/personality/provided.sh |
| git revision | branch-2.2 / da72e2186b |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/4/testReport/ |
| Max. process+thread count | 4301 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-543/4/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
