### PR TITLE
HBASE-28840: Optimise memory utilization bucketcache retrieval from persistence.

### PR DESCRIPTION
**Pull request by jhungund**
During the persistence of bucket-cache backing map to a file, the backing map is divided into multiple smaller chunks and persisted to the file. This chunking avoids the high memory utilisation of during persistence, since only a small subset of backing map entries need to persisted in one chunk.

However, during the retrieval of the backing map during the server startup, we accumulate all these chunks into a list and then process each chunk to recreate the in-memory backing map. Since, all the chunks are fetched from the persistence file and then processed, the memory requirement is higher.

With this change, the retrieval of bucket-cache from persistence file is optimised to enable the processing of one chunk at a time to avoid high memory utilisation.

Change-Id: I12ed252d543be120183cbe5a3e769e5cda7998c1

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 21s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  |  Patch does not have any anti-patterns.  |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m  9s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   2m 51s |  |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   0m 39s |  |  branch-2 passed  |
| +1 :green_heart: |  spotbugs  |   1m 35s |  |  branch-2 passed  |
| +1 :green_heart: |  spotless  |   0m 48s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 54s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 15s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 15s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 57s |  |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   2m 21s |  |  the patch passed  |
| +1 :green_heart: |  hadoopcheck  |  19m  6s |  |  Patch does not cause any errors with Hadoop 2.10.2 or 3.3.6 3.4.0.  |
| +1 :green_heart: |  spotless  |   0m 53s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 13s |  |  The patch does not generate ASF License warnings.  |
|  |   |  40m 49s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6264 |
| JIRA Issue | HBASE-28840 |
| Optional Tests | dupname asflicense javac spotbugs checkstyle codespell detsecrets compile hadoopcheck hbaseanti spotless |
| uname | Linux ba379bbb7d20 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 79f6242edbb41fa1e1c4e92b4c995dc46e4c00cf |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| Max. process+thread count | 79 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/console |
| versions | git=2.34.1 maven=3.9.8 spotbugs=4.7.3 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 42s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m  9s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   0m 53s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 27s |  |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   5m 45s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 55s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 53s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 53s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 26s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 41s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 205m 34s |  |  hbase-server in the patch passed.  |
|  |   | 230m 40s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6264 |
| JIRA Issue | HBASE-28840 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 89152f77e191 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 79f6242edbb41fa1e1c4e92b4c995dc46e4c00cf |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/testReport/ |
| Max. process+thread count | 4431 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   1m 15s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 59s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   1m 24s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 45s |  |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   6m 40s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m  8s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 51s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 51s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 25s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   6m  7s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 218m 34s |  |  hbase-server in the patch passed.  |
|  |   | 248m 24s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6264 |
| JIRA Issue | HBASE-28840 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 70a1bd2b9540 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 79f6242edbb41fa1e1c4e92b4c995dc46e4c00cf |
| Default Java | Eclipse Adoptium-11.0.23+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/testReport/ |
| Max. process+thread count | 4353 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 44s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 36s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   0m 42s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 24s |  |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   5m 18s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 29s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 40s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 40s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 23s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 18s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 225m 53s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
|  |   | 249m 15s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6264 |
| JIRA Issue | HBASE-28840 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 30a88fc0fafd 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 79f6242edbb41fa1e1c4e92b4c995dc46e4c00cf |
| Default Java | Temurin-1.8.0_412-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/testReport/ |
| Max. process+thread count | 4182 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6264/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by jhungund** [comment]
Hi @wchevreuil ,
The test failures seem unrelated to these changes. I executed these changes on top of this change and the tests passed.

(base) janardhan.hungund@MacBook-Pro-4 hbase % git log
commit 79f6242edbb41fa1e1c4e92b4c995dc46e4c00cf (HEAD -> branch-2-for-HBASE-28840, upstream-fork/branch-2-for-HBASE-28840)
Author: Janardhan Hungund <janardhan.hungund@cloudera.com>
Date:   Sun Sep 15 18:43:07 2024 +0530

    HBASE-28840: Optimise memory utilization bucketcache retrieval from persistence.
    
  
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.hbase.quotas.TestQuotaAdmin
[INFO] Running org.apache.hadoop.hbase.client.TestClientScannerTimeouts
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.apache.hadoop.hbase.SystemExitRule (file:/Users/janardhan.hungund/hbase-down/hbase/hbase-common/target/hbase-common-2.7.0-SNAPSHOT-tests.jar)
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.hbase.SystemExitRule
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.apache.hadoop.hbase.SystemExitRule (file:/Users/janardhan.hungund/hbase-down/hbase/hbase-common/target/hbase-common-2.7.0-SNAPSHOT-tests.jar)
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.hbase.SystemExitRule
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.apache.hadoop.hbase.SystemExitRule$1 (file:/Users/janardhan.hungund/hbase-down/hbase/hbase-common/target/hbase-common-2.7.0-SNAPSHOT-tests.jar)
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.hbase.SystemExitRule$1
WARNING: System::setSecurityManager will be removed in a future release
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 85.283 s - in org.apache.hadoop.hbase.quotas.TestQuotaAdmin
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.apache.hadoop.hbase.SystemExitRule$1 (file:/Users/janardhan.hungund/hbase-down/hbase/hbase-common/target/hbase-common-2.7.0-SNAPSHOT-tests.jar)
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.hbase.SystemExitRule$1
WARNING: System::setSecurityManager will be removed in a future release
[INFO] Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 217.97 s - in org.apache.hadoop.hbase.client.TestClientScannerTimeouts
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 48, Failures: 0, Errors: 0, Skipped: 0

Can you please take a look?
Thanks,
Janardhan

**Review by wchevreuil — APPROVED** [review]

**Pull request merged**
