### PR TITLE
HBASE-21725 Implement BufferedMutator Based on AsyncBufferedMutator

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ HBASE-21512 Compile Tests _ |
| 0 | mvndep | 33 | Maven dependency ordering for branch |
| +1 | mvninstall | 246 | HBASE-21512 passed |
| +1 | compile | 76 | HBASE-21512 passed |
| +1 | checkstyle | 98 | HBASE-21512 passed |
| +1 | shadedjars | 260 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 213 | HBASE-21512 passed |
| +1 | javadoc | 54 | HBASE-21512 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for patch |
| +1 | mvninstall | 236 | the patch passed |
| +1 | compile | 72 | the patch passed |
| +1 | javac | 72 | the patch passed |
| -1 | checkstyle | 29 | hbase-client: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 252 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 489 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 254 | the patch passed |
| +1 | javadoc | 53 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 193 | hbase-client in the patch passed. |
| -1 | unit | 8677 | hbase-server in the patch failed. |
| +1 | asflicense | 55 | The patch does not generate ASF License warnings. |
| | | 11492 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.TestRegionMergeTransactionOnCluster |
|   | hadoop.hbase.client.TestBufferedMutator |
|   | hadoop.hbase.client.TestHbck |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/140 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 746e25029f57 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | HBASE-21512 / f47f6dfe51 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/1/artifact/out/diff-checkstyle-hbase-client.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/1/testReport/ |
| Max. process+thread count | 4785 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 18 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ HBASE-21512 Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for branch |
| +1 | mvninstall | 261 | HBASE-21512 passed |
| +1 | compile | 79 | HBASE-21512 passed |
| +1 | checkstyle | 104 | HBASE-21512 passed |
| +1 | shadedjars | 272 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 246 | HBASE-21512 passed |
| +1 | javadoc | 55 | HBASE-21512 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for patch |
| +1 | mvninstall | 254 | the patch passed |
| +1 | compile | 78 | the patch passed |
| +1 | javac | 78 | the patch passed |
| +1 | checkstyle | 105 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 275 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 533 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 298 | the patch passed |
| +1 | javadoc | 62 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 202 | hbase-client in the patch passed. |
| -1 | unit | 9160 | hbase-server in the patch failed. |
| +1 | asflicense | 54 | The patch does not generate ASF License warnings. |
| | | 12186 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.TestRegionMergeTransactionOnCluster |
|   | hadoop.hbase.replication.TestReplicationDroppedTables |
|   | hadoop.hbase.client.TestHbck |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/140 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 9badbcb24f6d 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | HBASE-21512 / f47f6dfe51 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/2/testReport/ |
| Max. process+thread count | 4893 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 44 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ HBASE-21512 Compile Tests _ |
| 0 | mvndep | 27 | Maven dependency ordering for branch |
| +1 | mvninstall | 268 | HBASE-21512 passed |
| +1 | compile | 81 | HBASE-21512 passed |
| +1 | checkstyle | 108 | HBASE-21512 passed |
| +1 | shadedjars | 280 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 289 | HBASE-21512 passed |
| +1 | javadoc | 61 | HBASE-21512 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for patch |
| +1 | mvninstall | 270 | the patch passed |
| +1 | compile | 86 | the patch passed |
| +1 | javac | 86 | the patch passed |
| +1 | checkstyle | 108 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 285 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 546 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 267 | the patch passed |
| +1 | javadoc | 56 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 194 | hbase-client in the patch passed. |
| -1 | unit | 14635 | hbase-server in the patch failed. |
| +1 | asflicense | 51 | The patch does not generate ASF License warnings. |
| | | 17766 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.quotas.TestSpaceQuotas |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicas |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/140 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 7cf768ed521d 4.4.0-144-generic #170~14.04.1-Ubuntu SMP Mon Mar 18 15:02:05 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | HBASE-21512 / f47f6dfe51 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/3/testReport/ |
| Max. process+thread count | 4640 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-140/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Ping @HorizonNet . Any other concerns? Thanks.

**Comment by HorizonNet** [comment]
@Apache9 No, my points are addressed.

**Pull request merged**
