### PR TITLE
HBASE-22812 InterfaceAudience annotation in CatalogJanitor uses fully…

### PR DESCRIPTION
**Pull request by syedmurtazahassan**
…-qualified name

### CODE REVIEW

**Comment by jatsakthi** [comment]
Will merge after the qa.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 78 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 447 | master passed |
| +1 | compile | 69 | master passed |
| +1 | checkstyle | 110 | master passed |
| +1 | shadedjars | 385 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 48 | master passed |
| 0 | spotbugs | 314 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 312 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 410 | the patch passed |
| +1 | compile | 70 | the patch passed |
| +1 | javac | 70 | the patch passed |
| -1 | checkstyle | 97 | hbase-server: The patch generated 1 new + 6 unchanged - 1 fixed = 7 total (was 7) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 365 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1199 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 41 | the patch passed |
| +1 | findbugs | 306 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 18777 | hbase-server in the patch failed. |
| +1 | asflicense | 39 | The patch does not generate ASF License warnings. |
| | | 23231 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestSnapshotTemporaryDirectory |
|   | hadoop.hbase.master.TestAssignmentManagerMetrics |
|   | hadoop.hbase.io.hfile.bucket.TestBucketCache |
|   | hadoop.hbase.replication.TestReplicationDisableInactivePeer |
|   | hadoop.hbase.replication.TestReplicationSmallTests |
|   | hadoop.hbase.regionserver.TestSplitTransactionOnCluster |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.replication.TestReplicationSmallTestsSync |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/462 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 04844dff8fa1 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-462/out/precommit/personality/provided.sh |
| git revision | master / 07c6bb16e7 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/1/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/1/testReport/ |
| Max. process+thread count | 4939 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jatsakthi** [comment]
The QA looks fine to me. The test failures are unrelated.

**Comment by jatsakthi** [comment]
Actually, @syedmurtazahassan the import order is wrong. Could you please rectify it? It's weird that the QA bot didn't point it out as a -1, even though it's pretty obvious here: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/1/artifact/out/diff-checkstyle-hbase-server.txt . Will file a separate jira for that.

**Comment by jatsakthi** [comment]
Yes Stack, I definitely think it should be < +1 or else it can be overlooked easily. (-0 being preferred).

**Comment by syedmurtazahassan** [comment]
@jatsakthi 
should i change the import order?

**Comment by jatsakthi** [comment]
@syedmurtazahassan Yes, please.

**Comment by syedmurtazahassan** [comment]
@jatsakthi 
Thanks for your comments. 

Changed the import order and now the checkstyle issue is gone.

**Comment by jatsakthi** [comment]
Thanks for the quick fix @syedmurtazahassan . Let's wait for the QA.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 110 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 360 | master passed |
| +1 | compile | 62 | master passed |
| +1 | checkstyle | 91 | master passed |
| +1 | shadedjars | 301 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 39 | master passed |
| 0 | spotbugs | 293 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 292 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 350 | the patch passed |
| +1 | compile | 63 | the patch passed |
| +1 | javac | 63 | the patch passed |
| -1 | checkstyle | 86 | hbase-server: The patch generated 1 new + 6 unchanged - 1 fixed = 7 total (was 7) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 300 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1041 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 36 | the patch passed |
| +1 | findbugs | 285 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 16235 | hbase-server in the patch failed. |
| +1 | asflicense | 34 | The patch does not generate ASF License warnings. |
| | | 20119 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.TestAssignmentManagerMetrics |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/462 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 9d32fb7609b7 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-462/out/precommit/personality/provided.sh |
| git revision | master / a9773ec5e8 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/2/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/2/testReport/ |
| Max. process+thread count | 4626 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 46 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 418 | master passed |
| +1 | compile | 76 | master passed |
| +1 | checkstyle | 106 | master passed |
| +1 | shadedjars | 340 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 47 | master passed |
| 0 | spotbugs | 336 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 333 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 384 | the patch passed |
| +1 | compile | 79 | the patch passed |
| +1 | javac | 79 | the patch passed |
| +1 | checkstyle | 122 | hbase-server: The patch generated 0 new + 6 unchanged - 1 fixed = 6 total (was 7) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 306 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1009 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 34 | the patch passed |
| +1 | findbugs | 254 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 9282 | hbase-server in the patch passed. |
| +1 | asflicense | 25 | The patch does not generate ASF License warnings. |
| | | 13288 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/462 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux ced9debd5fde 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-462/out/precommit/personality/provided.sh |
| git revision | master / a9773ec5e8 |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/3/testReport/ |
| Max. process+thread count | 4479 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-462/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
