### PR TITLE
HBASE-24839 Backport to branch-1 HBASE-20561 The way we stop a ReplicationSource may cause the RS down

### PR DESCRIPTION
**Pull request by thangTang**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  0s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  10m 36s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 27s |  branch-1 passed with JDK v1.8.0_262  |
| +1 :green_heart: |  compile  |   0m 30s |  branch-1 passed with JDK v1.7.0_272  |
| +1 :green_heart: |  checkstyle  |   0m 58s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m 15s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 37s |  branch-1 passed with JDK v1.8.0_262  |
| +1 :green_heart: |  javadoc  |   0m 26s |  branch-1 passed with JDK v1.7.0_272  |
| +0 :ok: |  spotbugs  |   1m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 39s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 19s |  the patch passed with JDK v1.8.0_262  |
| +1 :green_heart: |  javac  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 24s |  the patch passed with JDK v1.7.0_272  |
| +1 :green_heart: |  javac  |   0m 24s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 37s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 49s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 37s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 21s |  the patch passed with JDK v1.8.0_262  |
| +1 :green_heart: |  javadoc  |   0m 25s |  the patch passed with JDK v1.7.0_272  |
| +1 :green_heart: |  findbugs  |   1m 29s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 44s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 22s |  The patch does not generate ASF License warnings.  |
|  |   |  39m 18s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.12 Server=19.03.12 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2259/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2259 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 2878eb4bc86c 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2259/out/precommit/personality/provided.sh |
| git revision | branch-1 / c2e0cf9 |
| Default Java | 1.7.0_272 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_262 /usr/lib/jvm/zulu-7-amd64:1.7.0_272 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2259/1/testReport/ |
| Max. process+thread count | 148 (vs. ulimit of 10000) |
| modules | C: hbase-client U: hbase-client |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2259/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by thangTang** [comment]
Hi @infraio , could u help me to review this patch?

**Comment by Apache9** [comment]
The replication related code are completely different between 2.x and 1.x. For 2.x, we will abort the RS when we fail to modify zk, so the trick is how do we deal with zk failure when modifying zk.

Could you please explain a bit how do we deal with zk failure on branch-1?

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 51s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   9m 45s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 19s |  branch-1 passed with JDK v1.8.0_262  |
| +1 :green_heart: |  compile  |   0m 24s |  branch-1 passed with JDK v1.7.0_272  |
| +1 :green_heart: |  checkstyle  |   0m 46s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   2m 59s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 37s |  branch-1 passed with JDK v1.8.0_262  |
| +1 :green_heart: |  javadoc  |   0m 25s |  branch-1 passed with JDK v1.7.0_272  |
| +0 :ok: |  spotbugs  |   1m 41s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 39s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 18s |  the patch passed with JDK v1.8.0_262  |
| +1 :green_heart: |  javac  |   0m 18s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 24s |  the patch passed with JDK v1.7.0_272  |
| +1 :green_heart: |  javac  |   0m 24s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 51s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 39s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 19s |  the patch passed with JDK v1.8.0_262  |
| +1 :green_heart: |  javadoc  |   0m 27s |  the patch passed with JDK v1.7.0_272  |
| +1 :green_heart: |  findbugs  |   1m 32s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 44s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 22s |  The patch does not generate ASF License warnings.  |
|  |   |  43m 21s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.13 Server=19.03.13 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2259/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2259 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 6738799986f8 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2259/out/precommit/personality/provided.sh |
| git revision | branch-1 / e4a8dcc |
| Default Java | 1.7.0_272 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_262 /usr/lib/jvm/zulu-7-amd64:1.7.0_272 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2259/2/testReport/ |
| Max. process+thread count | 148 (vs. ulimit of 10000) |
| modules | C: hbase-client U: hbase-client |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2259/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
