### PR TITLE
HBASE-23834. Use shaded Jetty from hbase-thirdparty.

### PR DESCRIPTION
**Pull request by jojochuang**
This PR depends on HBASE-19256 so it won't run now.
But I'd like to share the amount of change it takes to use a shaded Jetty so the community can weigh in.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 31s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --findbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 46s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 26s |  master passed  |
| +1 :green_heart: |  compile  |   3m  9s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 48s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   5m 25s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m 29s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 12s |  root in the patch failed.  |
| -0 :warning: |  javac  |   0m 12s |  root in the patch failed.  |
| -1 :x: |  shadedjars  |   0m 28s |  patch has 11 errors when building our shaded downstream artifacts.  |
| -0 :warning: |  javadoc  |   0m 10s |  hbase-shaded in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 11s |  root in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  8s |  hbase-client in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-http in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  8s |  hbase-it in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-rest in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-server in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-shaded-mapreduce in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  8s |  hbase-thrift in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 31s |  root in the patch failed.  |
|  |   |  25m 21s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.7 Server=19.03.7 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1255 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 31fd48aa5b9d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1f77b1ffa5 |
| Default Java | 1.8.0_232 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-compile-root.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-compile-root.txt |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-shadedjars.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-hbase-shaded.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-root.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-hbase-client.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-hbase-http.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-hbase-it.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-hbase-rest.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-hbase-server.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-hbase-shaded_hbase-shaded-mapreduce.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-hbase-thrift.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/testReport/ |
| Max. process+thread count | 92 (vs. ulimit of 10000) |
| modules | C: hbase-shaded . hbase-client hbase-http hbase-it hbase-rest hbase-server hbase-shaded/hbase-shaded-mapreduce hbase-thrift U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/console |
| versions | git=2.17.1 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 31s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  Unprocessed flag(s): --brief-report-file --findbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 44s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   6m 31s |  master passed  |
| +1 :green_heart: |  compile  |   3m 53s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 55s |  branch has no errors when building our shaded downstream artifacts.  |
| -0 :warning: |  javadoc  |   0m 26s |  hbase-client in master failed.  |
| -0 :warning: |  javadoc  |   0m 17s |  hbase-http in master failed.  |
| -0 :warning: |  javadoc  |   0m 19s |  root in master failed.  |
| -0 :warning: |  javadoc  |   0m 22s |  hbase-rest in master failed.  |
| -0 :warning: |  javadoc  |   0m 38s |  hbase-server in master failed.  |
| -0 :warning: |  javadoc  |   0m 48s |  hbase-thrift in master failed.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m 35s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 12s |  root in the patch failed.  |
| -0 :warning: |  javac  |   0m 12s |  root in the patch failed.  |
| -1 :x: |  shadedjars  |   0m 32s |  patch has 11 errors when building our shaded downstream artifacts.  |
| -0 :warning: |  javadoc  |   0m 10s |  hbase-shaded in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 11s |  root in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-client in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-http in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 10s |  hbase-it in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 10s |  hbase-rest in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-server in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-shaded-mapreduce in the patch failed.  |
| -0 :warning: |  javadoc  |   0m  9s |  hbase-thrift in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 33s |  root in the patch failed.  |
|  |   |  25m 48s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.7 Server=19.03.7 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1255 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux f393e920cf0e 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1f77b1ffa5 |
| Default Java | 2020-01-14 |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-client.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-http.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-root.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-rest.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-server.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-thrift.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-compile-root.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-compile-root.txt |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-shadedjars.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-shaded.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-root.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-client.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-http.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-it.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-rest.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-server.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-shaded_hbase-shaded-mapreduce.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-thrift.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/testReport/ |
| Max. process+thread count | 99 (vs. ulimit of 10000) |
| modules | C: hbase-shaded . hbase-client hbase-http hbase-it hbase-rest hbase-server hbase-shaded/hbase-shaded-mapreduce hbase-thrift U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/console |
| versions | git=2.17.1 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 33s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 45s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 15s |  master passed  |
| +1 :green_heart: |  checkstyle  |   2m 21s |  master passed  |
| +0 :ok: |  spotbugs  |   1m 22s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 40s |  branch/hbase-shaded no findbugs output file (findbugsXml.xml)  |
| -1 :x: |  findbugs  |   8m 43s |  root in master failed.  |
| -1 :x: |  findbugs  |   2m 56s |  hbase-server in master failed.  |
| +0 :ok: |  findbugs  |   0m 20s |  branch/hbase-shaded/hbase-shaded-mapreduce no findbugs output file (findbugsXml.xml)  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m 29s |  root in the patch failed.  |
| -0 :warning: |  checkstyle  |   0m 10s |  The patch fails to run checkstyle in root  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m 12s |  The patch has no ill-formed XML file.  |
| -1 :x: |  hadoopcheck  |   0m 11s |  The patch causes 10 errors with Hadoop v2.8.5.  |
| -1 :x: |  hadoopcheck  |   0m 22s |  The patch causes 10 errors with Hadoop v2.9.2.  |
| -1 :x: |  hadoopcheck  |   0m 33s |  The patch causes 10 errors with Hadoop v3.1.2.  |
| -1 :x: |  findbugs  |   0m 11s |  hbase-shaded in the patch failed.  |
| -1 :x: |  findbugs  |   0m 12s |  root in the patch failed.  |
| -1 :x: |  findbugs  |   0m  8s |  hbase-client in the patch failed.  |
| -1 :x: |  findbugs  |   0m  9s |  hbase-http in the patch failed.  |
| -1 :x: |  findbugs  |   0m  9s |  hbase-rest in the patch failed.  |
| -1 :x: |  findbugs  |   0m  9s |  hbase-server in the patch failed.  |
| -1 :x: |  findbugs  |   0m  9s |  hbase-shaded-mapreduce in the patch failed.  |
| -1 :x: |  findbugs  |   0m  8s |  hbase-thrift in the patch failed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  32m  1s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.7 Server=19.03.7 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1255 |
| Optional Tests | dupname asflicense hadoopcheck xml spotbugs findbugs hbaseanti checkstyle |
| uname | Linux e32b4ff68e14 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1f77b1ffa5 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/branch-findbugs-root.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/branch-findbugs-hbase-server.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output//home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1255@2/yetus-general-check/output/maven-patch-checkstyle-root.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-javac-2.8.5.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-javac-2.9.2.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-javac-3.1.2.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-findbugs-hbase-shaded.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-findbugs-root.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-findbugs-hbase-client.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-findbugs-hbase-http.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-findbugs-hbase-rest.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-findbugs-hbase-server.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-findbugs-hbase-shaded_hbase-shaded-mapreduce.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/artifact/yetus-general-check/output/patch-findbugs-hbase-thrift.txt |
| Max. process+thread count | 93 (vs. ulimit of 10000) |
| modules | C: hbase-shaded . hbase-client hbase-http hbase-it hbase-rest hbase-server hbase-shaded/hbase-shaded-mapreduce hbase-thrift U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1255/1/console |
| versions | git=2.17.1 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Looks like HBASE-19256 is in. Can this one be refreshed?

**Comment by Apache9** [comment]
Solved by https://github.com/apache/hbase/pull/2222

**Pull request closed without merging**
