### PR TITLE
Made DemoClient python 3.0 compatible ..

### PR DESCRIPTION
**Pull request by pytalkweb**
Issue is the DemoClient.py is not updated for python 3.X.  Python 2.X support has ended.  Updating this to 3.0.  Please see 
https://issues.apache.org/jira/browse/HBASE-23644

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 33s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 30s |  master passed  |
| -1 :x: |  pylint  |   0m  1s |  Error running pylint. Please check pylint stderr files.  |
| +1 :green_heart: |  javadoc  |   0m 22s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 56s |  the patch passed  |
| -1 :x: |  pylint  |   0m  2s |  Error running pylint. Please check pylint stderr files.  |
| +1 :green_heart: |  pylint  |   0m  2s |  There were no new pylint issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 19s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 40s |  hbase-examples in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 14s |  The patch does not generate ASF License warnings.  |
|  |   |  14m 50s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/988 |
| Optional Tests | dupname asflicense javac javadoc unit pylint |
| uname | Linux 746236977ed4 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-988/out/precommit/personality/provided.sh |
| git revision | master / ab9766599d |
| Default Java | 1.8.0_181 |
| pylint | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/out/patch-pylint-stderr.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/testReport/ |
| Max. process+thread count | 2171 (vs. ulimit of 10000) |
| modules | C: hbase-examples U: hbase-examples |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) pylint=1.6.5 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 34s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 36s |  master passed  |
| -1 :x: |  pylint  |   0m  0s |  Error running pylint. Please check pylint stderr files.  |
| +1 :green_heart: |  javadoc  |   0m 22s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 54s |  the patch passed  |
| -1 :x: |  pylint  |   0m  0s |  Error running pylint. Please check pylint stderr files.  |
| +1 :green_heart: |  pylint  |   0m  0s |  There were no new pylint issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 21s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 40s |  hbase-examples in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 15s |  The patch does not generate ASF License warnings.  |
|  |   |  15m 40s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/988 |
| Optional Tests | dupname asflicense javac javadoc unit pylint |
| uname | Linux b2f68058fb7d 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-988/out/precommit/personality/provided.sh |
| git revision | master / ab9766599d |
| Default Java | 1.8.0_181 |
| pylint | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/2/artifact/out/branch-pylint-stderr.txt |
| pylint | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/2/artifact/out/patch-pylint-stderr.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/2/testReport/ |
| Max. process+thread count | 2179 (vs. ulimit of 10000) |
| modules | C: hbase-examples U: hbase-examples |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) pylint=1.6.5 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
Does this still work with python 2? Or is it python 3 only?

I'd be fine with the master branch being python 3 only if we can make branch-2 python 2 and python 3. This could be done with mutliple examples if needed.

**Comment by pytalkweb** [comment]
The file DemoClient.py that I made a new pull request in
https://github.com/apache/hbase works with python 3.X. I'm not sure what
the issue with github is, it has broken heart with -1 on top with some
error from pylint. I'm not sure what I need to do to get it fixed. If you
can let me know, I can get it committed.

**Comment by HorizonNet** [comment]
@pytalkweb We're running pylint from the build. Could you please check your changes with pylint?

**Comment by pytalkweb** [comment]
It seems problem might be with script that runs pylint as stderr.txt
says there is no such option —score. Please see below.


Usage:  pylint [options] module_or_package

  Check that a module satisfies a coding standard (and more !).

    pylint --help

  Display this help message and exit.

    pylint --help-msg <msg-id>[,<msg-id>]

  Display help messages about given message identifiers and exit.


pylint: error: no such option: --score

Regards, Madhu

**Comment by HorizonNet** [comment]
The pylint problems could be the same as in #1088.

**Comment by busbey** [comment]
Just to reiterate here, I would be fine with this being Python 3 only in the master branch, but to do that we need an option to maintain python 2 for branch-2 / branch-1 and hopefully opt-in to python 3 on branch-2 at least.

**Comment by saintstack** [comment]
Will close out unless update inside next week. Thanks.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| -0 :warning: |  pylint  |   0m  5s |  The patch generated 11 new + 0 unchanged - 1 fixed = 11 total (was 1)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |   3m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.9 Server=19.03.9 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/988 |
| Optional Tests | dupname asflicense pylint |
| uname | Linux 16bf6196dd7a 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / e1d7dc82ea |
| pylint | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/yetus-general-check/output/diff-patch-pylint.txt |
| Max. process+thread count | 47 (vs. ulimit of 12500) |
| modules | C: hbase-examples U: hbase-examples |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) pylint=2.4.4 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  9s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  2s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  2s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 21s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 46s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 20s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m  7s |  hbase-examples in the patch passed.  |
|  |   |  12m 34s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.9 Server=19.03.9 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/988 |
| Optional Tests | javac javadoc unit |
| uname | Linux 0d43326f15f5 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / e1d7dc82ea |
| Default Java | 1.8.0_232 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/testReport/ |
| Max. process+thread count | 1886 (vs. ulimit of 12500) |
| modules | C: hbase-examples U: hbase-examples |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   4m 13s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 47s |  master passed  |
| -0 :warning: |  javadoc  |   0m 20s |  hbase-examples in master failed.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m  4s |  the patch passed  |
| -0 :warning: |  javadoc  |   0m 21s |  hbase-examples in the patch failed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m  4s |  hbase-examples in the patch passed.  |
|  |   |  17m 44s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.9 Server=19.03.9 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/988 |
| Optional Tests | javac javadoc unit |
| uname | Linux 37d3adfaeda5 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 0ce85fe63c |
| Default Java | 2020-01-14 |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/yetus-jdk11-hadoop3-check/output/branch-javadoc-hbase-examples.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-hbase-examples.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/testReport/ |
| Max. process+thread count | 1488 (vs. ulimit of 12500) |
| modules | C: hbase-examples U: hbase-examples |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-988/1/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
Closing abandoned PR

**Pull request closed without merging**
