### PR TITLE
HBASE-22639 Unexpected split when a big table has only one region on …

### PR DESCRIPTION
**Pull request by bsglz**
…a regionServer

### CODE REVIEW

**Comment by bsglz** [comment]
Improve the SteppingSplitPolicy，if region count in local rs is 1, then make a rpc request to master to get all region count of the table , and if resp num more than a threshold, then the table may be not small enough, so we should use maxFileSize as checkSize.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  0s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 35s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 19s |  master passed  |
| +1 :green_heart: |  compile  |   2m 26s |  master passed  |
| +1 :green_heart: |  checkstyle  |   2m 34s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 36s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 37s |  master passed  |
| +0 :ok: |  spotbugs  |   4m 24s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   8m 46s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 26s |  the patch passed  |
| +1 :green_heart: |  cc  |   2m 26s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 26s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 34s |  hbase-client: The patch generated 1 new + 100 unchanged - 0 fixed = 101 total (was 100)  |
| -1 :x: |  checkstyle  |   1m 18s |  hbase-server: The patch generated 5 new + 68 unchanged - 3 fixed = 73 total (was 71)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 38s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  15m 49s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  hbaseprotoc  |   2m 18s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 36s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   9m 37s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 41s |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 19s |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 56s |  hbase-client in the patch passed.  |
| -1 :x: |  unit  |  33m 23s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m  8s |  The patch does not generate ASF License warnings.  |
|  |   | 118m 13s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.TestRegionSplitPolicy |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1007/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1007 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 42c551b22708 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1007/out/precommit/personality/provided.sh |
| git revision | master / 54af279ce0 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1007/1/artifact/out/diff-checkstyle-hbase-client.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1007/1/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1007/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1007/1/testReport/ |
| Max. process+thread count | 700 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-common hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1007/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
The RS is asking the Master how many Regions in a table?

We do not want the RegionServers harrassing Master with random queries.

Doesn't the RS ask the Master if it can split currently? Can you not have the Master say not split if only one Region in table?

**Comment by bsglz** [comment]
> The RS is asking the Master how many Regions in a table?
Yeah

> We do not want the RegionServers harrassing Master with random queries.
> Doesn't the RS ask the Master if it can split currently? Can you not have the Master say not split if only one Region in table?
The other way is through heartbeat to get this info ,but may be some delay.

**Comment by bsglz** [comment]
@saintstack Maybe i can make it as another implement of splitPolicy, named SteppingWithMasterCheckSplitPolicy.java, and as an option of user, WDYT?

**Pull request closed without merging**
