### PR TITLE
Branch 2.6 reverts

### PR DESCRIPTION
**Pull request by ndimiduk**
This is the set of reverts necessary to unwind the API compatibility report issues we've discussed on the [VOTE thread](https://lists.apache.org/thread/j3sv12msdcpk9sh4g7hq5v8q560zknjn) so far. I've run this branch through the compatibility report generator. Once looking at just the `IA.Public` classes, and a second time looking at both `IA.Public` and `IA.LimitedPrivate`. Let me figure out how to share them.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m  0s |  |  Docker mode activated.  |
| -1 :x: |  docker  |   0m 16s |  |  Docker failed to build run-specific yetus/hbase:tp-16966}.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/6344 |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
I shared them via SVN:
* https://dist.apache.org/repos/dist/dev/hbase/2.6.1RC0/api_compare_2.6.0_to_3f8f42be_Public.html
* https://dist.apache.org/repos/dist/dev/hbase/2.6.1RC0/api_compare_2.6.0_to_3f8f42be_Public_LimitedPrivate.html

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 46s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.6 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  8s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 33s |  |  branch-2.6 passed  |
| +1 :green_heart: |  compile  |   1m 43s |  |  branch-2.6 passed  |
| +1 :green_heart: |  javadoc  |   1m 11s |  |  branch-2.6 passed  |
| +1 :green_heart: |  shadedjars  |   4m 56s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   1m 23s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk8-hadoop2-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 43s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk8-hadoop2-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javac  |   0m 43s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk8-hadoop2-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| +1 :green_heart: |  javadoc  |   0m 18s |  |  hbase-client generated 0 new + 31 unchanged - 2 fixed = 31 total (was 33)  |
| +1 :green_heart: |  javadoc  |   0m 25s |  |  hbase-server in the patch passed.  |
| +1 :green_heart: |  javadoc  |   0m 12s |  |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  |  hbase-examples in the patch passed.  |
| -1 :x: |  shadedjars  |   3m 43s |  |  patch has 17 errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   7m 29s |  |  hbase-client in the patch passed.  |
| -1 :x: |  unit  |   0m 43s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
| +1 :green_heart: |  unit  |   3m 39s |  |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 17s |  |  hbase-examples in the patch passed.  |
|  |   |  35m 24s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6344 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux fb26dd4dc005 5.4.0-195-generic #215-Ubuntu SMP Fri Aug 2 18:28:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.6 / 3f8f42be168f9e11efd5f7e36ab2b53bfc5c8b8b |
| Default Java | Temurin-1.8.0_412-b08 |
| shadedjars | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk8-hadoop2-check/output/patch-shadedjars.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/testReport/ |
| Max. process+thread count | 1496 (vs. ulimit of 30000) |
| modules | C: hbase-client hbase-server hbase-endpoint hbase-examples U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 44s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +0 :ok: |  buf  |   0m  0s |  |  buf was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  |  Patch does not have any anti-patterns.  |
|||| _ branch-2.6 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m 10s |  |  branch-2.6 passed  |
| +1 :green_heart: |  compile  |   4m 27s |  |  branch-2.6 passed  |
| +1 :green_heart: |  checkstyle  |   1m 12s |  |  branch-2.6 passed  |
| +1 :green_heart: |  spotbugs  |   3m 18s |  |  branch-2.6 passed  |
| +1 :green_heart: |  spotless  |   0m 46s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   1m 38s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 59s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -1 :x: |  cc  |   1m 59s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javac  |   1m 59s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 15s |  |  the patch passed  |
| -1 :x: |  spotbugs  |   0m 43s | [/patch-spotbugs-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-spotbugs-hbase-server.txt) |  hbase-server in the patch failed.  |
| -1 :x: |  hadoopcheck  |   1m 44s |  |  The patch causes 17 errors with Hadoop v2.10.2.  |
| -1 :x: |  hadoopcheck  |   3m 59s |  |  The patch causes 17 errors with Hadoop v3.3.6.  |
| -1 :x: |  hadoopcheck  |   6m 18s |  |  The patch causes 17 errors with Hadoop v3.4.0.  |
| -1 :x: |  hbaseprotoc  |   0m 35s | [/patch-hbaseprotoc-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-hbaseprotoc-hbase-server.txt) |  hbase-server in the patch failed.  |
| +1 :green_heart: |  spotless  |   0m 47s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 38s |  |  The patch does not generate ASF License warnings.  |
|  |   |  35m 29s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6344 |
| Optional Tests | dupname asflicense javac spotbugs checkstyle codespell detsecrets compile hadoopcheck hbaseanti spotless cc buflint bufcompat hbaseprotoc |
| uname | Linux cc34ab327c26 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.6 / 3f8f42be168f9e11efd5f7e36ab2b53bfc5c8b8b |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-javac-2.10.2.txt |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-javac-3.3.6.txt |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-general-check/output/patch-javac-3.4.0.txt |
| Max. process+thread count | 79 (vs. ulimit of 30000) |
| modules | C: hbase-client hbase-server hbase-endpoint hbase-examples U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/console |
| versions | git=2.34.1 maven=3.9.8 spotbugs=4.7.3 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 57s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.6 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m 10s |  |  branch-2.6 passed  |
| +1 :green_heart: |  compile  |   1m 56s |  |  branch-2.6 passed  |
| +1 :green_heart: |  javadoc  |   1m  9s |  |  branch-2.6 passed  |
| +1 :green_heart: |  shadedjars  |   5m 55s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   1m 41s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk17-hadoop3-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 56s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk17-hadoop3-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javac  |   0m 56s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk17-hadoop3-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| +1 :green_heart: |  javadoc  |   0m 18s |  |  hbase-client generated 0 new + 38 unchanged - 2 fixed = 38 total (was 40)  |
| +1 :green_heart: |  javadoc  |   0m 27s |  |  hbase-server in the patch passed.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  javadoc  |   0m 14s |  |  hbase-examples in the patch passed.  |
| -1 :x: |  shadedjars  |   4m 26s |  |  patch has 17 errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   7m 38s |  |  hbase-client in the patch passed.  |
| -1 :x: |  unit  |   0m 55s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
| +1 :green_heart: |  unit  |   2m 51s |  |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 45s |  |  hbase-examples in the patch passed.  |
|  |   |  37m 34s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6344 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 04685b5e7841 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.6 / 3f8f42be168f9e11efd5f7e36ab2b53bfc5c8b8b |
| Default Java | Eclipse Adoptium-17.0.11+9 |
| shadedjars | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/artifact/yetus-jdk17-hadoop3-check/output/patch-shadedjars.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/testReport/ |
| Max. process+thread count | 2030 (vs. ulimit of 30000) |
| modules | C: hbase-client hbase-server hbase-endpoint hbase-examples U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6344/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
