### PR TITLE
[HBASE-22874] Mark Canary as LA(Tools)

### PR DESCRIPTION
**Pull request by shahrs87**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1282 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 544 | branch-1 passed |
| +1 | compile | 49 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 53 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 104 | branch-1 passed |
| +1 | shadedjars | 212 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 47 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 50 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 215 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 210 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 153 | the patch passed |
| +1 | compile | 50 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 50 | the patch passed |
| +1 | compile | 55 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 55 | the patch passed |
| +1 | checkstyle | 101 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 210 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 363 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 40 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 51 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 220 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 9621 | hbase-server in the patch failed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 13712 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |
|   | hadoop.hbase.master.normalizer.TestSimpleRegionNormalizerOnCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/516 |
| JIRA Issue | HBASE-22874 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 0b1409f7e7ce 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-516/out/precommit/personality/provided.sh |
| git revision | branch-1 / bb31ffa |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/1/testReport/ |
| Max. process+thread count | 4340 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 496 | branch-1 passed |
| +1 | compile | 37 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 40 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 86 | branch-1 passed |
| +1 | shadedjars | 160 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 34 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 37 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 167 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 163 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 113 | the patch passed |
| +1 | compile | 38 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 38 | the patch passed |
| +1 | compile | 41 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 41 | the patch passed |
| +1 | checkstyle | 79 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 160 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 291 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 29 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 37 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 165 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 7357 | hbase-server in the patch failed. |
| +1 | asflicense | 27 | The patch does not generate ASF License warnings. |
| | | 9640 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |
|   | hadoop.hbase.replication.TestReplicationSmallTests |
|   | hadoop.hbase.client.TestClientOperationInterrupt |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/516 |
| JIRA Issue | HBASE-22874 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 3c6bb84afac7 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-516/out/precommit/personality/provided.sh |
| git revision | branch-1 / 24a821c |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/2/testReport/ |
| Max. process+thread count | 4282 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 107 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 567 | branch-1 passed |
| +1 | compile | 65 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 55 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 119 | branch-1 passed |
| +1 | shadedjars | 223 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 45 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 48 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 226 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 219 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 153 | the patch passed |
| +1 | compile | 50 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 50 | the patch passed |
| +1 | compile | 55 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 55 | the patch passed |
| +1 | checkstyle | 115 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 224 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 387 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 36 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 48 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 218 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 11812 | hbase-server in the patch failed. |
| +1 | asflicense | 63 | The patch does not generate ASF License warnings. |
| | | 14884 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAdmin2 |
|   | hadoop.hbase.master.normalizer.TestSimpleRegionNormalizerOnCluster |
|   | hadoop.hbase.master.TestWarmupRegion |
|   | hadoop.hbase.regionserver.TestRegionMergeTransactionOnCluster |
|   | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/516 |
| JIRA Issue | HBASE-22874 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux ddda9d801ea6 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-516/out/precommit/personality/provided.sh |
| git revision | branch-1 / be2de08 |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/4/testReport/ |
| Max. process+thread count | 4170 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-516/4/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
I'm going to close this first approach since it lacks what we need per the [continued discussion on HBASE-22874](https://issues.apache.org/jira/browse/HBASE-22874?focusedCommentId=16911700&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16911700) . I'm only doing this to avoid having the QA bot continue rebuilding the PR every time a commit lands on the target branch. Please continue discussion about needs on HBASE-22874 and let's start with a PR _just for master_ to start dealing with implementation details and look at backports once we get that merged.

**Pull request closed without merging**
