### PR TITLE
test yetus

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache9** [comment]
Seems the build is alright but it does not post report back to github...

Let me check what is the problem...

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 19s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  |  Unprocessed flag(s): --blanks-eol-ignore-list --blanks-tabs-ignore-list  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ HBASE-28679 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 46s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  compile  |   5m 51s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  spotless  |   0m 54s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 37s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   6m  4s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   6m  4s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  hadolint  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  rubocop  |   0m  5s |  |  No new issues.  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  xmllint  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  hadoopcheck  |   5m 24s |  |  Patch does not cause any errors with Hadoop 3.3.6.  |
| +1 :green_heart: |  spotless  |   0m 44s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 22s |  |  The patch does not generate ASF License warnings.  |
|  |   |  32m 57s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6005 |
| Optional Tests | dupname asflicense codespell detsecrets hadolint shellcheck shelldocs spotless xmllint javac rubocop hadoopcheck compile |
| uname | Linux 98a6f062878e 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28679 / 21c678b092f7ebb5a4e4307af7eb88990b91f23a |
| Default Java | Eclipse Adoptium-11.0.17+8 |
| Max. process+thread count | 77 (vs. ulimit of 30000) |
| modules | C: hbase-shell . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/console |
| versions | git=2.34.1 maven=3.8.6 hadolint=2.10.0 rubocop=1.37.1 shellcheck=0.8.0 xmllint=20913 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Ah, OK, add --write-github-comment can get the comment back.

We still get

```
ERROR: Failed to write github status. Token expired or missing repo:status write?
```

But anyway, it does not seem to fail the build, should be OK.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 38s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-list --blanks-tabs-ignore-list --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ HBASE-28679 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 44s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  compile  |   2m  2s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  javadoc  |   2m  6s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  shadedjars  |   5m 10s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 59s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 59s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m  4s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m  9s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 267m 58s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   | 300m  6s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6005 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux dc333b1ba04f 5.4.0-174-generic #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28679 / 21c678b092f7ebb5a4e4307af7eb88990b91f23a |
| Default Java | Eclipse Adoptium-11.0.17+8 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/testReport/ |
| Max. process+thread count | 8362 (vs. ulimit of 30000) |
| modules | C: hbase-shell . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 40s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-list --blanks-tabs-ignore-list --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ HBASE-28679 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m  0s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  compile  |   2m  7s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  javadoc  |   2m  3s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  shadedjars  |   6m 13s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m  8s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 15s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 15s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 50s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   6m 31s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 392m  1s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/artifact/yetus-jdk8-hadoop3-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   | 426m 25s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6005 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 31b1da04d31e 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28679 / 21c678b092f7ebb5a4e4307af7eb88990b91f23a |
| Default Java | Temurin-1.8.0_352-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/testReport/ |
| Max. process+thread count | 6427 (vs. ulimit of 30000) |
| modules | C: hbase-shell . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/5/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 40s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  |  Unprocessed flag(s): --blanks-eol-ignore-list --blanks-tabs-ignore-list  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ HBASE-28679 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 58s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  compile  |   5m 23s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  spotless  |   0m 44s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 43s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   5m 15s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   5m 15s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  hadolint  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  rubocop  |   0m  3s |  |  No new issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  |  No new issues.  |
| +1 :green_heart: |  xmllint  |   0m  1s |  |  No new issues.  |
| +1 :green_heart: |  hadoopcheck  |   4m 54s |  |  Patch does not cause any errors with Hadoop 3.3.6.  |
| +1 :green_heart: |  spotless  |   0m 45s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 19s |  |  The patch does not generate ASF License warnings.  |
|  |   |  30m 37s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6005 |
| Optional Tests | dupname asflicense codespell detsecrets hadolint shellcheck shelldocs spotless xmllint javac rubocop hadoopcheck compile |
| uname | Linux a629c0a19f99 5.4.0-174-generic #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28679 / a6e413822e6471846ad3db828a890ab92e46bd65 |
| Default Java | Eclipse Adoptium-11.0.17+8 |
| Max. process+thread count | 78 (vs. ulimit of 30000) |
| modules | C: hbase-shell . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/console |
| versions | git=2.34.1 maven=3.8.6 hadolint=2.10.0 rubocop=1.37.1 shellcheck=0.8.0 xmllint=20913 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   2m 32s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-list --blanks-tabs-ignore-list --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ HBASE-28679 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m 14s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  compile  |   2m  1s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  javadoc  |   2m  0s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  shadedjars  |   5m 56s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 57s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  0s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m  0s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 57s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 50s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 253m 30s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   | 288m 36s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6005 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 1f14f5bd1cf4 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28679 / a6e413822e6471846ad3db828a890ab92e46bd65 |
| Default Java | Eclipse Adoptium-11.0.17+8 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/testReport/ |
| Max. process+thread count | 5410 (vs. ulimit of 30000) |
| modules | C: hbase-shell . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 46s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  2s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-list --blanks-tabs-ignore-list --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ HBASE-28679 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   4m  3s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  compile  |   2m 47s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  javadoc  |   3m 14s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  shadedjars  |   6m  9s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 49s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 57s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 57s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 41s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   6m 42s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 354m  5s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   | 394m 14s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6005 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux b18d244c50d8 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28679 / a6e413822e6471846ad3db828a890ab92e46bd65 |
| Default Java | Eclipse Adoptium-17.0.10+7 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/testReport/ |
| Max. process+thread count | 5161 (vs. ulimit of 30000) |
| modules | C: hbase-shell . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 46s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-list --blanks-tabs-ignore-list --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ HBASE-28679 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m 33s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  compile  |   2m 19s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  javadoc  |   2m 29s |  |  HBASE-28679 passed  |
| +1 :green_heart: |  shadedjars  |   6m 20s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 10s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 12s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 12s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 18s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   6m 48s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 457m 58s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/artifact/yetus-jdk8-hadoop3-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   | 494m 30s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6005 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux d87524cbd8eb 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-28679 / a6e413822e6471846ad3db828a890ab92e46bd65 |
| Default Java | Temurin-1.8.0_352-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/testReport/ |
| Max. process+thread count | 5738 (vs. ulimit of 30000) |
| modules | C: hbase-shell . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6005/7/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
