### PR TITLE
HBASE-22196 Split TestRestartCluster

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 264 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 9 new or modified test files. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 82 | root in master failed. |
| -1 | compile | 30 | hbase-server in master failed. |
| +1 | checkstyle | 73 | master passed |
| +1 | shadedjars | 270 | branch has no errors when building our shaded downstream artifacts. |
| -1 | findbugs | 153 | hbase-server in master has 14 extant Findbugs warnings. |
| -1 | javadoc | 18 | hbase-server in master failed. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 76 | root in the patch failed. |
| -1 | compile | 27 | hbase-server in the patch failed. |
| -1 | javac | 27 | hbase-server in the patch failed. |
| +1 | checkstyle | 73 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 275 | patch has no errors when building our shaded downstream artifacts. |
| -1 | hadoopcheck | 44 | The patch causes 10 errors with Hadoop v2.7.4. |
| -1 | hadoopcheck | 89 | The patch causes 10 errors with Hadoop v3.0.0. |
| +1 | findbugs | 158 | the patch passed |
| -1 | javadoc | 19 | hbase-server in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 26 | hbase-server in the patch failed. |
| +1 | asflicense | 11 | The patch does not generate ASF License warnings. |
| | | 1716 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/134 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux e9bde0408be5 4.4.0-141-generic #167~14.04.1-Ubuntu SMP Mon Dec 10 13:20:24 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 387a5da462 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/branch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/branch-compile-hbase-server.txt |
| findbugs | v3.1.11 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/branch-findbugs-hbase-server-warnings.html |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/branch-javadoc-hbase-server.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/patch-compile-hbase-server.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/patch-compile-hbase-server.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/patch-javac-2.7.4.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/patch-javac-3.0.0.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/patch-javadoc-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/testReport/ |
| Max. process+thread count | 86 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 298 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 9 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 292 | master passed |
| +1 | compile | 54 | master passed |
| +1 | checkstyle | 67 | master passed |
| +1 | shadedjars | 275 | branch has no errors when building our shaded downstream artifacts. |
| -1 | findbugs | 164 | hbase-server in master has 11 extant Findbugs warnings. |
| +1 | javadoc | 35 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 249 | the patch passed |
| +1 | compile | 54 | the patch passed |
| +1 | javac | 54 | the patch passed |
| +1 | checkstyle | 67 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 288 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 528 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 167 | the patch passed |
| +1 | javadoc | 32 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 17503 | hbase-server in the patch failed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 20176 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestHbck |
|   | hadoop.hbase.replication.TestReplicationSmallTestsSync |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleWAL |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicasWithoutZKCoordinated |
|   | hadoop.hbase.replication.TestReplicationDisableInactivePeer |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.replication.TestReplicationSmallTests |
|   | hadoop.hbase.master.TestAssignmentManagerMetrics |
|   | hadoop.hbase.master.TestRetainAssignmentOnRestart |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicas |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestAdmin1 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/134 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux ccca1fcc4914 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 494a8efe5f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/3/artifact/out/branch-findbugs-hbase-server-warnings.html |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/3/testReport/ |
| Max. process+thread count | 5195 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
OK, let me check TestRetainAssignmentOnRestart.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 54 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 9 new or modified test files. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 98 | root in master failed. |
| -1 | compile | 33 | hbase-server in master failed. |
| +1 | checkstyle | 77 | master passed |
| +1 | shadedjars | 286 | branch has no errors when building our shaded downstream artifacts. |
| -1 | findbugs | 181 | hbase-server in master has 14 extant Findbugs warnings. |
| -1 | javadoc | 21 | hbase-server in master failed. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 130 | root in the patch failed. |
| -1 | compile | 72 | hbase-server in the patch failed. |
| -1 | javac | 72 | hbase-server in the patch failed. |
| +1 | checkstyle | 81 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 293 | patch has no errors when building our shaded downstream artifacts. |
| -1 | hadoopcheck | 53 | The patch causes 10 errors with Hadoop v2.7.4. |
| -1 | hadoopcheck | 106 | The patch causes 10 errors with Hadoop v3.0.0. |
| +1 | findbugs | 169 | the patch passed |
| -1 | javadoc | 59 | hbase-server in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 29 | hbase-server in the patch failed. |
| +1 | asflicense | 11 | The patch does not generate ASF License warnings. |
| | | 1782 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/134 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 5d5ed77bbb7c 4.4.0-141-generic #167~14.04.1-Ubuntu SMP Mon Dec 10 13:20:24 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 494a8efe5f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/branch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/branch-compile-hbase-server.txt |
| findbugs | v3.1.11 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/branch-findbugs-hbase-server-warnings.html |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/branch-javadoc-hbase-server.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/patch-compile-hbase-server.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/patch-compile-hbase-server.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/patch-javac-2.7.4.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/patch-javac-3.0.0.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/patch-javadoc-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/testReport/ |
| Max. process+thread count | 86 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
This should be a broken machine, I've pushed again to trigger a new build. The patch for the first and the second QA run are the same, but the first one failed but the second one succeeded. And the failed module is hbase-shaded-protocol, which is not touched by the patch here.

**Comment by openinx** [comment]
OK, let's see what's next feedback from HBase QA.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 9 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 278 | master passed |
| +1 | compile | 55 | master passed |
| +1 | checkstyle | 68 | master passed |
| +1 | shadedjars | 275 | branch has no errors when building our shaded downstream artifacts. |
| -1 | findbugs | 174 | hbase-server in master has 11 extant Findbugs warnings. |
| +1 | javadoc | 35 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 279 | the patch passed |
| +1 | compile | 53 | the patch passed |
| +1 | javac | 53 | the patch passed |
| +1 | checkstyle | 70 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 277 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 571 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 173 | the patch passed |
| +1 | javadoc | 32 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 17249 | hbase-server in the patch failed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 19739 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.quotas.TestSpaceQuotas |
|   | hadoop.hbase.util.TestFromClientSide3WoUnsafe |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicas |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleAsyncWAL |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectory |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestAsyncTableBatch |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicasWithoutZKCoordinated |
|   | hadoop.hbase.client.TestAdmin1 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/134 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 644fb89aa0e3 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 494a8efe5f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/5/artifact/out/branch-findbugs-hbase-server-warnings.html |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/5/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/5/testReport/ |
| Max. process+thread count | 4808 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-134/5/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
