### PR TITLE
HBASE-28942 Purge all netty 3 dependencies by default

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 15s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m  5s |  |  master passed  |
| +1 :green_heart: |  compile  |   2m 11s |  |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 17s |  |  master passed  |
| +1 :green_heart: |  shadedjars  |   5m 23s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 51s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 10s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 10s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 17s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 22s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 295m 55s |  |  root in the patch passed.  |
|  |   | 329m 12s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6406/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6406 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 71c8374cce63 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / f3997178ee94bf820a10728eb2630989202850c6 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6406/1/testReport/ |
| Max. process+thread count | 9271 (vs. ulimit of 30000) |
| modules | C: hbase-external-blockcache . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6406/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Review by jojochuang — COMMENTED** [review]
Would be nice to have a rule to ban netty3 from transitive dependencies like in here: https://github.com/apache/hbase/blob/master/hbase-shaded/hbase-shaded-with-hadoop-check-invariants/pom.xml#L94

**Comment by Apache9** [comment]
We have lots of enforcer rule in the root pom but unfortunately we still need to support compiling with hadoop 3.x so we can not add this rule...

**Review by ndimiduk — APPROVED** [review]
I don't quite see how these changes match the title. Nett3 was a transitive dependency of one of these removed jars?

**Comment by Apache9** [comment]
The jmemcahed daemon depends on netty, so here I used mockito to inject the memcached client, then we do not need to start the jmemcached daemon any more.

Jmemcached is not active for more than 10 years...

**Pull request merged**
