### PR TITLE
HBASE-22400 Remove the adapter code in async fs implementation for ha…

### PR DESCRIPTION
**Pull request by Apache9**
…doop-2.7.x

### CODE REVIEW

**Comment by Apache9** [comment]
@jojochuang PTAL.

**Comment by jojochuang** [comment]
Thanks. Mostly looks good to me. I think you can also remove `createTransparentCryptoHelper27()`

**Comment by Apache9** [comment]
OK, good. Let me see.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 58 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 244 | master passed |
| +1 | compile | 52 | master passed |
| +1 | checkstyle | 67 | master passed |
| +1 | shadedjars | 266 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 164 | master passed |
| +1 | javadoc | 33 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 238 | the patch passed |
| +1 | compile | 52 | the patch passed |
| +1 | javac | 52 | the patch passed |
| +1 | checkstyle | 68 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 265 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 729 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.0.0. |
| +1 | findbugs | 224 | the patch passed |
| +1 | javadoc | 34 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8193 | hbase-server in the patch failed. |
| +1 | asflicense | 21 | The patch does not generate ASF License warnings. |
| | | 10786 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestScannersFromClientSide2 |
|   | hadoop.hbase.client.TestAsyncAdminMasterSwitch |
|   | hadoop.hbase.client.TestRawAsyncScanCursor |
|   | hadoop.hbase.client.TestSplitOrMergeAtTableLevel |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |
|   | hadoop.hbase.client.TestCIDeleteOperationTimeout |
|   | hadoop.hbase.TestClientClusterStatus |
|   | hadoop.hbase.client.TestAsyncReplicationAdminApi |
|   | hadoop.hbase.client.TestCISleep |
|   | hadoop.hbase.client.TestAsyncTableScanAll |
|   | hadoop.hbase.client.TestAdmin2 |
|   | hadoop.hbase.client.TestCIGetOperationTimeout |
|   | hadoop.hbase.client.TestCIIncrementRpcTimeout |
|   | hadoop.hbase.TestClientOperationTimeout |
|   | hadoop.hbase.io.encoding.TestLoadAndSwitchEncodeOnDisk |
|   | hadoop.hbase.client.TestAsyncSnapshotAdminApi |
|   | hadoop.hbase.client.TestAsyncTableRegionReplicasGet |
|   | hadoop.hbase.client.TestMobRestoreSnapshotFromClientClone |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.client.TestAsyncTable |
|   | hadoop.hbase.client.TestClientPushback |
|   | hadoop.hbase.io.asyncfs.TestSaslFanOutOneBlockAsyncDFSOutput |
|   | hadoop.hbase.io.asyncfs.TestFanOutOneBlockAsyncDFSOutput |
|   | hadoop.hbase.client.TestSnapshotFromClient |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.client.TestClientScannerRPCTimeout |
|   | hadoop.hbase.client.TestAsyncTableRegionLocator |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/240 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 4782827af5c2 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 083605df8f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/1/testReport/ |
| Max. process+thread count | 5018 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
The error is

> java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/zookeeper/MiniZooKeeperCluster
	at org.apache.hadoop.hbase.TestClientOperationTimeout.setUpClass(TestClientOperationTimeout.java:92)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hbase.zookeeper.MiniZooKeeperCluster
	at org.apache.hadoop.hbase.TestClientOperationTimeout.setUpClass(TestClientOperationTimeout.java:92)

A bit strange, this is a class inside hbase...

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 29 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 253 | master passed |
| +1 | compile | 57 | master passed |
| +1 | checkstyle | 71 | master passed |
| +1 | shadedjars | 275 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 185 | master passed |
| +1 | javadoc | 40 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 253 | the patch passed |
| +1 | compile | 60 | the patch passed |
| +1 | javac | 60 | the patch passed |
| +1 | checkstyle | 67 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 271 | patch has no errors when building our shaded downstream artifacts. |
| -1 | hadoopcheck | 586 | The patch causes 20 errors with Hadoop v3.0.0. |
| +1 | findbugs | 244 | the patch passed |
| +1 | javadoc | 34 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8173 | hbase-server in the patch passed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 10705 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/240 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux e44fabae0145 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 083605df8f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/2/artifact/out/patch-javac-3.0.0.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/2/testReport/ |
| Max. process+thread count | 5110 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
https://issues.apache.org/jira/browse/HDFS-12396

The HdfsKmsUtil is introduced in this issue, and it is fix version is 3.0.1 so we failed to build with 3.0.0. Although we seem to drop the support for 3.0.2-, but the fix version on 2.8.x is 2.8.4 and we still need to support 2.8.2 and 2.8.3, so here we still need to keep the `createTransparentCryptoHelper` method, but maybe change the sub method name.

Let me update the patch.

**Comment by jojochuang** [comment]
Makes sense to me.
+1 (non-binding) looks good to me.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 47 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 249 | master passed |
| +1 | compile | 51 | master passed |
| +1 | checkstyle | 70 | master passed |
| +1 | shadedjars | 269 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 172 | master passed |
| +1 | javadoc | 33 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 246 | the patch passed |
| +1 | compile | 52 | the patch passed |
| +1 | javac | 52 | the patch passed |
| +1 | checkstyle | 68 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 272 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 737 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.0.0. |
| +1 | findbugs | 228 | the patch passed |
| +1 | javadoc | 33 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 16412 | hbase-server in the patch failed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 19045 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.procedure.TestSCPWithReplicas |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleWAL |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.client.TestMetaWithReplicas |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicasWithoutZKCoordinated |
|   | hadoop.hbase.master.TestAssignmentManagerMetrics |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleAsyncWAL |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/240 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 2349eefc39b0 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 7878389669 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/4/testReport/ |
| Max. process+thread count | 4917 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-240/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
The failed UTs are not related, it should be a slow build machine. And I need to binding +1 here...

**Pull request merged**
