### PR TITLE
HBASE-22628 Document the custom WAL directory (hbase.wal.dir) usage

### PR DESCRIPTION
**Pull request by pankaj72981**
@anoopsjohn @zyork  please review

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 245 | master passed |
| 0 | refguide | 438 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 240 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 451 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 15 | The patch does not generate ASF License warnings. |
| | | 1482 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests |  dupname  asflicense  refguide  |
| uname | Linux ea4fdf56ae5d 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 00075ea4fc |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/1/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/1/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 209 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 19 | root in master failed. |
| -1 | refguide | 473 | branch has 2 errors when building the reference guide. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 12 | root in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| -1 | refguide | 437 | patch has 2 errors when building the reference guide. |
||| _ Other Tests _ |
| +1 | asflicense | 11 | The patch does not generate ASF License warnings. |
| | | 1211 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux ac91dafe0f03 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / c9293b0b12 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/branch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/branch-refguide.log |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/patch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/patch-refguide.log |
| Max. process+thread count | 56 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 32 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 241 | master passed |
| 0 | refguide | 446 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 235 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 440 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 17 | The patch does not generate ASF License warnings. |
| | | 1469 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux 8ac208cf44c0 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / aa9679ddbc |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 57 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 14 | root in master failed. |
| -1 | refguide | 448 | branch has 2 errors when building the reference guide. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 12 | root in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| -1 | refguide | 433 | patch has 2 errors when building the reference guide. |
||| _ Other Tests _ |
| +1 | asflicense | 12 | The patch does not generate ASF License warnings. |
| | | 1022 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux 1bb5c821cbfc 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / 7f68591767 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/artifact/out/branch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/artifact/out/branch-refguide.log |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/artifact/out/patch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/artifact/out/patch-refguide.log |
| Max. process+thread count | 55 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 36 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 237 | master passed |
| 0 | refguide | 442 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 238 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 427 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 14 | The patch does not generate ASF License warnings. |
| | | 1446 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux db31a34420fd 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / 7f68591767 |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/1/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/1/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 81 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 30 | root in master failed. |
| -1 | refguide | 452 | branch has 2 errors when building the reference guide. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 12 | root in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| -1 | refguide | 435 | patch has 2 errors when building the reference guide. |
||| _ Other Tests _ |
| +1 | asflicense | 11 | The patch does not generate ASF License warnings. |
| | | 1073 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux fdb00cdcd7a8 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / 9615c644f5 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/branch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/branch-refguide.log |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/patch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/artifact/out/patch-refguide.log |
| Max. process+thread count | 55 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 108 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 28 | root in master failed. |
| -1 | refguide | 488 | branch has 2 errors when building the reference guide. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 12 | root in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| -1 | refguide | 464 | patch has 2 errors when building the reference guide. |
||| _ Other Tests _ |
| +1 | asflicense | 13 | The patch does not generate ASF License warnings. |
| | | 1167 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux c9a8f1ed7b69 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / fe450b50c1 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/artifact/out/branch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/artifact/out/branch-refguide.log |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/artifact/out/patch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/artifact/out/patch-refguide.log |
| Max. process+thread count | 56 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 80 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 339 | master passed |
| 0 | refguide | 607 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 333 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 558 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 16 | The patch does not generate ASF License warnings. |
| | | 1996 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux ef1aad29fabe 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / 06f5c43de3 |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/4/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 57 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 268 | root in master failed. |
| 0 | refguide | 481 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 235 | root in the patch failed. |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 449 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 13 | The patch does not generate ASF License warnings. |
| | | 1561 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux 0d4afda2c5d5 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / 06f5c43de3 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/5/artifact/out/branch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/5/artifact/out/branch-site/book.html |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/5/artifact/out/patch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/5/artifact/out/patch-site/book.html |
| Max. process+thread count | 76 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/5/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Reidddddd** [comment]
LGTM, let's wait for 1 more day if there are further comments.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 56 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 268 | master passed |
| 0 | refguide | 452 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 244 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 438 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 15 | The patch does not generate ASF License warnings. |
| | | 1532 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux ed6f4ccbf10d 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / d9493c539f |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/6/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/6/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/6/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 63 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 369 | master passed |
| 0 | refguide | 535 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 402 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 595 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 19 | The patch does not generate ASF License warnings. |
| | | 2045 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux f8cccd1ffa94 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / e74d501df9 |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/7/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/7/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/7/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 73 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 189 | root in master failed. |
| 0 | refguide | 532 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 382 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 530 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 19 | The patch does not generate ASF License warnings. |
| | | 1780 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux 6ede736c5e8f 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / 6705d4ffdf |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/9/artifact/out/branch-mvninstall-root.txt |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/9/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/9/artifact/out/patch-site/book.html |
| Max. process+thread count | 96 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/9/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 78 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 322 | master passed |
| 0 | refguide | 484 | branch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 305 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| 0 | refguide | 465 | patch has no errors when building the reference guide. See footer for rendered docs, which you should manually inspect. |
||| _ Other Tests _ |
| +1 | asflicense | 15 | The patch does not generate ASF License warnings. |
| | | 1728 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/10/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/391 |
| Optional Tests | dupname asflicense refguide |
| uname | Linux 17c5cc05c11b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-391/out/precommit/personality/provided.sh |
| git revision | master / 20ee7ab154 |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/10/artifact/out/branch-site/book.html |
| refguide | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/10/artifact/out/patch-site/book.html |
| Max. process+thread count | 76 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-391/10/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
