### PR TITLE
HBASE-24643 Improve data structure and algorithm for BalanceClusterSt…

### PR DESCRIPTION
**Pull request by clarax**
…ate to improve computation speed for large cluster

### CODE REVIEW

**Comment by clarax** [comment]
WIP.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  7s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  3s |  master passed  |
| +1 :green_heart: |  compile  |   0m 35s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 17s |  master passed  |
| +1 :green_heart: |  spotbugs  |   0m 37s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 35s |  the patch passed  |
| -0 :warning: |  javac  |   0m 35s |  hbase-balancer generated 9 new + 18 unchanged - 0 fixed = 27 total (was 18)  |
| -0 :warning: |  checkstyle  |   0m 15s |  hbase-balancer: The patch generated 13 new + 1 unchanged - 0 fixed = 14 total (was 1)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  hadoopcheck  |  19m  3s |  Patch does not cause any errors with Hadoop 3.1.2 3.2.1 3.3.0.  |
| -1 :x: |  spotbugs  |   0m 50s |  hbase-balancer generated 5 new + 0 unchanged - 0 fixed = 5 total (was 0)  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  39m 20s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-balancer |
|  |  org.apache.hadoop.hbase.master.balancer.BalancerClusterState.doAction(BalanceAction) invokes inefficient new Integer(int) constructor; use Integer.valueOf(int) instead  At BalancerClusterState.java:constructor; use Integer.valueOf(int) instead  At BalancerClusterState.java:[line 559] |
|  |  Possible null pointer dereference of map in org.apache.hadoop.hbase.master.balancer.BalancerClusterState.addElement(HashMap, Integer, int)  Dereferenced at BalancerClusterState.java:map in org.apache.hadoop.hbase.master.balancer.BalancerClusterState.addElement(HashMap, Integer, int)  Dereferenced at BalancerClusterState.java:[line 831] |
|  |  Possible null pointer dereference of map in org.apache.hadoop.hbase.master.balancer.BalancerClusterState.removeElement(HashMap, Integer, int)  Dereferenced at BalancerClusterState.java:map in org.apache.hadoop.hbase.master.balancer.BalancerClusterState.removeElement(HashMap, Integer, int)  Dereferenced at BalancerClusterState.java:[line 843] |
|  |  Possible null pointer dereference of regions in org.apache.hadoop.hbase.master.balancer.BalancerClusterState.replaceRegion(ArrayList, Integer, Integer)  Dereferenced at BalancerClusterState.java:regions in org.apache.hadoop.hbase.master.balancer.BalancerClusterState.replaceRegion(ArrayList, Integer, Integer)  Dereferenced at BalancerClusterState.java:[line 735] |
|  |  Suspicious comparison of Integer references in org.apache.hadoop.hbase.master.balancer.RegionReplicaCandidateGenerator.selectCoHostedRegionPerGroup(HashMap, Collection, int[])  At RegionReplicaCandidateGenerator.java:in org.apache.hadoop.hbase.master.balancer.RegionReplicaCandidateGenerator.selectCoHostedRegionPerGroup(HashMap, Collection, int[])  At RegionReplicaCandidateGenerator.java:[line 77] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/3570 |
| Optional Tests | dupname asflicense javac spotbugs hadoopcheck hbaseanti checkstyle compile |
| uname | Linux b99d237febff 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / c9383f2c89 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/artifact/yetus-general-check/output/diff-compile-javac-hbase-balancer.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/artifact/yetus-general-check/output/diff-checkstyle-hbase-balancer.txt |
| spotbugs | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/artifact/yetus-general-check/output/new-spotbugs-hbase-balancer.html |
| Max. process+thread count | 95 (vs. ulimit of 30000) |
| modules | C: hbase-balancer U: hbase-balancer |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/console |
| versions | git=2.17.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 27s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  2s |  master passed  |
| +1 :green_heart: |  compile  |   0m 20s |  master passed  |
| +1 :green_heart: |  shadedjars  |   8m 18s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 19s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 43s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 21s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 21s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   8m 18s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 16s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  37m 17s |  hbase-balancer in the patch failed.  |
|  |   |  64m 40s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/3570 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 4fb917c0a936 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / c9383f2c89 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/artifact/yetus-jdk8-hadoop3-check/output/patch-unit-hbase-balancer.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/testReport/ |
| Max. process+thread count | 354 (vs. ulimit of 30000) |
| modules | C: hbase-balancer U: hbase-balancer |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  4s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m  4s |  master passed  |
| +1 :green_heart: |  compile  |   0m 21s |  master passed  |
| +1 :green_heart: |  shadedjars  |   9m  5s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 19s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 47s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 21s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 21s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   9m 13s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 16s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  43m 43s |  hbase-balancer in the patch failed.  |
|  |   |  75m 38s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/3570 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 529b1f943104 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / c9383f2c89 |
| Default Java | AdoptOpenJDK-11.0.10+9 |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-hbase-balancer.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/testReport/ |
| Max. process+thread count | 224 (vs. ulimit of 30000) |
| modules | C: hbase-balancer U: hbase-balancer |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3570/1/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Wrong jira id? And mind explain why this is faster? Locating an element in array is always O(1), what is the advantage of changing it to a HashSet?

**Comment by clarax** [comment]
> Wrong jira id? And mind explain why this is faster? Locating an element in array is always O(1), what is the advantage of changing it to a HashSet?

I opened https://issues.apache.org/jira/browse/HBASE-26178 later which explains the plan. Closing this one to open a new PR. HashSet is for quick lookup and updates by VALUE for move steps.

**Comment by clarax** [comment]
https://github.com/apache/hbase/pull/3575 new pr

**Pull request closed without merging**
