### PR TITLE
HBASE-27274 Re-enable the disabled tests when implementing HBASE-27212

### PR DESCRIPTION
**Pull request by 2005hithlj**
https://issues.apache.org/jira/browse/HBASE-27274

### CODE REVIEW

**Comment by Apache9** [comment]
Let's wait for the pre commit result.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 54s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ HBASE-27109/table_based_rqs Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 44s |  HBASE-27109/table_based_rqs passed  |
| +1 :green_heart: |  compile  |   0m 45s |  HBASE-27109/table_based_rqs passed  |
| +1 :green_heart: |  shadedjars  |   4m 27s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 27s |  HBASE-27109/table_based_rqs passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 27s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 24s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 26s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 230m 23s |  hbase-server in the patch failed.  |
|  |   | 254m 18s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5178/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5178 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux c3ed4bfcb5ef 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-27109/table_based_rqs / 2ea9c59fe8 |
| Default Java | Eclipse Adoptium-11.0.17+8 |
| unit | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5178/1/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-hbase-server.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5178/1/testReport/ |
| Max. process+thread count | 2679 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5178/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 28s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ HBASE-27109/table_based_rqs Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 46s |  HBASE-27109/table_based_rqs passed  |
| +1 :green_heart: |  compile  |   1m  8s |  HBASE-27109/table_based_rqs passed  |
| +1 :green_heart: |  shadedjars  |   6m 16s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 37s |  HBASE-27109/table_based_rqs passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 28s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  0s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  0s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   6m 42s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 31s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 263m 47s |  hbase-server in the patch failed.  |
|  |   | 295m 42s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5178/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5178 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 821ba2606fbc 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-27109/table_based_rqs / 2ea9c59fe8 |
| Default Java | Temurin-1.8.0_352-b08 |
| unit | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5178/1/artifact/yetus-jdk8-hadoop3-check/output/patch-unit-hbase-server.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5178/1/testReport/ |
| Max. process+thread count | 2684 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5178/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by 2005hithlj** [comment]
There are some failed UTs,  but I found that they are not related to TestHBaseFsckReplication.

**Review by Apache9 — APPROVED** [review]
Let's dig on the replication related test failures later.

**Comment by 2005hithlj** [comment]
In my local environment, TestReplicationValueCompressedWAL will still fail, but TestReplicationDroppedTables will succeed.

**Comment by Apache9** [comment]
> In my local environment, TestReplicationValueCompressedWAL will still fail, but TestReplicationDroppedTables will succeed.

Oh, you can reproduce the failure of TestReplicationValueCompressedWAL locally? It has been flaky for a long time but it is really hard to reproduce the failure locally so no big progress on the fixing...
If you can reproduce it locally, could you please try to find out the root cause?

Thanks.

**Comment by 2005hithlj** [comment]
> > In my local environment, TestReplicationValueCompressedWAL will still fail, but TestReplicationDroppedTables will succeed.
> 
> Oh, you can reproduce the failure of TestReplicationValueCompressedWAL locally? It has been flaky for a long time but it is really hard to reproduce the failure locally so no big progress on the fixing... If you can reproduce it locally, could you please try to find out the root cause?
> 
> Thanks.

OK, I will try to find out.

**Pull request merged**
