### PR TITLE
HBASE-22810 Initialize an separate ThreadPoolExecutor for taking/restoring snapshot (addendum - use the old config key)

### PR DESCRIPTION
**Pull request by openinx**

### CODE REVIEW

**Comment by ankitsinghal** [comment]
:+1:

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 37 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 35 | Maven dependency ordering for branch |
| +1 | mvninstall | 316 | master passed |
| +1 | compile | 78 | master passed |
| +1 | checkstyle | 101 | master passed |
| +1 | shadedjars | 279 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 54 | master passed |
| 0 | spotbugs | 256 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 300 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for patch |
| +1 | mvninstall | 321 | the patch passed |
| +1 | compile | 81 | the patch passed |
| +1 | javac | 81 | the patch passed |
| +1 | checkstyle | 23 | The patch passed checkstyle in hbase-common |
| +1 | checkstyle | 76 | hbase-server: The patch generated 0 new + 123 unchanged - 1 fixed = 123 total (was 124) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 282 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1002 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 52 | the patch passed |
| +1 | findbugs | 300 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 172 | hbase-common in the patch passed. |
| +1 | unit | 8371 | hbase-server in the patch passed. |
| +1 | asflicense | 48 | The patch does not generate ASF License warnings. |
| | | 12348 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/517 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 71a09ebeb520 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-517/out/precommit/personality/provided.sh |
| git revision | master / b8857ec010 |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/2/testReport/ |
| Max. process+thread count | 4634 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 32 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 33 | Maven dependency ordering for branch |
| +1 | mvninstall | 345 | master passed |
| +1 | compile | 97 | master passed |
| +1 | checkstyle | 134 | master passed |
| +1 | shadedjars | 310 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 59 | master passed |
| 0 | spotbugs | 279 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 331 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 16 | Maven dependency ordering for patch |
| +1 | mvninstall | 336 | the patch passed |
| +1 | compile | 84 | the patch passed |
| +1 | javac | 84 | the patch passed |
| +1 | checkstyle | 28 | The patch passed checkstyle in hbase-common |
| +1 | checkstyle | 94 | hbase-server: The patch generated 0 new + 123 unchanged - 1 fixed = 123 total (was 124) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 308 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1169 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 69 | the patch passed |
| +1 | findbugs | 416 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 205 | hbase-common in the patch passed. |
| -1 | unit | 10249 | hbase-server in the patch failed. |
| +1 | asflicense | 50 | The patch does not generate ASF License warnings. |
| | | 14884 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/517 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 06d22b1932ff 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-517/out/precommit/personality/provided.sh |
| git revision | master / b8857ec010 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/3/testReport/ |
| Max. process+thread count | 4874 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 102 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 38 | Maven dependency ordering for branch |
| +1 | mvninstall | 379 | master passed |
| +1 | compile | 86 | master passed |
| +1 | checkstyle | 120 | master passed |
| +1 | shadedjars | 305 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 64 | master passed |
| 0 | spotbugs | 304 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 376 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 17 | Maven dependency ordering for patch |
| +1 | mvninstall | 465 | the patch passed |
| +1 | compile | 196 | the patch passed |
| +1 | javac | 196 | the patch passed |
| +1 | checkstyle | 74 | The patch passed checkstyle in hbase-common |
| +1 | checkstyle | 171 | hbase-server: The patch generated 0 new + 123 unchanged - 1 fixed = 123 total (was 124) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 496 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1708 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 172 | the patch passed |
| +1 | findbugs | 650 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 182 | hbase-common in the patch passed. |
| -1 | unit | 17194 | hbase-server in the patch failed. |
| +1 | asflicense | 73 | The patch does not generate ASF License warnings. |
| | | 23535 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/517 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 837ca6db7b3f 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-517/out/precommit/personality/provided.sh |
| git revision | master / 61a3a9ffbb |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/1/testReport/ |
| Max. process+thread count | 4681 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-517/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
