### PR TITLE
Backport: HBASE-24273 HBCK's "Orphan Regions on FileSystem" reports regions wit…

### PR DESCRIPTION
**Pull request by huaxiangsun**
…h referenced HFiles (#1613)

Signed-off-by: stack <stack@apache.org>

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   1m 21s |  Docker failed to build yetus/hbase:d9b4982ad4.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1682 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1682/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   2m 47s |  Docker failed to build yetus/hbase:d9b4982ad4.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1682 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1682/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   0m 52s |  Docker failed to build yetus/hbase:d9b4982ad4.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1682 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1682/3/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by huaxiangsun** [comment]
It looks like there is an issue with docker, I built it locally with branch-2.2 and test passed with the test modified. The backport is a clean backport from branch-2.3, I am going to push and will revert if there is any issue.

**Pull request merged**
