### PR TITLE
HBASE-22548 Split TestAdmin1

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 181 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 332 | master passed |
| +1 | compile | 72 | master passed |
| +1 | checkstyle | 88 | master passed |
| +1 | shadedjars | 331 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 273 | master passed |
| +1 | javadoc | 43 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 306 | the patch passed |
| +1 | compile | 70 | the patch passed |
| +1 | javac | 70 | the patch passed |
| -1 | checkstyle | 86 | hbase-server: The patch generated 2 new + 2 unchanged - 32 fixed = 4 total (was 34) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 342 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 990 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 290 | the patch passed |
| +1 | javadoc | 43 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 14549 | hbase-server in the patch passed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 18429 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/290 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 8675d922518a 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / a826f41e83 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/1/artifact/out/diff-checkstyle-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/1/testReport/ |
| Max. process+thread count | 4822 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 139 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 251 | master passed |
| +1 | compile | 52 | master passed |
| +1 | checkstyle | 69 | master passed |
| +1 | shadedjars | 273 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 164 | master passed |
| +1 | javadoc | 32 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 249 | the patch passed |
| +1 | compile | 56 | the patch passed |
| +1 | javac | 56 | the patch passed |
| -1 | checkstyle | 70 | hbase-server: The patch generated 1 new + 1 unchanged - 33 fixed = 2 total (was 34) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 276 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 733 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 199 | the patch passed |
| +1 | javadoc | 33 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 15180 | hbase-server in the patch failed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 18123 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicasWithoutZKCoordinated |
|   | hadoop.hbase.util.TestFromClientSide3WoUnsafe |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/290 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux bdd3890b5428 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 302a9ce056 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/2/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/2/testReport/ |
| Max. process+thread count | 4992 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
Otherwise, patch looks good.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 47 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 322 | master passed |
| +1 | compile | 69 | master passed |
| +1 | checkstyle | 84 | master passed |
| +1 | shadedjars | 332 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 264 | master passed |
| +1 | javadoc | 41 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 303 | the patch passed |
| +1 | compile | 71 | the patch passed |
| +1 | javac | 71 | the patch passed |
| -1 | checkstyle | 82 | hbase-server: The patch generated 1 new + 1 unchanged - 33 fixed = 2 total (was 34) |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | shadedjars | 336 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 928 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 284 | the patch passed |
| +1 | javadoc | 41 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 15583 | hbase-server in the patch failed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 19207 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAsyncTableAdminApi |
|   | hadoop.hbase.client.TestAdmin1 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/290 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux cbfa38cf553a 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 302a9ce056 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/3/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/3/testReport/ |
| Max. process+thread count | 4766 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 19 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 5 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 246 | master passed |
| +1 | compile | 55 | master passed |
| +1 | checkstyle | 74 | master passed |
| +1 | shadedjars | 277 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 215 | master passed |
| +1 | javadoc | 34 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 253 | the patch passed |
| +1 | compile | 54 | the patch passed |
| +1 | javac | 54 | the patch passed |
| +1 | checkstyle | 73 | hbase-server: The patch generated 0 new + 6 unchanged - 34 fixed = 6 total (was 40) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 273 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 771 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 226 | the patch passed |
| +1 | javadoc | 35 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8225 | hbase-server in the patch passed. |
| +1 | asflicense | 28 | The patch does not generate ASF License warnings. |
| | | 11182 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/290 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 04454321766b 4.4.0-131-generic #157~14.04.1-Ubuntu SMP Fri Jul 13 08:53:17 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 4157d1e3cd |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/4/testReport/ |
| Max. process+thread count | 4758 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-290/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
