### PR TITLE
HBASE-24931 Fix for Candidate generator getAction method ignoring 0th…

### PR DESCRIPTION
**Pull request by rda3mon**
… index

### CODE REVIEW

**Review by virajjasani — APPROVED** [review]
+1, sounds reasonable.

**Comment by virajjasani** [comment]
@busbey would you like to take a look?

**Comment by virajjasani** [comment]
@rda3mon did you miss git push by any chance when you said "Fixing broken tests" ?

**Comment by rda3mon** [comment]
@virajjasani I need another day or so. It requires more involved understanding to fix broken tests. I will get back once I fix them

**Comment by virajjasani** [comment]
No worries, please take your time.
Thanks

**Comment by rda3mon** [comment]
@virajjasani I spent a good day and half. Couldn't solve this issue. Tagging origin author to help me on this @PierreZ and have written a detailed email.

Brief detail:
On correcting this line `if (fromRegion >= 0 && toRegion >= 0) {` from `if (fromRegion > 0 && toRegion > 0) {`. `TestStochasticLoadBalancerHeterogeneousCost` tests broke down.

**Comment by virajjasani** [comment]
Thanks @rda3mon for all your efforts. IMHO, test might require modification in this case. However, to cross verify, you can initiate a mail thread on `dev@hbase` asking if anyone with better understanding of `TestStochasticLoadBalancerHeterogeneousCost` can confirm whether your source code change is directly proportional to test change and also if it is fine increasing `ALLOWED_WINDOW` or any better approach should help.

**Comment by rda3mon** [comment]
@virajjasani Original author @PierreZ will be able to look at this post 14th Sep as he doesn't have access to laptop until then.. So, will wait till then.

**Comment by rda3mon** [comment]
@virajjasani Increase in ALLOWED_WINDOW will not be of much help. Because, the deviation isn't small. Expected 50 * 0.4 = 20. Actual is 49.

**Comment by rda3mon** [comment]
@virajjasani I am closing this as I couldn't fix the test cases and it was very tricky to narrow down the issue.

**Comment by Apache9** [comment]
FIxed by #3024

**Pull request closed without merging**
