### PR TITLE
Basic heat map implementation at region level

### PR DESCRIPTION
**Pull request by archana-katiyar-29**

### CODE REVIEW

**Comment by Reidddddd** [comment]
Hi,

Thanks for this PR.

The HBase project mainly use [Review Board](https://reviews.apache.org/) for review, would you mind attaching your patch there?

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 6 | https://github.com/apache/hbase/pull/98 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/98 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-98/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 6 | https://github.com/apache/hbase/pull/98 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/98 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-98/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
Closing pull request. HBASE-21301 says this is no longer being worked on.

**Pull request closed without merging**
