### PR TITLE
HBASE-23875 Add JDK11 compilation and unit test support to Jira attached patch precommit

### PR DESCRIPTION
**Pull request by ndimiduk**
Doing up this patch as a PR in order to more easily solicit feedback. It's based off of the patch in apache/hbase#1183 because it assumes on the Dockerfile changes therein. Thus, for now, that commit shows in this PR's history. I'll be iterating on this change by attaching patch files to the issue.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1192/1/console in case of problems.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   7m  3s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m  5s |  master passed  |
| +1 :green_heart: |  compile  |   4m  5s |  master passed with JDK AdoptOpenJDK-11.0.6+10  |
| +1 :green_heart: |  compile  |   3m 21s |  master passed with JDK AdoptOpenJDK-1.8.0_232-b09  |
| +1 :green_heart: |  shadedjars  |   5m  9s |  branch has no errors when building our shaded downstream artifacts.  |
| -1 :x: |  javadoc  |   0m 20s |  root in master failed with JDK AdoptOpenJDK-11.0.6+10.  |
| +1 :green_heart: |  javadoc  |   2m 51s |  master passed with JDK AdoptOpenJDK-1.8.0_232-b09  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 35s |  the patch passed  |
| +1 :green_heart: |  compile  |   4m  3s |  the patch passed with JDK AdoptOpenJDK-11.0.6+10  |
| +1 :green_heart: |  javac  |   4m  3s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 21s |  the patch passed with JDK AdoptOpenJDK-1.8.0_232-b09  |
| +1 :green_heart: |  javac  |   3m 21s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  2s |  The patch generated 0 new + 0 unchanged - 4 fixed = 0 total (was 4)  |
| +1 :green_heart: |  shellcheck  |   0m  2s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedjars  |   5m  7s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  17m 40s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| -1 :x: |  javadoc  |   0m 18s |  root in the patch failed with JDK AdoptOpenJDK-11.0.6+10.  |
| +1 :green_heart: |  javadoc  |   2m 51s |  the patch passed with JDK AdoptOpenJDK-1.8.0_232-b09  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 130m 24s |  root in the patch failed with JDK AdoptOpenJDK-1.8.0_232-b09.  |
| +1 :green_heart: |  asflicense  |   1m 15s |  The patch does not generate ASF License warnings.  |
|  |   | 208m  9s |   |


| Reason | Tests |
|-------:|:------|
| JDK AdoptOpenJDK-11.0.6+10 Failed junit tests | hadoop.hbase.util.TestFutureUtils |
| JDK AdoptOpenJDK-1.8.0_232-b09 Failed junit tests | hadoop.hbase.mapreduce.TestImportTsv |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1192/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1192 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 09e4f65decd9 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1192/out/precommit/personality/provided.sh |
| git revision | master / fe0d49bc52 |
| Default Java | AdoptOpenJDK-1.8.0_232-b09 |
| Multi-JDK versions | /usr/lib/jvm/jdk-11.0.6+10:AdoptOpenJDK-11.0.6+10 /usr/lib/jvm/jdk8u232-b09:AdoptOpenJDK-1.8.0_232-b09 |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1192/1/artifact/out/branch-javadoc-root-jdkAdoptOpenJDK-11.0.6+10.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1192/1/artifact/out/patch-javadoc-root-jdkAdoptOpenJDK-11.0.6+10.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1192/1/artifact/out/patch-unit-root-jdkAdoptOpenJDK-1.8.0_232-b09.txt |
| JDK AdoptOpenJDK-1.8.0_232-b09  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1192/1/testReport/ |
| Max. process+thread count | 6696 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1192/1/console |
| versions | git=2.17.1 maven=2018-06-17T18:33:14Z) shellcheck=0.4.6 hadolint=1.17.5-0-g443423c |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
@ndimiduk  need this still sir?

**Comment by ndimiduk** [comment]
Oops, no. We closed the issue as "Won't Fix". Thanks for checking.

**Pull request closed without merging**
