### PR TITLE
HBASE-27564 Add default encryption type for MiniKDC to fix failed tests on JDK11+

### PR DESCRIPTION
**Pull request by thangTang**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 21s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  spotless  |   0m 50s |  branch has no errors when running spotless:check.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  spotless  |   0m 46s |  patch has no errors when running spotless:check.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 29s |  The patch does not generate ASF License warnings.  |
|  |   |   4m 17s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4955/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4955 |
| Optional Tests | dupname asflicense spotless |
| uname | Linux 6835aa3dc1e7 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 4add5250ed |
| Max. process+thread count | 42 (vs. ulimit of 30000) |
| modules | C: hbase-endpoint hbase-examples hbase-http hbase-mapreduce U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4955/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
we only need to support hadoop3 on 3.0+, so I think we only need to apply the patch to branch-2.x?

**Comment by thangTang** [comment]
> we only need to support hadoop3 on 3.0+, so I think we only need to apply the patch to branch-2.x?

Yes. Will reopen a PR to branch-2 later.

**Comment by thangTang** [comment]
> > we only need to support hadoop3 on 3.0+, so I think we only need to apply the patch to branch-2.x?
> 
> Yes. Will reopen a PR to branch-2 later.

Done. Close this PR.

**Pull request closed without merging**
