### PR TITLE
HBASE-28275 Flaky test: Fix 'test_list_decommissioned_regionservers' …

### PR DESCRIPTION
**Pull request by NihalJain**
…in TestAdminShell2.java

### CODE REVIEW

**Comment by NihalJain** [comment]
Logs (with extra debug info) to demonstrate why the tests were failing. It can be seen the count was not 1 as it was expected in test assertion. 

Changed logic to do counting relatively instead of absolutely, which was causing flakiness, due to test case ordering.
```
server_name=HOST_NAME,63596,1703112668148
2023-12-21T04:22:20,258 DEBUG [Listener at localhost/63569-EventThread {}] zookeeper.ZKWatcher(604): master:63585-0x100004905c30000, quorum=127.0.0.1:64405, baseZNode=/hbase Received ZooKeeper Event, type=NodeChildrenChanged, state=SyncConnected, path=/hbase/draining
2023-12-21T04:22:20,258 INFO  [RpcServer.default.FPBQ.Fifo.handler=2,queue=0,port=63585 {}] master.ServerManager(681): Server HOST_NAME,63596,1703112668148 added to draining server list.
Took 0.0068 seconds                                                                                                                                                                                                     2023-12-21T04:22:20,259 DEBUG [zk-event-processor-pool-0 {}] zookeeper.ZKUtil(111): master:63585-0x100004905c30000, quorum=127.0.0.1:64405, baseZNode=/hbase Set watcher on existing znode=/hbase/draining/HOST_NAME,63602,1703112668656
2023-12-21T04:22:20,259 DEBUG [zk-event-processor-pool-0 {}] zookeeper.ZKUtil(111): master:63585-0x100004905c30000, quorum=127.0.0.1:64405, baseZNode=/hbase Set watcher on existing znode=/hbase/draining/HOST_NAME,63599,1703112668493
2023-12-21T04:22:20,259 DEBUG [zk-event-processor-pool-0 {}] zookeeper.ZKUtil(111): master:63585-0x100004905c30000, quorum=127.0.0.1:64405, baseZNode=/hbase Set watcher on existing znode=/hbase/draining/HOST_NAME,63596,1703112668148
2023-12-21T04:22:20,259 WARN  [zk-event-processor-pool-0 {}] master.ServerManager(677): Server HOST_NAME,63602,1703112668656 is already in the draining server list.Ignoring request to add it again.
2023-12-21T04:22:20,259 INFO  [zk-event-processor-pool-0 {}] master.DrainingServerTracker(92): Draining RS node created, adding to list [HOST_NAME,63602,1703112668656]
2023-12-21T04:22:20,259 WARN  [zk-event-processor-pool-0 {}] master.ServerManager(677): Server HOST_NAME,63599,1703112668493 is already in the draining server list.Ignoring request to add it again.
2023-12-21T04:22:20,259 INFO  [zk-event-processor-pool-0 {}] master.DrainingServerTracker(92): Draining RS node created, adding to list [HOST_NAME,63599,1703112668493]
2023-12-21T04:22:20,259 WARN  [zk-event-processor-pool-0 {}] master.ServerManager(677): Server HOST_NAME,63596,1703112668148 is already in the draining server list.Ignoring request to add it again.
2023-12-21T04:22:20,259 INFO  [zk-event-processor-pool-0 {}] master.DrainingServerTracker(92): Draining RS node created, adding to list [HOST_NAME,63596,1703112668148]
DECOMMISSIONED REGION SERVERS
HOST_NAME,63599,1703112668493
HOST_NAME,63602,1703112668656
HOST_NAME,63596,1703112668148
3 row(s)
Took 0.0015 seconds
initial_number_of_rows=3
2023-12-21T04:22:20,267 DEBUG [Listener at localhost/63569-EventThread {}] zookeeper.ZKWatcher(604): master:63585-0x100004905c30000, quorum=127.0.0.1:64405, baseZNode=/hbase Received ZooKeeper Event, type=NodeDeleted, state=SyncConnected, path=/hbase/draining/HOST_NAME,63596,1703112668148
2023-12-21T04:22:20,267 DEBUG [Listener at localhost/63569-EventThread {}] zookeeper.ZKWatcher(604): master:63585-0x100004905c30000, quorum=127.0.0.1:64405, baseZNode=/hbase Received ZooKeeper Event, type=NodeChildrenChanged, state=SyncConnected, path=/hbase/draining
2023-12-21T04:22:20,268 INFO  [zk-event-processor-pool-0 {}] master.DrainingServerTracker(109): Draining RS node deleted, removing from list [HOST_NAME,63596,1703112668148]
Took 0.0070 seconds                                                                                                                                                                                                     2023-12-21T04:22:20,268 DEBUG [zk-event-processor-pool-0 {}] zookeeper.ZKUtil(111): master:63585-0x100004905c30000, quorum=127.0.0.1:64405, baseZNode=/hbase Set watcher on existing znode=/hbase/draining/HOST_NAME,63602,1703112668656
2023-12-21T04:22:20,269 DEBUG [zk-event-processor-pool-0 {}] zookeeper.ZKUtil(111): master:63585-0x100004905c30000, quorum=127.0.0.1:64405, baseZNode=/hbase Set watcher on existing znode=/hbase/draining/HOST_NAME,63599,1703112668493
2023-12-21T04:22:20,269 WARN  [zk-event-processor-pool-0 {}] master.ServerManager(677): Server HOST_NAME,63602,1703112668656 is already in the draining server list.Ignoring request to add it again.
2023-12-21T04:22:20,269 INFO  [zk-event-processor-pool-0 {}] master.DrainingServerTracker(92): Draining RS node created, adding to list [HOST_NAME,63602,1703112668656]
2023-12-21T04:22:20,269 WARN  [zk-event-processor-pool-0 {}] master.ServerManager(677): Server HOST_NAME,63599,1703112668493 is already in the draining server list.Ignoring request to add it again.
2023-12-21T04:22:20,269 INFO  [zk-event-processor-pool-0 {}] master.DrainingServerTracker(92): Draining RS node created, adding to list [HOST_NAME,63599,1703112668493]
DECOMMISSIONED REGION SERVERS
HOST_NAME,63599,1703112668493
HOST_NAME,63602,1703112668656
2 row(s)
Took 0.0025 seconds
final_number_of_rows=2
```

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 31s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  spotless  |   0m 45s |  branch has no errors when running spotless:check.  |
||| _ Patch Compile Tests _ |
| -0 :warning: |  rubocop  |   0m  4s |  The patch generated 2 new + 148 unchanged - 1 fixed = 150 total (was 149)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  spotless  |   0m 38s |  patch has no errors when running spotless:check.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 10s |  The patch does not generate ASF License warnings.  |
|  |   |   3m  7s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5594 |
| Optional Tests | dupname asflicense spotless rubocop |
| uname | Linux 0ffe2c2a5ae6 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 2c07847656 |
| rubocop | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/artifact/yetus-general-check/output/diff-patch-rubocop.txt |
| Max. process+thread count | 45 (vs. ulimit of 30000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/console |
| versions | git=2.34.1 maven=3.8.6 rubocop=1.37.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 25s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  2s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 58s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 40s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 40s |  hbase-shell in the patch passed.  |
|  |   |  13m 35s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5594 |
| Optional Tests | unit |
| uname | Linux 8828933c71b7 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 2c07847656 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/testReport/ |
| Max. process+thread count | 1927 (vs. ulimit of 30000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 44s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 43s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 18s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   7m 13s |  hbase-shell in the patch passed.  |
|  |   |  16m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5594 |
| Optional Tests | unit |
| uname | Linux 3f336748d8c6 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 2c07847656 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/testReport/ |
| Max. process+thread count | 1895 (vs. ulimit of 30000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5594/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by NihalJain** [comment]
FYI @bbeaudreault

**Review by bbeaudreault — APPROVED** [review]
Thanks for handling this.

My first thought for why the change from 1 to 3 RS matters is maybe related to test ordering issues. I added some debug lines locally and 2 servers were "decommissioned" before the test even runs a command. Maybe some other test is decommissioning.

I have hit other issues where junit test ordering changes between master and branch-3, so that could be it here too

**Pull request merged**
