### PR TITLE
HBASE-22857 Fix the failed ut TestHRegion and TestHRegionWithInMemoryFlush

### PR DESCRIPTION
**Pull request by infraio**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 37 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ branch-2.2 Compile Tests _ |
| +1 | mvninstall | 305 | branch-2.2 passed |
| +1 | compile | 49 | branch-2.2 passed |
| +1 | checkstyle | 75 | branch-2.2 passed |
| +1 | shadedjars | 230 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 34 | branch-2.2 passed |
| 0 | spotbugs | 175 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 173 | branch-2.2 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 279 | the patch passed |
| +1 | compile | 54 | the patch passed |
| +1 | javac | 54 | the patch passed |
| +1 | checkstyle | 71 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 233 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 876 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 31 | the patch passed |
| +1 | findbugs | 192 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 7902 | hbase-server in the patch passed. |
| +1 | asflicense | 23 | The patch does not generate ASF License warnings. |
| | | 10940 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/495 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux c98a769d0fcf 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-495/out/precommit/personality/provided.sh |
| git revision | branch-2.2 / 413508ab49 |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/2/testReport/ |
| Max. process+thread count | 4853 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 73 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ branch-2.2 Compile Tests _ |
| +1 | mvninstall | 295 | branch-2.2 passed |
| +1 | compile | 54 | branch-2.2 passed |
| +1 | checkstyle | 77 | branch-2.2 passed |
| +1 | shadedjars | 243 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 34 | branch-2.2 passed |
| 0 | spotbugs | 166 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 165 | branch-2.2 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 282 | the patch passed |
| +1 | compile | 53 | the patch passed |
| +1 | javac | 53 | the patch passed |
| +1 | checkstyle | 79 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 238 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 885 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 32 | the patch passed |
| +1 | findbugs | 164 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 15802 | hbase-server in the patch failed. |
| +1 | asflicense | 34 | The patch does not generate ASF License warnings. |
| | | 18876 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleWAL |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/495 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux aa1e6a631bbb 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-495/out/precommit/personality/provided.sh |
| git revision | branch-2.2 / c04dcc49e7 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/1/testReport/ |
| Max. process+thread count | 4130 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 79 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ branch-2.2 Compile Tests _ |
| +1 | mvninstall | 454 | branch-2.2 passed |
| +1 | compile | 62 | branch-2.2 passed |
| +1 | checkstyle | 95 | branch-2.2 passed |
| +1 | shadedjars | 300 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 41 | branch-2.2 passed |
| 0 | spotbugs | 237 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 233 | branch-2.2 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 373 | the patch passed |
| +1 | compile | 67 | the patch passed |
| +1 | javac | 67 | the patch passed |
| +1 | checkstyle | 96 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 315 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1198 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 36 | the patch passed |
| +1 | findbugs | 228 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 17691 | hbase-server in the patch failed. |
| +1 | asflicense | 33 | The patch does not generate ASF License warnings. |
| | | 21797 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.snapshot.TestMobFlushSnapshotFromClient |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/495 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 51ee83b3fb2e 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-495/out/precommit/personality/provided.sh |
| git revision | branch-2.2 / b4734e7667 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/3/testReport/ |
| Max. process+thread count | 5041 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-495/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
Let me merge while Guanghao is sleeping so we can get some nightly runs in before he wakes.

**Comment by saintstack** [comment]
Signed-off-by: Peter Somogyi <psomogyi@apache.org>
Signed-off-by: stack <stack@apache.org>

**Pull request merged**
