### PR TITLE
HBASE-22690 Deprecate / Remove OfflineMetaRepair in hbase-2+

### PR DESCRIPTION
**Pull request by brfrn169**
This is for the master branch. In this PR, I removed OfflineMetaRepair completely and remove some unnecessary logics in HBaseFsck.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 234 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 1 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 279 | master passed |
| +1 | compile | 54 | master passed |
| +1 | checkstyle | 71 | master passed |
| +1 | shadedjars | 287 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 218 | master passed |
| +1 | javadoc | 31 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 247 | the patch passed |
| +1 | compile | 57 | the patch passed |
| +1 | javac | 57 | the patch passed |
| +1 | checkstyle | 72 | hbase-server: The patch generated 0 new + 97 unchanged - 6 fixed = 97 total (was 103) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 286 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 761 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 210 | the patch passed |
| +1 | javadoc | 32 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 14751 | hbase-server in the patch failed. |
| +1 | asflicense | 23 | The patch does not generate ASF License warnings. |
| | | 17943 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.namespace.TestNamespaceAuditor |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux beec4d844e1e 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 74731c2a46 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/1/testReport/ |
| Max. process+thread count | 4749 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by brfrn169** [comment]
Thank you for reviewing @saintstack 

> The removed methods are only used by OMR?
Yes.

**Comment by saintstack** [comment]
Ok. Good by me.  Long as other concerns addressed, +1 from me @brfrn169

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 74 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 1 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 307 | master passed |
| +1 | compile | 56 | master passed |
| +1 | checkstyle | 73 | master passed |
| +1 | shadedjars | 276 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 229 | master passed |
| +1 | javadoc | 38 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 280 | the patch passed |
| -1 | compile | 33 | hbase-server in the patch failed. |
| -1 | javac | 33 | hbase-server in the patch failed. |
| +1 | checkstyle | 69 | hbase-server: The patch generated 0 new + 97 unchanged - 6 fixed = 97 total (was 103) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 266 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 817 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 163 | the patch passed |
| +1 | javadoc | 35 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 16119 | hbase-server in the patch failed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 19179 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestSnapshotTemporaryDirectory |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 9c1cbdf784f4 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / cc38de1a39 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/2/artifact/out/patch-compile-hbase-server.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/2/artifact/out/patch-compile-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/2/testReport/ |
| Max. process+thread count | 4865 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 87 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 284 | master passed |
| +1 | compile | 61 | master passed |
| +1 | checkstyle | 87 | master passed |
| +1 | shadedjars | 303 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 247 | master passed |
| +1 | javadoc | 39 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 287 | the patch passed |
| -1 | compile | 48 | hbase-server in the patch failed. |
| -1 | javac | 48 | hbase-server in the patch failed. |
| +1 | checkstyle | 82 | hbase-server: The patch generated 0 new + 97 unchanged - 6 fixed = 97 total (was 103) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 296 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 841 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 216 | the patch passed |
| +1 | javadoc | 36 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 15758 | hbase-server in the patch failed. |
| +1 | asflicense | 35 | The patch does not generate ASF License warnings. |
| | | 19049 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.7 Server=18.09.7 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux acf2f831c0eb 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 72e58a8fed |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/3/artifact/out/patch-compile-hbase-server.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/3/artifact/out/patch-compile-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/3/testReport/ |
| Max. process+thread count | 4706 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 57 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 249 | master passed |
| +1 | compile | 52 | master passed |
| +1 | checkstyle | 66 | master passed |
| +1 | shadedjars | 254 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 198 | master passed |
| +1 | javadoc | 29 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 231 | the patch passed |
| +1 | compile | 51 | the patch passed |
| +1 | javac | 51 | the patch passed |
| +1 | checkstyle | 68 | hbase-server: The patch generated 0 new + 97 unchanged - 6 fixed = 97 total (was 103) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 258 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 739 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 212 | the patch passed |
| +1 | javadoc | 33 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 15069 | hbase-server in the patch failed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 17902 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.util.TestFromClientSide3WoUnsafe |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 7e71a27b4d11 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 00075ea4fc |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/4/testReport/ |
| Max. process+thread count | 5081 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 266 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 351 | master passed |
| +1 | compile | 72 | master passed |
| +1 | checkstyle | 101 | master passed |
| +1 | shadedjars | 365 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 41 | master passed |
| 0 | spotbugs | 297 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 295 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 335 | the patch passed |
| +1 | compile | 69 | the patch passed |
| +1 | javac | 69 | the patch passed |
| +1 | checkstyle | 103 | hbase-server: The patch generated 0 new + 97 unchanged - 6 fixed = 97 total (was 103) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 367 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1041 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 44 | the patch passed |
| +1 | findbugs | 320 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 16069 | hbase-server in the patch failed. |
| +1 | asflicense | 28 | The patch does not generate ASF License warnings. |
| | | 20298 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 8ff2aab84623 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-381/out/precommit/personality/provided.sh |
| git revision | master / c9293b0b12 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/5/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/5/testReport/ |
| Max. process+thread count | 4993 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/5/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by brfrn169** [comment]
Thank you for reviewing @saintstack. I'll commit this.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 10 | https://github.com/apache/hbase/pull/381 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/7/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 35 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 249 | master passed |
| +1 | compile | 55 | master passed |
| +1 | checkstyle | 75 | master passed |
| +1 | shadedjars | 269 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 34 | master passed |
| 0 | spotbugs | 228 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 225 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 248 | the patch passed |
| +1 | compile | 86 | the patch passed |
| +1 | javac | 86 | the patch passed |
| +1 | checkstyle | 92 | hbase-server: The patch generated 0 new + 97 unchanged - 6 fixed = 97 total (was 103) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 259 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 754 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 33 | the patch passed |
| +1 | findbugs | 237 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8178 | hbase-server in the patch passed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 11176 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux a1c7af72c81f 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-381/out/precommit/personality/provided.sh |
| git revision | master / aa9679ddbc |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/6/testReport/ |
| Max. process+thread count | 4512 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/6/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 10 | https://github.com/apache/hbase/pull/381 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/1/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 10 | https://github.com/apache/hbase/pull/381 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/381 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-381/2/console |
| versions | git=2.7.4 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
