### PR TITLE
HBASE-23564 RegionStates may has some expired serverinfo and make reg…

### PR DESCRIPTION
**Pull request by binlijin**
…ions do not balance.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m  6s |  master passed  |
| +1 :green_heart: |  compile  |   1m  0s |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 32s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 56s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 39s |  master passed  |
| +0 :ok: |  spotbugs  |   4m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m 39s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m  1s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  5s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  5s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 37s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   5m 14s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  17m 17s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   0m 35s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   4m 38s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 233m  7s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 29s |  The patch does not generate ASF License warnings.  |
|  |   | 297m 19s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-930/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/930 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux e39b95b44b68 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-930/out/precommit/personality/provided.sh |
| git revision | master / 85a081925b |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-930/1/testReport/ |
| Max. process+thread count | 5132 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-930/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
I have run into this issue. Thanks for digging in.  One concern I have is why the deviation between serverManager list of online servers and those seen down in RegionStates? The RegionStates list gets updated eventually? Or not? Do you know @binlijin ?  Thanks.

**Comment by binlijin** [comment]
@saintstack 
The RegionStates list do not gets updated eventually, and has some expired serverinfo.
https://issues.apache.org/jira/browse/HBASE-23564
TransitRegionStateProcedure (open a region on a server) may run after the server have done ServerCrashProcedure. The ServerCrashProcedure will remove the ServerName entry from serverMap in RegionStates, but later the TransitRegionStateProcedure open a region on this server will add a entry in serverMap in RegionStates for this ServerName, the open will fail and retry, but serverMap in RegionStates leaves some expired ServerNames and have no chance to clear and it will make balance not correct.

**Comment by binlijin** [comment]
@saintstack  any other concern?

**Comment by saintstack** [comment]
I am just trying to follow accounting of Regions by Server and vice versa. This patch bypasses any possible deviation by pushing the current list of online servers. +1.

**Pull request merged**
