### PR TITLE
HBASE-27373 Fix new spotbugs warnings after upgrading spotbugs to 4.7.2

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  5s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 44s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 17s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   5m 54s |  branch-2.4 passed  |
| +1 :green_heart: |  checkstyle  |   1m  1s |  branch-2.4 passed  |
| +1 :green_heart: |  spotless  |   0m 39s |  branch has no errors when running spotless:check.  |
| -1 :x: |  spotbugs  |   5m 52s |  root in branch-2.4 has 49 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 45s |  hbase-client in branch-2.4 has 11 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 26s |  hbase-common in branch-2.4 has 6 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 14s |  hbase-metrics in branch-2.4 has 1 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 52s |  hbase-protocol in branch-2.4 has 1 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 26s |  hbase-rest in branch-2.4 has 2 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   1m 15s |  hbase-server in branch-2.4 has 28 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 57s |  the patch passed  |
| -1 :x: |  compile  |   2m  6s |  root in the patch failed.  |
| -0 :warning: |  javac  |   2m  6s |  root in the patch failed.  |
| +1 :green_heart: |  checkstyle  |   1m  2s |  root: The patch generated 0 new + 57 unchanged - 5 fixed = 57 total (was 62)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  hadoopcheck  |  14m 31s |  Patch does not cause any errors with Hadoop 2.10.2 or 3.1.4 3.2.4 3.3.4.  |
| +1 :green_heart: |  spotless  |   0m 36s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  spotbugs  |   0m 35s |  hbase-common generated 0 new + 1 unchanged - 5 fixed = 1 total (was 6)  |
| +1 :green_heart: |  spotbugs  |   0m 22s |  hbase-metrics generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   0m 59s |  hbase-protocol generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   0m 51s |  hbase-client generated 0 new + 0 unchanged - 11 fixed = 0 total (was 11)  |
| +1 :green_heart: |  spotbugs  |   1m 23s |  hbase-server generated 0 new + 1 unchanged - 27 fixed = 1 total (was 28)  |
| +1 :green_heart: |  spotbugs  |   0m 35s |  hbase-rest generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
| -1 :x: |  spotbugs  |   3m 17s |  root in the patch failed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  3s |  The patch does not generate ASF License warnings.  |
|  |   |  56m 44s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4791 |
| Optional Tests | dupname asflicense javac spotbugs hadoopcheck hbaseanti spotless checkstyle compile xml |
| uname | Linux 94de20f3618a 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / c94ec54185 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/branch-spotbugs-root-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/branch-spotbugs-hbase-client-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/branch-spotbugs-hbase-common-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/branch-spotbugs-hbase-metrics-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/branch-spotbugs-hbase-protocol-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/branch-spotbugs-hbase-rest-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/branch-spotbugs-hbase-server-warnings.html |
| compile | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/patch-compile-root.txt |
| javac | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/patch-compile-root.txt |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/artifact/yetus-general-check/output/patch-spotbugs-root.txt |
| Max. process+thread count | 139 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-metrics hbase-protocol hbase-client hbase-server hbase-rest . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/1/console |
| versions | git=2.17.1 maven=3.6.3 spotbugs=4.7.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  3s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   1m 56s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   5m 57s |  branch-2.4 passed  |
| +1 :green_heart: |  checkstyle  |   1m  0s |  branch-2.4 passed  |
| +1 :green_heart: |  spotless  |   0m 35s |  branch has no errors when running spotless:check.  |
| -1 :x: |  spotbugs  |   0m 25s |  hbase-common in branch-2.4 has 6 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 16s |  hbase-metrics in branch-2.4 has 1 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 50s |  hbase-protocol in branch-2.4 has 1 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 44s |  hbase-client in branch-2.4 has 11 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   1m 13s |  hbase-server in branch-2.4 has 28 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 26s |  hbase-rest in branch-2.4 has 2 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   5m 50s |  root in branch-2.4 has 49 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 58s |  the patch passed  |
| +1 :green_heart: |  compile  |   5m 50s |  the patch passed  |
| +1 :green_heart: |  javac  |   5m 50s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m  1s |  root: The patch generated 0 new + 57 unchanged - 5 fixed = 57 total (was 62)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  hadoopcheck  |  14m  6s |  Patch does not cause any errors with Hadoop 2.10.2 or 3.1.4 3.2.4 3.3.4.  |
| +1 :green_heart: |  spotless  |   0m 37s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  spotbugs  |   0m 33s |  hbase-common generated 0 new + 1 unchanged - 5 fixed = 1 total (was 6)  |
| +1 :green_heart: |  spotbugs  |   0m 23s |  hbase-metrics generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   0m 58s |  hbase-protocol generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   0m 52s |  hbase-client generated 0 new + 0 unchanged - 11 fixed = 0 total (was 11)  |
| +1 :green_heart: |  spotbugs  |   1m 23s |  hbase-server generated 0 new + 1 unchanged - 27 fixed = 1 total (was 28)  |
| +1 :green_heart: |  spotbugs  |   0m 34s |  hbase-rest generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
| +1 :green_heart: |  spotbugs  |   6m  1s |  root generated 0 new + 2 unchanged - 47 fixed = 2 total (was 49)  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  1s |  The patch does not generate ASF License warnings.  |
|  |   |  61m 49s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4791 |
| Optional Tests | dupname asflicense javac spotbugs hadoopcheck hbaseanti spotless checkstyle compile xml |
| uname | Linux e660174fa34d 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / c94ec54185 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-general-check/output/branch-spotbugs-hbase-common-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-general-check/output/branch-spotbugs-hbase-metrics-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-general-check/output/branch-spotbugs-hbase-protocol-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-general-check/output/branch-spotbugs-hbase-client-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-general-check/output/branch-spotbugs-hbase-server-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-general-check/output/branch-spotbugs-hbase-rest-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-general-check/output/branch-spotbugs-root-warnings.html |
| Max. process+thread count | 140 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-metrics hbase-protocol hbase-client hbase-server hbase-rest . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/console |
| versions | git=2.17.1 maven=3.6.3 spotbugs=4.7.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 51s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 17s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   1m 30s |  branch-2.4 passed  |
| +1 :green_heart: |  shadedjars  |   4m 21s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   3m 13s |  branch-2.4 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 32s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 32s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 21s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   3m  7s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 197m 29s |  root in the patch passed.  |
|  |   | 224m 25s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4791 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux c7e5a81985f3 5.4.0-1081-aws #88~18.04.1-Ubuntu SMP Thu Jun 23 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / c94ec54185 |
| Default Java | AdoptOpenJDK-11.0.10+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/testReport/ |
| Max. process+thread count | 5155 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-metrics hbase-protocol hbase-client hbase-server hbase-rest . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 56s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 12s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   1m 13s |  branch-2.4 passed  |
| +1 :green_heart: |  shadedjars  |   4m  8s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 37s |  branch-2.4 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 48s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 16s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 16s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m  4s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 35s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 305m 46s |  root in the patch passed.  |
|  |   | 329m 58s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4791 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 98928204dc27 5.4.0-1081-aws #88~18.04.1-Ubuntu SMP Thu Jun 23 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / c94ec54185 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/testReport/ |
| Max. process+thread count | 4205 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-metrics hbase-protocol hbase-client hbase-server hbase-rest . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/2/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  8s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m  0s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   5m 52s |  branch-2.4 passed  |
| +1 :green_heart: |  checkstyle  |   1m  1s |  branch-2.4 passed  |
| +1 :green_heart: |  spotless  |   0m 36s |  branch has no errors when running spotless:check.  |
| -1 :x: |  spotbugs  |   0m 27s |  hbase-common in branch-2.4 has 6 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 15s |  hbase-metrics in branch-2.4 has 1 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 50s |  hbase-protocol in branch-2.4 has 1 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 44s |  hbase-client in branch-2.4 has 11 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   1m 16s |  hbase-server in branch-2.4 has 28 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   0m 26s |  hbase-rest in branch-2.4 has 2 extant spotbugs warnings.  |
| -1 :x: |  spotbugs  |   3m 10s |  root in branch-2.4 failed.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   5m 45s |  the patch passed  |
| +1 :green_heart: |  javac  |   5m 45s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m  0s |  root: The patch generated 0 new + 57 unchanged - 5 fixed = 57 total (was 62)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  hadoopcheck  |  14m 13s |  Patch does not cause any errors with Hadoop 2.10.2 or 3.1.4 3.2.4 3.3.4.  |
| +1 :green_heart: |  spotless  |   0m 36s |  patch has no errors when running spotless:check.  |
| +1 :green_heart: |  spotbugs  |   0m 34s |  hbase-common generated 0 new + 0 unchanged - 6 fixed = 0 total (was 6)  |
| +1 :green_heart: |  spotbugs  |   0m 22s |  hbase-metrics generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   0m 58s |  hbase-protocol generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  spotbugs  |   0m 51s |  hbase-client generated 0 new + 0 unchanged - 11 fixed = 0 total (was 11)  |
| +1 :green_heart: |  spotbugs  |   1m 21s |  hbase-server generated 0 new + 0 unchanged - 28 fixed = 0 total (was 28)  |
| +1 :green_heart: |  spotbugs  |   0m 34s |  hbase-rest generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
| +1 :green_heart: |  spotbugs  |   5m 56s |  root in the patch passed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  1s |  The patch does not generate ASF License warnings.  |
|  |   |  59m  8s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4791 |
| Optional Tests | dupname asflicense javac spotbugs hadoopcheck hbaseanti spotless checkstyle compile xml |
| uname | Linux 8bc8ea62fb61 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / c94ec54185 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-general-check/output/branch-spotbugs-hbase-common-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-general-check/output/branch-spotbugs-hbase-metrics-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-general-check/output/branch-spotbugs-hbase-protocol-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-general-check/output/branch-spotbugs-hbase-client-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-general-check/output/branch-spotbugs-hbase-server-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-general-check/output/branch-spotbugs-hbase-rest-warnings.html |
| spotbugs | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-general-check/output/branch-spotbugs-root.txt |
| Max. process+thread count | 137 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-metrics hbase-protocol hbase-client hbase-server hbase-rest . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/console |
| versions | git=2.17.1 maven=3.6.3 spotbugs=4.7.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
The  compilation is a bit flaky but I checked the newest spotbugs html after patching, there is no spotbugs warnings. Let me update the PR and merge it.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 53s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 19s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 26s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   1m 30s |  branch-2.4 passed  |
| +1 :green_heart: |  shadedjars  |   4m 22s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   3m 18s |  branch-2.4 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 14s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 30s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 30s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 20s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   3m  7s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 197m 24s |  root in the patch passed.  |
|  |   | 225m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4791 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux e590084e5051 5.4.0-1081-aws #88~18.04.1-Ubuntu SMP Thu Jun 23 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / c94ec54185 |
| Default Java | AdoptOpenJDK-11.0.10+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/testReport/ |
| Max. process+thread count | 5099 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-metrics hbase-protocol hbase-client hbase-server hbase-rest . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 51s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 13s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   1m 15s |  branch-2.4 passed  |
| +1 :green_heart: |  shadedjars  |   4m 14s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 38s |  branch-2.4 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 14s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 14s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 10s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 37s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 311m 38s |  root in the patch passed.  |
|  |   | 334m 59s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4791 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 761adb627638 5.4.0-1081-aws #88~18.04.1-Ubuntu SMP Thu Jun 23 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / c94ec54185 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/testReport/ |
| Max. process+thread count | 4468 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-metrics hbase-protocol hbase-client hbase-server hbase-rest . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4791/3/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
