### PR TITLE
HBASE-28888 Backport "HBASE-18382 [Thrift] Add transport type info to…

### PR DESCRIPTION
**Pull request by NihalJain**
… info server" to branch-2

Signed-off-by: Wellington Chevreuil <wchevreuil@apache.org>
Signed-off-by: Bharath Vissapragada <bharathv@apache.org>
Signed-off-by: Viraj Jasani <virajjasani007@gmail.com>

(cherry picked from commit 82e155eb26cddd642e151d9276e2f4f281b4df88)

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 54s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 43s |  |  branch-2 passed  |
| +1 :green_heart: |  spotless  |   1m 17s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 24s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  spotless  |   0m 55s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 11s |  |  The patch does not generate ASF License warnings.  |
|  |   |  14m  1s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6312 |
| Optional Tests | dupname asflicense javac codespell detsecrets spotless |
| uname | Linux 809b5aa12a33 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / df88827e2a854d3d0f9eee6e0c54000c8d809046 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| Max. process+thread count | 76 (vs. ulimit of 30000) |
| modules | C: hbase-thrift U: hbase-thrift |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 44s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 42s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 22s |  |  branch-2 passed  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 50s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 22s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 39s |  |  hbase-thrift in the patch passed.  |
|  |   |  14m 49s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6312 |
| Optional Tests | javac javadoc unit |
| uname | Linux 75c7414f06fc 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / df88827e2a854d3d0f9eee6e0c54000c8d809046 |
| Default Java | Temurin-1.8.0_412-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/testReport/ |
| Max. process+thread count | 1355 (vs. ulimit of 30000) |
| modules | C: hbase-thrift U: hbase-thrift |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 45s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 29s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 18s |  |  branch-2 passed  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 25s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 17s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 49s |  |  hbase-thrift in the patch passed.  |
|  |   |  16m 12s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6312 |
| Optional Tests | javac javadoc unit |
| uname | Linux 76042321941e 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / df88827e2a854d3d0f9eee6e0c54000c8d809046 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/testReport/ |
| Max. process+thread count | 1451 (vs. ulimit of 30000) |
| modules | C: hbase-thrift U: hbase-thrift |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 54s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 35s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 22s |  |  branch-2 passed  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 26s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 27s |  |  the patch passed  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   8m 52s |  |  hbase-thrift in the patch passed.  |
|  |   |  20m 50s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6312 |
| Optional Tests | javac javadoc unit |
| uname | Linux 2f00e50f354c 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / df88827e2a854d3d0f9eee6e0c54000c8d809046 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/testReport/ |
| Max. process+thread count | 1437 (vs. ulimit of 30000) |
| modules | C: hbase-thrift U: hbase-thrift |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6312/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by NihalJain** [comment]
Verified the changes in local standalone cluster:
Screenshot 2024-09-27 at 12 09 27 PM

**Comment by NihalJain** [comment]
Since this is a clean cherry-pick / backport of a already reviewed code, merging this since all checks pass and manual verification is SUCCESS!

**Pull request merged**
