### PR TITLE
HBASE-22485 Fix failed ut TestClusterRestartFailover

### PR DESCRIPTION
**Pull request by infraio**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 55 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 245 | master passed |
| +1 | compile | 49 | master passed |
| +1 | checkstyle | 64 | master passed |
| +1 | shadedjars | 256 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 202 | master passed |
| +1 | javadoc | 30 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 229 | the patch passed |
| +1 | compile | 49 | the patch passed |
| +1 | javac | 49 | the patch passed |
| +1 | checkstyle | 63 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 247 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 949 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.0.3 3.1.2. |
| +1 | findbugs | 205 | the patch passed |
| +1 | javadoc | 31 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 18943 | hbase-server in the patch failed. |
| +1 | asflicense | 36 | The patch does not generate ASF License warnings. |
| | | 21969 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAsyncTableAdminApi |
|   | hadoop.hbase.tool.TestSecureLoadIncrementalHFiles |
|   | hadoop.hbase.namespace.TestNamespaceAuditor |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleWAL |
|   | hadoop.hbase.replication.TestReplicationSmallTestsSync |
|   | hadoop.hbase.master.procedure.TestTruncateTableProcedure |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicas |
|   | hadoop.hbase.client.TestCloneSnapshotFromClientNormal |
|   | hadoop.hbase.master.TestMasterMetricsWrapper |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/258 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 8046e1d9915f 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 1c1638f698 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/1/testReport/ |
| Max. process+thread count | 5612 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by infraio** [comment]
The failed ut not related...

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 264 | master passed |
| +1 | compile | 57 | master passed |
| +1 | checkstyle | 69 | master passed |
| +1 | shadedjars | 271 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 206 | master passed |
| +1 | javadoc | 32 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 239 | the patch passed |
| +1 | compile | 52 | the patch passed |
| +1 | javac | 52 | the patch passed |
| +1 | checkstyle | 69 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 264 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 987 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.0.3 3.1.2. |
| +1 | findbugs | 220 | the patch passed |
| +1 | javadoc | 32 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 8042 | hbase-server in the patch passed. |
| +1 | asflicense | 31 | The patch does not generate ASF License warnings. |
| | | 11160 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/258 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 59ba6605f038 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 97090560a5 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/2/testReport/ |
| Max. process+thread count | 4320 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 261 | master passed |
| +1 | compile | 57 | master passed |
| +1 | checkstyle | 68 | master passed |
| +1 | shadedjars | 269 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 230 | master passed |
| +1 | javadoc | 36 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 256 | the patch passed |
| +1 | compile | 61 | the patch passed |
| +1 | javac | 61 | the patch passed |
| +1 | checkstyle | 73 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 279 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1009 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.0.3 3.1.2. |
| +1 | findbugs | 221 | the patch passed |
| +1 | javadoc | 33 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 7927 | hbase-server in the patch passed. |
| +1 | asflicense | 24 | The patch does not generate ASF License warnings. |
| | | 11127 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/258 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 708cd492429d 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 97090560a5 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/3/testReport/ |
| Max. process+thread count | 4579 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-258/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
