### PR TITLE
HBASE-22861 [WAL] Merged region should get its WAL according to WALProvider

### PR DESCRIPTION
**Pull request by Reidddddd**
JIRA: [HBASE-22861](https://issues.apache.org/jira/browse/HBASE-22861)

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1214 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 489 | branch-1 passed |
| +1 | compile | 38 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 39 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 89 | branch-1 passed |
| +1 | shadedjars | 163 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 37 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 39 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 211 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 206 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 119 | the patch passed |
| +1 | compile | 37 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 37 | the patch passed |
| +1 | compile | 39 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 39 | the patch passed |
| -1 | checkstyle | 83 | hbase-server: The patch generated 1 new + 326 unchanged - 0 fixed = 327 total (was 326) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 170 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 298 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 28 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 38 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 167 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 1888 | hbase-server in the patch failed. |
| +1 | asflicense | 19 | The patch does not generate ASF License warnings. |
| | | 5401 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.TestRegionMergeTransaction |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/507 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 2f87f86425fb 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-507/out/precommit/personality/provided.sh |
| git revision | branch-1 / d2793f1 |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/1/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/1/testReport/ |
| Max. process+thread count | 733 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 72 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 512 | branch-1 passed |
| +1 | compile | 66 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 41 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 90 | branch-1 passed |
| +1 | shadedjars | 169 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 43 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 36 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 166 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 162 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 112 | the patch passed |
| +1 | compile | 37 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 37 | the patch passed |
| +1 | compile | 39 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 39 | the patch passed |
| -1 | checkstyle | 83 | hbase-server: The patch generated 2 new + 326 unchanged - 0 fixed = 328 total (was 326) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 153 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 281 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 27 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 37 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 156 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 9475 | hbase-server in the patch failed. |
| +1 | asflicense | 47 | The patch does not generate ASF License warnings. |
| | | 11880 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAdmin2 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/507 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 7b42d820793c 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-507/out/precommit/personality/provided.sh |
| git revision | branch-1 / d2793f1 |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/2/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/2/testReport/ |
| Max. process+thread count | 4545 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 116 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 535 | branch-1 passed |
| +1 | compile | 53 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 42 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 93 | branch-1 passed |
| +1 | shadedjars | 167 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 41 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 39 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 181 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 175 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 121 | the patch passed |
| +1 | compile | 39 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 39 | the patch passed |
| +1 | compile | 43 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 43 | the patch passed |
| -1 | checkstyle | 89 | hbase-server: The patch generated 1 new + 326 unchanged - 0 fixed = 327 total (was 326) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 174 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 300 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 30 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 40 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 174 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 9709 | hbase-server in the patch failed. |
| +1 | asflicense | 60 | The patch does not generate ASF License warnings. |
| | | 12296 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/507 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 447c075d127b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-507/out/precommit/personality/provided.sh |
| git revision | branch-1 / d2793f1 |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/3/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/3/testReport/ |
| Max. process+thread count | 4173 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/3/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Reidddddd** [comment]
Not related failed UT.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 75 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 646 | branch-1 passed |
| +1 | compile | 65 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 41 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 87 | branch-1 passed |
| +1 | shadedjars | 163 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 37 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 38 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 172 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 164 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 120 | the patch passed |
| +1 | compile | 37 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 37 | the patch passed |
| +1 | compile | 41 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 41 | the patch passed |
| -1 | checkstyle | 89 | hbase-server: The patch generated 1 new + 326 unchanged - 0 fixed = 327 total (was 326) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 158 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 299 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 28 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 38 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 170 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 11097 | hbase-server in the patch failed. |
| +1 | asflicense | 88 | The patch does not generate ASF License warnings. |
| | | 13732 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.TestMasterShutdown |
|   | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |
|   | hadoop.hbase.client.TestAdmin2 |
|   | hadoop.hbase.master.TestDistributedLogSplitting |
|   | hadoop.hbase.master.TestWarmupRegion |
|   | hadoop.hbase.master.cleaner.TestLogsCleaner |
|   | hadoop.hbase.regionserver.TestSplitTransactionOnCluster |
|   | hadoop.hbase.master.TestAssignmentManagerOnCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/507 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux e6228ceca06a 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-507/out/precommit/personality/provided.sh |
| git revision | branch-1 / bb31ffa |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/4/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/4/testReport/ |
| Max. process+thread count | 4490 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/4/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1326 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 507 | branch-1 passed |
| +1 | compile | 42 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 42 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 93 | branch-1 passed |
| +1 | shadedjars | 193 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 36 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 41 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 181 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 177 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 155 | the patch passed |
| +1 | compile | 46 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 46 | the patch passed |
| +1 | compile | 46 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 46 | the patch passed |
| +1 | checkstyle | 90 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 169 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 323 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 32 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 42 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 175 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 10792 | hbase-server in the patch failed. |
| +1 | asflicense | 61 | The patch does not generate ASF License warnings. |
| | | 14620 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.multiwal.TestReplicationEndpointWithMultipleWAL |
|   | hadoop.hbase.client.TestAdmin2 |
|   | hadoop.hbase.master.normalizer.TestSimpleRegionNormalizerOnCluster |
|   | hadoop.hbase.client.TestReplicaWithCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/507 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 31d6509eb033 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-507/out/precommit/personality/provided.sh |
| git revision | branch-1 / bb31ffa |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/5/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/5/testReport/ |
| Max. process+thread count | 4298 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/5/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Reidddddd** [comment]
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.hbase.master.normalizer.TestSimpleRegionNormalizerOnCluster
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.361 s - in org.apache.hadoop.hbase.master.normalizer.TestSimpleRegionNormalizerOnCluster
[INFO] Running org.apache.hadoop.hbase.replication.multiwal.TestReplicationEndpointWithMultipleWAL
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.84 s - in org.apache.hadoop.hbase.replication.multiwal.TestReplicationEndpointWithMultipleWAL
[INFO] Running org.apache.hadoop.hbase.client.TestAdmin2
[INFO] Tests run: 29, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 130.194 s - in org.apache.hadoop.hbase.client.TestAdmin2
[INFO] Running org.apache.hadoop.hbase.client.TestReplicaWithCluster
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 115.657 s - in org.apache.hadoop.hbase.client.TestReplicaWithCluster
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 47, Failures: 0, Errors: 0, Skipped: 0
```

All failed tests are not related.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 51 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 512 | branch-1 passed |
| +1 | compile | 43 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 49 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 100 | branch-1 passed |
| +1 | shadedjars | 178 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 38 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 49 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 174 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 170 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 125 | the patch passed |
| +1 | compile | 41 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 41 | the patch passed |
| +1 | compile | 44 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 44 | the patch passed |
| +1 | checkstyle | 90 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 179 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 329 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 29 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 43 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 169 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 7065 | hbase-server in the patch failed. |
| +1 | asflicense | 25 | The patch does not generate ASF License warnings. |
| | | 9538 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.procedure.TestFailedProcCleanup |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/507 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 07dbcafbabb8 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-507/out/precommit/personality/provided.sh |
| git revision | branch-1 / 24a821c |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/6/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/6/testReport/ |
| Max. process+thread count | 4522 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-507/6/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
