### PR TITLE
HBASE-23035 Retain region to the last RegionServer make the failover …

### PR DESCRIPTION
**Pull request by infraio**
…slower

### CODE REVIEW

**Comment by infraio** [comment]
Pull request for branch-2.1.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 14s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-2.1 Compile Tests _ |
| :green_heart: |  mvninstall  |   5m 10s |  branch-2.1 passed  |
| :green_heart: |  compile  |   0m 54s |  branch-2.1 passed  |
| :green_heart: |  checkstyle  |   1m 18s |  branch-2.1 passed  |
| :green_heart: |  shadedjars  |   3m 57s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 38s |  branch-2.1 passed  |
| :blue_heart: |  spotbugs  |   2m 45s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   2m 42s |  branch-2.1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   4m 36s |  the patch passed  |
| :green_heart: |  compile  |   0m 54s |  the patch passed  |
| :green_heart: |  javac  |   0m 54s |  the patch passed  |
| :green_heart: |  checkstyle  |   1m 15s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   3m 57s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  20m 12s |  Patch does not cause any errors with Hadoop 2.7.7 2.8.5 or 3.0.3 3.1.2.  |
| :green_heart: |  javadoc  |   0m 38s |  the patch passed  |
| :green_heart: |  findbugs  |   3m  6s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 231m 51s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   0m 34s |  The patch does not generate ASF License warnings.  |
|  |   | 289m 38s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.TestRestartCluster |
|   | hadoop.hbase.master.procedure.TestServerCrashProcedureWithReplicas |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/650 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux c79a6770b365 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-650/out/precommit/personality/provided.sh |
| git revision | branch-2.1 / 20e0289fe5 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/1/testReport/ |
| Max. process+thread count | 4784 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   3m 27s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.1 Compile Tests _ |
| :green_heart: |  mvninstall  |   5m 38s |  branch-2.1 passed  |
| :green_heart: |  compile  |   0m 56s |  branch-2.1 passed  |
| :green_heart: |  checkstyle  |   1m 32s |  branch-2.1 passed  |
| :green_heart: |  shadedjars  |   4m 19s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 35s |  branch-2.1 passed  |
| :blue_heart: |  spotbugs  |   2m 51s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   2m 48s |  branch-2.1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   5m  4s |  the patch passed  |
| :green_heart: |  compile  |   0m 55s |  the patch passed  |
| :green_heart: |  javac  |   0m 55s |  the patch passed  |
| :broken_heart: |  checkstyle  |   1m 25s |  hbase-server: The patch generated 1 new + 4 unchanged - 0 fixed = 5 total (was 4)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   4m 18s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  21m 44s |  Patch does not cause any errors with Hadoop 2.7.7 2.8.5 or 3.0.3 3.1.2.  |
| :green_heart: |  javadoc  |   0m 33s |  the patch passed  |
| :green_heart: |  findbugs  |   3m  1s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 212m 30s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   0m 35s |  The patch does not generate ASF License warnings.  |
|  |   | 275m 51s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.TestMasterOperationsForRegionReplicas |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.master.procedure.TestServerCrashProcedureWithReplicas |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/650 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 87b04a776c00 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-650/out/precommit/personality/provided.sh |
| git revision | branch-2.1 / 20e0289fe5 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/2/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/2/testReport/ |
| Max. process+thread count | 4490 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   2m 44s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 4 new or modified test files.  |
||| _ branch-2.1 Compile Tests _ |
| :green_heart: |  mvninstall  |   8m  9s |  branch-2.1 passed  |
| :green_heart: |  compile  |   1m 26s |  branch-2.1 passed  |
| :green_heart: |  checkstyle  |   2m  1s |  branch-2.1 passed  |
| :green_heart: |  shadedjars  |   5m 33s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 46s |  branch-2.1 passed  |
| :blue_heart: |  spotbugs  |   3m 25s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   3m 24s |  branch-2.1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   7m  1s |  the patch passed  |
| :green_heart: |  compile  |   1m 14s |  the patch passed  |
| :green_heart: |  javac  |   1m 14s |  the patch passed  |
| :broken_heart: |  checkstyle  |   1m 51s |  hbase-server: The patch generated 6 new + 19 unchanged - 0 fixed = 25 total (was 19)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   5m 23s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  28m 57s |  Patch does not cause any errors with Hadoop 2.7.7 2.8.5 or 3.0.3 3.1.2.  |
| :green_heart: |  javadoc  |   0m 46s |  the patch passed  |
| :green_heart: |  findbugs  |   3m 40s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 212m 45s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   0m 27s |  The patch does not generate ASF License warnings.  |
|  |   | 294m 53s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAdmin1 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/650 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 3cdd8f9d9f99 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-650/out/precommit/personality/provided.sh |
| git revision | branch-2.1 / 23adf23a4f |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/3/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/3/testReport/ |
| Max. process+thread count | 4423 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 39s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 4 new or modified test files.  |
||| _ branch-2.1 Compile Tests _ |
| :green_heart: |  mvninstall  |   5m 10s |  branch-2.1 passed  |
| :green_heart: |  compile  |   0m 55s |  branch-2.1 passed  |
| :green_heart: |  checkstyle  |   1m 17s |  branch-2.1 passed  |
| :green_heart: |  shadedjars  |   3m 57s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 36s |  branch-2.1 passed  |
| :blue_heart: |  spotbugs  |   2m 44s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   2m 43s |  branch-2.1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   4m 34s |  the patch passed  |
| :green_heart: |  compile  |   0m 54s |  the patch passed  |
| :green_heart: |  javac  |   0m 54s |  the patch passed  |
| :green_heart: |  checkstyle  |   1m 18s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   3m 55s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  19m 32s |  Patch does not cause any errors with Hadoop 2.7.7 2.8.5 or 3.0.3 3.1.2.  |
| :green_heart: |  javadoc  |   0m 34s |  the patch passed  |
| :green_heart: |  findbugs  |   2m 38s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  | 138m  9s |  hbase-server in the patch passed.  |
| :green_heart: |  asflicense  |   0m 28s |  The patch does not generate ASF License warnings.  |
|  |   | 193m 30s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/650 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux c42139cd7122 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-650/out/precommit/personality/provided.sh |
| git revision | branch-2.1 / 23adf23a4f |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/4/testReport/ |
| Max. process+thread count | 4124 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-650/4/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
