### PR TITLE
HBASE-22615 Make TestChoreService more robust to timing

### PR DESCRIPTION
**Pull request by busbey**
* phrase fudge factor "deltas" in terms of the original period
* increase the delta allowed for chore timing from 5% to 20%
* improve some assertions

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 118 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 303 | master passed |
| +1 | compile | 24 | master passed |
| +1 | checkstyle | 25 | master passed |
| +1 | shadedjars | 301 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 42 | master passed |
| +1 | javadoc | 21 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 269 | the patch passed |
| +1 | compile | 23 | the patch passed |
| +1 | javac | 23 | the patch passed |
| +1 | checkstyle | 24 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 279 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 867 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 49 | the patch passed |
| +1 | javadoc | 19 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 159 | hbase-common in the patch passed. |
| +1 | asflicense | 11 | The patch does not generate ASF License warnings. |
| | | 2857 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.5 Server=18.09.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-328/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/328 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 3c3c7984dc11 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 6d08ffcfc6 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-328/1/testReport/ |
| Max. process+thread count | 252 (vs. ulimit of 10000) |
| modules | C: hbase-common U: hbase-common |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-328/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
before this change it takes me ~10 runs to get a failure. after it so far I've gotten through 25.

**Comment by busbey** [comment]
have now gotten through 100 additional runs with this patch in place.

**Comment by jatsakthi** [comment]
+1 from my side as well, Sean!

**Comment by busbey** [comment]
thanks folks!

**Pull request closed without merging**
