### PR TITLE
For testing github PR

### PR DESCRIPTION
**Pull request by Apache9**
Check whether we could trigger a yetus build

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 236 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ HBASE-22147 Compile Tests _ |
| +1 | mvninstall | 269 | HBASE-22147 passed |
| +1 | compile | 55 | HBASE-22147 passed |
| +1 | checkstyle | 33 | HBASE-22147 passed |
| +1 | shadedjars | 252 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 63 | HBASE-22147 passed |
| +1 | javadoc | 22 | HBASE-22147 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 235 | the patch passed |
| +1 | compile | 52 | the patch passed |
| +1 | javac | 52 | the patch passed |
| +1 | checkstyle | 30 | the patch passed |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | shadedjars | 256 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1298 | Patch does not cause any errors with Hadoop 2.7.1 2.7.2 2.7.3 2.7.4 or 3.0.0. |
| +1 | findbugs | 67 | the patch passed |
| +1 | javadoc | 22 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 196 | hbase-client in the patch passed. |
| +1 | asflicense | 11 | The patch does not generate ASF License warnings. |
| | | 3169 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-110/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/110 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 9bd9ebfb6720 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | HBASE-22147 / 604e7e2346 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-110/1/testReport/ |
| Max. process+thread count | 305 (vs. ulimit of 10000) |
| modules | C: hbase-client U: hbase-client |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-110/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by maoling** [comment]
awesome work!

**Comment by busbey** [comment]
We need our own commenting account. We shouldn't be using Hadoop's. I'm a bit surprised we were able to.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 243 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ HBASE-22147 Compile Tests _ |
| +1 | mvninstall | 255 | HBASE-22147 passed |
| +1 | compile | 58 | HBASE-22147 passed |
| +1 | checkstyle | 33 | HBASE-22147 passed |
| +1 | shadedjars | 257 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 60 | HBASE-22147 passed |
| +1 | javadoc | 23 | HBASE-22147 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 243 | the patch passed |
| +1 | compile | 54 | the patch passed |
| +1 | javac | 54 | the patch passed |
| +1 | checkstyle | 32 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 257 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 495 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 67 | the patch passed |
| +1 | javadoc | 23 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 204 | hbase-client in the patch passed. |
| +1 | asflicense | 12 | The patch does not generate ASF License warnings. |
| | | 2393 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-110/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/110 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 04824f7c2430 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | HBASE-22147 / 4301f26752 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-110/2/testReport/ |
| Max. process+thread count | 300 (vs. ulimit of 10000) |
| modules | C: hbase-client U: hbase-client |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-110/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
@busbey You can see the config of this job

https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/

On the Credentials, you can select the hadoop-yetus.

So we need to file an INFRA issue to create a new hbase-yetus github account?

**Comment by busbey** [comment]
IIRC Steve L over in Hadoop set things up. Essentially he made the GitHub account and made sure the Hadoop pmc had control of it.

I'm not sure if getting the access token into Jenkins was handled by himself or done via infra.

**Comment by Apache9** [comment]
The token can be added by ourselves I believe, there is an 'Add' button after the Credentials config.

And hadoop-yetus account is a member of the Apache on GitHub, I'm not sure how can we do this without the help of infra team? And we need to share a common email account across all the PMC members? Not sure what is the best practice...

**Comment by Apache9** [comment]
Oh, it is just the company field of the github profile, not the Organizations...

OK, the only problem is that how do we share the github account across the PMC members...

**Comment by joshelser** [comment]
> OK, the only problem is that how do we share the github account across the PMC members...

Maybe just a randomly generated password sent to private@hbase for now? Don't want that to the be the thing holding you up :)

**Comment by Apache9** [comment]
@joshelser We need an email address when creating a github account, so just the private@hbase?

It seems that we also have an apache-yetus account, so how do the yetus PMC members manage this account? Out mighty @busbey , I think you are the PMC member of yetus.

**Comment by joshelser** [comment]
> We need an email address when creating a github account, so just the private@hbase?

That'd be my suggestion.

**Comment by petersomogyi** [comment]
If I'm correct the hadoop-yetus email address was created for this and made it private. We could do the same and request an hbase-yetus list for this purpose.

**Comment by Apache9** [comment]
And another thing is that, seems the hadoop-yetus can only comment on this PR but for the PRs of hadoop, the hadoop-yetus can start a review. Maybe this also means we need to create our own account and do some magics...

**Comment by Apache9** [comment]
> If I'm correct the hadoop-yetus email address was created for this and made it private. We could do the same and request an hbase-yetus list for this purpose.

So file an issue on infra?

**Comment by busbey** [comment]
we could use private@hbase. I believe the apache-yetus account uses private@yetus.

If I had to guess, I'd say making a new email list as hadoop-yetus did would be so that non-PMC members can share in maintenance work. If we want that, then yes I think an INFRA jira is needed since we'd want it to be private. (there's a self-serve thing for making public mailing lists.)

**Comment by Apache9** [comment]
Oh, I deleted the HBASE-22147 branch after committing HBASE-22152...

Let continue the discussion on HBASE-22147.

**Pull request closed without merging**
