### PR TITLE
HBASE-22962 Fix typo in javadoc description

### PR DESCRIPTION
**Pull request by KangZhiDong**

### CODE REVIEW

**Comment by busbey** [comment]
Hi,

Thanks for this PR.

The HBase project mainly use [The ASF JIRA](https://issues.apache.org/jira/projects/HBASE/issues) for tracking issues, would you mind filing a jira and describing your problem there? 

For how to contribute to HBase, please refer to [Get involved](http://hbase.apache.org/book.html#getting.involved) for more details.

And feel free to email your questions or doubts to dev@hbase.apache.org for help.

**Comment by KangZhiDong** [comment]
> Hi,
> 
> Thanks for this PR.
> 
> The HBase project mainly use [The ASF JIRA](https://issues.apache.org/jira/projects/HBASE/issues) for tracking issues, would you mind filing a jira and describing your problem there?
> 
> For how to contribute to HBase, please refer to [Get involved](http://hbase.apache.org/book.html#getting.involved) for more details.
> 
> And feel free to email your questions or doubts to [dev@hbase.apache.org](mailto:dev@hbase.apache.org) for help.

https://issues.apache.org/jira/browse/HBASE-22962

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 55 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 6 new or modified test files. |
||| _ master Compile Tests _ |
| 0 | mvndep | 39 | Maven dependency ordering for branch |
| +1 | mvninstall | 388 | master passed |
| +1 | compile | 218 | master passed |
| +1 | checkstyle | 230 | master passed |
| +1 | shadedjars | 319 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 160 | master passed |
| 0 | spotbugs | 108 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 617 | master passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 18 | Maven dependency ordering for patch |
| +1 | mvninstall | 398 | the patch passed |
| +1 | compile | 230 | the patch passed |
| +1 | javac | 230 | the patch passed |
| +1 | checkstyle | 238 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 347 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1167 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 146 | the patch passed |
| +1 | findbugs | 540 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 185 | hbase-common in the patch passed. |
| +1 | unit | 74 | hbase-http in the patch passed. |
| +1 | unit | 9491 | hbase-server in the patch passed. |
| +1 | unit | 222 | hbase-thrift in the patch passed. |
| +1 | unit | 899 | hbase-backup in the patch passed. |
| +1 | unit | 328 | hbase-rest in the patch passed. |
| +1 | asflicense | 208 | The patch does not generate ASF License warnings. |
| | | 17017 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-569/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/569 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux a6a031e38842 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-569/out/precommit/personality/provided.sh |
| git revision | master / b642ee0418 |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-569/1/testReport/ |
| Max. process+thread count | 4605 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-http hbase-server hbase-thrift hbase-backup hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-569/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jojochuang** [comment]
LGTM +1 (non binding)

**Comment by jojochuang** [comment]
(I reviewed the patch, and then realized it's a HBase patch, not a Hadoop patch. Still, since I invested my time in this review, I thought to post a patch review to save other reviewers' time)

**Comment by Apache9** [comment]
Merged to master. Thanks @jojochuang for reviewing.

**Comment by busbey** [comment]
> (I reviewed the patch, and then realized it's a HBase patch, not a Hadoop patch. Still, since I invested my time in this review, I thought to post a patch review to save other reviewers' time)

We love reviews from not-yet-committers. Please feel free to keep doing them. It definitely helps me if someone else has taken a look at a change request. 😸

**Pull request merged**
