### PR TITLE
[HBASE-25539] Add age of oldest wal metric

### PR DESCRIPTION
**Pull request by shahrs87**
Master branch PR: https://github.com/apache/hbase/pull/2945
branch-2 PR: https://github.com/apache/hbase/pull/2962

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  12m  6s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 31s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 12s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m  9s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   1m 19s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   2m  9s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  4s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  9s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 16s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   2m 44s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m  7s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 58s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  8s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   1m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 18s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  javac  |   1m 18s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m  2s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 50s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 38s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 14s |  hbase-hadoop-compat in the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  hbase-hadoop2-compat in the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| +1 :green_heart: |  javadoc  |   0m 32s |  hbase-server-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8)  |
| +1 :green_heart: |  javadoc  |   0m 17s |  hbase-hadoop-compat in the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  javadoc  |   0m 18s |  hbase-hadoop2-compat in the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  javadoc  |   0m 41s |  hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8)  |
| -1 :x: |  findbugs  |   2m 58s |  hbase-server generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  hbase-hadoop-compat in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 39s |  hbase-hadoop2-compat in the patch passed.  |
| -1 :x: |  unit  | 130m 23s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m 15s |  The patch does not generate ASF License warnings.  |
|  |   | 195m 13s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-server |
|  |  Unread field:ReplicationSourceLogQueue.java:[line 55] |
| Failed junit tests | hadoop.hbase.replication.regionserver.TestWALEntryStream |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2963 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux f4f4d3fb8cc2 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2963/out/precommit/personality/provided.sh |
| git revision | branch-1 / 2d26c94 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| findbugs | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/1/artifact/out/new-findbugs-hbase-server.html |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/1/testReport/ |
| Max. process+thread count | 4005 (vs. ulimit of 10000) |
| modules | C: hbase-hadoop-compat hbase-hadoop2-compat hbase-server U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by bharathv** [comment]
@shahrs87 failures seem related? Mind taking a quick look?

**Comment by shahrs87** [comment]
> @shahrs87 failures seem related? Mind taking a quick look?

Yes..Missed it due to many emails for the same jira. :(

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 48s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 22s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m  9s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   1m 31s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   2m  8s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  3s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  9s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 15s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   2m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m  6s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 58s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 11s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   1m 11s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 19s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  javac  |   1m 19s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 52s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 44s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 14s |  hbase-hadoop-compat in the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| +1 :green_heart: |  javadoc  |   0m 14s |  hbase-hadoop2-compat in the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| +1 :green_heart: |  javadoc  |   0m 32s |  hbase-server-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8)  |
| +1 :green_heart: |  javadoc  |   0m 17s |  hbase-hadoop-compat in the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  javadoc  |   0m 18s |  hbase-hadoop2-compat in the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  javadoc  |   0m 40s |  hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8)  |
| -1 :x: |  findbugs  |   2m 54s |  hbase-server generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  hbase-hadoop-compat in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  hbase-hadoop2-compat in the patch passed.  |
| +1 :green_heart: |  unit  | 108m 27s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 16s |  The patch does not generate ASF License warnings.  |
|  |   | 168m 23s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:hbase-server |
|  |  Unread field:ReplicationSourceLogQueue.java:[line 55] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2963 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux bcec2f2bbdcd 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2963/out/precommit/personality/provided.sh |
| git revision | branch-1 / f9a9148 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| findbugs | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/2/artifact/out/new-findbugs-hbase-server.html |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/2/testReport/ |
| Max. process+thread count | 4493 (vs. ulimit of 10000) |
| modules | C: hbase-hadoop-compat hbase-hadoop2-compat hbase-server U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by shahrs87** [comment]
@bharathv I have fixed the test failures. Code in branch-1 and branch-2 are very different. So missed to apply some changes while resolving merge conflicts.
There is 1 findbugs warning. That is because of an unused variable `ReplicationSource source` in newly created `ReplicationSourceLogQueue` class. In master and branch-2, we refer to ReplicationSource class to print some log line with peerId. We get that peerId from ReplicationSource class. But in branch-1, we don't have that logline.
I have the following options with me:
1. Remove ReplicationSource reference from  branch-1 and make findbugs happy. This will create some difference in code between branch-1 and branch-2/master.
2. Keep as it is and introduce 1 extra findbugs warning.

I would like to have minimal code difference so I prefer option#2 but open for suggestions. Thank you !

**Comment by shahrs87** [comment]
@bharathv  Ignore my previous comment. I made changes to fix findbugs warning. Thank you for the review !

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 48s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 28s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 36s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 21s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   1m 25s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   2m  5s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  2s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  8s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 18s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   2m 40s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m  4s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  3s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 11s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   1m 11s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 23s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  javac  |   1m 23s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 32s |  hbase-server: The patch generated 1 new + 12 unchanged - 0 fixed = 13 total (was 12)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 53s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 46s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  hbase-hadoop-compat in the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  hbase-hadoop2-compat in the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| +1 :green_heart: |  javadoc  |   0m 33s |  hbase-server-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8)  |
| +1 :green_heart: |  javadoc  |   0m 17s |  hbase-hadoop-compat in the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  javadoc  |   0m 18s |  hbase-hadoop2-compat in the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  javadoc  |   0m 42s |  hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8)  |
| +1 :green_heart: |  findbugs  |   4m 29s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  hbase-hadoop-compat in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 39s |  hbase-hadoop2-compat in the patch passed.  |
| +1 :green_heart: |  unit  | 112m 50s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  2s |  The patch does not generate ASF License warnings.  |
|  |   | 167m 12s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2963 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux a622083f95e1 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2963/out/precommit/personality/provided.sh |
| git revision | branch-1 / f9a9148 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/3/artifact/out/diff-checkstyle-hbase-server.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/3/testReport/ |
| Max. process+thread count | 4360 (vs. ulimit of 10000) |
| modules | C: hbase-hadoop-compat hbase-hadoop2-compat hbase-server U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/3/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by bharathv** [comment]
@shahrs87 One last nit from checkstyle, if you don't mind fixing. 

```
./hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicationSourceLogQueue.java:21:import static org.mockito.Mockito.mock;:15: Unused import - org.mockito.Mockito.mock. [UnusedImports]
```

**Comment by shahrs87** [comment]
> @shahrs87 One last nit from checkstyle, if you don't mind fixing.

@bharathv  Done !! Thank you !

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 39s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 27s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  3s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 12s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   1m 24s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   2m 18s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  7s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 10s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   1m 20s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   2m 53s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m 18s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  7s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 15s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   1m 15s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 22s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  javac  |   1m 22s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 14s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 58s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 58s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 14s |  hbase-hadoop-compat in the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  hbase-hadoop2-compat in the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| +1 :green_heart: |  javadoc  |   0m 34s |  hbase-server-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8)  |
| +1 :green_heart: |  javadoc  |   0m 18s |  hbase-hadoop-compat in the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  javadoc  |   0m 18s |  hbase-hadoop2-compat in the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  javadoc  |   0m 43s |  hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8)  |
| +1 :green_heart: |  findbugs  |   4m 37s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  hbase-hadoop-compat in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  hbase-hadoop2-compat in the patch passed.  |
| +1 :green_heart: |  unit  | 110m 18s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 15s |  The patch does not generate ASF License warnings.  |
|  |   | 165m 10s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2963 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 1c49f831f5c2 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2963/out/precommit/personality/provided.sh |
| git revision | branch-1 / f9a9148 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/4/testReport/ |
| Max. process+thread count | 3887 (vs. ulimit of 10000) |
| modules | C: hbase-hadoop-compat hbase-hadoop2-compat hbase-server U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2963/4/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by bharathv** [comment]
Thanks @shahrs87

**Pull request merged**
