### PR TITLE
HBASE-26899 [branch-2.4] Run spotless:apply

### PR DESCRIPTION
**Pull request by apurtell**
Backport HBASE-26617 to enable spotless on `branch-2.4`. Then run `spotless:apply` without a ratchet.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  7s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  7s |  Shelldocs was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m  4s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   5m 54s |  branch-2.4 passed  |
| +1 :green_heart: |  checkstyle  |   2m 19s |  branch-2.4 passed  |
| +1 :green_heart: |  spotbugs  |  18m 27s |  branch-2.4 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 50s |  the patch passed  |
| +1 :green_heart: |  compile  |   5m 53s |  the patch passed  |
| -0 :warning: |  javac  |   5m 53s |  root generated 38 new + 1638 unchanged - 38 fixed = 1676 total (was 1676)  |
| -0 :warning: |  checkstyle  |   1m 48s |  root: The patch generated 752 new + 2006 unchanged - 2565 fixed = 2758 total (was 4571)  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| -0 :warning: |  whitespace  |   0m  0s |  The patch has 26 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m 29s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  hadoopcheck  |  10m 11s |  Patch does not cause any errors with Hadoop 2.10.0 or 3.1.2 3.2.1.  |
| +1 :green_heart: |  spotbugs  |  22m 18s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   5m 49s |  The patch does not generate ASF License warnings.  |
|  |   |  99m 31s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4290 |
| Optional Tests | dupname asflicense shellcheck shelldocs javac hadoopcheck xml compile spotbugs hbaseanti checkstyle |
| uname | Linux bf317bfb9313 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / 9355506c30 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| javac | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/artifact/yetus-general-check/output/diff-compile-javac-root.txt |
| checkstyle | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/artifact/yetus-general-check/output/diff-checkstyle-root.txt |
| whitespace | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/artifact/yetus-general-check/output/whitespace-eol.txt |
| Max. process+thread count | 138 (vs. ulimit of 12500) |
| modules | C: hbase-checkstyle hbase-annotations hbase-build-configuration hbase-logging hbase-protocol-shaded hbase-common hbase-metrics-api hbase-hadoop-compat hbase-metrics hbase-hadoop2-compat hbase-protocol hbase-client hbase-zookeeper hbase-replication hbase-resource-bundle hbase-http hbase-asyncfs hbase-procedure hbase-server hbase-mapreduce hbase-testing-util hbase-thrift hbase-rsgroup hbase-shell hbase-endpoint hbase-it hbase-rest hbase-examples hbase-shaded hbase-shaded/hbase-shaded-client hbase-shaded/hbase-shaded-client-byo-hadoop hbase-shaded/hbase-shaded-mapreduce hbase-external-blockcache hbase-hbtop hbase-assembly hbase-shaded/hbase-shaded-testing-util hbase-shaded/hbase-shaded-testing-util-tester hbase-shaded/hbase-shaded-check-invariants hbase-shaded/hbase-shaded-with-hadoop-check-invariants hbase-archetypes hbase-archetypes/hbase-client-project hbase-archetypes/hbase-shaded-client-project hbase-archetypes/hbase-archetype-builder . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/console |
| versions | git=2.17.1 maven=3.6.3 shellcheck=0.4.6 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 43s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m 26s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 33s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   4m 36s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   3m 54s |  branch-2.4 passed  |
| +1 :green_heart: |  shadedjars  |  10m 22s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |  25m  9s |  branch-2.4 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 35s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 46s |  the patch passed  |
| +1 :green_heart: |  compile  |   4m 28s |  the patch passed  |
| +1 :green_heart: |  javac  |   4m 28s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   9m 53s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |  23m 13s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  14m 24s |  root in the patch failed.  |
|  |   | 132m 54s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4290 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux de3a06a9bd76 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / 9355506c30 |
| Default Java | AdoptOpenJDK-11.0.10+9 |
| unit | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/testReport/ |
| Max. process+thread count | 726 (vs. ulimit of 12500) |
| modules | C: hbase-checkstyle hbase-annotations hbase-build-configuration hbase-logging hbase-protocol-shaded hbase-common hbase-metrics-api hbase-hadoop-compat hbase-metrics hbase-hadoop2-compat hbase-protocol hbase-client hbase-zookeeper hbase-replication hbase-resource-bundle hbase-http hbase-asyncfs hbase-procedure hbase-server hbase-mapreduce hbase-testing-util hbase-thrift hbase-rsgroup hbase-shell hbase-endpoint hbase-it hbase-rest hbase-examples hbase-shaded hbase-shaded/hbase-shaded-client hbase-shaded/hbase-shaded-client-byo-hadoop hbase-shaded/hbase-shaded-mapreduce hbase-external-blockcache hbase-hbtop hbase-assembly hbase-shaded/hbase-shaded-testing-util hbase-shaded/hbase-shaded-testing-util-tester hbase-shaded/hbase-shaded-check-invariants hbase-shaded/hbase-shaded-with-hadoop-check-invariants hbase-archetypes hbase-archetypes/hbase-client-project hbase-archetypes/hbase-shaded-client-project hbase-archetypes/hbase-archetype-builder . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 56s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m 22s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2.4 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 21s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 42s |  branch-2.4 passed  |
| +1 :green_heart: |  compile  |   1m 27s |  branch-2.4 passed  |
| +1 :green_heart: |  shadedjars  |   4m 15s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   8m 31s |  branch-2.4 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 50s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 19s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 19s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   3m 50s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   8m 39s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 265m 44s |  root in the patch failed.  |
|  |   | 313m 32s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4290 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 7def600675cb 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.4 / 9355506c30 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| unit | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/testReport/ |
| Max. process+thread count | 2726 (vs. ulimit of 12500) |
| modules | C: hbase-checkstyle hbase-annotations hbase-build-configuration hbase-logging hbase-protocol-shaded hbase-common hbase-metrics-api hbase-hadoop-compat hbase-metrics hbase-hadoop2-compat hbase-protocol hbase-client hbase-zookeeper hbase-replication hbase-resource-bundle hbase-http hbase-asyncfs hbase-procedure hbase-server hbase-mapreduce hbase-testing-util hbase-thrift hbase-rsgroup hbase-shell hbase-endpoint hbase-it hbase-rest hbase-examples hbase-shaded hbase-shaded/hbase-shaded-client hbase-shaded/hbase-shaded-client-byo-hadoop hbase-shaded/hbase-shaded-mapreduce hbase-external-blockcache hbase-hbtop hbase-assembly hbase-shaded/hbase-shaded-testing-util hbase-shaded/hbase-shaded-testing-util-tester hbase-shaded/hbase-shaded-check-invariants hbase-shaded/hbase-shaded-with-hadoop-check-invariants hbase-archetypes hbase-archetypes/hbase-client-project hbase-archetypes/hbase-shaded-client-project hbase-archetypes/hbase-archetype-builder . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4290/1/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
The precommit result is revealing some flaky test issues. This change includes only formatting changes.

**Review by Apache9 — APPROVED** [review]

**Comment by apurtell** [comment]
Work has been progressing on #4312 instead.

**Pull request closed without merging**
