### PR TITLE
HBASE-23575: Remove dead code in AsyncRegistry

### PR DESCRIPTION
**Pull request by bharathv**
This is a prep change for master based async registry impl.
Removes a bunch of dead code and fixes some checkstyle nits.

### CODE REVIEW

**Comment by bharathv** [comment]
@ndimiduk / @saintstack / @wchevreuil  FYI. This is a prep change for the next patch that implements master based registry. No change in functionality. Just cleans up the dead code from the base interface and impls.

**Comment by busbey** [comment]
if you're still planning to use jira ID HBASE-23305 to implement the registry, and you want this to merge prior to that then please give this change its own jira id.

**Comment by bharathv** [comment]
Yes, I plan to use the same jira ID. Just curious, why is there 1-1 commit-jira ID mapping? I thought it'd be good to group all the commits related to same jira grouped under a single jira ID. I'm breaking them up into smaller changes to make it easier for reviewers. Otherwise there is a lot of noise in the core PR that implements the functionality.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 44s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ HBASE-18095/client-locate-meta-no-zookeeper Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 40s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   6m 44s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  compile  |   1m 38s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  checkstyle  |   2m 21s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  shadedjars  |   6m  2s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m  9s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +0 :ok: |  spotbugs  |   5m  6s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   6m 26s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 56s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 46s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 46s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 20s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   5m  2s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  16m  1s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   0m 59s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   5m 36s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 53s |  hbase-client in the patch passed.  |
| -1 :x: |  unit  | 177m 44s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m  8s |  The patch does not generate ASF License warnings.  |
|  |   | 251m 19s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.quotas.TestClusterScopeQuotaThrottle |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-929/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/929 |
| JIRA Issue | HBASE-23305 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux f2e665a009af 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-929/out/precommit/personality/provided.sh |
| git revision | HBASE-18095/client-locate-meta-no-zookeeper / d0f68831f4 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-929/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-929/1/testReport/ |
| Max. process+thread count | 4938 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-929/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by bharathv** [comment]
@busbey Any thoughts on my last comment? Just to be clear, I don't mind creating a new jira and updating the PR with the ID. Just want to be sure I'm doing the right thing. Let me know how to proceed.

**Comment by busbey** [comment]
> Yes, I was planning to use the same jira ID for registry implementation. Just curious, why is there 1-1 commit-jira ID mapping? I thought it'd be good to group all the commits related to same jira grouped under a single jira ID. I'm breaking them up into smaller changes to make it easier for reviewers. Otherwise there is a lot of noise in the core PR that implements the functionality.

that's fine, but then we should merge all of these into a feature branch and then get the feature branch into the main code base.

we aim for 1:1 commit:jira id to ensure that the work represented by a given jira is either in a release or not. If you want work broken up but still to point towards a larger goal, historically we've done that via an umbrella jira that then has subtasks.

> @busbey Any thoughts on my last comment? Just to be clear, I don't mind creating a new jira and updating the PR with the ID. Just want to be sure I'm doing the right thing. Let me know how to proceed.

In general you should expect turn around time on responses measured in 1-3 days from me, just fyi.

**Comment by bharathv** [comment]
Cool. I updated the jira ID.

**Comment by busbey** [comment]
(merge in progress)

**Comment by bharathv** [comment]
Thanks Sean. Once you are done with the merge, can you please rebase the feature branch (HBASE-18095/client-locate-meta-no-zookeeper) against the latest master? Helps me keep my code conflict free.

**Comment by busbey** [comment]
@bharathv can you make a branch-2 specific version of this? there's a nontrivial number of gaps backporting.

**Comment by busbey** [comment]
further backports off of #940

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  7s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ HBASE-18095/client-locate-meta-no-zookeeper Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 34s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 49s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  compile  |   1m 22s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  checkstyle  |   2m  3s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  shadedjars  |   5m  1s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 57s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +0 :ok: |  spotbugs  |   4m 37s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   5m 46s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 26s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 24s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 24s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 57s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   5m  1s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  17m 30s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   0m 56s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   6m 12s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 45s |  hbase-client in the patch passed.  |
| -1 :x: |  unit  | 251m 26s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 51s |  The patch does not generate ASF License warnings.  |
|  |   | 322m 33s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.assignment.TestRegionReplicaSplit |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-929/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/929 |
| JIRA Issue | HBASE-23575 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 87e1ff474473 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-929/out/precommit/personality/provided.sh |
| git revision | HBASE-18095/client-locate-meta-no-zookeeper / d0f68831f4 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-929/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-929/2/testReport/ |
| Max. process+thread count | 5203 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-929/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
