### PR TITLE
HBASE-22389 Revert "HBASE-19275 TestSnapshotFileCache never worked pr…

### PR DESCRIPTION
**Pull request by z-york**
…operly"

This reverts commit e8e4beacb039299a9e56cd355e3ada08784a7acb.

### CODE REVIEW

**Comment by z-york** [comment]
Note this will actually cause the new test added in HBASE-21070 in TestSnapshotFileCache to fail until HBASE-22190 is backported (I'm opening a different PR for that). I originally missed that it wasn't backported to branch-1, then when I realized it wasn't, I was confused why the test I added was passing which led me to this.

**Comment by z-york** [comment]
https://github.com/apache/hbase/pull/230 should be merged first since it will cause test failures otherwise (as mentioned previously)

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 85 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | findbugs | 5 | Findbugs executables are not available. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 1 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 241 | branch-1 passed |
| +1 | compile | 48 | branch-1 passed with JDK v1.8.0_212 |
| +1 | compile | 44 | branch-1 passed with JDK v1.7.0_222 |
| +1 | checkstyle | 88 | branch-1 passed |
| +1 | shadedjars | 221 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 47 | branch-1 passed with JDK v1.8.0_212 |
| +1 | javadoc | 45 | branch-1 passed with JDK v1.7.0_222 |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 109 | the patch passed |
| +1 | compile | 40 | the patch passed with JDK v1.8.0_212 |
| +1 | javac | 40 | the patch passed |
| +1 | compile | 44 | the patch passed with JDK v1.7.0_222 |
| +1 | javac | 44 | the patch passed |
| -1 | checkstyle | 82 | hbase-server: The patch generated 2 new + 4 unchanged - 0 fixed = 6 total (was 4) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 167 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 98 | Patch does not cause any errors with Hadoop 2.7.4. |
| +1 | javadoc | 29 | the patch passed with JDK v1.8.0_212 |
| +1 | javadoc | 38 | the patch passed with JDK v1.7.0_222 |
||| _ Other Tests _ |
| -1 | unit | 7184 | hbase-server in the patch failed. |
| +1 | asflicense | 25 | The patch does not generate ASF License warnings. |
| | | 8746 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.snapshot.TestSnapshotFileCache |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-229/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/229 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 4a8c9b6ca0cd 4.4.0-143-generic #169~14.04.2-Ubuntu SMP Wed Feb 13 15:00:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-1 / 56548fc |
| maven | version: Apache Maven 3.0.5 |
| Default Java | 1.7.0_222 |
| Multi-JDK versions |  /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_212 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_222 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-229/1/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-229/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-229/1/testReport/ |
| Max. process+thread count | 3672 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-229/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by z-york** [comment]
Reran TestSnapshotFileCache after #230 and confirmed it passes now. Fixed checkstyle.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 9 | https://github.com/apache/hbase/pull/229 does not apply to branch-1. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/229 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-229/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
