### PR TITLE
HBASE-24578 [WAL] Add a parameter to config RingBufferEventHandler's SyncFuture count

### PR DESCRIPTION
**Pull request by WenFeiYi**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   9m 27s |  Docker failed to build yetus/hbase:7cf97016b9.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/2063 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-2063/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Reidddddd** [comment]
@WenFeiYi you can try again

**Comment by Reidddddd** [comment]
By adding a space or something to trigger the QA, if it works, you can change back

**Comment by Reidddddd** [comment]
Let me directly push it, it couldn't have much problem. It gets stuck too long

**Pull request merged**
