### PR TITLE
HBASE-23304: RPCs needed for client meta information lookup (apache#904)

### PR DESCRIPTION
**Pull request by bharathv**
This patch implements the RPCs needed for the meta information
lookup during connection init. New tests added to cover the RPC
code paths. HBASE-23305 builds on this to implement the client
side logic.

Fixed a bunch of checkstyle nits around the places the patch
touches.

Signed-off-by: Andrew Purtell <apurtell@apache.org>

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 35s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  0s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 19 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 22s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   2m 25s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 15s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   4m 16s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 34s |  branch-2 passed  |
| +0 :ok: |  spotbugs  |   0m 34s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   7m 51s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 24s |  the patch passed  |
| +1 :green_heart: |  cc  |   2m 24s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 24s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 12s |  The patch passed checkstyle in hbase-protocol-shaded  |
| +1 :green_heart: |  checkstyle  |   0m 37s |  hbase-client: The patch generated 0 new + 194 unchanged - 1 fixed = 194 total (was 195)  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  The patch passed checkstyle in hbase-zookeeper  |
| +1 :green_heart: |  checkstyle  |   1m 12s |  hbase-server: The patch generated 0 new + 119 unchanged - 13 fixed = 119 total (was 132)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 19s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  15m 39s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  hbaseprotoc  |   2m 17s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 33s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   8m 20s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 42s |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 45s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 53s |  hbase-zookeeper in the patch passed.  |
| +1 :green_heart: |  unit  | 153m 34s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 12s |  The patch does not generate ASF License warnings.  |
|  |   | 235m  0s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1098/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1098 |
| JIRA Issue | HBASE-23304 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 1aaa31531bb2 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1098/out/precommit/personality/provided.sh |
| git revision | branch-2 / e0f913323e |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1098/1/testReport/ |
| Max. process+thread count | 6066 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-zookeeper hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1098/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
@bharathv @apurtell What exactly was this commit? The message looks like it contains everything from the feature branch, but the changed files is just HBASE-23304.

Anyway, we haven't merged the feature branch to master yet; we're not quite ready to back port to branch-2. I think this should be reverted.

**Comment by bharathv** [comment]
Ya, so this is a squashed commit up until HBASE-23304. I'm ok with reverting it. I can submit a single PR with all the commits later, once the feature branch merges with master.

**Comment by apurtell** [comment]
Copying my comment from the JIRA:

There were multiple PRs opened for the same set of changes. I merged the one @bharathv indicated. 

If you want to do it per JIRA per branch, fine. One PR per JIRA per branch. However that's a lot of noise for what it's worth. 

I think it better one PR/merge for the whole backport per branch, with commit message incorporating all relevant JIRA references. These changes for the most part aren't useful in isolation.

**Comment by ndimiduk** [comment]
I see your reasoning. Squishing all the commits makes accounting more difficult, IMHO. The larger issue is that we're still stabilizing the tests vs. master; none of these commits have landed on master yet.

**Comment by ndimiduk** [comment]
I should say -- I propose one PR per branch containing all the commits, but land it using "rebase and merge" instead of "squash and merge" so that the individual commits are preserved. That make the accounting I refer to simpler. Agreed there's no need for one PR per commit.

**Pull request merged**
