### PR TITLE
HBASE-23008 put batch with updated position into queue even empty

### PR DESCRIPTION
**Pull request by bsglz**
In order to trigger cleanOldLogs

### CODE REVIEW

**Comment by bsglz** [comment]
@saintstack Could you help to review it ?

**Comment by HorizonNet** [comment]
@bsglz Is this a branch-2-only problem? If not, can you please target master and we then start backporting it.

**Comment by saintstack** [comment]
But like @HorizonNet says, Master branch is different. Does it have this issue?

**Comment by bsglz** [comment]
Yeah, branch-2 only, master is ok.
Close it.

**Pull request closed without merging**
