### PR TITLE
HBASE-19763 Fixed Checkstyle errors in hbase-procedure

### PR DESCRIPTION
**Pull request by HorizonNet**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 23 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 16 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 253 | master passed |
| +1 | compile | 20 | master passed |
| +1 | checkstyle | 17 | master passed |
| +1 | shadedjars | 265 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 30 | master passed |
| +1 | javadoc | 18 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 247 | the patch passed |
| +1 | compile | 19 | the patch passed |
| +1 | javac | 19 | the patch passed |
| +1 | checkstyle | 15 | hbase-procedure: The patch generated 0 new + 0 unchanged - 106 fixed = 0 total (was 106) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 266 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 505 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 35 | the patch passed |
| +1 | javadoc | 17 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 224 | hbase-procedure in the patch passed. |
| +1 | asflicense | 14 | The patch does not generate ASF License warnings. |
| | | 2051 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-167/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/167 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux b63e9c16b68b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 268bcce76f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-167/1/testReport/ |
| Max. process+thread count | 312 (vs. ulimit of 10000) |
| modules | C: hbase-procedure U: hbase-procedure |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-167/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Do we need to modify the pom to fail the compile when there are checkstyle errors? IIRC we do this for other modules?

**Comment by HorizonNet** [comment]
Good point. I forgot this one. Will update the PR.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 24 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 1 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 16 new or modified test files. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 258 | master passed |
| +1 | compile | 16 | master passed |
| +1 | checkstyle | 19 | master passed |
| +1 | shadedjars | 272 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 29 | master passed |
| +1 | javadoc | 16 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 250 | the patch passed |
| +1 | compile | 17 | the patch passed |
| +1 | javac | 17 | the patch passed |
| +1 | checkstyle | 13 | hbase-procedure: The patch generated 0 new + 0 unchanged - 106 fixed = 0 total (was 106) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 1 | The patch has no ill-formed XML file. |
| +1 | shadedjars | 263 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 509 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 37 | the patch passed |
| +1 | javadoc | 16 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 234 | hbase-procedure in the patch passed. |
| +1 | asflicense | 13 | The patch does not generate ASF License warnings. |
| | | 2064 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-167/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/167 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  shadedjars  hadoopcheck  xml  compile  findbugs  hbaseanti  checkstyle  |
| uname | Linux 07ceaba8c8ee 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 268bcce76f |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-167/2/testReport/ |
| Max. process+thread count | 310 (vs. ulimit of 10000) |
| modules | C: hbase-procedure U: hbase-procedure |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-167/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
