### PR TITLE
HBASE-22635 : Prevent NPE for WALMapper - Delete/Put add() calls

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 179 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 286 | master passed |
| +1 | compile | 25 | master passed |
| +1 | checkstyle | 15 | master passed |
| +1 | shadedjars | 253 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 40 | master passed |
| +1 | javadoc | 15 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 234 | the patch passed |
| +1 | compile | 24 | the patch passed |
| +1 | javac | 24 | the patch passed |
| +1 | checkstyle | 17 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 269 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 794 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | findbugs | 46 | the patch passed |
| +1 | javadoc | 15 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 1482 | hbase-mapreduce in the patch passed. |
| +1 | asflicense | 13 | The patch does not generate ASF License warnings. |
| | | 4026 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-342/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/342 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 9cba9623e3bf 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / 0198868531 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-342/1/testReport/ |
| Max. process+thread count | 4775 (vs. ulimit of 10000) |
| modules | C: hbase-mapreduce U: hbase-mapreduce |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-342/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by jatsakthi** [comment]
Left a comment in the jira

**Comment by Apache9** [comment]
Mind explaining why we could hit NPE here?

**Comment by virajjasani** [comment]
@Apache9 @jatsakthi Thanks for your inputs. I just double checked, ran tests and realized that I was mislead by this if condition: https://github.com/apache/hbase/blob/019886853156e6af787236acc90ca7fcc304c53a/hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/WALPlayer.java#L171
However, it will always be true for the first run. Hence, this patch is not required. Apologies for causing trouble. Closing the PR

**Pull request closed without merging**
