### PR TITLE
[HBASE-23000] Backport HBASE-18150 to branch-1.3

### PR DESCRIPTION
**Pull request by shahrs87**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 14s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1.3 Compile Tests _ |
| :green_heart: |  mvninstall  |   7m 12s |  branch-1.3 passed  |
| :green_heart: |  compile  |   0m 40s |  branch-1.3 passed  |
| :green_heart: |  checkstyle  |   1m 43s |  branch-1.3 passed  |
| :broken_heart: |  shadedjars  |   0m 13s |  branch has 10 errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 36s |  branch-1.3 passed  |
| :blue_heart: |  spotbugs  |   2m 20s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   2m 18s |  branch-1.3 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   1m 48s |  the patch passed  |
| :green_heart: |  compile  |   0m 40s |  the patch passed  |
| :green_heart: |  javac  |   0m 40s |  the patch passed  |
| :broken_heart: |  checkstyle  |   1m 40s |  hbase-server: The patch generated 2 new + 26 unchanged - 0 fixed = 28 total (was 26)  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :broken_heart: |  shadedjars  |   0m 14s |  patch has 10 errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |   9m 43s |  Patch does not cause any errors with Hadoop 2.4.1 2.5.2 2.6.5 2.7.7.  |
| :green_heart: |  javadoc  |   0m 29s |  the patch passed  |
| :green_heart: |  findbugs  |   2m 14s |  the patch passed  |
||| _ Other Tests _ |
| :green_heart: |  unit  | 113m 24s |  hbase-server in the patch passed.  |
| :green_heart: |  asflicense  |   0m 28s |  The patch does not generate ASF License warnings.  |
|  |   | 146m  9s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/608 |
| JIRA Issue | HBASE-23000 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 8f8d4326274b 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-608/out/precommit/personality/provided.sh |
| git revision | branch-1.3 / 64c0ac5 |
| Default Java | 1.8.0_222 |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/1/artifact/out/branch-shadedjars.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/1/artifact/out/diff-checkstyle-hbase-server.txt |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/1/artifact/out/patch-shadedjars.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/1/testReport/ |
| Max. process+thread count | 4091 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 48s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1.3 Compile Tests _ |
| :green_heart: |  mvninstall  |   7m 37s |  branch-1.3 passed  |
| :green_heart: |  compile  |   0m 40s |  branch-1.3 passed  |
| :green_heart: |  checkstyle  |   1m 36s |  branch-1.3 passed  |
| :broken_heart: |  shadedjars  |   0m 12s |  branch has 10 errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 42s |  branch-1.3 passed  |
| :blue_heart: |  spotbugs  |   2m 32s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   2m 28s |  branch-1.3 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   1m 45s |  the patch passed  |
| :green_heart: |  compile  |   0m 41s |  the patch passed  |
| :green_heart: |  javac  |   0m 41s |  the patch passed  |
| :green_heart: |  checkstyle  |   1m 39s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :broken_heart: |  shadedjars  |   0m 12s |  patch has 10 errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  10m  6s |  Patch does not cause any errors with Hadoop 2.4.1 2.5.2 2.6.5 2.7.7.  |
| :green_heart: |  javadoc  |   0m 35s |  the patch passed  |
| :green_heart: |  findbugs  |   2m 32s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 101m 46s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   0m 22s |  The patch does not generate ASF License warnings.  |
|  |   | 135m  7s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.cleaner.TestSnapshotFromMaster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/608 |
| JIRA Issue | HBASE-23000 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux f6f7512ed469 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-608/out/precommit/personality/provided.sh |
| git revision | branch-1.3 / 64c0ac5 |
| Default Java | 1.8.0_222 |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/2/artifact/out/branch-shadedjars.txt |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/2/artifact/out/patch-shadedjars.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/2/testReport/ |
| Max. process+thread count | 4004 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-608/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.1.0-RC1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by shahrs87** [comment]
@jatsakthi could you please review this PR ? Thank you !

**Comment by jatsakthi** [comment]
Thanks for the patch @shahrs87 let me give it a look

**Comment by jatsakthi** [comment]
Let me run this patch in our adhoc testing framework to crosscheck

**Comment by jatsakthi** [comment]
Running [TestLogRollAbort, TestBlockReorder, TestHRegionServerBulkLoad, TestMasterFileSystemWithWALDir] - https://builds.apache.org/view/H-L/view/HBase/job/HBase-adhoc-run-tests/30/console

**Comment by jatsakthi** [comment]
The tests passed continuously around ~15 times. I think we are good here. Let me merge this in. Thanks @shahrs87

**Comment by shahrs87** [comment]
Thank you @jatsakthi  for the review and commit !

**Pull request merged**
