### PR TITLE
HBASE-24912 Enlarge MemstoreFlusherChore/CompactionChecker period for…

### PR DESCRIPTION
**Pull request by infraio**
… unit test

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   7m 13s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  7s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m 16s |  The patch has no ill-formed XML file.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m 45s |  The patch does not generate ASF License warnings.  |
|  |   |  12m 25s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.12 Server=19.03.12 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2285 |
| Optional Tests | dupname asflicense xml |
| uname | Linux 3994a325eca0 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1164531d5a |
| Max. process+thread count | 47 (vs. ulimit of 12500) |
| modules | C: hbase-asyncfs hbase-backup hbase-client hbase-endpoint hbase-examples hbase-mapreduce hbase-procedure hbase-rest hbase-server hbase-shell hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
@infraio There's a small typo in the commit message: "Enalrge" => "Enlarge"

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 29s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 24s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   4m 33s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 21s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 11s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 26s |  hbase-asyncfs in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 42s |  hbase-procedure in the patch passed.  |
| -1 :x: |  unit  | 136m 55s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  unit  |  11m 10s |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 49s |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   7m 15s |  hbase-shell in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 48s |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 32s |  hbase-backup in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 56s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 47s |  hbase-examples in the patch passed.  |
|  |   | 196m 35s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.12 Server=19.03.12 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2285 |
| Optional Tests | unit |
| uname | Linux 71f0cc73dc44 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1164531d5a |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-hbase-server.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/testReport/ |
| Max. process+thread count | 5080 (vs. ulimit of 12500) |
| modules | C: hbase-client hbase-asyncfs hbase-procedure hbase-server hbase-mapreduce hbase-thrift hbase-shell hbase-endpoint hbase-backup hbase-rest hbase-examples U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 21s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   4m 17s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 16s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 17s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 48s |  hbase-asyncfs in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  6s |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  | 220m  3s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |  16m 27s |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 47s |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   7m  4s |  hbase-shell in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  2s |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  unit  |  12m 47s |  hbase-backup in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 56s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  9s |  hbase-examples in the patch passed.  |
|  |   | 290m 26s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.12 Server=19.03.12 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2285 |
| Optional Tests | unit |
| uname | Linux 37c8c16f0d93 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1164531d5a |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/testReport/ |
| Max. process+thread count | 3113 (vs. ulimit of 12500) |
| modules | C: hbase-client hbase-asyncfs hbase-procedure hbase-server hbase-mapreduce hbase-thrift hbase-shell hbase-endpoint hbase-backup hbase-rest hbase-examples U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/1/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  3s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 20s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  6s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m 13s |  The patch has no ill-formed XML file.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m 26s |  The patch does not generate ASF License warnings.  |
|  |   |   5m 27s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.12 Server=19.03.12 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2285 |
| Optional Tests | dupname asflicense xml |
| uname | Linux 03e12538f524 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1164531d5a |
| Max. process+thread count | 47 (vs. ulimit of 12500) |
| modules | C: hbase-asyncfs hbase-backup hbase-client hbase-endpoint hbase-examples hbase-mapreduce hbase-procedure hbase-rest hbase-server hbase-shell hbase-thrift U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/2/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 26s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   4m 19s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m  1s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 11s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 25s |  hbase-asyncfs in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 37s |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  | 130m 37s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 31s |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  6s |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   7m 13s |  hbase-shell in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 54s |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  unit  |  10m  2s |  hbase-backup in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 30s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 51s |  hbase-examples in the patch passed.  |
|  |   | 187m  9s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.12 Server=19.03.12 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/2/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2285 |
| Optional Tests | unit |
| uname | Linux e7e42ba31b5a 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1164531d5a |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/2/testReport/ |
| Max. process+thread count | 5376 (vs. ulimit of 12500) |
| modules | C: hbase-client hbase-asyncfs hbase-procedure hbase-server hbase-mapreduce hbase-thrift hbase-shell hbase-endpoint hbase-backup hbase-rest hbase-examples U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/2/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 26s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 22s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m 38s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 26s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m  3s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 31s |  hbase-asyncfs in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 47s |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  | 139m 37s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |  11m 14s |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 50s |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   7m 19s |  hbase-shell in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 44s |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  unit  |  10m 30s |  hbase-backup in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 57s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  6s |  hbase-examples in the patch passed.  |
|  |   | 199m 38s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.12 Server=19.03.12 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/2/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2285 |
| Optional Tests | unit |
| uname | Linux c64eddb17500 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 1164531d5a |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/2/testReport/ |
| Max. process+thread count | 5112 (vs. ulimit of 12500) |
| modules | C: hbase-client hbase-asyncfs hbase-procedure hbase-server hbase-mapreduce hbase-thrift hbase-shell hbase-endpoint hbase-backup hbase-rest hbase-examples U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2285/2/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by infraio** [comment]
> @infraio There's a small typo in the commit message: "Enalrge" => "Enlarge"

Fixed.

**Pull request merged**
