### PR TITLE
HBASE-24550 Passing '-h' or '--help' to bin/hbase doesn't do as expected

### PR DESCRIPTION
**Pull request by WenFeiYi**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |  19m 41s |  Docker failed to build yetus/hbase:de2952b78c.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1949 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1949/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |  11m 22s |  Docker failed to build yetus/hbase:de2952b78c.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1949 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1949/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
@WenFeiYi usually we commit to branch-1 only as it is the active one but since this is good fix to have, we can commit to more branches. 
As of now, the build is broken for this PR.

**Comment by WenFeiYi** [comment]
I got it, I will be close the PR.

**Pull request closed without merging**
