### PR TITLE
HBASE-23139 MapReduce jobs lauched from convenience distribution are nonfunctional

### PR DESCRIPTION
**Pull request by apurtell**
Add the hbase-thirdparty jar to base job dependencies.

### CODE REVIEW

**Comment by apurtell** [comment]
Confirmed fix, merging

**Comment by busbey** [comment]
Just want to confirm that this fixed `hbase mapredcp` specifically? (Presuming gson thirdpart-gson is always needed for jobs based on our utils)

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 16s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| :green_heart: |  mvninstall  |   8m 26s |  branch-1 passed  |
| :green_heart: |  compile  |   0m 42s |  branch-1 passed with JDK v1.8.0_222  |
| :green_heart: |  compile  |   0m 46s |  branch-1 passed with JDK v1.7.0_232  |
| :green_heart: |  checkstyle  |   1m 45s |  branch-1 passed  |
| :green_heart: |  shadedjars  |   3m 15s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 39s |  branch-1 passed with JDK v1.8.0_222  |
| :green_heart: |  javadoc  |   0m 42s |  branch-1 passed with JDK v1.7.0_232  |
| :blue_heart: |  spotbugs  |   3m  2s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   2m 59s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   2m  7s |  the patch passed  |
| :green_heart: |  compile  |   0m 41s |  the patch passed with JDK v1.8.0_222  |
| :green_heart: |  javac  |   0m 41s |  the patch passed  |
| :green_heart: |  compile  |   0m 47s |  the patch passed with JDK v1.7.0_232  |
| :green_heart: |  javac  |   0m 47s |  the patch passed  |
| :green_heart: |  checkstyle  |   1m 42s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   3m  4s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |   5m 17s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| :green_heart: |  javadoc  |   0m 33s |  the patch passed with JDK v1.8.0_222  |
| :green_heart: |  javadoc  |   0m 42s |  the patch passed with JDK v1.7.0_232  |
| :green_heart: |  findbugs  |   3m  4s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  |  32m 33s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   0m 21s |  The patch does not generate ASF License warnings.  |
|  |   |  75m  8s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.http.log.TestLogLevel |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.3 Server=19.03.3 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-705/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/705 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux e0fa3ff40f97 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-705/out/precommit/personality/provided.sh |
| git revision | branch-1 / 1d531f1 |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_222 /usr/lib/jvm/zulu-7-amd64:1.7.0_232 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-705/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-705/1/testReport/ |
| Max. process+thread count | 713 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-705/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
Tested with RowCounter and IntegrationTestBigLinkedList

**Pull request merged**
