### PR TITLE
HBASE-26922 Fix LineLength warnings as much as possible if it can not…

### PR DESCRIPTION
**Pull request by Apache9**
… be fixed by spotless

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   3m 27s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 50s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 37s |  master passed  |
| +1 :green_heart: |  compile  |   3m 15s |  master passed  |
| +1 :green_heart: |  shadedjars  |   3m 49s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 28s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 29s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 19s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 19s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   3m 48s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 25s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 41s |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 33s |  hbase-hadoop-compat in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 19s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 35s |  hbase-zookeeper in the patch passed.  |
| +1 :green_heart: |  unit  |  10m  4s |  hbase-balancer in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  2s |  hbase-asyncfs in the patch passed.  |
| +1 :green_heart: |  unit  | 181m 10s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |  13m  4s |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 23s |  hbase-testing-util in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 43s |  hbase-it in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 39s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 42s |  hbase-examples in the patch passed.  |
|  |   | 249m 12s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4324 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux c29a2e91187d 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / e68c61dd54 |
| Default Java | AdoptOpenJDK-11.0.10+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/1/testReport/ |
| Max. process+thread count | 3506 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-hadoop-compat hbase-client hbase-zookeeper hbase-balancer hbase-asyncfs hbase-server hbase-mapreduce hbase-testing-util hbase-it hbase-rest hbase-examples U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/1/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  4s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 22s |  master passed  |
| +1 :green_heart: |  compile  |   7m  3s |  master passed  |
| +1 :green_heart: |  checkstyle  |   2m 48s |  master passed  |
| +1 :green_heart: |  spotbugs  |   5m 57s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 10s |  the patch passed  |
| +1 :green_heart: |  compile  |   7m  0s |  the patch passed  |
| -0 :warning: |  javac  |   0m 32s |  hbase-common generated 1 new + 150 unchanged - 1 fixed = 151 total (was 151)  |
| +1 :green_heart: |  checkstyle  |   0m 16s |  hbase-common: The patch generated 0 new + 67 unchanged - 1 fixed = 67 total (was 68)  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  hbase-hadoop-compat: The patch generated 0 new + 1 unchanged - 1 fixed = 1 total (was 2)  |
| +1 :green_heart: |  checkstyle  |   0m 20s |  hbase-client: The patch generated 0 new + 216 unchanged - 7 fixed = 216 total (was 223)  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  The patch passed checkstyle in hbase-zookeeper  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  The patch passed checkstyle in hbase-balancer  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  The patch passed checkstyle in hbase-asyncfs  |
| -0 :warning: |  checkstyle  |   0m 38s |  hbase-server: The patch generated 1 new + 92 unchanged - 18 fixed = 93 total (was 110)  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  hbase-mapreduce: The patch generated 0 new + 63 unchanged - 4 fixed = 63 total (was 67)  |
| +1 :green_heart: |  checkstyle  |   0m 11s |  The patch passed checkstyle in hbase-testing-util  |
| +1 :green_heart: |  checkstyle  |   0m 12s |  hbase-it: The patch generated 0 new + 1 unchanged - 5 fixed = 1 total (was 6)  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  The patch passed checkstyle in hbase-rest  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  The patch passed checkstyle in hbase-examples  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  hadoopcheck  |  11m 39s |  Patch does not cause any errors with Hadoop 3.1.2 3.2.2 3.3.1.  |
| +1 :green_heart: |  spotbugs  |   7m 11s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m 49s |  The patch does not generate ASF License warnings.  |
|  |   |  59m 30s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4324 |
| Optional Tests | dupname asflicense javac spotbugs hadoopcheck hbaseanti checkstyle compile |
| uname | Linux e8f0cc4e9854 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / c791c8181a |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| javac | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/artifact/yetus-general-check/output/diff-compile-javac-hbase-common.txt |
| checkstyle | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/artifact/yetus-general-check/output/diff-checkstyle-hbase-server.txt |
| Max. process+thread count | 69 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-hadoop-compat hbase-client hbase-zookeeper hbase-balancer hbase-asyncfs hbase-server hbase-mapreduce hbase-testing-util hbase-it hbase-rest hbase-examples U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/console |
| versions | git=2.17.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 39s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 31s |  master passed  |
| +1 :green_heart: |  compile  |   3m 21s |  master passed  |
| +1 :green_heart: |  shadedjars  |   3m 49s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 28s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 32s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 34s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 34s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   4m 46s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   3m 43s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 18s |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 44s |  hbase-hadoop-compat in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 43s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  3s |  hbase-zookeeper in the patch passed.  |
| +1 :green_heart: |  unit  |  10m 26s |  hbase-balancer in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 21s |  hbase-asyncfs in the patch passed.  |
| +1 :green_heart: |  unit  | 182m  3s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |  13m  0s |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 19s |  hbase-testing-util in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 43s |  hbase-it in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 41s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 39s |  hbase-examples in the patch passed.  |
|  |   | 251m 37s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4324 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 48a4c52a0aa8 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / c791c8181a |
| Default Java | AdoptOpenJDK-11.0.10+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/testReport/ |
| Max. process+thread count | 2974 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-hadoop-compat hbase-client hbase-zookeeper hbase-balancer hbase-asyncfs hbase-server hbase-mapreduce hbase-testing-util hbase-it hbase-rest hbase-examples U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 29s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m 32s |  master passed  |
| +1 :green_heart: |  compile  |   5m  9s |  master passed  |
| +1 :green_heart: |  shadedjars  |   5m 28s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   3m 31s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   4m 57s |  the patch passed  |
| +1 :green_heart: |  javac  |   4m 57s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 28s |  patch has no errors when building our shaded downstream artifacts.  |
| -0 :warning: |  javadoc  |   0m 20s |  hbase-client generated 27 new + 3 unchanged - 0 fixed = 30 total (was 3)  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 17s |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 50s |  hbase-hadoop-compat in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 31s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 47s |  hbase-zookeeper in the patch passed.  |
| +1 :green_heart: |  unit  |  10m 54s |  hbase-balancer in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 46s |  hbase-asyncfs in the patch passed.  |
| -1 :x: |  unit  | 252m 49s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  unit  |  13m 22s |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 50s |  hbase-testing-util in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  0s |  hbase-it in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 31s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 36s |  hbase-examples in the patch passed.  |
|  |   | 334m 33s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4324 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 4dd76196b30f 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / c791c8181a |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| javadoc | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/artifact/yetus-jdk8-hadoop3-check/output/diff-javadoc-javadoc-hbase-client.txt |
| unit | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/artifact/yetus-jdk8-hadoop3-check/output/patch-unit-hbase-server.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/testReport/ |
| Max. process+thread count | 2731 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-hadoop-compat hbase-client hbase-zookeeper hbase-balancer hbase-asyncfs hbase-server hbase-mapreduce hbase-testing-util hbase-it hbase-rest hbase-examples U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4324/2/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
OK, it is a bit strange that JDK11 can find the referenced types in javadoc while JDK8 can not...

**Review by nyl3532016 — APPROVED** [review]
+1

**Pull request merged**
