### PR TITLE
HBASE-24148 Upgrade Thrift to 0.13.0: 0.12.0 has outstanding CVEs.

### PR DESCRIPTION
**Pull request by apurtell**
Backport for branch-2.2

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   2m 23s |  Docker failed to build yetus/hbase:d9b4982ad4.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1532 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1532/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Looks like the Dockerfile on branch-2.2 has bit-rot. I suspect package versions are partially pinned or not pinned at all: the rubocop version has incremented by ruby version has not.

```
[2020-04-16T18:43:21.548Z] Setting up ruby2.3 (2.3.3-1+deb9u7) ...
[2020-04-16T18:43:21.548Z] Setting up ruby2.3-dev:amd64 (2.3.3-1+deb9u7) ...
[2020-04-16T18:43:21.548Z] Setting up ruby-dev:amd64 (1:2.3.3) ...
[2020-04-16T18:43:21.548Z] Setting up ruby (1:2.3.3) ...
[2020-04-16T18:43:22.261Z] Processing triggers for libc-bin (2.24-11+deb9u3) ...
[2020-04-16T18:43:22.975Z] Successfully installed rake-13.0.1
[2020-04-16T18:43:22.975Z] Building native extensions.  This could take a while...
[2020-04-16T18:43:25.277Z] ERROR:  Error installing rubocop:
[2020-04-16T18:43:25.277Z] 	rubocop requires Ruby version >= 2.4.0.
```

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   1m 19s |  Docker failed to build yetus/hbase:d9b4982ad4.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1532 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1532/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
Thanks @ndimiduk 

We have prioritized CVE fixes over compatibility usually (always?) and should continue to do so IMHO

**Pull request merged**
