### PR TITLE
HBASE-23269 Hbase crashed due to two versions of regionservers when rolling upgrading

### PR DESCRIPTION
**Pull request by xujianzhen**
HBASE-23269 Hbase crashed due to two versions of regionservers when rolling upgrading. JianzhenXu

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m 10s |  https://github.com/apache/hbase/pull/895 does not apply to branch-1.4. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/895 |
| JIRA Issue | HBASE-23269 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-895/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by xujianzhen** [comment]
@liuml07 Hi, Now I'm developing directly on the branch-1.4  of fork to my github, and then propose a pr, which is still error。How can i do it?

**Comment by xujianzhen** [comment]
@apurtell Hi, I coding at branch-1.4 branch of forked  in my github, and propose a pr to apache branch-1.4, but also prompt version issue。How can i do it? The problem is same in #844'

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  9s |  https://github.com/apache/hbase/pull/895 does not apply to branch-1.4. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/895 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-895/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  9s |  https://github.com/apache/hbase/pull/895 does not apply to branch-1.4. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/895 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-895/3/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by liuml07** [comment]
I'm not sure about the root cause of error. I think it's suggested to file patches against master branch, even if you want to patch in another branch. When this patch is first committed to the master branch, the committer can backport to branch-1.4.

**Pull request closed without merging**
