### PR TITLE
HBASE-28900: Avoid resetting the bucket cache during recovery from persistence. (#6360)

### PR DESCRIPTION
**Pull request by jhungund**
Backport the fix of HBASE-28900 to branch-2.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 23s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 54s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   1m  2s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 30s |  |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   5m 27s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   1m 42s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk17-hadoop3-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 56s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk17-hadoop3-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javac  |   0m 56s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk17-hadoop3-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 30s | [/results-javadoc-javadoc-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk17-hadoop3-check/output/results-javadoc-javadoc-hbase-server.txt) |  hbase-server generated 7 new + 44 unchanged - 0 fixed = 51 total (was 44)  |
| -1 :x: |  shadedjars  |   4m 11s |  |  patch has 20 errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 56s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
|  |   |  20m 42s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6365 |
| JIRA Issue | HBASE-28900 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux ae30bd3abcd4 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 2f750ad66a35e72b446ffecd0877bc8bb6e21b42 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
| shadedjars | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk17-hadoop3-check/output/patch-shadedjars.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/testReport/ |
| Max. process+thread count | 83 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 43s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 28s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   0m 54s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 28s |  |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   5m 57s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   1m 39s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk11-hadoop3-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 49s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk11-hadoop3-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javac  |   0m 49s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk11-hadoop3-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 25s | [/results-javadoc-javadoc-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk11-hadoop3-check/output/results-javadoc-javadoc-hbase-server.txt) |  hbase-server generated 7 new + 85 unchanged - 0 fixed = 92 total (was 85)  |
| -1 :x: |  shadedjars  |   4m 26s |  |  patch has 20 errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 49s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
|  |   |  20m 45s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6365 |
| JIRA Issue | HBASE-28900 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 41475515348d 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 2f750ad66a35e72b446ffecd0877bc8bb6e21b42 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| shadedjars | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk11-hadoop3-check/output/patch-shadedjars.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/testReport/ |
| Max. process+thread count | 80 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 55s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 31s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   1m  5s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 34s |  |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   5m 52s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   1m 52s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk8-hadoop2-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 56s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk8-hadoop2-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javac  |   0m 56s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk8-hadoop2-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 32s | [/results-javadoc-javadoc-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk8-hadoop2-check/output/results-javadoc-javadoc-hbase-server.txt) |  hbase-server generated 4 new + 21 unchanged - 0 fixed = 25 total (was 21)  |
| -1 :x: |  shadedjars  |   4m 51s |  |  patch has 20 errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 55s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
|  |   |  22m  8s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6365 |
| JIRA Issue | HBASE-28900 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 17c7ed1a0b7d 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 2f750ad66a35e72b446ffecd0877bc8bb6e21b42 |
| Default Java | Temurin-1.8.0_412-b08 |
| shadedjars | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-jdk8-hadoop2-check/output/patch-shadedjars.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/testReport/ |
| Max. process+thread count | 64 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 49s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  |  Patch does not have any anti-patterns.  |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 10s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   3m 46s |  |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   0m 42s |  |  branch-2 passed  |
| +1 :green_heart: |  spotbugs  |   1m 54s |  |  branch-2 passed  |
| +1 :green_heart: |  spotless  |   0m 52s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   1m 56s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 43s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-general-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| -0 :warning: |  javac  |   1m 43s | [/patch-compile-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-general-check/output/patch-compile-hbase-server.txt) |  hbase-server in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  |  hbase-server: The patch generated 0 new + 25 unchanged - 1 fixed = 25 total (was 26)  |
| -1 :x: |  spotbugs  |   0m 43s | [/patch-spotbugs-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-general-check/output/patch-spotbugs-hbase-server.txt) |  hbase-server in the patch failed.  |
| -1 :x: |  hadoopcheck  |   1m 50s |  |  The patch causes 20 errors with Hadoop v2.10.2.  |
| -1 :x: |  hadoopcheck  |   4m  2s |  |  The patch causes 20 errors with Hadoop v3.3.6.  |
| -1 :x: |  hadoopcheck  |   6m 29s |  |  The patch causes 20 errors with Hadoop v3.4.0.  |
| +1 :green_heart: |  spotless  |   1m  3s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 12s |  |  The patch does not generate ASF License warnings.  |
|  |   |  26m 36s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6365 |
| JIRA Issue | HBASE-28900 |
| Optional Tests | dupname asflicense javac spotbugs checkstyle codespell detsecrets compile hadoopcheck hbaseanti spotless |
| uname | Linux e0156aa86a3b 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 2f750ad66a35e72b446ffecd0877bc8bb6e21b42 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-general-check/output/patch-javac-2.10.2.txt |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-general-check/output/patch-javac-3.3.6.txt |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/artifact/yetus-general-check/output/patch-javac-3.4.0.txt |
| Max. process+thread count | 79 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/1/console |
| versions | git=2.34.1 maven=3.9.8 spotbugs=4.7.3 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m  0s |  |  Docker mode activated.  |
| -1 :x: |  docker  |   0m  6s |  |  Docker failed to build run-specific yetus/hbase:tp-6445}.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/6365 |
| JIRA Issue | HBASE-28900 |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/console |
| versions | git=2.25.1 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 25s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  |  Patch does not have any anti-patterns.  |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 34s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   4m  0s |  |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   0m 42s |  |  branch-2 passed  |
| +1 :green_heart: |  spotbugs  |   1m 56s |  |  branch-2 passed  |
| +1 :green_heart: |  spotless  |   0m 53s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 22s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 46s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 46s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 45s |  |  hbase-server: The patch generated 0 new + 25 unchanged - 1 fixed = 25 total (was 26)  |
| +1 :green_heart: |  spotbugs  |   2m  0s |  |  the patch passed  |
| +1 :green_heart: |  hadoopcheck  |  23m 50s |  |  Patch does not cause any errors with Hadoop 2.10.2 or 3.3.6 3.4.0.  |
| +1 :green_heart: |  spotless  |   0m 55s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 12s |  |  The patch does not generate ASF License warnings.  |
|  |   |  50m 12s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6365 |
| JIRA Issue | HBASE-28900 |
| Optional Tests | dupname asflicense javac spotbugs checkstyle codespell detsecrets compile hadoopcheck hbaseanti spotless |
| uname | Linux e2ee75349da3 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 968aa56b86a66e2468ab5f36980d0338ccdb7e35 |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| Max. process+thread count | 79 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/console |
| versions | git=2.34.1 maven=3.9.8 spotbugs=4.7.3 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 25s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 36s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   1m 19s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 35s |  |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   6m 47s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 22s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 11s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 11s |  |  the patch passed  |
| -0 :warning: |  javadoc  |   0m 33s | [/results-javadoc-javadoc-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/artifact/yetus-jdk17-hadoop3-check/output/results-javadoc-javadoc-hbase-server.txt) |  hbase-server generated 7 new + 44 unchanged - 0 fixed = 51 total (was 44)  |
| +1 :green_heart: |  shadedjars  |   6m 33s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 214m 53s |  |  hbase-server in the patch passed.  |
|  |   | 245m 57s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6365 |
| JIRA Issue | HBASE-28900 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux b2f63a019c06 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 968aa56b86a66e2468ab5f36980d0338ccdb7e35 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/testReport/ |
| Max. process+thread count | 4954 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 41s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 39s |  |  branch-2 passed  |
| +1 :green_heart: |  compile  |   0m 41s |  |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 26s |  |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   5m 15s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 26s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 41s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 41s |  |  the patch passed  |
| -0 :warning: |  javadoc  |   0m 23s | [/results-javadoc-javadoc-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/artifact/yetus-jdk8-hadoop2-check/output/results-javadoc-javadoc-hbase-server.txt) |  hbase-server generated 4 new + 21 unchanged - 0 fixed = 25 total (was 21)  |
| +1 :green_heart: |  shadedjars  |   5m 13s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  | 233m  3s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
|  |   | 255m 57s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6365 |
| JIRA Issue | HBASE-28900 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 03c4dbb51064 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 968aa56b86a66e2468ab5f36980d0338ccdb7e35 |
| Default Java | Temurin-1.8.0_412-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/testReport/ |
| Max. process+thread count | 4294 (vs. ulimit of 30000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6365/2/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Review by wchevreuil — APPROVED** [review]

**Pull request merged**
