### PR TITLE
HBASE-26299 Fix TestHTableTracing.testTableClose for nightly build of…

### PR DESCRIPTION
**Pull request by taklwu**
… branch-2

For unit testing in sync connection with OpenTelemetry tracing,
there is a race condition between ConnectionImplementation#finalize
(object GC) and the test method before Rule triggered by
`OpenTelemetryRule.create`. such that it triggers an error message 
of `GlobalOpenTelemetry.set has already been called`.

This change fixed those tests by moving up the `TRACE_RULE`
creation to class-level such that the `GlobalOpenTelemetry` is 
being set once during multi-thread execution and reuse it for 
all methods.

### CODE REVIEW

**Comment by taklwu** [comment]
Build locally with hadoop3 profile with the following command and hbase-client test passed 

```
mvn --batch-mode  --threads=2 -DHBasePatchProcess \
-Dhadoop.profile=3.0 -PrunAllTests \
-Dtest.exclude.pattern="**/regionserver.TestDirectStoreSplitsMerges.java,**/master.normalizer.TestRegionNormalizerWorkQueue.java,**/rsgroup.TestTableDescriptorWithRSGroup.java,**/master.cleaner.TestSnapshotFromMaster.java,**/rsgroup.TestUpdateRSGroupConfiguration.java,**/TestZooKeeper.java,**/master.balancer.TestStochasticLoadBalancerRegionReplicaReplicationGreaterThanNumNodes.java,**/replication.regionserver.TestReplicationValueCompressedWAL.java,**/replication.regionserver.TestBasicWALEntryStreamFSHLog.java,**/master.assignment.TestAssignmentManager.java,**/wal.TestFSHLogProvider.java,**/master.procedure.TestMasterFailoverWithProcedures.java,**/master.TestMaster.java" \
clean test -fae

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.hbase.TestHColumnDescriptor
[INFO] Running org.apache.hadoop.hbase.TestHTableDescriptor
[INFO] Running org.apache.hadoop.hbase.util.TestRoundRobinPoolMap
...
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 302, Failures: 0, Errors: 0, Skipped: 1
[INFO]
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (secondPartTestsExecution) @ hbase-client ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.hadoop.hbase.client.TestAsyncTableRpcPriority
[INFO] Running org.apache.hadoop.hbase.client.TestAsyncProcess
[INFO] Running org.apache.hadoop.hbase.client.TestRegionLocatorTracing
...
[INFO] Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 85.343 s - in org.apache.hadoop.hbase.client.TestAsyncProcess
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 134, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
```

**Comment by taklwu** [comment]
meanwhile I found the tests for async connection does not fail e.g. `AsyncConnectionImpl` , it should be related to the sync implementation with [`ConnectionImplementation`](https://github.com/apache/hbase/blob/branch-2/hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java#L2146-L2150) has the GC cleanup logic that `AsyncConnectionImpl` does not have


```

  @Override
  protected void finalize() throws Throwable {
    super.finalize();
    close();
  }
```

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  6s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 22s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   0m 32s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   7m 12s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 31s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  3s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 31s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 31s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   7m 13s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 30s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 42s |  hbase-client in the patch passed.  |
|  |   |  30m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3703/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/3703 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 22edd5c5779f 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 73f42b27bf |
| Default Java | AdoptOpenJDK-11.0.10+9 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3703/1/testReport/ |
| Max. process+thread count | 296 (vs. ulimit of 12500) |
| modules | C: hbase-client U: hbase-client |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3703/1/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  8s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   1m  5s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  branch-2 passed  |
| +1 :green_heart: |  spotbugs  |   1m 17s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 42s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  4s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  4s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  hadoopcheck  |  13m 11s |  Patch does not cause any errors with Hadoop 3.1.2 3.2.1.  |
| +1 :green_heart: |  spotbugs  |   1m 24s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  36m 28s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3703/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/3703 |
| Optional Tests | dupname asflicense javac spotbugs hadoopcheck hbaseanti checkstyle compile |
| uname | Linux d8c4760c34ca 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 73f42b27bf |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| Max. process+thread count | 86 (vs. ulimit of 12500) |
| modules | C: hbase-client U: hbase-client |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3703/1/console |
| versions | git=2.17.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by wchevreuil — APPROVED** [review]

**Review by Apache9 — APPROVED** [review]

**Pull request merged**
