### PR TITLE
Revert "HBASE-23304: RPCs needed for client meta information lookup (…

### PR DESCRIPTION
**Pull request by ndimiduk**
…apache#904) (#1098)"

This reverts commit 71f035450df0c8f56622b5151003bc134ca0091b.

### CODE REVIEW

**Comment by ndimiduk** [comment]
FYI @bharathv @apurtell

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 40s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  1s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 18 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 30s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   2m 26s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 17s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   4m 26s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 32s |  branch-2 passed  |
| +0 :ok: |  spotbugs  |   0m 38s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   8m 13s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   2m 49s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 55s |  hbase-server in the patch failed.  |
| -1 :x: |  cc  |   0m 55s |  hbase-server in the patch failed.  |
| -1 :x: |  javac  |   0m 55s |  hbase-server in the patch failed.  |
| -1 :x: |  checkstyle  |   0m 36s |  hbase-client: The patch generated 1 new + 194 unchanged - 0 fixed = 195 total (was 194)  |
| -1 :x: |  checkstyle  |   1m  8s |  hbase-server: The patch generated 13 new + 119 unchanged - 0 fixed = 132 total (was 119)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   3m 34s |  patch has 36 errors when building our shaded downstream artifacts.  |
| -1 :x: |  hadoopcheck  |   2m  5s |  The patch causes 36 errors with Hadoop v2.8.5.  |
| -1 :x: |  hadoopcheck  |   4m 35s |  The patch causes 36 errors with Hadoop v2.9.2.  |
| -1 :x: |  hadoopcheck  |   7m 31s |  The patch causes 36 errors with Hadoop v3.1.2.  |
| -1 :x: |  hbaseprotoc  |   0m 55s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  javadoc  |   1m 35s |  the patch passed  |
| -1 :x: |  findbugs  |   1m  1s |  hbase-server in the patch failed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 50s |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  3s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 53s |  hbase-zookeeper in the patch passed.  |
| -1 :x: |  unit  |   1m  5s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 47s |  The patch does not generate ASF License warnings.  |
|  |   |  64m 49s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1119 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 2d3305e3a61c 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1119/out/precommit/personality/provided.sh |
| git revision | branch-2 / 12f4e0977c |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-compile-hbase-server.txt |
| cc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-compile-hbase-server.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-compile-hbase-server.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/diff-checkstyle-hbase-client.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/diff-checkstyle-hbase-server.txt |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-shadedjars.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-javac-2.8.5.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-javac-2.9.2.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-javac-3.1.2.txt |
| hbaseprotoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-hbaseprotoc-hbase-server.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-findbugs-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/testReport/ |
| Max. process+thread count | 283 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-zookeeper hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m 12s |  https://github.com/apache/hbase/pull/1119 does not apply to branch-2. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by bharathv** [comment]
+1 subject to a clean QA build. Thanks for the revert.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  4s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  0s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 19 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 47s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   2m 23s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   2m 17s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   4m 43s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 26s |  branch-2 passed  |
| +0 :ok: |  spotbugs  |   0m 34s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   8m 11s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 21s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 22s |  the patch passed  |
| +1 :green_heart: |  cc  |   2m 22s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 22s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 37s |  hbase-client: The patch generated 1 new + 194 unchanged - 0 fixed = 195 total (was 194)  |
| -1 :x: |  checkstyle  |   1m 14s |  hbase-server: The patch generated 13 new + 119 unchanged - 0 fixed = 132 total (was 119)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 39s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  17m  4s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  hbaseprotoc  |   2m 12s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 27s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   8m 27s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 42s |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 32s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 48s |  hbase-zookeeper in the patch passed.  |
| +1 :green_heart: |  unit  | 155m  2s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 32s |  The patch does not generate ASF License warnings.  |
|  |   | 239m 20s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1119 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux b1f1ac2279cb 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1119/out/precommit/personality/provided.sh |
| git revision | branch-2 / 12f4e0977c |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/3/artifact/out/diff-checkstyle-hbase-client.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/3/artifact/out/diff-checkstyle-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/3/testReport/ |
| Max. process+thread count | 4979 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-client hbase-zookeeper hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1119/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
