### PR TITLE
[Back-port to branch-1] HBASE-24196 [Shell] Add rename rsgroup command in hbase shell

### PR DESCRIPTION
**Pull request by Reidddddd**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   6m 24s |  Docker failed to build yetus/hbase:41990ba20a.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1555 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1555/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   6m 23s |  Docker failed to build yetus/hbase:41990ba20a.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1555 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1555/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   0m  8s |  Docker failed to build yetus/hbase:41990ba20a.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1555 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1555/3/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Reidddddd** [comment]
ping @busbey 
Any Idea how to fix this one?
From output, it looks like ruby version problem:
> [91mERROR:  Error installing rubocop:
rubocop requires Ruby version >= 2.4.0.
The command '/bin/sh -c gem install rubocop' returned a non-zero code: 1

**Comment by busbey** [comment]
Looks like the same thing Avro ran into in https://issues.apache.org/jira/browse/AVRO-2807

We need to pin out rubocop version to 0.81

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 52s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m 35s |  branch-1 passed  |
| +1 :green_heart: |  javadoc  |   0m 23s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 15s |  branch-1 passed with JDK v1.7.0_262  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 52s |  the patch passed  |
| -1 :x: |  rubocop  |   0m 10s |  The patch generated 4 new + 123 unchanged - 2 fixed = 127 total (was 125)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 13s |  the patch passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 16s |  the patch passed with JDK v1.7.0_262  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   8m 58s |  hbase-shell in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 24s |  The patch does not generate ASF License warnings.  |
|  |   |  23m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1555/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1555 |
| Optional Tests | dupname asflicense javac javadoc unit rubocop |
| uname | Linux 1f041095327e 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1555/out/precommit/personality/provided.sh |
| git revision | branch-1 / 7cf9701 |
| Default Java | 1.7.0_262 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_252 /usr/lib/jvm/zulu-7-amd64:1.7.0_262 |
| rubocop | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1555/4/artifact/out/diff-patch-rubocop.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1555/4/testReport/ |
| Max. process+thread count | 1663 (vs. ulimit of 10000) |
| modules | C: hbase-shell U: hbase-shell |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1555/4/console |
| versions | git=1.9.1 maven=3.0.5 rubocop=0.81.0 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
