### PR TITLE
HBASE-28618: Fixed hadolint check in nightly build.

### PR DESCRIPTION
**Pull request by subrat-mishra**
Tested hadolint <Dockerfile> and verified that it doesn't throw any error.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 25s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  2s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
||| _ Other Tests _ |
|  |   |   1m 26s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5957/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5957 |
| JIRA Issue | HBASE-28618 |
| Optional Tests |  |
| uname | Linux ad3bdc5b754d 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / a16f45811e |
| Max. process+thread count | 39 (vs. ulimit of 30000) |
| modules | C:  U:  |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5957/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
||| _ Other Tests _ |
|  |   |   1m 30s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5957/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5957 |
| JIRA Issue | HBASE-28618 |
| Optional Tests |  |
| uname | Linux 0e838ab07403 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / a16f45811e |
| Max. process+thread count | 29 (vs. ulimit of 30000) |
| modules | C:  U:  |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5957/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  4s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  6s |  Maven dependency ordering for patch  |
||| _ Other Tests _ |
|  |   |   2m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5957/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5957 |
| JIRA Issue | HBASE-28618 |
| Optional Tests |  |
| uname | Linux e25bb538cc36 5.4.0-174-generic #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / a16f45811e |
| Max. process+thread count | 43 (vs. ulimit of 30000) |
| modules | C:  U:  |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5957/1/console |
| versions | git=2.34.1 maven=3.8.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 36s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  spotless  |   0m 42s |  branch has no errors when running spotless:check.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  5s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  hadolint  |   0m  0s |  The patch generated 0 new + 0 unchanged - 1 fixed = 0 total (was 1)  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  spotless  |   0m 39s |  patch has no errors when running spotless:check.  |
||| _ Other Tests _ |
| +0 :ok: |  asflicense  |   0m  0s |  ASF License check generated no output?  |
|  |   |   3m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5957/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/5957 |
| JIRA Issue | HBASE-28618 |
| Optional Tests | dupname asflicense spotless hadolint shellcheck shelldocs |
| uname | Linux f3f52d0ce22e 5.4.0-174-generic #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / a16f45811e |
| Max. process+thread count | 43 (vs. ulimit of 30000) |
| modules | C:  U:  |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-5957/1/console |
| versions | git=2.34.1 maven=3.8.6 shellcheck=0.8.0 hadolint=Haskell Dockerfile Linter 2.10.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Does this work for normal x86 platforms?

**Comment by subrat-mishra** [comment]
> Does this work for normal x86 platforms?

I believe you mean the 'hadolint' command on the x86 platform. It should work, although I haven't tested it since my laptop uses an M3 processor.

**Comment by Apache9** [comment]
I mean if we could merge the two Dockerfile... We introduce a new Dockerfile for m1 since we use a different from I believe, could we just merge it back after this change?

**Comment by subrat-mishra** [comment]
> I mean if we could merge the two Dockerfile... We introduce a new Dockerfile for m1 since we use a different from I believe, could we just merge it back after this change?

This change is a minor one for fixing the 'hadolint' command. We may need to support multi-platform docker images, as mentioned by @ndimiduk in HBASE-27915 [comments](https://issues.apache.org/jira/browse/HBASE-27915?focusedCommentId=17848880&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17848880)

**Comment by Apache9** [comment]
@wchevreuil @taklwu Please verify this on M1 mac?

Thanks.

**Comment by wchevreuil** [comment]
> @wchevreuil @taklwu Please verify this on M1 mac?
> 
> Thanks.

Yes, it does work for me. However, since @ndimiduk pointed out in [HBASE-27915](https://issues.apache.org/jira/browse/HBASE-27915?focusedCommentId=17848880&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17848880), shouldn't we revert this extra Dockerfile and do a single file for multiple platforms?

**Comment by Apache9** [comment]
> > @wchevreuil @taklwu Please verify this on M1 mac?
> > Thanks.
> 
> Yes, it does work for me. However, since @ndimiduk pointed out in [HBASE-27915](https://issues.apache.org/jira/browse/HBASE-27915?focusedCommentId=17848880&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17848880), shouldn't we revert this extra Dockerfile and do a single file for multiple platforms?

I'm OK with merging this first to fix the nightly failures, and then open a new issue to merge these two dockerfiles.

Or if it is trivial to merge these two dockerfiles, we can do it in this PR too.

**Review by wchevreuil — APPROVED** [review]

**Comment by wchevreuil** [comment]
> > > @wchevreuil @taklwu Please verify this on M1 mac?
> > > Thanks.
> > 
> > 
> > Yes, it does work for me. However, since @ndimiduk pointed out in [HBASE-27915](https://issues.apache.org/jira/browse/HBASE-27915?focusedCommentId=17848880&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17848880), shouldn't we revert this extra Dockerfile and do a single file for multiple platforms?
> 
> I'm OK with merging this first to fix the nightly failures, and then open a new issue to merge these two dockerfiles.
> 
> Or if it is trivial to merge these two dockerfiles, we can do it in this PR too.

Ok, let me merge this to fix the hadolint check, @subrat-mishra will open a new PR with the single docker file solution.

**Pull request merged**
