### PR TITLE
Backport HBASE-24073 [flakey test] client.TestAsyncRegionAdminApi messed up compaction state. (#1387)

### PR DESCRIPTION
**Pull request by huaxiangsun**
…mpaction state. (#1387)

Signed-off-by: Viraj Jasani <vjasani@apache.org>

### CODE REVIEW

**Comment by huaxiangsun** [comment]
Did a local build and test the TestAsyncRegionAdminApi, it passed, merge it for now. Will revert and merge if it runs into any issues.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  7s |  https://github.com/apache/hbase/pull/1389 does not apply to branch-2. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1389 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1389/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  7s |  https://github.com/apache/hbase/pull/1389 does not apply to branch-2. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1389 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1389/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  5s |  https://github.com/apache/hbase/pull/1389 does not apply to branch-2. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1389 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1389/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by huaxiangsun** [comment]
Sorry, the error message is due to the fact that I already merged the patch, and yetus tries to apply the patch to the branch with patch, it complained that the patch does not apply. It can be ignored.

**Pull request merged**
