### PR TITLE
Backport "Test with hbase-thirdparty 4.1.9RC0" to branch-2.5

### PR DESCRIPTION
**Pull request by ndimiduk**
#6295

### CODE REVIEW

**Comment by ndimiduk** [comment]
Oops nope, that is a major version bump of the protobuf jar.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 52s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
|||| _ branch-2.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 20s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   7m 52s |  |  branch-2.5 passed  |
| +1 :green_heart: |  spotless  |   0m 50s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 37s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 20s | [/patch-compile-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/patch-compile-root.txt) |  root in the patch failed.  |
| -0 :warning: |  javac  |   0m 20s | [/patch-compile-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/patch-compile-root.txt) |  root in the patch failed.  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  xmllint  |   0m  0s |  |  No new issues.  |
| -1 :x: |  hadoopcheck  |   0m  9s |  |  The patch causes 36 errors with Hadoop v2.10.2.  |
| -1 :x: |  hadoopcheck  |   0m 17s |  |  The patch causes 36 errors with Hadoop v3.2.4.  |
| -1 :x: |  hadoopcheck  |   0m 26s |  |  The patch causes 36 errors with Hadoop v3.3.6.  |
| -1 :x: |  hadoopcheck  |   0m 35s |  |  The patch causes 36 errors with Hadoop v3.4.0.  |
| -1 :x: |  spotless  |   0m  6s |  |  patch has 36 errors when running spotless:check, run spotless:apply to fix.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 11s |  |  The patch does not generate ASF License warnings.  |
|  |   |  18m 21s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6299 |
| Optional Tests | dupname asflicense javac codespell detsecrets xmllint hadoopcheck spotless compile |
| uname | Linux 7a07455cb821 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 43f2ce97698c075af8b10a3c37aab70ab4fe438f |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/patch-javac-2.10.2.txt |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/patch-javac-3.2.4.txt |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/patch-javac-3.3.6.txt |
| hadoopcheck | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/patch-javac-3.4.0.txt |
| spotless | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-general-check/output/patch-spotless.txt |
| Max. process+thread count | 73 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/console |
| versions | git=2.34.1 maven=3.9.8 xmllint=20913 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 23s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m  0s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   2m  6s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   1m 55s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   5m  7s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 30s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk11-hadoop3-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 20s | [/patch-compile-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk11-hadoop3-check/output/patch-compile-root.txt) |  root in the patch failed.  |
| -0 :warning: |  javac  |   0m 20s | [/patch-compile-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk11-hadoop3-check/output/patch-compile-root.txt) |  root in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 11s | [/patch-javadoc-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk11-hadoop3-check/output/patch-javadoc-root.txt) |  root in the patch failed.  |
| -1 :x: |  shadedjars  |   1m 35s |  |  patch has 36 errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   3m  7s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk11-hadoop3-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   |  19m 42s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6299 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux c436f139db14 5.4.0-192-generic #212-Ubuntu SMP Fri Jul 5 09:47:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 43f2ce97698c075af8b10a3c37aab70ab4fe438f |
| Default Java | Eclipse Adoptium-11.0.23+9 |
| shadedjars | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk11-hadoop3-check/output/patch-shadedjars.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/testReport/ |
| Max. process+thread count | 745 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 47s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m  9s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   2m  7s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   1m 50s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   5m 30s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 36s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk17-hadoop3-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 18s | [/patch-compile-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk17-hadoop3-check/output/patch-compile-root.txt) |  root in the patch failed.  |
| -0 :warning: |  javac  |   0m 18s | [/patch-compile-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk17-hadoop3-check/output/patch-compile-root.txt) |  root in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 10s | [/patch-javadoc-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk17-hadoop3-check/output/patch-javadoc-root.txt) |  root in the patch failed.  |
| -1 :x: |  shadedjars  |   1m 37s |  |  patch has 36 errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   2m 42s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   |  20m  9s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6299 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 53d9843d9183 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 43f2ce97698c075af8b10a3c37aab70ab4fe438f |
| Default Java | Eclipse Adoptium-17.0.11+9 |
| shadedjars | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk17-hadoop3-check/output/patch-shadedjars.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/testReport/ |
| Max. process+thread count | 782 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 53s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  6s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ branch-2.5 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 21s |  |  branch-2.5 passed  |
| +1 :green_heart: |  compile  |   2m 41s |  |  branch-2.5 passed  |
| +1 :green_heart: |  javadoc  |   2m 44s |  |  branch-2.5 passed  |
| +1 :green_heart: |  shadedjars  |   5m 45s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 50s | [/patch-mvninstall-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk8-hadoop2-check/output/patch-mvninstall-root.txt) |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 28s | [/patch-compile-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk8-hadoop2-check/output/patch-compile-root.txt) |  root in the patch failed.  |
| -0 :warning: |  javac  |   0m 28s | [/patch-compile-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk8-hadoop2-check/output/patch-compile-root.txt) |  root in the patch failed.  |
| -0 :warning: |  javadoc  |   0m 15s | [/patch-javadoc-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk8-hadoop2-check/output/patch-javadoc-root.txt) |  root in the patch failed.  |
| -1 :x: |  shadedjars  |   2m 39s |  |  patch has 36 errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| -1 :x: |  unit  |   3m 31s | [/patch-unit-root.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk8-hadoop2-check/output/patch-unit-root.txt) |  root in the patch failed.  |
|  |   |  24m 53s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6299 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 8a188e19eba0 5.4.0-195-generic #215-Ubuntu SMP Fri Aug 2 18:28:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2.5 / 43f2ce97698c075af8b10a3c37aab70ab4fe438f |
| Default Java | Temurin-1.8.0_412-b08 |
| shadedjars | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/artifact/yetus-jdk8-hadoop2-check/output/patch-shadedjars.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/testReport/ |
| Max. process+thread count | 738 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6299/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
