### PR TITLE
HBASE-24665 MultiWAL : Avoid rolling of ALL WALs when one of the WAL needs a roll

### PR DESCRIPTION
**Pull request by WenFeiYi**

### CODE REVIEW

**Comment by anoopsjohn** [comment]
Not sure why this did not get a QA run. Any pointers @Apache9 ?

**Comment by virajjasani** [comment]
Looks like updating on QA is broken overall, recently (~24 hr)

**Comment by anoopsjohn** [comment]
@WenFeiYi  can u do one more commit to kick a QA run.  Can be like a new blank line create or so

**Comment by WenFeiYi** [comment]
> @WenFeiYi can u do one more commit to kick a QA run. Can be like a new blank line create or so

ok

**Comment by anoopsjohn** [comment]
Seems no luck. Can u pls close this and raise a new PR for branch-2.2?   Same for branch-1 also

**Pull request closed without merging**
