### PR TITLE
HBASE-24235 Wrap creation of NettyHBaseSaslRpcClient with ugi.doAs

### PR DESCRIPTION
**Pull request by mkazia**
When Java HBase client is run in IBM JDK, sasl connections fails
to find the Kerberos ticket. The call needs to be wrapped in
ugi.doAs

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   0m 14s |  Docker failed to build yetus/hbase:6d4e15a7ac.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1565 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1565/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 15s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 26s |  master passed  |
| +1 :green_heart: |  compile  |   0m 27s |  master passed  |
| +1 :green_heart: |  shadedjars  |   5m 50s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 26s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  0s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 49s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 23s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 17s |  hbase-client in the patch passed.  |
|  |   |  25m 17s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1565/1/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1565 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux 9d9d66dcc9f0 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 4ed15e51d9 |
| Default Java | 1.8.0_232 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1565/1/testReport/ |
| Max. process+thread count | 218 (vs. ulimit of 12500) |
| modules | C: hbase-client U: hbase-client |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1565/1/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  9s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  0s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 30s |  master passed  |
| +1 :green_heart: |  spotbugs  |   1m  3s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 39s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 28s |  hbase-client: The patch generated 1 new + 6 unchanged - 0 fixed = 7 total (was 6)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  hadoopcheck  |  12m  0s |  Patch does not cause any errors with Hadoop 3.1.2 3.2.1.  |
| +1 :green_heart: |  spotbugs  |   1m  9s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 12s |  The patch does not generate ASF License warnings.  |
|  |   |  31m 46s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.8 Server=19.03.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1565/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1565 |
| Optional Tests | dupname asflicense spotbugs hadoopcheck hbaseanti checkstyle |
| uname | Linux e0321f44108b 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 4ed15e51d9 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1565/1/artifact/yetus-general-check/output/diff-checkstyle-hbase-client.txt |
| Max. process+thread count | 84 (vs. ulimit of 12500) |
| modules | C: hbase-client U: hbase-client |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1565/1/console |
| versions | git=2.17.1 maven=(cecedd343002696d0abb50b32b541b8a6ba2883f) spotbugs=3.1.12 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by joshelser** [comment]
I am -1 until an actual explanation can be given as to why this change is required for IBM which extends beyond "Hive did it this way".

**Comment by mkazia** [comment]
So I took the Sasl sample code from here https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/lab/src/SaslTestClient.java and ran with both IBM and Oracle JDK. It ran successfully. Notice that `Sasl.createSaslClient` is called within `Jaas.loginAndAction` which wraps everything in `Subject.doAs`. Next I modified the class as below where I moved `Sasl.createSaslClient` outside of `Jaas.loginAndAction`. The code ran successfully in Oracle JDK but failed in IBM JDK. The stack has some commonality with stacktrace I have in jira. 

Is this explanation good enough to change your -1 to +1?

Stack trace:
```
Connected to address nightly6x-1.nightly6x.root.hwx.site/172.27.31.197
Got connection from client /172.27.31.197
IBMJGSSProvider Build-Level: -20200127
[JGSS_DBG_PROV]  main IBMJGSSProvider (version 8.0) loaded
[JGSS_DBG_PROV]  main Number of system providers=9
[JGSS_DBG_PROV]  main getMechOidFromProperty: mech oid string = 1.3.6.1.5.5.2
[JGSS_DBG_PROV]  main getMechOidFromProperty: mech oid string = 1.2.840.113554.1.2.2
[JGSS_DBG_PROV]  main getMechOidFromProperty: mech oid string = 1.3.6.1.5.5.2
[JGSS_DBG_PROV]  main 3 system providers found/added
[JGSS_DBG_PROV]  main getMechOidFromProperty: mech oid string = 1.3.6.1.5.5.2
[JGSS_DBG_PROV]  main getMechOidFromProperty: mech oid string = 1.2.840.113554.1.2.2
[JGSS_DBG_PROV]  main getMechs: Mechanism(s) supported by provider IBMJGSSProvider
[JGSS_DBG_PROV]  main   1.3.6.1.5.5.2
[JGSS_DBG_PROV]  main getMechOidFromProperty: mech oid string = 1.3.6.1.5.5.2
[JGSS_DBG_PROV]  main getMechOidFromProperty: mech oid string = 1.2.840.113554.1.2.2
[JGSS_DBG_PROV]  main getMechs: Mechanism(s) supported by provider IBMJGSSProvider
[JGSS_DBG_PROV]  main   1.2.840.113554.1.2.2
[JGSS_DBG_PROV]  main getMechOidFromProperty: mech oid string = 1.3.6.1.5.5.2
[JGSS_DBG_PROV]  main getMechs: Mechanism(s) supported by provider IBMSPNEGO
[JGSS_DBG_PROV]  main   1.3.6.1.5.5.2
[JGSS_DBG_PROV]  main getMechs: 2 unique mechanism(s) found
[JGSS_DBG_PROV]  main   [0]: 1.3.6.1.5.5.2
[JGSS_DBG_PROV]  main   [1]: 1.2.840.113554.1.2.2
[JGSS_DBG_CRED]  main MN not found; creating one
[JGSS_DBG_PROV]  main Provider Entry: provider: IBMJGSSProvider, mechanism: 1.3.6.1.5.5.2 get Factory for mech: 1.2.840.113554.1.2.2 GSSCaller:
[JGSS_DBG_PROV]  main Provider Entry: provider: IBMJGSSProvider, mechanism: 1.2.840.113554.1.2.2 get Factory for mech: 1.2.840.113554.1.2.2 GSSCaller:
[JGSS_DBG_PROV]  main Created new (empty) factory list (size=1) for provider IBMJGSSProvider version 8.0
[JGSS_DBG_PROV]  main Loading factory
[JGSS_DBG_PROV]  main Factory class name for provider IBMJGSSProvider version 8.0 is com.ibm.security.jgss.mech.krb5.Krb5MechFactory
[JGSS_DBG_PROV]  main IBMJGSSProvider (version 8.0) loaded
[JGSS_DBG_PROV]  main Prior to load
[JGSS_DBG_PROV]  main Done to load
[JGSS_DBG_PROV]  main Loaded factory for provider IBMJGSSProvider version 8.0
[JGSS_DBG_PROV]  main Loaded factory ok
[JGSS_DBG_PROV]  main getFactory: index = 1 found factory caller = GSSCaller{UNKNOWN}
[JGSS_DBG_CRED]  main Before Cannonicalizing hostbased service name HTTP@nightly6x-1.nightly6x.root.hwx.site
[KRB_DBG_CFG] Config:main:   readKrb5Properties: defaultRealm = null
[KRB_DBG_CFG] Config:main:   readKrb5Properties: defaultKDC   = null
[KRB_DBG_CFG] Config:main:   Java config file: /etc/krb5.conf
[KRB_DBG_CFG] Config:main:   loadConfigFile: configFile = [logging = {, default = FILE:/var/log/krb5libs.log, kdc = FILE:/var/log/krb5kdc.log, admin_server = FILE:/var/log/kadmind.log, }, libdefaults = {, renew_lifetime = 90m, default_realm = ROOT.HWX.SITE, dns_lookup_realm = false, dns_lookup_kdc = false, ticket_lifetime = 25m, forwardable = yes, allow_weak_crypto = true, }, realms = {, ROOT.HWX.SITE = {, kdc = nightly6x-1.nightly6x.root.hwx.site:88, admin_server = nightly6x-1.nightly6x.root.hwx.site:749, default_domain = nightly6x.root.hwx.site, }, }, domain_realm = {, .nightly6x.root.hwx.site = ROOT.HWX.SITE, nightly6x.root.hwx.site = ROOT.HWX.SITE, }]
[KRB_DBG_CFG] Config:main:   Loaded from Java config
[KRB_DBG_CFG] Config:main:   Config: stanzaTable = {libdefaults={allow_weak_crypto=[true], ticket_lifetime=[25m], default_realm=[ROOT.HWX.SITE], forwardable=[yes], dns_lookup_kdc=[false], renew_lifetime=[90m], dns_lookup_realm=[false]}, domain_realm={.nightly6x.root.hwx.site=[ROOT.HWX.SITE], nightly6x.root.hwx.site=[ROOT.HWX.SITE]}, logging={kdc=[FILE:/var/log/krb5kdc.log], default=[FILE:/var/log/krb5libs.log], admin_server=[FILE:/var/log/kadmind.log]}, realms={ROOT.HWX.SITE={default_domain=[nightly6x.root.hwx.site], kdc=[nightly6x-1.nightly6x.root.hwx.site:88], admin_server=[nightly6x-1.nightly6x.root.hwx.site:749]}}}
[KRB_DBG_CFG] Config:main:   get: section     = libdefaults
[KRB_DBG_CFG] Config:main:   get: name        = dns_lookup_realm
[KRB_DBG_CFG] Config:main:   get: result      = false
[JGSS_DBG_CRED]  main Cannonicalizing hostbased service name HTTP@nightly6x-1.nightly6x.root.hwx.site
[JGSS_DBG_CRED]  main Hostname nightly6x-1.nightly6x.root.hwx.site
[KRB_DBG_CFG] Config:main:   get: section     = domain_realm
[KRB_DBG_CFG] Config:main:   get: name        = .nightly6x.root.hwx.site
[KRB_DBG_CFG] Config:main:   get: result      = ROOT.HWX.SITE
[KRB_DBG_CFG] Config:main:   get: section     = domain_realm
[KRB_DBG_CFG] Config:main:   get: name        = .nightly6x.root.hwx.site
[KRB_DBG_CFG] Config:main:   get: result      = ROOT.HWX.SITE
[JGSS_DBG_CRED]  main Name cannonicalization complete, resulting name string=HTTP/nightly6x-1.nightly6x.root.hwx.site@ROOT.HWX.SITE
[JGSS_DBG_CTX]  main Creating context, initiator = yes, input cred = null
[JGSS_DBG_CTX]  main Creating default initiator creds
[JGSS_DBG_CRED]  main Creating mech cred for null, mech 1.2.840.113554.1.2.2, usage initiate only
[JGSS_DBG_PROV]  main Provider Entry: provider: IBMJGSSProvider, mechanism: 1.3.6.1.5.5.2 get Factory for mech: 1.2.840.113554.1.2.2 GSSCaller:
[JGSS_DBG_PROV]  main Provider Entry: provider: IBMJGSSProvider, mechanism: 1.2.840.113554.1.2.2 get Factory for mech: 1.2.840.113554.1.2.2 GSSCaller:
[JGSS_DBG_PROV]  main getFactory: index = 1 found factory caller = GSSCaller{UNKNOWN}
[JGSS_DBG_CRED]  main Search Subject for Kerberos V5 INIT cred (<<DEF>>, com.ibm.security.jgss.mech.krb5.s)
[JGSS_DBG_CRED]  main No Subject
[JGSS_DBG_CRED]  main Creating credentials for name null, servName null, usage 1
[JGSS_DBG_CRED]  main Trying to get credentials for null
[JGSS_DBG_CRED]  main usage: initiator only, check subject, useAllCred : false
[JGSS_DBG_CRED]  main Obtaining Subject creds for default principal
[JGSS_DBG_CRED]  main SubjectCredFinder: client=null, server=null
Exception in thread "main" javax.security.sasl.SaslException: Failure to initialize security context [Caused by org.ietf.jgss.GSSException, major code: 13, minor code: 0
        major string: Invalid credentials
        minor string: SubjectCredFinder: no JAAS Subject]
        at com.ibm.security.sasl.gsskerb.GssKrb5Client.<init>(GssKrb5Client.java:161)
        at com.ibm.security.sasl.gsskerb.FactoryImpl.createSaslClient(FactoryImpl.java:79)
        at javax.security.sasl.Sasl.createSaslClient(Sasl.java:400)
        at SaslTestClient2.main(SaslTestClient2.java:108)
Caused by: org.ietf.jgss.GSSException, major code: 13, minor code: 0
        major string: Invalid credentials
        minor string: SubjectCredFinder: no JAAS Subject
        at com.ibm.security.jgss.i18n.I18NException.throwGSSException(Unknown Source)
        at com.ibm.security.jgss.mech.krb5.v.run(Unknown Source)
        at java.security.AccessController.doPrivileged(AccessController.java:734)
        at com.ibm.security.jgss.mech.krb5.s.c(Unknown Source)
        at com.ibm.security.jgss.mech.krb5.s.a(Unknown Source)
        at com.ibm.security.jgss.mech.krb5.s.a(Unknown Source)
        at com.ibm.security.jgss.mech.krb5.s.<init>(Unknown Source)
        at com.ibm.security.jgss.mech.krb5.Krb5MechFactory.getCredentialElement(Unknown Source)
        at com.ibm.security.jgss.GSSManagerImpl.createMechCredential(Unknown Source)
        at com.ibm.security.jgss.GSSCredentialImpl.add(Unknown Source)
        at com.ibm.security.jgss.GSSCredentialImpl.<init>(Unknown Source)
        at com.ibm.security.jgss.GSSManagerImpl.createCredential(Unknown Source)
        at com.ibm.security.jgss.GSSContextImpl.a(Unknown Source)
        at com.ibm.security.jgss.GSSContextImpl.<init>(Unknown Source)
        at com.ibm.security.jgss.GSSManagerImpl.createContext(Unknown Source)
        at com.ibm.security.sasl.gsskerb.GssKrb5Client.<init>(GssKrb5Client.java:135)
        ... 3 more
```

Modified code:

```
import javax.security.sasl.*;
import javax.security.auth.callback.*;
import java.security.*;
import javax.security.auth.Subject;
import javax.security.auth.login.*;
import com.sun.security.auth.callback.*;
import java.util.HashMap;

public class SaslTestClient2 {
    private static final String MECH = "GSSAPI"; // SASL name for GSS-API/Kerberos
    private static final int PORT = 4568;

    private static final byte[] EMPTY = new byte[0];

    public static void main(String[] args) throws Exception {
        // Obtain the command-line arguments and parse the server's principal

        if (args.length < 2) {
            System.err.println(
                "Usage: java <options> SaslTestClient2 <service> <serverName>");
            System.exit(-1);
        }

       // Create application-level connection
       AppConnection conn = new AppConnection(args[1], PORT);

       HashMap<String,Object> props = new HashMap<String,Object>();
       // Request confidentiality
       props.put(Sasl.QOP, "auth-conf");

        CallbackHandler cbh = null; // Don't need handler for GSSAPI
       // Create SaslClient to perform authentication
       SaslClient clnt = Sasl.createSaslClient(
           new String[]{MECH}, null, args[0], args[1], props, cbh);

       if (clnt == null) {
           throw new Exception(
               "Unable to find client implementation for " + MECH);
       }

        PrivilegedExceptionAction action =
            new SaslClientAction(conn, clnt);

        Jaas.loginAndAction("client", action);
    }

    static class SaslClientAction implements PrivilegedExceptionAction {
        private AppConnection conn;
        private SaslClient clnt;

        SaslClientAction(AppConnection conn, SaslClient clnt) {
            this.conn = conn;
            this.clnt = clnt;
        }

        public Object run() throws Exception {
            byte[] response;
            byte[] challenge;

            // Get initial response for authentication
            response = clnt.hasInitialResponse() ?
                clnt.evaluateChallenge(EMPTY) : EMPTY;

            // Send initial response to server
            AppConnection.AppReply reply =
                conn.send(AppConnection.AUTH_CMD, response);

            // Repeat until authentication terminates
            while (!clnt.isComplete() &&
                (reply.getStatus() == AppConnection.AUTH_INPROGRESS ||
                 reply.getStatus() == AppConnection.SUCCESS)) {

                // Evaluate challenge to generate response
                challenge = reply.getBytes();
                response = clnt.evaluateChallenge(challenge);

                if (reply.getStatus() == AppConnection.SUCCESS) {
                    if (response != null) {
                        throw new Exception("Protocol error interacting with SASL");
                    }
                    break;
                }

                // Send response to server and read server's next challenge
                reply = conn.send(AppConnection.AUTH_CMD, response);
            }

            // Check status of authentication
            if (clnt.isComplete() && reply.getStatus() == AppConnection.SUCCESS) {
                System.out.println("Client authenticated.");
            } else {
                throw new Exception("Authentication failed: " +
                    " connection status? " + reply.getStatus());
            }

            String qop = (String) clnt.getNegotiatedProperty(Sasl.QOP);
            System.out.println("Negotiated QOP: " + qop);

            // Try out security layer
            boolean sl = (qop.equals("auth-conf") || qop.equals("auth-int"));

            byte[] msg = "Hello There!".getBytes("UTF-8");
            System.out.println("Sending: " + new String(msg, "UTF-8"));

            byte[] encrypted = (sl ? clnt.wrap(msg, 0, msg.length) : msg);

            reply = conn.send(AppConnection.DATA_CMD, encrypted);

            if (reply.getStatus() == AppConnection.SUCCESS) {
                byte[] encryptedReply = reply.getBytes();

                byte[] clearReply = (sl ? clnt.unwrap(encryptedReply,
                    0, encryptedReply.length) : encryptedReply);

                System.out.println("Received: " + new String(clearReply, "UTF-8"));
            } else {
                System.out.println("Failed exchange: " + reply.getStatus());
            }

            conn.close();

            return null;
        }
    }
}
```

**Comment by mkazia** [comment]
Another reference here https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/ipc/Client.java#L817-L824 that shows that creating SaslClient should be wrapped in doAs.

**Comment by joshelser** [comment]
HBase *already does* doAs calls. I was trying to encourage you to read the code to find this yourself.

https://github.com/apache/hbase/blob/e96ad0ac1e69dd2a273365a7ae089a4a39fa0e0c/hbase-client/src/main/java/org/apache/hadoop/hbase/security/NettyHBaseSaslRpcClientHandler.java

The question I asked is why IBM Java is ineffective, because we already know that HBase is doing the correct thing given automated tests against OpenJDK (which is what Apache HBase expressly tests against).

**Comment by mkazia** [comment]
@joshelser thanks for looking into this. 
The code path for creating the SaslClient ([`NettyHBaseSaslRpcClient`](https://github.com/apache/hbase/blob/master/hbase-client/src/main/java/org/apache/hadoop/hbase/security/NettyHBaseSaslRpcClientHandler.java#L74)) is not wrapped in the doAs. You can see from the stack trace that is given in the initial jira. In the Class you mentioned, doAs is wrapped for [`saslRpcClient.getInitialResponse()`](https://github.com/apache/hbase/blob/master/hbase-client/src/main/java/org/apache/hadoop/hbase/security/NettyHBaseSaslRpcClientHandler.java#L119) and [`saslRpcClient.evaluateChallenge(challenge)`](https://github.com/apache/hbase/blob/master/hbase-client/src/main/java/org/apache/hadoop/hbase/security/NettyHBaseSaslRpcClientHandler.java#L157). I have shown from the example/test code, while Oracle/Open JDK does not require the **creation of SaslClient** to be wrapped in doAs, IBM JDK requires it. And this is all this PR does, wrapping the creation of SaslClient creation in doAs.

If this is still not clear or if there is a point you are making that I'm not following, please let me know.

**Comment by joshelser** [comment]
> I have shown from the example/test code, while Oracle/Open JDK does not require the creation of SaslClient to be wrapped in doAs, IBM JDK requires it

I'm trying to understand what the fundamental difference is here between other JVMs and IBM Java. You are providing anecdotal evidence, not something which gives me any confidence in your solution.

For example: why is IBM java different? Is this a known or conscious decision by IBM Java to be different? What is the creation of the SaslClient object doing that requires a privileged execution context? Why _doesn't_ Oracle/Open JDK require this?

Simply showing that one test passes in isolation does not give me any confidence in this solution you've shown here as being correct.

**Comment by mkazia** [comment]
@joshelser Thanks for your continued indulgence in this.

So far from IBM I have managed to find this example 

> The mechanism expects the calling threads Subject to contain the clients Kerberos credentials or that the credentials could be obtained by implicitly logging in to Kerberos. To obtain the clients Kerberos credentials, use the Java™ Authentication and Authorization Service (JAAS) to log in using the Kerberos login module. See the Java GSS-API and JAAS Tutorials for Use with Kerberos for details and examples. After using JAAS authentication to obtain the Kerberos credentials, you put the code that uses the SASL GSSAPI mechanism within doAs or doAsPrivileged. 

The example that follows shows the `Sasl.createSaslClient` wrapped in doAs. You can find it all here:
https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/saslDocs/clientmechanisms.html?view=embed#clientmechanisms__gssapi 

The reason why OpenJDK does not need this for creating SaslClient is because it does not call `secCtx.initSecContext()` in the constructor of class [com.sun.security.sasl.gsskerb.GssKrb5Client](https://github.com/openjdk/jdk/blob/master/src/jdk.security.jgss/share/classes/com/sun/security/sasl/gsskerb/GssKrb5Client.java#L94-L165) which is what gets called when `Sasl.createSaslClient` gets called with GSSAPI mech. Since OpenJDK uses SunSASL and IBM uses IBMSASL, I would imagine they are both different implementations and IBM SASL is possibly calling `secCtx.initSecContext()`. The stack trace show it is calling `com.ibm.security.jgss.GSSManagerImpl.createContext` which I would assume is something similar to  `secCtx.initSecContext()`

In the absence of IBM JDK source code or proper documentation that shows what the differences are between JDKs, I can only show you by experimentation or by finding precedences. So far I have:

1. Used  a bare bone standalone SaslClient code and demonstrated that while the code runs in Oracle/Open JDK it fails in IBM JDK when the SaslClient creation is not wrapped in doAs. I have also shown that wrapping SaslClient creation in doAs works for all 3 JDKs for this example.
2. By way of precedence I have shown that the SaslClient creation code in HDFS client is wrapped in doAs.
3. By way of precedence I have shown that the SaslClient creation code in Hive jdbc client is wrapped in doAs.
4. The application of this patch itself fixes the issue in HBase client for IBM JDK and does not break anything for other JDKs.

I hope I have answered the questions to your satisfaction.

**Comment by Apache9** [comment]
> The reason why OpenJDK does not need this for creating SaslClient is because it does not call secCtx.initSecContext() in the constructor of class com.sun.security.sasl.gsskerb.GssKrb5Client which is what gets called when Sasl.createSaslClient gets called with GSSAPI mech. Since OpenJDK uses SunSASL and IBM uses IBMSASL, I would imagine they are both different implementations and IBM SASL is possibly calling secCtx.initSecContext(). The stack trace show it is calling com.ibm.security.jgss.GSSManagerImpl.createContext which I would assume is something similar to secCtx.initSecContext()

I think Josh is exactly asking why OpenJDK and IBMJDK use different implementations here. It's 'why', not 'how'...

Thanks.

**Comment by mkazia** [comment]
Thanks @Apache9 for looking into this PR
> I think Josh is exactly asking why OpenJDK and IBMJDK use different implementations here. It's 'why', not 'how'...

I'm not from IBM and I don't know the historical reasons why IBMJDK has it own SASL implementation. I would speculate that IBMSASL existed before OpenJDK ever existed. And I would speculate that IBM continues to use IBMSASL and not OpenJDK SASL(SunSASL) because of backward compatibility and licensing issues. INAL, IBM JDK is closed source product and I presume, using components from Copyleft products could cause licensing issues.

**Comment by joshelser** [comment]
This is essentially what we're trying to get to the bottom of. We are not in the habit of making changes because of speculation or "seems to be".

The more leg work you can do to explain why IBM Java is the way it is will give some clout to your suggested change. Right now, you are pushing all of the burden onto someone from HBase to validate your speculations.

**Comment by mkazia** [comment]
>Right now, you are pushing all of the burden onto someone from HBase to validate your speculations.

I'm not pushing anything on anyone to validate my speculations. I would like to understand what would you do technically different if any of the things I speculated was true or false? Other than hinting to go make IBM JDK work like OpenJDK what would you do to fix the problem? How can I help in this regard other than bringing a IBM JDK engineer to answer your questions? What is your concern with the proposed change?

**Comment by mkazia** [comment]
Closing this PR as there does not seem to be interest in getting this implemented and I will not be available to work on this anymore.

**Pull request closed without merging**
