### PR TITLE
HBASE-23254 Release replication buffer quota correctly, when batch includes bulk loaded hfiles

### PR DESCRIPTION
**Pull request by JeongDaeKim**
https://issues.apache.org/jira/browse/HBASE-23254

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |  10m 51s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| :green_heart: |  mvninstall  |   8m 42s |  branch-1 passed  |
| :green_heart: |  compile  |   0m 45s |  branch-1 passed with JDK v1.8.0_232  |
| :green_heart: |  compile  |   0m 54s |  branch-1 passed with JDK v1.7.0_242  |
| :green_heart: |  checkstyle  |   1m 54s |  branch-1 passed  |
| :green_heart: |  shadedjars  |   3m 35s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   0m 40s |  branch-1 passed with JDK v1.8.0_232  |
| :green_heart: |  javadoc  |   0m 46s |  branch-1 passed with JDK v1.7.0_242  |
| :blue_heart: |  spotbugs  |   3m  9s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| :green_heart: |  findbugs  |   3m  5s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   2m 21s |  the patch passed  |
| :green_heart: |  compile  |   0m 47s |  the patch passed with JDK v1.8.0_232  |
| :green_heart: |  javac  |   0m 47s |  the patch passed  |
| :green_heart: |  compile  |   0m 48s |  the patch passed with JDK v1.7.0_242  |
| :green_heart: |  javac  |   0m 48s |  the patch passed  |
| :green_heart: |  checkstyle  |   1m 51s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  shadedjars  |   3m 23s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |   5m 41s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| :green_heart: |  javadoc  |   0m 31s |  the patch passed with JDK v1.8.0_232  |
| :green_heart: |  javadoc  |   0m 39s |  the patch passed with JDK v1.7.0_242  |
| :green_heart: |  findbugs  |   2m 51s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 125m 17s |  hbase-server in the patch failed.  |
| :green_heart: |  asflicense  |   0m 34s |  The patch does not generate ASF License warnings.  |
|  |   | 179m 46s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.TestReplicationKillSlaveRS |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.4 Server=19.03.4 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/792 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux b96acf2ef010 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-792/out/precommit/personality/provided.sh |
| git revision | branch-1 / 3f9ce86 |
| Default Java | 1.7.0_242 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_232 /usr/lib/jvm/zulu-7-amd64:1.7.0_242 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/1/testReport/ |
| Max. process+thread count | 4145 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by JeongDaeKim** [comment]
I just wanted to add a missing line from the (branch-1) backport of HBASE-18116 to work as intended in HBASE-18116. I don't think a new UT for  branch-1 only.  Here is the region why original author didn't have  a UT. (https://issues.apache.org/jira/browse/HBASE-18116?focusedCommentId=16476668&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16476668)

**Comment by JeongDaeKim** [comment]
I can't reproduce the failed test in my local repo. and It seems unrelated to this.

**Comment by JeongDaeKim** [comment]
I just added to a test to clarify this issue. @wchevreuil please have a look when you have time.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  12m 18s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m 36s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 40s |  branch-1 passed with JDK v1.8.0_232  |
| +1 :green_heart: |  compile  |   0m 45s |  branch-1 passed with JDK v1.7.0_242  |
| +1 :green_heart: |  checkstyle  |   1m 34s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   2m 52s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 38s |  branch-1 passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javadoc  |   0m 42s |  branch-1 passed with JDK v1.7.0_242  |
| +0 :ok: |  spotbugs  |   2m 48s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 46s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 58s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 41s |  the patch passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javac  |   0m 41s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 44s |  the patch passed with JDK v1.7.0_242  |
| +1 :green_heart: |  javac  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 29s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 46s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   5m  5s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 31s |  the patch passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javadoc  |   0m 41s |  the patch passed with JDK v1.7.0_242  |
| +1 :green_heart: |  findbugs  |   2m 55s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 161m 35s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 35s |  The patch does not generate ASF License warnings.  |
|  |   | 213m 35s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.mapreduce.TestLoadIncrementalHFilesUseSecurityEndPoint |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectory |
|   | hadoop.hbase.regionserver.TestCompactionState |
|   | hadoop.hbase.client.TestAdmin2 |
|   | hadoop.hbase.mapreduce.TestLoadIncrementalHFiles |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/792 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 72f9cb6dba0b 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-792/out/precommit/personality/provided.sh |
| git revision | branch-1 / 248d80b |
| Default Java | 1.7.0_242 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_232 /usr/lib/jvm/zulu-7-amd64:1.7.0_242 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/2/testReport/ |
| Max. process+thread count | 4227 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by JeongDaeKim** [comment]
The following exception were thrown in all failed tests.
These failures has happened since #1010 (JUnit upgrade)
I confirmed all tests passed Without JUnit upgrade.

I'm not sure but it seems to be related to this change https://github.com/junit-team/junit4/pull/1517
ping~ @ndimiduk 
```
java.lang.RuntimeException: java.lang.IllegalThreadStateException

	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:239)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:273)
	at org.apache.hadoop.hbase.client.ClientScanner.loadCache(ClientScanner.java:434)
	at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:308)
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:639)
	at org.apache.hadoop.hbase.MetaTableAccessor.getTableRegionsAndLocations(MetaTableAccessor.java:558)
	at org.apache.hadoop.hbase.MetaTableAccessor.getTableRegions(MetaTableAccessor.java:414)
	at org.apache.hadoop.hbase.MetaTableAccessor.getTableRegions(MetaTableAccessor.java:397)
	at org.apache.hadoop.hbase.client.HBaseAdmin.getTableRegions(HBaseAdmin.java:3317)
	at org.apache.hadoop.hbase.client.TestAdmin2.testEnableTableAfterprocessedServersCleaned(TestAdmin2.java:816)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalThreadStateException
	at java.lang.ThreadGroup.addUnstarted(ThreadGroup.java:867)
	at java.lang.Thread.init(Thread.java:405)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:599)
	at org.apache.hadoop.hbase.util.Threads$2.newThread(Threads.java:220)
	at org.apache.hadoop.hbase.util.Threads$3.newThread(Threads.java:246)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:619)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:932)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367)
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService.submit(ResultBoundedCompletionService.java:171)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.addCallsForCurrentReplica(ScannerCallableWithReplicas.java:330)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:191)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:58)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:231)
	... 21 more
```

**Comment by ndimiduk** [comment]
thanks @JeongDaeKim I'll take a look.

**Comment by ndimiduk** [comment]
FYI #1031

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  8s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   9m  0s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 41s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  compile  |   0m 45s |  branch-1 passed with JDK v1.7.0_252  |
| +1 :green_heart: |  checkstyle  |   1m 32s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   2m 59s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 39s |  branch-1 passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   0m 42s |  branch-1 passed with JDK v1.7.0_252  |
| +0 :ok: |  spotbugs  |   2m 49s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 46s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m 57s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 41s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javac  |   0m 41s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 45s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  javac  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 28s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 49s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 53s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 32s |  the patch passed with JDK v1.8.0_242  |
| +1 :green_heart: |  javadoc  |   0m 41s |  the patch passed with JDK v1.7.0_252  |
| +1 :green_heart: |  findbugs  |   2m 52s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 169m  4s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 33s |  The patch does not generate ASF License warnings.  |
|  |   | 209m 51s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/792 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 33cf7cfe0e92 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-792/out/precommit/personality/provided.sh |
| git revision | branch-1 / 99a59cf |
| Default Java | 1.7.0_252 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_242 /usr/lib/jvm/zulu-7-amd64:1.7.0_252 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/3/testReport/ |
| Max. process+thread count | 4370 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-792/3/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by wchevreuil** [comment]
Re-submitted build to confirm on the junit issue is solved now, this is good to go. Am merging it now.

**Pull request merged**
