### PR TITLE
HBASE-23330: Fix delegation token fetch with MasterRegistry

### PR DESCRIPTION
**Pull request by bharathv**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  8s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  1s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ HBASE-18095/client-locate-meta-no-zookeeper Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 34s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 41s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  compile  |   2m 22s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  checkstyle  |   3m  2s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  shadedjars  |   5m  3s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 44s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +0 :ok: |  spotbugs  |   1m 41s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   8m 29s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 45s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 31s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 31s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 28s |  hbase-server: The patch generated 3 new + 5 unchanged - 0 fixed = 8 total (was 5)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   5m 25s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  18m 29s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   2m  3s |  the patch passed  |
| +1 :green_heart: |  findbugs  |  10m  8s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m  6s |  hbase-client in the patch passed.  |
| -1 :x: |  unit  | 194m 22s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  unit  |  24m 20s |  hbase-mapreduce in the patch passed.  |
| -1 :x: |  unit  |   4m  6s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  asflicense  |   2m 25s |  The patch does not generate ASF License warnings.  |
|  |   | 311m 33s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.regionserver.TestTags |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.thrift2.TestThriftConnection |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1084 |
| JIRA Issue | HBASE-23330 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 4cea401909ad 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1084/out/precommit/personality/provided.sh |
| git revision | HBASE-18095/client-locate-meta-no-zookeeper / d9bb034c94 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/1/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/1/artifact/out/patch-unit-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/1/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/1/testReport/ |
| Max. process+thread count | 5256 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server hbase-mapreduce hbase-thrift U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
Changes look fine, waiting on a clean precommit before approval

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 39s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ HBASE-18095/client-locate-meta-no-zookeeper Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 39s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 32s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  compile  |   2m 36s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  checkstyle  |   3m  2s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  shadedjars  |   4m 57s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m  8s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +0 :ok: |  spotbugs  |   1m 55s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   9m 13s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 38s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 38s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   3m  6s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 54s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  16m 44s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   2m  4s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   9m 56s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 15s |  hbase-client in the patch passed.  |
| -1 :x: |  unit  | 170m 13s |  hbase-server in the patch failed.  |
| -1 :x: |  unit  |  20m 17s |  hbase-mapreduce in the patch failed.  |
| +1 :green_heart: |  unit  |   4m  7s |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 18s |  The patch does not generate ASF License warnings.  |
|  |   | 280m 58s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.snapshot.TestExportSnapshotNoCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1084 |
| JIRA Issue | HBASE-23330 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux cd1927c94e6f 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1084/out/precommit/personality/provided.sh |
| git revision | HBASE-18095/client-locate-meta-no-zookeeper / d9bb034c94 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/2/artifact/out/patch-unit-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/2/artifact/out/patch-unit-hbase-mapreduce.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/2/testReport/ |
| Max. process+thread count | 5524 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server hbase-mapreduce hbase-thrift U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
TestFromClientSide is a known issue and the other failure doesn't look related.

**Comment by apurtell** [comment]
@bharathv Please push an update that resolves the conflicts.

**Comment by bharathv** [comment]
Rebased after the feature branch got force-pushed.!

**Comment by apurtell** [comment]
Got tired of waiting for another QA run. Since this is a feature branch I think it's fine to merge now.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m  2s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 3 new or modified test files.  |
||| _ HBASE-18095/client-locate-meta-no-zookeeper Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 39s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 32s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  compile  |   2m 36s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  checkstyle  |   2m 39s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +1 :green_heart: |  shadedjars  |   4m 56s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m  0s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
| +0 :ok: |  spotbugs  |   1m 43s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   8m 29s |  HBASE-18095/client-locate-meta-no-zookeeper passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 12s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 44s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 44s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   2m 38s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 49s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  16m 31s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   8m 49s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m  9s |  hbase-client in the patch passed.  |
| -1 :x: |  unit  | 170m 55s |  hbase-server in the patch failed.  |
| -1 :x: |  unit  |  20m 26s |  hbase-mapreduce in the patch failed.  |
| +1 :green_heart: |  unit  |   4m  3s |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 31s |  The patch does not generate ASF License warnings.  |
|  |   | 280m  2s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.snapshot.TestExportSnapshotNoCluster |
|   | hadoop.hbase.mapred.TestMultiTableSnapshotInputFormat |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1084 |
| JIRA Issue | HBASE-23330 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 196d16ec350d 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1084/out/precommit/personality/provided.sh |
| git revision | HBASE-18095/client-locate-meta-no-zookeeper / 62da419b23 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/3/artifact/out/patch-unit-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/3/artifact/out/patch-unit-hbase-mapreduce.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/3/testReport/ |
| Max. process+thread count | 5671 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-server hbase-mapreduce hbase-thrift U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1084/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
