### PR TITLE
HBASE-22676 Move all the code in hbase-rsgroup to hbase-server and re…

### PR DESCRIPTION
**Pull request by Apache9**
…move hbase-rsgroup module

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 57 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 1 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 30 new or modified test files. |
||| _ HBASE-22514 Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for branch |
| -1 | mvninstall | 11 | root in HBASE-22514 failed. |
| +1 | compile | 161 | HBASE-22514 passed |
| +1 | checkstyle | 143 | HBASE-22514 passed |
| +1 | shadedjars | 270 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 250 | HBASE-22514 passed |
| 0 | spotbugs | 843 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| -1 | findbugs | 36 | hbase-server in HBASE-22514 failed. |
| -1 | findbugs | 18 | hbase-rsgroup in HBASE-22514 failed. |
| 0 | findbugs | 29 | branch/hbase-assembly no findbugs output file (findbugsXml.xml) |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 12 | Maven dependency ordering for patch |
| -1 | mvninstall | 11 | root in the patch failed. |
| +1 | compile | 163 | the patch passed |
| +1 | javac | 163 | the patch passed |
| +1 | checkstyle | 136 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | xml | 7 | The patch has no ill-formed XML file. |
| +1 | shadedjars | 271 | patch has no errors when building our shaded downstream artifacts. |
| -1 | hadoopcheck | 11 | The patch causes 10 errors with Hadoop v2.8.5. |
| -1 | hadoopcheck | 20 | The patch causes 10 errors with Hadoop v2.9.2. |
| -1 | hadoopcheck | 31 | The patch causes 10 errors with Hadoop v3.1.2. |
| -1 | javadoc | 33 | hbase-server generated 63 new + 4 unchanged - 1 fixed = 67 total (was 5) |
| -1 | javadoc | 151 | root generated 63 new + 17 unchanged - 72 fixed = 80 total (was 89) |
| -1 | findbugs | 35 | hbase-server in the patch failed. |
| 0 | findbugs | 23 | hbase-assembly has no data from findbugs |
||| _ Other Tests _ |
| +1 | unit | 21078 | root in the patch passed. |
| +1 | asflicense | 187 | The patch does not generate ASF License warnings. |
| | | 24992 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=18.09.8 Server=18.09.8 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/399 |
| Optional Tests | dupname asflicense javac javadoc unit xml shadedjars hadoopcheck compile spotbugs findbugs hbaseanti checkstyle |
| uname | Linux dc47ea7822a9 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-399/out/precommit/personality/provided.sh |
| git revision | HBASE-22514 / bf2055a09a |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/branch-mvninstall-root.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/branch-findbugs-hbase-server.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/branch-findbugs-hbase-rsgroup.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/patch-mvninstall-root.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/patch-javac-2.8.5.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/patch-javac-2.9.2.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/patch-javac-3.1.2.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/diff-javadoc-javadoc-hbase-server.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/diff-javadoc-javadoc-root.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/artifact/out/patch-findbugs-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/testReport/ |
| Max. process+thread count | 5548 (vs. ulimit of 10000) |
| modules | C: hbase-server hbase-shell hbase-it hbase-assembly . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-399/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
The result is a bit strange... Tried locally, mvn install is fine. Let me trigger a build again...

And on the spotbugs, I think the problem is that we switch to yetus 0.10.0. Let me check how to fix it.

**Comment by Apache9** [comment]
Not sure what's the problem but at least the mvn install failed also for the base branch...

Anyway, the UTs are all passed, and tried locally, the mvn install also passed.

Let me merge it back as this is on a feature branch.

**Comment by openinx** [comment]
Let me have a check on my host...

**Pull request merged**
