### PR TITLE
HBASE-22451 TestLoadIncrementalHFiles and TestSecureLoadIncrementalHFiles are flaky

### PR DESCRIPTION
**Pull request by apurtell**
Start ZKNamespaceManager as first step in TableNamespaceManager initialization

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | findbugs | 0 | Findbugs executables are not available. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 159 | branch-1 passed |
| +1 | compile | 42 | branch-1 passed with JDK v1.8.0_212 |
| -1 | compile | 25 | hbase-server in branch-1 failed with JDK v1.7.0_222. |
| +1 | checkstyle | 80 | branch-1 passed |
| +1 | shadedjars | 168 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 34 | branch-1 passed with JDK v1.8.0_212 |
| +1 | javadoc | 37 | branch-1 passed with JDK v1.7.0_222 |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 98 | the patch passed |
| +1 | compile | 38 | the patch passed with JDK v1.8.0_212 |
| +1 | javac | 39 | the patch passed |
| +1 | compile | 40 | the patch passed with JDK v1.7.0_222 |
| +1 | javac | 40 | hbase-server-jdk1.7.0_222 with JDK v1.7.0_222 generated 0 new + 6 unchanged - 2 fixed = 6 total (was 8) |
| +1 | checkstyle | 80 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 161 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 206 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 31 | the patch passed with JDK v1.8.0_212 |
| +1 | javadoc | 39 | the patch passed with JDK v1.7.0_222 |
||| _ Other Tests _ |
| -1 | unit | 1794 | hbase-server in the patch failed. |
| +1 | asflicense | 13 | The patch does not generate ASF License warnings. |
| | | 3176 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.TestMinVersions |
|   | hadoop.hbase.regionserver.TestSplitTransaction |
|   | hadoop.hbase.regionserver.TestDateTieredCompactionPolicy |
|   | hadoop.hbase.regionserver.TestDefaultCompactSelection |
|   | hadoop.hbase.regionserver.TestBulkLoad |
|   | hadoop.hbase.regionserver.TestStoreFileScannerWithTagCompression |
|   | hadoop.hbase.filter.TestFilter |
|   | hadoop.hbase.filter.TestQualifierFilterWithEmptyQualifier |
|   | hadoop.hbase.regionserver.TestStoreFileRefresherChore |
|   | hadoop.hbase.regionserver.TestRegionMergeTransaction |
|   | hadoop.hbase.filter.TestInvocationRecordFilter |
|   | hadoop.hbase.filter.TestFilterFromRegionSide |
|   | hadoop.hbase.regionserver.TestDateTieredCompactionPolicyOverflow |
|   | hadoop.hbase.filter.TestMultipleColumnPrefixFilter |
|   | hadoop.hbase.filter.TestDependentColumnFilter |
|   | hadoop.hbase.regionserver.TestBlocksScanned |
|   | hadoop.hbase.regionserver.TestHRegionInfo |
|   | hadoop.hbase.regionserver.TestColumnSeeking |
|   | hadoop.hbase.regionserver.TestHRegionFileSystem |
|   | hadoop.hbase.regionserver.TestStripeStoreFileManager |
|   | hadoop.hbase.regionserver.TestScanner |
|   | hadoop.hbase.filter.TestColumnPrefixFilter |
|   | hadoop.hbase.master.TestCatalogJanitor |
|   | hadoop.hbase.client.TestRollbackFromClient |
|   | hadoop.hbase.client.TestIntraRowPagination |
|   | hadoop.hbase.regionserver.TestScanWithBloomError |
|   | hadoop.hbase.regionserver.TestWideScanner |
|   | hadoop.hbase.coprocessor.TestCoprocessorInterface |
|   | hadoop.hbase.client.TestClientClusterStatus |
|   | hadoop.hbase.coprocessor.TestRegionObserverStacking |
|   | hadoop.hbase.regionserver.TestResettingCounters |
|   | hadoop.hbase.regionserver.TestKeepDeletes |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/250 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 7f4953bbed5e 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-1 / b5d667c |
| maven | version: Apache Maven 3.0.5 |
| Default Java | 1.7.0_222 |
| Multi-JDK versions |  /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_212 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_222 |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/1/artifact/out/branch-compile-hbase-server-jdk1.7.0_222.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/1/testReport/ |
| Max. process+thread count | 709 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
Ok, that looks like a legitimate result. This doesn't seem the right way to do this.

**Comment by apurtell** [comment]
Some kind of compile/classpath problem

[ERROR] /testptch/hbase/hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/CacheStats.java:[77,41] cannot access org.apache.hadoop.hbase.util.Counter.Cell
  bad class file: /home/jenkins/.m2/repository/org/apache/hbase/hbase-common/1.5.0-SNAPSHOT/hbase-common-1.5.0-SNAPSHOT.jar(org/apache/hadoop/hbase/util/Counter$Cell.class)
    unable to access file: corrupted zip file
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[INFO] 1 error

[ERROR] testInsertFilesIntoL0(org.apache.hadoop.hbase.regionserver.TestStripeStoreFileManager)  Time elapsed: 0.015 s  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.hadoop.hbase.io.util.HeapMemorySizeUtil.getLruCacheSize(Lorg/apache/hadoop/conf/Configuration;)J

**Comment by apurtell** [comment]
@busbey Does precommit clean out and reset the jenkins workspace first?

**Comment by petersomogyi** [comment]
The workspace is clean before the job but it looks like ${HOME}.m2 is shared on the host which could cause similar issues.
The current call to yetus test-patch call does not have `--mvn-custom-repo` parameter. Let me create an issue for this.

I've retriggered this execution.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1181 | Docker mode activated. |
||| _ Prechecks _ |
| 0 | findbugs | 0 | Findbugs executables are not available. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 185 | branch-1 passed |
| +1 | compile | 48 | branch-1 passed with JDK v1.8.0_212 |
| +1 | compile | 50 | branch-1 passed with JDK v1.7.0_222 |
| +1 | checkstyle | 94 | branch-1 passed |
| +1 | shadedjars | 188 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 39 | branch-1 passed with JDK v1.8.0_212 |
| +1 | javadoc | 48 | branch-1 passed with JDK v1.7.0_222 |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 129 | the patch passed |
| +1 | compile | 50 | the patch passed with JDK v1.8.0_212 |
| +1 | javac | 50 | the patch passed |
| +1 | compile | 53 | the patch passed with JDK v1.7.0_222 |
| +1 | javac | 53 | the patch passed |
| +1 | checkstyle | 99 | the patch passed |
| +1 | whitespace | 1 | The patch has no whitespace issues. |
| +1 | shadedjars | 216 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 309 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 37 | the patch passed with JDK v1.8.0_212 |
| +1 | javadoc | 48 | the patch passed with JDK v1.7.0_222 |
||| _ Other Tests _ |
| +1 | unit | 9196 | hbase-server in the patch passed. |
| +1 | asflicense | 26 | The patch does not generate ASF License warnings. |
| | | 17070 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/250 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 02d9253aa87b 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-1 / 68a0160 |
| maven | version: Apache Maven 3.0.5 |
| Default Java | 1.7.0_222 |
| Multi-JDK versions |  /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_212 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_222 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/3/testReport/ |
| Max. process+thread count | 4330 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/3/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
Thank you so much for your help @petersomogyi !

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 0 | Docker mode activated. |
| -1 | patch | 7 | https://github.com/apache/hbase/pull/250 does not apply to branch-1. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/250 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-250/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
