### PR TITLE
HBASE-22927 Upgrade Mockito version for jdk11

### PR DESCRIPTION
**Pull request by ravowlga123**
Original PR: https://github.com/apache/hbase/pull/584 Added module-info class in ignore class as suggested in https://github.com/apache/hbase/pull/584#issuecomment-528391822. Creating a new one and hopefully this will pass the test.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 35s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :green_heart: |  mvninstall  |   5m 53s |  master passed  |
| :green_heart: |  compile  |   3m 12s |  master passed  |
| :green_heart: |  shadedjars  |   5m  0s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   2m 49s |  master passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   5m 31s |  the patch passed  |
| :green_heart: |  compile  |   3m 14s |  the patch passed  |
| :green_heart: |  javac  |   3m 14s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| :green_heart: |  shadedjars  |   5m 15s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  17m 39s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   2m 50s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 175m 16s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   0m 31s |  The patch does not generate ASF License warnings.  |
|  |   | 234m 32s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/593 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 2f25d66a39f8 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-593/out/precommit/personality/provided.sh |
| git revision | master / 51b6ce391b |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/1/testReport/ |
| Max. process+thread count | 4422 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
OK, seems good. Only one question, why not just upgrade to 2.28.2?

**Comment by ravowlga123** [comment]
Okay @Apache9 I will update the version to 2.28.2 and run the test.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 44s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :green_heart: |  mvninstall  |   7m  1s |  master passed  |
| :green_heart: |  compile  |   4m  3s |  master passed  |
| :green_heart: |  shadedjars  |   5m 50s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   3m 27s |  master passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   6m 33s |  the patch passed  |
| :green_heart: |  compile  |   3m 50s |  the patch passed  |
| :green_heart: |  javac  |   3m 50s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| :broken_heart: |  shadedjars  |   5m 39s |  patch has 10 errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  19m 49s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   3m 31s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 219m 26s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   0m 43s |  The patch does not generate ASF License warnings.  |
|  |   | 288m 38s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.TestVerifyReplicationCrossDiffHdfs |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/593 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux a975b62a711d 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-593/out/precommit/personality/provided.sh |
| git revision | master / ac8fe1627a |
| Default Java | 1.8.0_181 |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/2/artifact/out/patch-shadedjars.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/2/testReport/ |
| Max. process+thread count | 5659 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Oh, seems 2.28.2 is not good?

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 49s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :green_heart: |  mvninstall  |   7m  4s |  master passed  |
| :green_heart: |  compile  |   3m 51s |  master passed  |
| :green_heart: |  shadedjars  |   5m 41s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   3m 26s |  master passed  |
||| _ Patch Compile Tests _ |
| :green_heart: |  mvninstall  |   6m 12s |  the patch passed  |
| :green_heart: |  compile  |   4m  0s |  the patch passed  |
| :green_heart: |  javac  |   4m  0s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| :broken_heart: |  shadedjars  |   6m  2s |  patch has 10 errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  20m 11s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   3m 31s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 181m 59s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   | 251m  4s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.TestReplicationDroppedTables |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/593 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux b67760cb5248 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-593/out/precommit/personality/provided.sh |
| git revision | master / b20d9b9d0e |
| Default Java | 1.8.0_181 |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/3/artifact/out/patch-shadedjars.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/3/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/3/testReport/ |
| Max. process+thread count | 4713 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
We still need the ignore class when using Mockito 2.28.2

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 47s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 10s |  master passed  |
| :green_heart: |  compile  |   3m  1s |  master passed  |
| :green_heart: |  shadedjars  |   4m 42s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   3m  0s |  master passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 22s |  Maven dependency ordering for patch  |
| :broken_heart: |  mvninstall  |   4m 52s |  root in the patch failed.  |
| :broken_heart: |  compile  |   2m 53s |  root in the patch failed.  |
| :broken_heart: |  javac  |   2m 53s |  root in the patch failed.  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| :broken_heart: |  shadedjars  |   4m 31s |  patch has 10 errors when building our shaded downstream artifacts.  |
| :broken_heart: |  hadoopcheck  |   4m 51s |  The patch causes 10 errors with Hadoop v2.8.5.  |
| :broken_heart: |  hadoopcheck  |   9m 56s |  The patch causes 10 errors with Hadoop v2.9.2.  |
| :broken_heart: |  hadoopcheck  |  15m 10s |  The patch causes 10 errors with Hadoop v3.1.2.  |
| :broken_heart: |  javadoc  |   0m 13s |  hbase-shaded-check-invariants in the patch failed.  |
| :broken_heart: |  javadoc  |   2m 43s |  root in the patch failed.  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 237m 58s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   1m 26s |  The patch does not generate ASF License warnings.  |
|  |   | 288m 56s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/593 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux e3ddd761c737 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-593/out/precommit/personality/provided.sh |
| git revision | master / 1dcc8ee50c |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-compile-root.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-compile-root.txt |
| shadedjars | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-shadedjars.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-javac-2.8.5.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-javac-2.9.2.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-javac-3.1.2.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-javadoc-hbase-shaded_hbase-shaded-check-invariants.txt |
| javadoc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-javadoc-root.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/testReport/ |
| Max. process+thread count | 5475 (vs. ulimit of 10000) |
| modules | C: hbase-shaded/hbase-shaded-check-invariants . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/6/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 25s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 48s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   6m  8s |  master passed  |
| :green_heart: |  compile  |   3m  1s |  master passed  |
| :green_heart: |  shadedjars  |   4m 52s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   3m 15s |  master passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 22s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   5m  7s |  the patch passed  |
| :green_heart: |  compile  |   3m  7s |  the patch passed  |
| :green_heart: |  javac  |   3m  7s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| :green_heart: |  shadedjars  |   4m 31s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  15m 22s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   3m  3s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 213m 12s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   1m 19s |  The patch does not generate ASF License warnings.  |
|  |   | 271m 48s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.snapshot.TestExportSnapshotNoCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/593 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 70f1639321db 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-593/out/precommit/personality/provided.sh |
| git revision | master / 1cb4f687c1 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/7/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/7/testReport/ |
| Max. process+thread count | 5385 (vs. ulimit of 10000) |
| modules | C: hbase-shaded/hbase-shaded-check-invariants . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-593/7/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
