### PR TITLE
HBASE-22702 [Log] 'Group not found for table' is chatty

### PR DESCRIPTION
**Pull request by syedmurtazahassan**
Changed log level to DEBUG level for "Group not found for table".

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 71 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 396 | master passed |
| +1 | compile | 26 | master passed |
| +1 | checkstyle | 13 | master passed |
| +1 | shadedjars | 333 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 21 | master passed |
| 0 | spotbugs | 62 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 60 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 390 | the patch passed |
| +1 | compile | 29 | the patch passed |
| +1 | javac | 29 | the patch passed |
| +1 | checkstyle | 14 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 359 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1292 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 23 | the patch passed |
| +1 | findbugs | 63 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 623 | hbase-rsgroup in the patch passed. |
| +1 | asflicense | 12 | The patch does not generate ASF License warnings. |
| | | 4228 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/406 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 190b22ccc0f2 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-406/out/precommit/personality/provided.sh |
| git revision | master / 2edbf0b85a |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/1/testReport/ |
| Max. process+thread count | 4074 (vs. ulimit of 10000) |
| modules | C: hbase-rsgroup U: hbase-rsgroup |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 50 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 367 | master passed |
| +1 | compile | 26 | master passed |
| +1 | checkstyle | 15 | master passed |
| +1 | shadedjars | 276 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 21 | master passed |
| 0 | spotbugs | 48 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 45 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 285 | the patch passed |
| +1 | compile | 24 | the patch passed |
| +1 | javac | 24 | the patch passed |
| +1 | checkstyle | 13 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 296 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1024 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 19 | the patch passed |
| +1 | findbugs | 49 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 465 | hbase-rsgroup in the patch passed. |
| +1 | asflicense | 12 | The patch does not generate ASF License warnings. |
| | | 3382 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/406 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 74a4f116ced5 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-406/out/precommit/personality/provided.sh |
| git revision | master / a65e72d5da |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/2/testReport/ |
| Max. process+thread count | 4437 (vs. ulimit of 10000) |
| modules | C: hbase-rsgroup U: hbase-rsgroup |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Reidddddd** [comment]
LGTM. Will commit it late this day if no further comment.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 71 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| -1 | mvninstall | 16 | root in master failed. |
| -1 | compile | 30 | hbase-rsgroup in master failed. |
| +1 | checkstyle | 9 | master passed |
| +1 | shadedjars | 270 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 16 | master passed |
| 0 | spotbugs | 308 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| -1 | findbugs | 20 | hbase-rsgroup in master failed. |
||| _ Patch Compile Tests _ |
| -1 | mvninstall | 12 | root in the patch failed. |
| -1 | compile | 20 | hbase-rsgroup in the patch failed. |
| -1 | javac | 20 | hbase-rsgroup in the patch failed. |
| +1 | checkstyle | 10 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 260 | patch has no errors when building our shaded downstream artifacts. |
| -1 | hadoopcheck | 10 | The patch causes 10 errors with Hadoop v2.8.5. |
| -1 | hadoopcheck | 19 | The patch causes 10 errors with Hadoop v2.9.2. |
| -1 | hadoopcheck | 29 | The patch causes 10 errors with Hadoop v3.1.2. |
| +1 | javadoc | 16 | the patch passed |
| -1 | findbugs | 19 | hbase-rsgroup in the patch failed. |
||| _ Other Tests _ |
| -1 | unit | 21 | hbase-rsgroup in the patch failed. |
| +1 | asflicense | 8 | The patch does not generate ASF License warnings. |
| | | 885 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/406 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux c33d66777177 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-406/out/precommit/personality/provided.sh |
| git revision | master / e28afec9ec |
| Default Java | 1.8.0_181 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/branch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/branch-compile-hbase-rsgroup.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/branch-findbugs-hbase-rsgroup.txt |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/patch-compile-hbase-rsgroup.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/patch-compile-hbase-rsgroup.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/patch-javac-2.8.5.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/patch-javac-2.9.2.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/patch-javac-3.1.2.txt |
| findbugs | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/patch-findbugs-hbase-rsgroup.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/artifact/out/patch-unit-hbase-rsgroup.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/testReport/ |
| Max. process+thread count | 88 (vs. ulimit of 10000) |
| modules | C: hbase-rsgroup U: hbase-rsgroup |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 211 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 395 | master passed |
| +1 | compile | 26 | master passed |
| +1 | checkstyle | 14 | master passed |
| +1 | shadedjars | 325 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 24 | master passed |
| 0 | spotbugs | 52 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 51 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 337 | the patch passed |
| +1 | compile | 25 | the patch passed |
| +1 | javac | 25 | the patch passed |
| +1 | checkstyle | 12 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 299 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1040 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2. |
| +1 | javadoc | 19 | the patch passed |
| +1 | findbugs | 50 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 382 | hbase-rsgroup in the patch passed. |
| +1 | asflicense | 12 | The patch does not generate ASF License warnings. |
| | | 3631 | |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/406 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 8610f56023b3 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-406/out/precommit/personality/provided.sh |
| git revision | master / b83d0c035f |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/4/testReport/ |
| Max. process+thread count | 4501 (vs. ulimit of 10000) |
| modules | C: hbase-rsgroup U: hbase-rsgroup |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-406/4/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
