### PR TITLE
HBASE-28684 Remove CellWrapper and use ExtendedCell internally in cli…

### PR DESCRIPTION
**Pull request by Apache9**
…ent side data structure

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 33s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  2s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m  8s |  |  master passed  |
| +1 :green_heart: |  compile  |   2m 51s |  |  master passed  |
| +1 :green_heart: |  javadoc  |   2m  4s |  |  master passed  |
| +1 :green_heart: |  shadedjars  |   5m 47s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 56s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 52s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 52s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m  3s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 46s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 13s |  |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 34s |  |  hbase-client in the patch passed.  |
| -1 :x: |  unit  |  12m 45s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/1/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
| -1 :x: |  unit  |  28m 15s | [/patch-unit-hbase-mapreduce.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/1/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-hbase-mapreduce.txt) |  hbase-mapreduce in the patch failed.  |
| -1 :x: |  unit  | 418m  9s | [/patch-unit-hbase-thrift.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/1/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-hbase-thrift.txt) |  hbase-thrift in the patch failed.  |
| -1 :x: |  unit  |   3m 31s | [/patch-unit-hbase-endpoint.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/1/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-hbase-endpoint.txt) |  hbase-endpoint in the patch failed.  |
| +1 :green_heart: |  unit  |  10m 15s |  |  hbase-backup in the patch passed.  |
|  |   | 508m 38s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/1/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6044 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 38012932f11d 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 578337b9fa26f735ad92696358f8fade02eab7d2 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/1/testReport/ |
| Max. process+thread count | 3725 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-client hbase-server hbase-mapreduce hbase-thrift hbase-endpoint hbase-backup U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/1/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 36s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  |  Patch does not have any anti-patterns.  |
|||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 57s |  |  master passed  |
| +1 :green_heart: |  compile  |   6m 18s |  |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 57s |  |  master passed  |
| +1 :green_heart: |  spotbugs  |   5m  5s |  |  master passed  |
| +1 :green_heart: |  spotless  |   0m 42s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 42s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   6m 14s |  |  the patch passed  |
| -0 :warning: |  javac  |   0m 37s | [/results-compile-javac-hbase-common.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/2/artifact/yetus-general-check/output/results-compile-javac-hbase-common.txt) |  hbase-common generated 1 new + 65 unchanged - 0 fixed = 66 total (was 65)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 12s |  |  hbase-common: The patch generated 0 new + 17 unchanged - 11 fixed = 17 total (was 28)  |
| +1 :green_heart: |  checkstyle  |   0m 15s |  |  hbase-client: The patch generated 0 new + 26 unchanged - 1 fixed = 26 total (was 27)  |
| -0 :warning: |  checkstyle  |   0m 34s | [/results-checkstyle-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/2/artifact/yetus-general-check/output/results-checkstyle-hbase-server.txt) |  hbase-server: The patch generated 2 new + 71 unchanged - 4 fixed = 73 total (was 75)  |
| +1 :green_heart: |  checkstyle  |   0m 11s |  |  hbase-mapreduce: The patch generated 0 new + 18 unchanged - 5 fixed = 18 total (was 23)  |
| +1 :green_heart: |  checkstyle  |   0m 28s |  |  The patch passed checkstyle in hbase-thrift  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  |  The patch passed checkstyle in hbase-endpoint  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  |  The patch passed checkstyle in hbase-backup  |
| -1 :x: |  spotbugs  |   1m 34s | [/new-spotbugs-hbase-server.html](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/2/artifact/yetus-general-check/output/new-spotbugs-hbase-server.html) |  hbase-server generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| +1 :green_heart: |  hadoopcheck  |   5m 16s |  |  Patch does not cause any errors with Hadoop 3.3.6.  |
| +1 :green_heart: |  spotless  |   0m 40s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 55s |  |  The patch does not generate ASF License warnings.  |
|  |   |  49m 33s |  |  |


| Reason | Tests |
|-------:|:------|
| SpotBugs | module:hbase-server |
|  |  instanceof will always return true for all non-null values in org.apache.hadoop.hbase.security.visibility.VisibilityController.preBatchMutate(ObserverContext, MiniBatchOperationInProgress), since all org.apache.hadoop.hbase.ExtendedCell are instances of org.apache.hadoop.hbase.ExtendedCell  At VisibilityController.java:for all non-null values in org.apache.hadoop.hbase.security.visibility.VisibilityController.preBatchMutate(ObserverContext, MiniBatchOperationInProgress), since all org.apache.hadoop.hbase.ExtendedCell are instances of org.apache.hadoop.hbase.ExtendedCell  At VisibilityController.java:[line 306] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6044 |
| Optional Tests | dupname asflicense javac spotbugs checkstyle codespell detsecrets compile hadoopcheck hbaseanti spotless |
| uname | Linux 0c55166fb5cc 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / e7d079152a579b32e4cc9109e49751e702c3349a |
| Default Java | Eclipse Adoptium-17.0.11+9 |
| Max. process+thread count | 85 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-client hbase-server hbase-mapreduce hbase-thrift hbase-endpoint hbase-backup U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/2/console |
| versions | git=2.34.1 maven=3.9.8 spotbugs=4.7.3 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 29s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  |  Patch does not have any anti-patterns.  |
|||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 48s |  |  master passed  |
| +1 :green_heart: |  compile  |   6m  4s |  |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 56s |  |  master passed  |
| +1 :green_heart: |  spotbugs  |   4m 57s |  |  master passed  |
| +1 :green_heart: |  spotless  |   0m 41s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 38s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   6m  0s |  |  the patch passed  |
| -0 :warning: |  javac  |   0m 35s | [/results-compile-javac-hbase-common.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/3/artifact/yetus-general-check/output/results-compile-javac-hbase-common.txt) |  hbase-common generated 1 new + 65 unchanged - 0 fixed = 66 total (was 65)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 12s |  |  hbase-common: The patch generated 0 new + 17 unchanged - 11 fixed = 17 total (was 28)  |
| +1 :green_heart: |  checkstyle  |   0m 14s |  |  hbase-client: The patch generated 0 new + 26 unchanged - 1 fixed = 26 total (was 27)  |
| -0 :warning: |  checkstyle  |   0m 34s | [/results-checkstyle-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/3/artifact/yetus-general-check/output/results-checkstyle-hbase-server.txt) |  hbase-server: The patch generated 2 new + 71 unchanged - 4 fixed = 73 total (was 75)  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  |  hbase-mapreduce: The patch generated 0 new + 18 unchanged - 5 fixed = 18 total (was 23)  |
| +1 :green_heart: |  checkstyle  |   0m 28s |  |  The patch passed checkstyle in hbase-thrift  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  |  The patch passed checkstyle in hbase-endpoint  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  |  The patch passed checkstyle in hbase-backup  |
| +1 :green_heart: |  spotbugs  |   5m 36s |  |  the patch passed  |
| +1 :green_heart: |  hadoopcheck  |   5m  3s |  |  Patch does not cause any errors with Hadoop 3.3.6.  |
| +1 :green_heart: |  spotless  |   0m 39s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 54s |  |  The patch does not generate ASF License warnings.  |
|  |   |  47m 44s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/3/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6044 |
| Optional Tests | dupname asflicense javac spotbugs checkstyle codespell detsecrets compile hadoopcheck hbaseanti spotless |
| uname | Linux 4e8dc2d88cc1 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 9b3c880b4ee40ef1feab9f3eda479bb075a795b4 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
| Max. process+thread count | 86 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-client hbase-server hbase-mapreduce hbase-thrift hbase-endpoint hbase-backup U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/3/console |
| versions | git=2.34.1 maven=3.9.8 spotbugs=4.7.3 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 27s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   2m 55s |  |  master passed  |
| +1 :green_heart: |  compile  |   2m 52s |  |  master passed  |
| +1 :green_heart: |  javadoc  |   2m  3s |  |  master passed  |
| +1 :green_heart: |  shadedjars  |   5m 43s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 58s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 52s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 52s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m  3s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 45s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 17s |  |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 33s |  |  hbase-client in the patch passed.  |
| -1 :x: |  unit  | 219m 36s | [/patch-unit-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/3/artifact/yetus-jdk17-hadoop3-check/output/patch-unit-hbase-server.txt) |  hbase-server in the patch failed.  |
| +1 :green_heart: |  unit  |  17m 51s |  |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   6m 42s |  |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 34s |  |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  unit  |  10m 11s |  |  hbase-backup in the patch passed.  |
|  |   | 296m  3s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/3/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6044 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 8c0789dbbe25 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 9b3c880b4ee40ef1feab9f3eda479bb075a795b4 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/3/testReport/ |
| Max. process+thread count | 5356 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-client hbase-server hbase-mapreduce hbase-thrift hbase-endpoint hbase-backup U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/3/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
TestPassCustomCellViaRegionObserver is added by HBASE-19550, where we allow passing customized Cell implementations in CP, now we do not allow this, so I just remove the test.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 56s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  |  Patch does not have any anti-patterns.  |
|||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  9s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m 38s |  |  master passed  |
| +1 :green_heart: |  compile  |   8m 43s |  |  master passed  |
| +1 :green_heart: |  checkstyle  |   3m  0s |  |  master passed  |
| +1 :green_heart: |  spotbugs  |   7m 15s |  |  master passed  |
| +1 :green_heart: |  spotless  |   1m  3s |  |  branch has no errors when running spotless:check.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 33s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  10m 29s |  |  the patch passed  |
| -0 :warning: |  javac  |   1m 16s | [/results-compile-javac-hbase-common.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/4/artifact/yetus-general-check/output/results-compile-javac-hbase-common.txt) |  hbase-common generated 1 new + 65 unchanged - 0 fixed = 66 total (was 65)  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   0m 22s |  |  hbase-common: The patch generated 0 new + 17 unchanged - 11 fixed = 17 total (was 28)  |
| +1 :green_heart: |  checkstyle  |   0m 25s |  |  hbase-client: The patch generated 0 new + 26 unchanged - 1 fixed = 26 total (was 27)  |
| -0 :warning: |  checkstyle  |   0m 57s | [/results-checkstyle-hbase-server.txt](https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/4/artifact/yetus-general-check/output/results-checkstyle-hbase-server.txt) |  hbase-server: The patch generated 2 new + 71 unchanged - 4 fixed = 73 total (was 75)  |
| +1 :green_heart: |  checkstyle  |   0m 17s |  |  hbase-mapreduce: The patch generated 0 new + 18 unchanged - 5 fixed = 18 total (was 23)  |
| +1 :green_heart: |  checkstyle  |   0m 40s |  |  The patch passed checkstyle in hbase-thrift  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  |  The patch passed checkstyle in hbase-endpoint  |
| +1 :green_heart: |  checkstyle  |   0m 15s |  |  The patch passed checkstyle in hbase-backup  |
| +1 :green_heart: |  spotbugs  |   9m 34s |  |  the patch passed  |
| +1 :green_heart: |  hadoopcheck  |   6m 40s |  |  Patch does not cause any errors with Hadoop 3.3.6.  |
| +1 :green_heart: |  spotless  |   1m  8s |  |  patch has no errors when running spotless:check.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m 34s |  |  The patch does not generate ASF License warnings.  |
|  |   |  73m 14s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.46 ServerAPI=1.46 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/4/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6044 |
| Optional Tests | dupname asflicense javac spotbugs checkstyle codespell detsecrets compile hadoopcheck hbaseanti spotless |
| uname | Linux c551da372639 5.4.0-186-generic #206-Ubuntu SMP Fri Apr 26 12:31:10 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 36ba5cac45c0004d082e39b1bf6e16e4d6112d36 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
| Max. process+thread count | 84 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-client hbase-server hbase-mapreduce hbase-thrift hbase-endpoint hbase-backup U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/4/console |
| versions | git=2.34.1 maven=3.9.8 spotbugs=4.7.3 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 29s |  |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --author-ignore-list --blanks-eol-ignore-file --blanks-tabs-ignore-file --quick-hadoopcheck  |
|||| _ Prechecks _ |
|||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   3m  8s |  |  master passed  |
| +1 :green_heart: |  compile  |   2m 51s |  |  master passed  |
| +1 :green_heart: |  javadoc  |   2m  3s |  |  master passed  |
| +1 :green_heart: |  shadedjars  |   5m 45s |  |  branch has no errors when building our shaded downstream artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m  0s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 54s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 54s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m  2s |  |  the patch passed  |
| +1 :green_heart: |  shadedjars  |   5m 46s |  |  patch has no errors when building our shaded downstream artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 16s |  |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 33s |  |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  | 210m 13s |  |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |  17m 48s |  |  hbase-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   6m 39s |  |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 38s |  |  hbase-endpoint in the patch passed.  |
| +1 :green_heart: |  unit  |  11m  4s |  |  hbase-backup in the patch passed.  |
|  |   | 289m 11s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/4/artifact/yetus-jdk17-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/6044 |
| Optional Tests | javac javadoc unit compile shadedjars |
| uname | Linux 0e367daf16d8 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | master / 36ba5cac45c0004d082e39b1bf6e16e4d6112d36 |
| Default Java | Eclipse Adoptium-17.0.11+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/4/testReport/ |
| Max. process+thread count | 4792 (vs. ulimit of 30000) |
| modules | C: hbase-common hbase-client hbase-server hbase-mapreduce hbase-thrift hbase-endpoint hbase-backup U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-6044/4/console |
| versions | git=2.34.1 maven=3.9.8 |
| Powered by | Apache Yetus 0.15.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
