### PR TITLE
HBASE-23664 Upgrade JUnit to 4.13

### PR DESCRIPTION
**Pull request by ndimiduk**

### CODE REVIEW

**Comment by bharathv** [comment]
Nice.. thanks for the quick patch. If this goes in, I can attempt the Before/AfterParam stuff.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 38s |  master passed  |
| +1 :green_heart: |  compile  |   3m 11s |  master passed  |
| +1 :green_heart: |  shadedjars  |   4m 43s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   3m  3s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 17s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  9s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m  9s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  shadedjars  |   4m 57s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  18m 35s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  javadoc  |   3m 10s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 201m 50s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 40s |  The patch does not generate ASF License warnings.  |
|  |   | 262m 35s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.replication.TestReplicationSmallTests |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1004/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1004 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 853c78b8223a 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1004/out/precommit/personality/provided.sh |
| git revision | master / 66d1258aa3 |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1004/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1004/1/testReport/ |
| Max. process+thread count | 4902 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1004/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
Build failed with the same failure to read xml that we've been seeing. Detailed summary:

```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] org.apache.hadoop.hbase.replication.TestReplicationSmallTests.null
[ERROR]   Run 1: TestReplicationSmallTests.setUp:93->TestReplicationBase.cleanUp:108 Â» TestTimedOut
[ERROR]   Run 2: TestReplicationSmallTests Â»  Appears to be stuck in thread Socket Reader #1 fo...
[ERROR]   Run 3: TestReplicationSmallTests>TestReplicationBase.setUpBeforeClass:256->TestReplicationBase.startClusters:219 Â» IO
[INFO] 
[ERROR]   TestReplicationSmallTests.setUp:93->TestReplicationBase.cleanUp:108 Â» RetriesExhausted
[ERROR]   TestReplicationSmallTests.setUp:93->TestReplicationBase.cleanUp:108 Â» RetriesExhausted
[ERROR]   TestReplicationSmallTests.setUp:93->TestReplicationBase.cleanUp:108 Â» RetriesExhausted
[ERROR]   TestReplicationSmallTests.setUp:93->TestReplicationBase.cleanUp:108 Â» RetriesExhausted
[ERROR]   TestReplicationSmallTests.setUp:93->TestReplicationBase.cleanUp:108 Â» RetriesExhausted
[ERROR]   TestReplicationSmallTests.setUp:93->TestReplicationBase.cleanUp:108 Â» RetriesExhausted
[WARNING] Flakes: 
[WARNING] org.apache.hadoop.hbase.replication.TestReplicationSmallTests.testDeleteTypes[1: serialPeer=false]
[ERROR]   Run 1: TestReplicationSmallTests.setUp:93->TestReplicationBase.cleanUp:108 Â» InterruptedIO
[INFO]   Run 2: PASS
[INFO] 
[INFO] 
[ERROR] Tests run: 4329, Failures: 0, Errors: 7, Skipped: 28, Flakes: 1
```

**Comment by ndimiduk** [comment]
How far back should we take this patch? All the way to branch-1?

**Comment by bharathv** [comment]
> How far back should we take this patch? All the way to branch-1?

Yes please, I'm planning to back port the registry changes to branch-1 and I might need this.

**Pull request merged**
