### PR TITLE
HBASE-23045.currentPath may be stitched in a loop in replication source code.

### PR DESCRIPTION
**Pull request by Gkkkk302**
…ce code.

### CODE REVIEW

**Comment by virajjasani** [comment]
@Gkkkk302 Thanks for the PR, changes look good, please incorporate Unit Test for this fix.

**Comment by virajjasani** [comment]
This seems applicable to all active branch-1s only and not to branch-2+

**Comment by virajjasani** [comment]
Can you please also confirm @Gkkkk302 ?

**Comment by Gkkkk302** [comment]
Yes, I agree. I will try to provide unit tests next. Thank you @virajjasani

**Comment by virajjasani** [comment]
Thanks for the fix @Gkkkk302 
Could you please also validate branch-1 patch to ensure if we can get this fix to branch-1 since it's good to have this fixed as part of 1.6 release.
Thanks

branch-1 patch:

```
diff --git a/hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java b/hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java
index 5acb70922f..a26bbd00cd 100644
--- a/hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java
+++ b/hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java
@@ -938,8 +938,9 @@ public class ReplicationSource extends Thread implements ReplicationSourceInterf
         Path p = rs.getPath();
         FileStatus[] logs = fs.listStatus(p);
         for (FileStatus log : logs) {
-          p = new Path(p, log.getPath().getName());
-          if (p.getName().equals(path.getName())) {
+          String logName = log.getPath().getName();
+          if (logName.equals(path.getName())) {
+            p = new Path(p, log.getPath().getName());
             LOG.info("Log " + p.getName() + " found at " + p);
             return p;
           }
```

**Pull request merged**
