### PR TITLE
HBASE-11262

### PR DESCRIPTION
**Pull request by ashubhumca**
In bulk import, it just stores everything in the table but some times we want to avoid empty column values to save some disk space. So, this code snippet to skip those empty columns values while bulk load based on the user's choice. By default, this feature will be disabled. User has to set SKIP_EMPTY_COLUMNS true to use this.

### CODE REVIEW

**Comment by tedyu** [comment]
HBase infra hasn't switched to accommodating pull request.

Review board is currently used.

Patch looks good.

**Comment by ashubhumca** [comment]
Thanks for the acknowledgement. Please let me know if I've to do something else in order to add this patch.

**Comment by busbey** [comment]
yes, please attach your patch to the jira for HBASE-11262 and close this PR.

**Comment by ashubhumca** [comment]
Closing this PR as patch has already been added via jira.

**Pull request closed without merging**
