### PR TITLE
check bounds when removeRegion

### PR DESCRIPTION
**Pull request by casuallc**

### CODE REVIEW

**Comment by Reidddddd** [comment]
Did you file a JIRA ticket? If not, please do that first.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 66 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.0 Compile Tests _ |
| +1 | mvninstall | 184 | branch-2.0 passed |
| +1 | compile | 52 | branch-2.0 passed |
| +1 | checkstyle | 78 | branch-2.0 passed |
| +1 | shadedjars | 254 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 30 | branch-2.0 passed |
| 0 | spotbugs | 162 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 159 | branch-2.0 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 168 | the patch passed |
| +1 | compile | 48 | the patch passed |
| +1 | javac | 48 | the patch passed |
| -1 | checkstyle | 72 | hbase-server: The patch generated 1 new + 60 unchanged - 0 fixed = 61 total (was 60) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 244 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 898 | Patch does not cause any errors with Hadoop 2.6.5 2.7.7 2.8.5 or 3.0.3 3.1.2. |
| +1 | javadoc | 31 | the patch passed |
| +1 | findbugs | 171 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 12199 | hbase-server in the patch failed. |
| +1 | asflicense | 24 | The patch does not generate ASF License warnings. |
| | | 14945 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplica |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaLargeCluster |
|   | hadoop.hbase.coprocessor.TestMetaTableMetrics |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerLargeCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaWithRacks |
|   | hadoop.hbase.TestRegionRebalancing |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerBalanceCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaHighReplication |
|   | hadoop.hbase.replication.regionserver.TestRegionReplicaReplicationEndpoint |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerSmallCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaReplicationGreaterThanNumNodes |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerMidCluster |
|   | hadoop.hbase.coprocessor.TestMasterObserver |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaMidCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaSameHosts |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/409 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux f0275520f6ff 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-409/out/precommit/personality/provided.sh |
| git revision | branch-2.0 / 1c4134e9ea |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/1/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/1/testReport/ |
| Max. process+thread count | 4604 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.0-RC3 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 64 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.0 Compile Tests _ |
| +1 | mvninstall | 190 | branch-2.0 passed |
| +1 | compile | 52 | branch-2.0 passed |
| +1 | checkstyle | 75 | branch-2.0 passed |
| +1 | shadedjars | 252 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 34 | branch-2.0 passed |
| 0 | spotbugs | 173 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 171 | branch-2.0 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 184 | the patch passed |
| +1 | compile | 52 | the patch passed |
| +1 | javac | 52 | the patch passed |
| -1 | checkstyle | 73 | hbase-server: The patch generated 1 new + 60 unchanged - 0 fixed = 61 total (was 60) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 254 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 904 | Patch does not cause any errors with Hadoop 2.6.5 2.7.7 2.8.5 or 3.0.3 3.1.2. |
| +1 | javadoc | 33 | the patch passed |
| +1 | findbugs | 175 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 9989 | hbase-server in the patch failed. |
| +1 | asflicense | 29 | The patch does not generate ASF License warnings. |
| | | 12804 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.balancer.TestStochasticLoadBalancerLargeCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaMidCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaLargeCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplica |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaHighReplication |
|   | hadoop.hbase.TestRegionRebalancing |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerMidCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaSameHosts |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaWithRacks |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancer |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaReplicationGreaterThanNumNodes |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerSmallCluster |
|   | hadoop.hbase.coprocessor.TestMasterObserver |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerBalanceCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/409 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux bf2cd9e13c5f 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-409/out/precommit/personality/provided.sh |
| git revision | branch-2.0 / e3e1c3fad6 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/2/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/2/testReport/ |
| Max. process+thread count | 4307 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.0-RC3 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 76 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ branch-2.0 Compile Tests _ |
| +1 | mvninstall | 302 | branch-2.0 passed |
| +1 | compile | 73 | branch-2.0 passed |
| +1 | checkstyle | 97 | branch-2.0 passed |
| +1 | shadedjars | 329 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 45 | branch-2.0 passed |
| 0 | spotbugs | 233 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 228 | branch-2.0 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 253 | the patch passed |
| +1 | compile | 71 | the patch passed |
| +1 | javac | 71 | the patch passed |
| -1 | checkstyle | 99 | hbase-server: The patch generated 1 new + 60 unchanged - 0 fixed = 61 total (was 60) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 335 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 1238 | Patch does not cause any errors with Hadoop 2.6.5 2.7.7 2.8.5 or 3.0.3 3.1.2. |
| +1 | javadoc | 41 | the patch passed |
| +1 | findbugs | 222 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 13627 | hbase-server in the patch failed. |
| +1 | asflicense | 50 | The patch does not generate ASF License warnings. |
| | | 17440 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaLargeCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerMidCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaWithRacks |
|   | hadoop.hbase.coprocessor.TestMasterObserver |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancer |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerSmallCluster |
|   | hadoop.hbase.master.procedure.TestProcedurePriority |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerBalanceCluster |
|   | hadoop.hbase.TestRegionRebalancing |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplica |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerLargeCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaHighReplication |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaReplicationGreaterThanNumNodes |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaSameHosts |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaMidCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/409 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 1f705f54b7e1 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-409/out/precommit/personality/provided.sh |
| git revision | branch-2.0 / dc9017aa49 |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/3/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/3/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/3/testReport/ |
| Max. process+thread count | 4623 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-409/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.0-RC3 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
