### PR TITLE
HBASE-22231 Removed unused and '*' import

### PR DESCRIPTION
**Pull request by HorizonNet**
Targeted for **branch-2.1**.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 48 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 77 new or modified test files. |
||| _ branch-2.1 Compile Tests _ |
| 0 | mvndep | 9 | Maven dependency ordering for branch |
| +1 | mvninstall | 230 | branch-2.1 passed |
| +1 | compile | 185 | branch-2.1 passed |
| +1 | checkstyle | 177 | branch-2.1 passed |
| +1 | shadedjars | 232 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 339 | branch-2.1 passed |
| +1 | javadoc | 129 | branch-2.1 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for patch |
| +1 | mvninstall | 233 | the patch passed |
| +1 | compile | 185 | the patch passed |
| +1 | javac | 185 | the patch passed |
| +1 | checkstyle | 22 | hbase-common: The patch generated 0 new + 11 unchanged - 3 fixed = 11 total (was 14) |
| -1 | checkstyle | 31 | hbase-client: The patch generated 2 new + 214 unchanged - 19 fixed = 216 total (was 233) |
| +1 | checkstyle | 12 | hbase-procedure: The patch generated 0 new + 1 unchanged - 7 fixed = 1 total (was 8) |
| -1 | checkstyle | 71 | hbase-server: The patch generated 4 new + 300 unchanged - 113 fixed = 304 total (was 413) |
| +1 | checkstyle | 18 | hbase-mapreduce: The patch generated 0 new + 91 unchanged - 12 fixed = 91 total (was 103) |
| -1 | checkstyle | 14 | hbase-it: The patch generated 1 new + 90 unchanged - 7 fixed = 91 total (was 97) |
| +1 | checkstyle | 15 | hbase-rest: The patch generated 0 new + 15 unchanged - 3 fixed = 15 total (was 18) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 230 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 473 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 389 | the patch passed |
| +1 | javadoc | 136 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 158 | hbase-common in the patch passed. |
| +1 | unit | 193 | hbase-client in the patch passed. |
| +1 | unit | 211 | hbase-procedure in the patch passed. |
| -1 | unit | 16993 | hbase-server in the patch failed. |
| +1 | unit | 1592 | hbase-mapreduce in the patch passed. |
| +1 | unit | 84 | hbase-it in the patch passed. |
| +1 | unit | 429 | hbase-rest in the patch passed. |
| +1 | asflicense | 232 | The patch does not generate ASF License warnings. |
| | | 23252 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.quotas.TestSpaceQuotas |
|   | hadoop.hbase.replication.TestReplicationKillSlaveRS |
|   | hadoop.hbase.client.replication.TestReplicationAdminWithClusters |
|   | hadoop.hbase.replication.TestReplicationDisableInactivePeer |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.replication.TestSerialReplication |
|   | hadoop.hbase.replication.TestNamespaceReplication |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleAsyncWAL |
|   | hadoop.hbase.regionserver.TestMutateRowsRecovery |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/179 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 0fa9f15e9753 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-2.1 / 8207886d07 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/1/artifact/out/diff-checkstyle-hbase-client.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/1/artifact/out/diff-checkstyle-hbase-server.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/1/artifact/out/diff-checkstyle-hbase-it.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/1/testReport/ |
| Max. process+thread count | 5764 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-client hbase-procedure hbase-server hbase-mapreduce hbase-it hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 169 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 77 new or modified test files. |
||| _ branch-2.1 Compile Tests _ |
| 0 | mvndep | 8 | Maven dependency ordering for branch |
| +1 | mvninstall | 220 | branch-2.1 passed |
| +1 | compile | 169 | branch-2.1 passed |
| +1 | checkstyle | 178 | branch-2.1 passed |
| +1 | shadedjars | 227 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 300 | branch-2.1 passed |
| +1 | javadoc | 125 | branch-2.1 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 10 | Maven dependency ordering for patch |
| +1 | mvninstall | 211 | the patch passed |
| +1 | compile | 178 | the patch passed |
| +1 | javac | 178 | the patch passed |
| +1 | checkstyle | 21 | hbase-common: The patch generated 0 new + 11 unchanged - 3 fixed = 11 total (was 14) |
| +1 | checkstyle | 31 | hbase-client: The patch generated 0 new + 213 unchanged - 20 fixed = 213 total (was 233) |
| +1 | checkstyle | 13 | hbase-procedure: The patch generated 0 new + 1 unchanged - 7 fixed = 1 total (was 8) |
| +1 | checkstyle | 63 | hbase-server: The patch generated 0 new + 297 unchanged - 116 fixed = 297 total (was 413) |
| +1 | checkstyle | 18 | hbase-mapreduce: The patch generated 0 new + 91 unchanged - 12 fixed = 91 total (was 103) |
| +1 | checkstyle | 15 | hbase-it: The patch generated 0 new + 88 unchanged - 9 fixed = 88 total (was 97) |
| +1 | checkstyle | 14 | hbase-rest: The patch generated 0 new + 15 unchanged - 3 fixed = 15 total (was 18) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 228 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 446 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 340 | the patch passed |
| +1 | javadoc | 127 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 160 | hbase-common in the patch passed. |
| +1 | unit | 196 | hbase-client in the patch passed. |
| +1 | unit | 201 | hbase-procedure in the patch passed. |
| -1 | unit | 15607 | hbase-server in the patch failed. |
| +1 | unit | 1548 | hbase-mapreduce in the patch passed. |
| +1 | unit | 78 | hbase-it in the patch passed. |
| +1 | unit | 329 | hbase-rest in the patch passed. |
| +1 | asflicense | 254 | The patch does not generate ASF License warnings. |
| | | 21661 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAsyncTableRegionReplicasGet |
|   | hadoop.hbase.TestIOFencing |
|   | hadoop.hbase.master.procedure.TestProcedureAdmin |
|   | hadoop.hbase.client.TestAsyncTableGetMultiThreaded |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaLargeCluster |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaSameHosts |
|   | hadoop.hbase.coprocessor.TestMetaTableMetrics |
|   | hadoop.hbase.client.TestAsyncTableRegionReplicasScan |
|   | hadoop.hbase.master.procedure.TestProcedurePriority |
|   | hadoop.hbase.master.balancer.TestStochasticLoadBalancerRegionReplicaHighReplication |
|   | hadoop.hbase.replication.regionserver.TestWALEntryStream |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/179 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 5500ca2e14f9 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-2.1 / 16cc2a3dfd |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/2/testReport/ |
| Max. process+thread count | 4346 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-client hbase-procedure hbase-server hbase-mapreduce hbase-it hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
Would like to re-run the build before merging it. @petersomogyi Do you know how to retrigger the build? Didn't find that option in Jenkins.

**Comment by petersomogyi** [comment]
Probably the failures are unrelated, but triggered a new build now: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/3

**Comment by HorizonNet** [comment]
Thanks @petersomogyi. Finally found it in Jenkins.

**Comment by saintstack** [comment]
How do you do it @HorizonNet ?

**Comment by Apache9** [comment]
Seems the HDDS project has a magic word to re-trigger a test. It is '/retest'...

**Comment by saintstack** [comment]
Thanks @Apache9

**Comment by HorizonNet** [comment]
I also know projects where you can do "Jenkins, test this please". For now I just logged into Jenkins, went to the appropriate job and clicked on "Rebuild".

**Comment by petersomogyi** [comment]
The previous build link I posted failed. I added the HBASE ID when triggered the build and the job tried to download patch file from Jira. Retriggered it again without specifying HBASE-22231: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/4

> Seems the HDDS project has a magic word to re-trigger a test. It is '/retest'...

On hbase-connectors and hbase-operator-tools precommits we have a 'retest build' magic string for which the jenkins reruns the verification. I don't know if it is possible to enable similar this setup.

**Comment by Apache9** [comment]
> On hbase-connectors and hbase-operator-tools precommits we have a 'retest build' magic string for which the jenkins reruns the verification.

How do you do this? I think we can do the same for the main hbase repo.

**Comment by petersomogyi** [comment]
[Check the job settings](https://builds.apache.org/job/PreCommit-HBASE-OPERATOR-TOOLS-Build/configure), Build Triggers > Use github hooks for build triggering (Advanced) > Trigger phrase

**Comment by Apache9** [comment]
Oh, the jenkins job for HBase is more complicated, we use yetus and it is a multibranch pipeline job... The config of the sub jobs is auto generated by the jenkins file...

Let me see how to add the option in jenkins file...

**Comment by Apache9** [comment]
OK, seems the '/retest' on HDDS project is a fake one, they just updated the PR and triggered a new pre commit build...

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 54 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 77 new or modified test files. |
||| _ branch-2.1 Compile Tests _ |
| 0 | mvndep | 8 | Maven dependency ordering for branch |
| +1 | mvninstall | 260 | branch-2.1 passed |
| +1 | compile | 193 | branch-2.1 passed |
| +1 | checkstyle | 193 | branch-2.1 passed |
| +1 | shadedjars | 246 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 333 | branch-2.1 passed |
| +1 | javadoc | 131 | branch-2.1 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 13 | Maven dependency ordering for patch |
| +1 | mvninstall | 231 | the patch passed |
| +1 | compile | 194 | the patch passed |
| +1 | javac | 194 | the patch passed |
| +1 | checkstyle | 22 | hbase-common: The patch generated 0 new + 11 unchanged - 3 fixed = 11 total (was 14) |
| +1 | checkstyle | 32 | hbase-client: The patch generated 0 new + 213 unchanged - 20 fixed = 213 total (was 233) |
| +1 | checkstyle | 13 | hbase-procedure: The patch generated 0 new + 1 unchanged - 7 fixed = 1 total (was 8) |
| +1 | checkstyle | 70 | hbase-server: The patch generated 0 new + 297 unchanged - 116 fixed = 297 total (was 413) |
| +1 | checkstyle | 17 | hbase-mapreduce: The patch generated 0 new + 91 unchanged - 12 fixed = 91 total (was 103) |
| +1 | checkstyle | 15 | hbase-it: The patch generated 0 new + 88 unchanged - 9 fixed = 88 total (was 97) |
| +1 | checkstyle | 13 | hbase-rest: The patch generated 0 new + 15 unchanged - 3 fixed = 15 total (was 18) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 242 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 496 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 383 | the patch passed |
| +1 | javadoc | 128 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 160 | hbase-common in the patch passed. |
| +1 | unit | 203 | hbase-client in the patch passed. |
| +1 | unit | 212 | hbase-procedure in the patch passed. |
| -1 | unit | 13342 | hbase-server in the patch failed. |
| +1 | unit | 1304 | hbase-mapreduce in the patch passed. |
| +1 | unit | 66 | hbase-it in the patch passed. |
| +1 | unit | 408 | hbase-rest in the patch passed. |
| +1 | asflicense | 219 | The patch does not generate ASF License warnings. |
| | | 19357 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAdmin1 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/179 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 9b09bda47051 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | branch-2.1 / d83a23e7d2 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/4/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/4/testReport/ |
| Max. process+thread count | 4883 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-client hbase-procedure hbase-server hbase-mapreduce hbase-it hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-179/4/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by petersomogyi** [comment]
+1, test failure is unrelated.

**Pull request merged**
