### PR TITLE
HBASE-22827 Expose multi-region merge in shell and Admin API (branch-2.1)

### PR DESCRIPTION
**Pull request by jatsakthi**
(cherry picked from commit c4a03c14ecc50604f44cf3b97ffdc40eddda70fd)

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 47s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-2.1 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   6m 39s |  branch-2.1 passed  |
| +1 :green_heart: |  compile  |   1m  0s |  branch-2.1 passed  |
| +1 :green_heart: |  checkstyle  |   1m  4s |  branch-2.1 passed  |
| +1 :green_heart: |  shadedjars  |   5m 14s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 43s |  branch-2.1 passed  |
| +0 :ok: |  spotbugs  |   1m 30s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 26s |  branch-2.1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 53s |  the patch passed  |
| +1 :green_heart: |  rubocop  |   0m 11s |  There were no new rubocop issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m  9s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  21m 41s |  Patch does not cause any errors with Hadoop 2.7.7 2.8.5 or 3.0.3 3.1.2.  |
| +1 :green_heart: |  javadoc  |   0m 39s |  the patch passed  |
| +1 :green_heart: |  findbugs  |   1m 19s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m 36s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 14s |  hbase-shell in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 25s |  The patch does not generate ASF License warnings.  |
|  |   |  71m 21s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1218/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1218 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile rubocop |
| uname | Linux 7d6cc43e718c 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1218/out/precommit/personality/provided.sh |
| git revision | branch-2.1 / e15525fcec |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1218/1/testReport/ |
| Max. process+thread count | 2543 (vs. ulimit of 10000) |
| modules | C: hbase-client hbase-shell U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1218/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 rubocop=0.80.0 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by jatsakthi** [comment]
Tested merging multiple regions from a local HBase jar.

**Comment by jatsakthi** [comment]
Any chance of a review over here @busbey ?

**Comment by jatsakthi** [comment]
Thanks for the review, @virajjasani

**Pull request merged**
