### PR TITLE
HBASE-24640 [branch-1] Purge use of VisibleForTesting

### PR DESCRIPTION
**Pull request by apurtell**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 22s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  0s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   2m 23s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   2m 46s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   5m  0s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  1s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 11s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m 34s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   2m 44s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   7m 47s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 19s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   2m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 40s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 44s |  hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 2 new + 4 unchanged - 2 fixed = 6 total (was 6)  |
| -1 :x: |  checkstyle  |   0m 35s |  hbase-common: The patch generated 3 new + 335 unchanged - 10 fixed = 338 total (was 345)  |
| -1 :x: |  checkstyle  |   0m 14s |  hbase-procedure: The patch generated 1 new + 20 unchanged - 1 fixed = 21 total (was 21)  |
| -1 :x: |  checkstyle  |   0m 45s |  hbase-client: The patch generated 5 new + 491 unchanged - 16 fixed = 496 total (was 507)  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  hbase-metrics-api: The patch generated 0 new + 1 unchanged - 1 fixed = 1 total (was 2)  |
| -1 :x: |  checkstyle  |   0m 15s |  hbase-hadoop2-compat: The patch generated 1 new + 7 unchanged - 4 fixed = 8 total (was 11)  |
| -1 :x: |  checkstyle  |   2m 24s |  hbase-server: The patch generated 28 new + 2413 unchanged - 83 fixed = 2441 total (was 2496)  |
| +1 :green_heart: |  checkstyle  |   0m 17s |  The patch passed checkstyle in hbase-rsgroup  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 56s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 34s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   2m  5s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m 34s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  findbugs  |   8m 47s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 47s |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 57s |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 42s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 16s |  hbase-metrics-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 37s |  hbase-hadoop2-compat in the patch passed.  |
| +1 :green_heart: |  unit  |  98m 28s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |  12m 21s |  hbase-rsgroup in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 27s |  The patch does not generate ASF License warnings.  |
|  |   | 199m 51s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2697 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux c6d2c53bf241 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2697/out/precommit/personality/provided.sh |
| git revision | branch-1 / edccfe4 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/artifact/out/diff-compile-javac-hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/artifact/out/diff-checkstyle-hbase-common.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/artifact/out/diff-checkstyle-hbase-procedure.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/artifact/out/diff-checkstyle-hbase-client.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/artifact/out/diff-checkstyle-hbase-hadoop2-compat.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/artifact/out/diff-checkstyle-hbase-server.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/testReport/ |
| Max. process+thread count | 3423 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-procedure hbase-client hbase-metrics-api hbase-hadoop2-compat hbase-server hbase-rsgroup U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by Reidddddd — APPROVED** [review]
Skimmed, LGTM, +1.
It would be good if we can fix the reported checkstyle, thought I believe most of them are legacies.

**Comment by Reidddddd** [comment]
I just merged https://github.com/apache/hbase/pull/2658, it probably introduced one conflict with this PR.

**Comment by apurtell** [comment]
@Reidddddd Will rebase. 
I can also make a pass over these checkstyle warns. Was expecting some legacy issues to turn up.

**Comment by apurtell** [comment]
Rebased.
Pushed checkstyle fixes.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 22s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 24s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 55s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   2m 24s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   2m 51s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   5m 21s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  3s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 18s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m 43s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   2m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   7m 46s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   1m  8s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 26s |  hbase-server in the patch failed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| -1 :x: |  javac  |   0m 26s |  hbase-server in the patch failed with JDK Azul Systems, Inc.-1.8.0_262-b19.  |
| -1 :x: |  compile  |   0m 30s |  hbase-server in the patch failed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| -1 :x: |  javac  |   0m 30s |  hbase-server in the patch failed with JDK Azul Systems, Inc.-1.7.0_272-b10.  |
| +1 :green_heart: |  checkstyle  |   0m 33s |  hbase-common: The patch generated 0 new + 335 unchanged - 10 fixed = 335 total (was 345)  |
| -1 :x: |  checkstyle  |   0m 15s |  hbase-procedure: The patch generated 1 new + 20 unchanged - 1 fixed = 21 total (was 21)  |
| +1 :green_heart: |  checkstyle  |   0m 44s |  hbase-client: The patch generated 0 new + 491 unchanged - 16 fixed = 491 total (was 507)  |
| +1 :green_heart: |  checkstyle  |   0m 12s |  hbase-metrics-api: The patch generated 0 new + 1 unchanged - 1 fixed = 1 total (was 2)  |
| +1 :green_heart: |  checkstyle  |   0m 14s |  hbase-hadoop2-compat: The patch generated 0 new + 7 unchanged - 4 fixed = 7 total (was 11)  |
| -1 :x: |  checkstyle  |   2m 22s |  hbase-server: The patch generated 7 new + 2413 unchanged - 96 fixed = 2420 total (was 2509)  |
| +1 :green_heart: |  checkstyle  |   0m 16s |  The patch passed checkstyle in hbase-rsgroup  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  shadedjars  |   1m 45s |  patch has 16 errors when building our shaded downstream artifacts.  |
| -1 :x: |  hadoopcheck  |   1m  0s |  The patch causes 16 errors with Hadoop v2.8.5.  |
| -1 :x: |  hadoopcheck  |   2m 43s |  The patch causes 16 errors with Hadoop v2.9.2.  |
| -1 :x: |  javadoc  |   0m 29s |  hbase-server-jdkAzulSystems,Inc.-1.8.0_262-b19 with JDK Azul Systems, Inc.-1.8.0_262-b19 generated 1 new + 8 unchanged - 0 fixed = 9 total (was 8)  |
| -1 :x: |  javadoc  |   0m 40s |  hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 1 new + 8 unchanged - 0 fixed = 9 total (was 8)  |
| -1 :x: |  findbugs  |   0m 29s |  hbase-server in the patch failed.  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 44s |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 21s |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  |   3m  9s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 21s |  hbase-metrics-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  hbase-hadoop2-compat in the patch passed.  |
| -1 :x: |  unit  |   0m 41s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  unit  |  15m 47s |  hbase-rsgroup in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 27s |  The patch does not generate ASF License warnings.  |
|  |   |  97m 28s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2697 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux b405acddfc8c 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2697/out/precommit/personality/provided.sh |
| git revision | branch-1 / 4640b22 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-compile-hbase-server-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-compile-hbase-server-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-compile-hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-compile-hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/diff-checkstyle-hbase-procedure.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/diff-checkstyle-hbase-server.txt |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-shadedjars.txt |
| hadoopcheck | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-javac-2.8.5.txt |
| hadoopcheck | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-javac-2.9.2.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/diff-javadoc-javadoc-hbase-server-jdkAzulSystems,Inc.-1.8.0_262-b19.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/diff-javadoc-javadoc-hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| findbugs | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-findbugs-hbase-server.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/testReport/ |
| Max. process+thread count | 1611 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-procedure hbase-client hbase-metrics-api hbase-hadoop2-compat hbase-server hbase-rsgroup U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ndimiduk — APPROVED** [review]
+1 from me as well; I don't think we should block this improvement with the check style issues.

**Comment by apurtell** [comment]
Let me make another pass to fix up checkstyle and insure VisibleForTesting is really gone. In one precommit it seems to have come back somewhere.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  3s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 56s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   2m 27s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  compile  |   2m 50s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  checkstyle  |   5m 25s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m  3s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 21s |  branch-1 passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m 42s |  branch-1 passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +0 :ok: |  spotbugs  |   2m 47s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   7m 54s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 54s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 29s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javac  |   2m 29s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 50s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| -1 :x: |  javac  |   0m 45s |  hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10 with JDK Azul Systems, Inc.-1.7.0_272-b10 generated 2 new + 4 unchanged - 2 fixed = 6 total (was 6)  |
| +1 :green_heart: |  checkstyle  |   0m 39s |  hbase-common: The patch generated 0 new + 335 unchanged - 10 fixed = 335 total (was 345)  |
| +1 :green_heart: |  checkstyle  |   0m 18s |  hbase-procedure: The patch generated 0 new + 20 unchanged - 1 fixed = 20 total (was 21)  |
| +1 :green_heart: |  checkstyle  |   0m 47s |  hbase-client: The patch generated 0 new + 491 unchanged - 16 fixed = 491 total (was 507)  |
| +1 :green_heart: |  checkstyle  |   0m 14s |  hbase-metrics-api: The patch generated 0 new + 1 unchanged - 1 fixed = 1 total (was 2)  |
| +1 :green_heart: |  checkstyle  |   0m 17s |  hbase-hadoop2-compat: The patch generated 0 new + 7 unchanged - 4 fixed = 7 total (was 11)  |
| -1 :x: |  checkstyle  |   2m 37s |  hbase-server: The patch generated 2 new + 2417 unchanged - 92 fixed = 2419 total (was 2509)  |
| +1 :green_heart: |  checkstyle  |   0m 19s |  The patch passed checkstyle in hbase-rsgroup  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   2m 51s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 43s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   2m  8s |  the patch passed with JDK Azul Systems, Inc.-1.8.0_262-b19  |
| +1 :green_heart: |  javadoc  |   2m 40s |  the patch passed with JDK Azul Systems, Inc.-1.7.0_272-b10  |
| +1 :green_heart: |  findbugs  |   9m  2s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 52s |  hbase-common in the patch passed.  |
| +1 :green_heart: |  unit  |   4m  4s |  hbase-procedure in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 43s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 18s |  hbase-metrics-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 39s |  hbase-hadoop2-compat in the patch passed.  |
| +1 :green_heart: |  unit  |  90m 35s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |  13m 55s |  hbase-rsgroup in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 33s |  The patch does not generate ASF License warnings.  |
|  |   | 195m 39s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/2697 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 753df3773eb7 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-home/workspace/Base-PreCommit-GitHub-PR_PR-2697/out/precommit/personality/provided.sh |
| git revision | branch-1 / 4640b22 |
| Default Java | Azul Systems, Inc.-1.7.0_272-b10 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:Azul Systems, Inc.-1.8.0_262-b19 /usr/lib/jvm/zulu-7-amd64:Azul Systems, Inc.-1.7.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/3/artifact/out/diff-compile-javac-hbase-server-jdkAzulSystems,Inc.-1.7.0_272-b10.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/3/artifact/out/diff-checkstyle-hbase-server.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/3/testReport/ |
| Max. process+thread count | 3128 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-procedure hbase-client hbase-metrics-api hbase-hadoop2-compat hbase-server hbase-rsgroup U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-2697/3/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
