### PR TITLE
HBASE-22724 Add a emoji on the vote table for pre commit result on gi…

### PR DESCRIPTION
**Pull request by Apache9**
…thub

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 38s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/1/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
Interesting. It can't get far enough to load the new personality.

Do we no longer need `skip-dir`? I haven't looked that one up to see why it's gone now.

**Comment by Apache9** [comment]
It should be skip-dirs and I tried to remove it when testing on the branch HBASE-22724 and nothing went wrong, so...

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 35s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/2/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
I think it'll only go wrong if there's a change to dev-support and a change to some Java file. Basically we'll do unit tests for the whole project instead of just the one that changed.

**Comment by Apache9** [comment]
https://github.com/apache/hbase/pull/535

Here I just modified a file under the dev-support directory and the pre commit was fine.

So I do not think this is a big deal? We do not use this in the past, it is copied from the Jenkins file in hadoop.

So if no other concerns, let’s merge this to master and try it first? If it is fine, then cherry pick to other branches.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 57s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/3/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by busbey** [comment]
No, that doesn't test the issue. To get the conditions I'm talking about you need a file under dev-support and a Java file in a small module. e.g. hbase-endpoint.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 36s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/4/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 40s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  5s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/5/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
OK, let me try a new PR on HBASE-22724 branch.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   2m 13s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  5s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.0 Server=19.03.0 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/6/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   2m  0s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/7/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 17s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/8/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
OK, seems you are right.

https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/view/change-requests/job/PR-573/1/console

Here we will run all the UTs although we only modified the hbase-common module.

Let me add the skip-dirs option.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 35s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --quick-hadoopcheck --skip-errorprone  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/9/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/568 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-568/9/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
The pre commit result in #573 is fine, the skip-dirs works as expected.

Let me merge this.

**Pull request merged**
