### PR TITLE
HBASE-23129 Move core to use hbase-thirdparty-3.1.1

### PR DESCRIPTION
**Pull request by saintstack**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 14s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 44s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 44s |  master passed  |
| :green_heart: |  compile  |   3m 14s |  master passed  |
| :green_heart: |  shadedjars  |   5m  3s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   3m 13s |  master passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 24s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   5m 35s |  the patch passed  |
| :green_heart: |  compile  |   3m 17s |  the patch passed  |
| :green_heart: |  javac  |   3m 17s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| :green_heart: |  shadedjars  |   4m 56s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  17m 15s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   3m 11s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  |  10m  3s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   0m 24s |  The patch does not generate ASF License warnings.  |
|  |   |  71m 11s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.shaded.protobuf.TestProtobufUtil |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/695 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux d941bf3d7f2e 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-695/out/precommit/personality/provided.sh |
| git revision | master / 10180e232e |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/1/testReport/ |
| Max. process+thread count | 282 (vs. ulimit of 10000) |
| modules | C: hbase-common . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by petersomogyi** [comment]
HBase will use hbase-thirdparty 3.1.1 once it is released, right?

**Comment by saintstack** [comment]
Yes. Need to update this patch when it is out. Thanks for review @petersomogyi

**Comment by saintstack** [comment]
This latest push has been pointed at the just-released 3.1.1 hbase-thirdparty (Thanks @petersomogyi )

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 35s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   1m  4s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   5m 48s |  master passed  |
| :green_heart: |  compile  |   3m 14s |  master passed  |
| :green_heart: |  shadedjars  |   4m 52s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   3m 17s |  master passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 24s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   5m  9s |  the patch passed  |
| :green_heart: |  compile  |   3m  0s |  the patch passed  |
| :green_heart: |  javac  |   3m  0s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| :green_heart: |  shadedjars  |   4m 54s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  17m 38s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   3m 20s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 183m 24s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   1m  1s |  The patch does not generate ASF License warnings.  |
|  |   | 244m 30s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.TestBulkLoadReplication |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.2 Server=19.03.2 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/695 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux d86a81685945 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-695/out/precommit/personality/provided.sh |
| git revision | master / fd9cfd789b |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/2/testReport/ |
| Max. process+thread count | 4700 (vs. ulimit of 10000) |
| modules | C: hbase-common . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
Rerunning build. The failure does not look related. I tried locally and indeed it failed... but then it started passing and kept passing.  It shows in our flakey dashboard but it is not too healthy these times: https://builds.apache.org/view/H-L/view/HBase/job/HBase-Find-Flaky-Tests/job/HBASE-22514/lastSuccessfulBuild/artifact/dashboard.html

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 12s |  Docker mode activated.  |
||| _ Prechecks _ |
| :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| :yellow_heart: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 45s |  Maven dependency ordering for branch  |
| :green_heart: |  mvninstall  |   6m  7s |  master passed  |
| :green_heart: |  compile  |   3m 15s |  master passed  |
| :green_heart: |  shadedjars  |   4m 59s |  branch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  javadoc  |   3m 15s |  master passed  |
||| _ Patch Compile Tests _ |
| :blue_heart: |  mvndep  |   0m 21s |  Maven dependency ordering for patch  |
| :green_heart: |  mvninstall  |   5m 28s |  the patch passed  |
| :green_heart: |  compile  |   3m 15s |  the patch passed  |
| :green_heart: |  javac  |   3m 15s |  the patch passed  |
| :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| :green_heart: |  shadedjars  |   4m 57s |  patch has no errors when building our shaded downstream artifacts.  |
| :green_heart: |  hadoopcheck  |  17m 12s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| :green_heart: |  javadoc  |   3m 11s |  the patch passed  |
||| _ Other Tests _ |
| :broken_heart: |  unit  | 248m 38s |  root in the patch failed.  |
| :green_heart: |  asflicense  |   0m 54s |  The patch does not generate ASF License warnings.  |
|  |   | 310m 21s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.regionserver.TestBulkLoadReplication |
|   | hadoop.hbase.master.assignment.TestOpenRegionProcedureHang |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.3 Server=19.03.3 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/695 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 3eedb4ceb010 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-695/out/precommit/personality/provided.sh |
| git revision | master / fd9cfd789b |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/3/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/3/testReport/ |
| Max. process+thread count | 4758 (vs. ulimit of 10000) |
| modules | C: hbase-common . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-695/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) |
| Powered by | Apache Yetus 0.11.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by petersomogyi** [comment]
TestBulkLoadReplication is broken, it is on the flaky list now. Failure shouldn't be related to this change.

**Pull request merged**
