### PR TITLE
HBASE-23664 Upgrade JUnit to 4.13

### PR DESCRIPTION
**Pull request by ndimiduk**
Backport of #1004 to branch-1.

### CODE REVIEW

**Comment by ndimiduk** [comment]
> Doesn't seem to be a junit5 issue open. Follow-up?

https://issues.apache.org/jira/browse/HBASE-23671

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 28s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m 22s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 48s |  branch-1 passed with JDK v1.8.0_232  |
| +1 :green_heart: |  compile  |   1m 57s |  branch-1 passed with JDK v1.7.0_242  |
| +1 :green_heart: |  shadedjars  |   3m 10s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 13s |  branch-1 passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javadoc  |   4m  5s |  branch-1 passed with JDK v1.7.0_242  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 48s |  the patch passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javac  |   1m 48s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 56s |  the patch passed with JDK v1.7.0_242  |
| +1 :green_heart: |  javac  |   1m 56s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 1 ill-formed XML file(s).  |
| +1 :green_heart: |  shadedjars  |   3m  6s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   5m 11s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   2m  5s |  the patch passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javadoc  |   4m  7s |  the patch passed with JDK v1.7.0_242  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 186m 22s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 34s |  The patch does not generate ASF License warnings.  |
|  |   | 238m 52s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | pom.xml |
| Failed junit tests | hadoop.hbase.client.TestSnapshotTemporaryDirectory |
|   | hadoop.hbase.mapreduce.TestLoadIncrementalHFiles |
|   | hadoop.hbase.mapreduce.TestLoadIncrementalHFilesUseSecurityEndPoint |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |
|   | hadoop.hbase.client.replication.TestReplicationAdminWithClusters |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.regionserver.TestCompactionState |
|   | hadoop.hbase.client.TestAdmin2 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1010 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 4e1a2e21534f 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1010/out/precommit/personality/provided.sh |
| git revision | branch-1 / 6b940ae |
| Default Java | 1.7.0_242 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_232 /usr/lib/jvm/zulu-7-amd64:1.7.0_242 |
| xml | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/1/artifact/out/xml.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/1/testReport/ |
| Max. process+thread count | 3896 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/1/console |
| versions | git=1.9.1 maven=3.0.5 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by ndimiduk** [comment]
That's a lot of failures. Kicking the PR job to try again.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   7m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-1 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m 43s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   1m 42s |  branch-1 passed with JDK v1.8.0_232  |
| +1 :green_heart: |  compile  |   1m 49s |  branch-1 passed with JDK v1.7.0_242  |
| +1 :green_heart: |  shadedjars  |   2m 49s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 13s |  branch-1 passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javadoc  |   3m 46s |  branch-1 passed with JDK v1.7.0_242  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m  1s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 42s |  the patch passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javac  |   1m 42s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 45s |  the patch passed with JDK v1.7.0_242  |
| +1 :green_heart: |  javac  |   1m 45s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  1s |  The patch has 1 ill-formed XML file(s).  |
| +1 :green_heart: |  shadedjars  |   2m 43s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   5m  0s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  javadoc  |   2m  7s |  the patch passed with JDK v1.8.0_232  |
| +1 :green_heart: |  javadoc  |   3m 48s |  the patch passed with JDK v1.7.0_242  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 147m 38s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  The patch does not generate ASF License warnings.  |
|  |   | 198m 52s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | pom.xml |
| Failed junit tests | hadoop.hbase.client.TestAdmin2 |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |
|   | hadoop.hbase.regionserver.TestCompactionState |
|   | hadoop.hbase.security.token.TestGenerateDelegationToken |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.5 Server=19.03.5 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1010 |
| Optional Tests | dupname asflicense javac javadoc unit shadedjars hadoopcheck xml compile |
| uname | Linux 84529f3a5ea7 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1010/out/precommit/personality/provided.sh |
| git revision | branch-1 / 6b940ae |
| Default Java | 1.7.0_242 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_232 /usr/lib/jvm/zulu-7-amd64:1.7.0_242 |
| xml | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/2/artifact/out/xml.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/2/testReport/ |
| Max. process+thread count | 4560 (vs. ulimit of 10000) |
| modules | C: . U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1010/2/console |
| versions | git=1.9.1 maven=3.0.5 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
