### PR TITLE
HBASE-24234 ChecksumUtil class validateChecksum method log level does not match

### PR DESCRIPTION
**Pull request by xiaozhang0319**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   1m 23s |  Docker failed to build yetus/hbase:d9b4982ad4.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1564 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1564/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by xiaozhang0319** [comment]
@wchevreuil ok

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   0m 49s |  Docker failed to build yetus/hbase:d9b4982ad4.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/hbase/pull/1564 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1564/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by wchevreuil** [comment]
As pointed by @liuml07 on related jira, this has already been addressed by HBASE-23047. I had backported HBASE-23047 to branch-2.2 now, so I think we can close this PR.

**Pull request closed without merging**
