### PR TITLE
HBASE-24260 Add a ClusterManager that issues commands via coprocessor

### PR DESCRIPTION
**Pull request by bharathv**
Implements `ClusterManager` that relies on the new
`ShellExecEndpointCoprocessor` for remote shell command execution.

Signed-off-by: Bharath Vissapragada <bharathv@apache.org>

### CODE REVIEW

**Comment by bharathv** [comment]
> This is useful to your teams as well?

Yes. Nice idea :-).

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  12m 36s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 8 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 21s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  2s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 46s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  compile  |   0m 55s |  branch-1 passed with JDK v1.7.0_262  |
| +1 :green_heart: |  checkstyle  |   3m 26s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m 16s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 34s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 26s |  branch-1 passed with JDK v1.7.0_262  |
| +0 :ok: |  spotbugs  |   2m 39s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 36s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   1m 59s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 21s |  hbase-it in the patch failed with JDK v1.8.0_252.  |
| -1 :x: |  javac  |   0m 21s |  hbase-it in the patch failed with JDK v1.8.0_252.  |
| -1 :x: |  compile  |   0m 26s |  hbase-it in the patch failed with JDK v1.7.0_262.  |
| -1 :x: |  javac  |   0m 26s |  hbase-it in the patch failed with JDK v1.7.0_262.  |
| -1 :x: |  checkstyle  |   0m 31s |  hbase-it: The patch generated 2 new + 13 unchanged - 0 fixed = 15 total (was 13)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  1s |  The patch has 1 ill-formed XML file(s).  |
| +1 :green_heart: |  shadedjars  |   3m  5s |  patch has no errors when building our shaded downstream artifacts.  |
| -1 :x: |  hadoopcheck  |   1m 38s |  The patch causes 145 errors with Hadoop v2.8.5.  |
| -1 :x: |  hadoopcheck  |   4m  2s |  The patch causes 145 errors with Hadoop v2.9.2.  |
| +1 :green_heart: |  javadoc  |   0m 21s |  the patch passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 26s |  the patch passed with JDK v1.7.0_262  |
| +1 :green_heart: |  findbugs  |   2m 31s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 27s |  hbase-protocol in the patch passed.  |
| -1 :x: |  unit  |   0m 26s |  hbase-it in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 23s |  The patch does not generate ASF License warnings.  |
|  |   |  55m 26s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | hbase-protocol/pom.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.11 Server=19.03.11 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1853 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile xml |
| uname | Linux 5fbde2e93d26 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1853/out/precommit/personality/provided.sh |
| git revision | branch-1 / 4118383 |
| Default Java | 1.7.0_262 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_252 /usr/lib/jvm/zulu-7-amd64:1.7.0_262 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/patch-compile-hbase-it-jdk1.8.0_252.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/patch-compile-hbase-it-jdk1.8.0_252.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/patch-compile-hbase-it-jdk1.7.0_262.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/patch-compile-hbase-it-jdk1.7.0_262.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/diff-checkstyle-hbase-it.txt |
| xml | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/xml.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/patch-javac-2.8.5.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/patch-javac-2.9.2.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/artifact/out/patch-unit-hbase-it.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/testReport/ |
| Max. process+thread count | 76 (vs. ulimit of 10000) |
| modules | C: hbase-protocol hbase-it U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 18s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  1s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 8 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 21s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  7s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 46s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  compile  |   0m 55s |  branch-1 passed with JDK v1.7.0_262  |
| +1 :green_heart: |  checkstyle  |   3m 28s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m 16s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 34s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 26s |  branch-1 passed with JDK v1.7.0_262  |
| +0 :ok: |  spotbugs  |   2m 39s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 35s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   1m 58s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 20s |  hbase-it in the patch failed with JDK v1.8.0_252.  |
| -1 :x: |  cc  |   0m 20s |  hbase-it in the patch failed with JDK v1.8.0_252.  |
| -1 :x: |  javac  |   0m 20s |  hbase-it in the patch failed with JDK v1.8.0_252.  |
| -1 :x: |  compile  |   0m 25s |  hbase-it in the patch failed with JDK v1.7.0_262.  |
| -1 :x: |  cc  |   0m 25s |  hbase-it in the patch failed with JDK v1.7.0_262.  |
| -1 :x: |  javac  |   0m 25s |  hbase-it in the patch failed with JDK v1.7.0_262.  |
| -1 :x: |  checkstyle  |   0m 31s |  hbase-it: The patch generated 2 new + 13 unchanged - 0 fixed = 15 total (was 13)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 1 ill-formed XML file(s).  |
| +1 :green_heart: |  shadedjars  |   3m  2s |  patch has no errors when building our shaded downstream artifacts.  |
| -1 :x: |  hadoopcheck  |   1m 40s |  The patch causes 145 errors with Hadoop v2.8.5.  |
| -1 :x: |  hadoopcheck  |   3m 59s |  The patch causes 145 errors with Hadoop v2.9.2.  |
| +1 :green_heart: |  hbaseprotoc  |   0m 59s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 20s |  the patch passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 25s |  the patch passed with JDK v1.7.0_262  |
| +1 :green_heart: |  findbugs  |   2m 30s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  hbase-protocol in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  9s |  hbase-it in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 22s |  The patch does not generate ASF License warnings.  |
|  |   |  45m 50s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | hbase-protocol/pom.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.11 Server=19.03.11 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1853 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile xml cc hbaseprotoc prototool |
| uname | Linux 7e41f5c6a9bb 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1853/out/precommit/personality/provided.sh |
| git revision | branch-1 / 4118383 |
| Default Java | 1.7.0_262 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_252 /usr/lib/jvm/zulu-7-amd64:1.7.0_262 |
| mvninstall | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-mvninstall-root.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-compile-hbase-it-jdk1.8.0_252.txt |
| cc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-compile-hbase-it-jdk1.8.0_252.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-compile-hbase-it-jdk1.8.0_252.txt |
| compile | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-compile-hbase-it-jdk1.7.0_262.txt |
| cc | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-compile-hbase-it-jdk1.7.0_262.txt |
| javac | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-compile-hbase-it-jdk1.7.0_262.txt |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/diff-checkstyle-hbase-it.txt |
| xml | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/xml.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-javac-2.8.5.txt |
| hadoopcheck | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/artifact/out/patch-javac-2.9.2.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/testReport/ |
| Max. process+thread count | 472 (vs. ulimit of 10000) |
| modules | C: hbase-protocol hbase-it U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 17s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  1s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 8 new or modified test files.  |
||| _ branch-1 Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 21s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m  0s |  branch-1 passed  |
| +1 :green_heart: |  compile  |   0m 45s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  compile  |   0m 54s |  branch-1 passed with JDK v1.7.0_262  |
| +1 :green_heart: |  checkstyle  |   3m 28s |  branch-1 passed  |
| +1 :green_heart: |  shadedjars  |   3m 13s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   0m 33s |  branch-1 passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 26s |  branch-1 passed with JDK v1.7.0_262  |
| +0 :ok: |  spotbugs  |   2m 40s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 36s |  branch-1 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m  3s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 45s |  the patch passed with JDK v1.8.0_252  |
| +1 :green_heart: |  cc  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 53s |  the patch passed with JDK v1.7.0_262  |
| +1 :green_heart: |  cc  |   0m 53s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 53s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 32s |  hbase-it: The patch generated 2 new + 13 unchanged - 0 fixed = 15 total (was 13)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  xml  |   0m  0s |  The patch has 1 ill-formed XML file(s).  |
| +1 :green_heart: |  shadedjars  |   3m  5s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |   4m 50s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2.  |
| +1 :green_heart: |  hbaseprotoc  |   0m 56s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 21s |  the patch passed with JDK v1.8.0_252  |
| +1 :green_heart: |  javadoc  |   0m 26s |  the patch passed with JDK v1.7.0_262  |
| +1 :green_heart: |  findbugs  |   2m 31s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  hbase-protocol in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  8s |  hbase-it in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 23s |  The patch does not generate ASF License warnings.  |
|  |   |  48m 54s |   |


| Reason | Tests |
|-------:|:------|
| XML | Parsing Error(s): |
|   | hbase-protocol/pom.xml |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.11 Server=19.03.11 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1853 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile xml cc hbaseprotoc prototool |
| uname | Linux 7c2905baaed2 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1853/out/precommit/personality/provided.sh |
| git revision | branch-1 / d3d5276 |
| Default Java | 1.7.0_262 |
| Multi-JDK versions | /usr/lib/jvm/zulu-8-amd64:1.8.0_252 /usr/lib/jvm/zulu-7-amd64:1.7.0_262 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/3/artifact/out/diff-checkstyle-hbase-it.txt |
| xml | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/3/artifact/out/xml.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/3/testReport/ |
| Max. process+thread count | 467 (vs. ulimit of 10000) |
| modules | C: hbase-protocol hbase-it U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1853/3/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
