### PR TITLE
HBASE-23923 Set suitable forkCount when running pre commit

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache9** [comment]
Switch back to 5 forks when running large tests.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 33s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 40s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  shellcheck  |   0m  2s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +0 :ok: |  asflicense  |   0m  0s |  ASF License check generated no output?  |
|  |   |   3m 28s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1236/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1236 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 48899fdb6138 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1236/out/precommit/personality/provided.sh |
| git revision | master / f411e395d3 |
| Max. process+thread count | 47 (vs. ulimit of 10000) |
| modules | C:  U:  |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1236/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by saintstack** [comment]
Close this PR now @Apache9 ? Things have settled some?

It hardcodes fork count for second part at 5. This patch ran on a 16-core machine. Our pom says 0.5C so we use 8 CPUs at the most but IIRC, Sean was saying that infra machines are split into two -- two 'workers' (let me get confirmation) -- so 0.5C is 4 CPUs.

**Comment by saintstack** [comment]
From Sean, yeah, two executors per host but I suppose mvn sees all CPUs when it queries so we are doing a fork count of 8 rather than the 4 in the above which is more aggressive than previous but seems ok going by how things have been of late on the flakey dashboards

**Pull request closed without merging**
