### PR TITLE
HBASE-23146 Support CheckAndMutate with multiple conditions

### PR DESCRIPTION
**Pull request by brfrn169**
Signed-off-by: Duo Zhang <zhangduo@apache.org>

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 36s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  0s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 7 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 14s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   3m 35s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   3m 18s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   4m 15s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 26s |  branch-2 passed  |
| +0 :ok: |  spotbugs  |   1m 33s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |  10m 25s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 52s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 39s |  the patch passed  |
| +1 :green_heart: |  cc  |   3m 39s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 39s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 12s |  The patch passed checkstyle in hbase-protocol-shaded  |
| +1 :green_heart: |  checkstyle  |   0m 12s |  The patch passed checkstyle in hbase-protocol  |
| -1 :x: |  checkstyle  |   0m 36s |  hbase-client: The patch generated 2 new + 132 unchanged - 26 fixed = 134 total (was 158)  |
| +1 :green_heart: |  checkstyle  |   1m 19s |  hbase-server: The patch generated 0 new + 468 unchanged - 8 fixed = 468 total (was 476)  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  The patch passed checkstyle in hbase-thrift  |
| +1 :green_heart: |  checkstyle  |   0m 20s |  hbase-rest: The patch generated 0 new + 105 unchanged - 1 fixed = 105 total (was 106)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 10s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  15m 31s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  hbaseprotoc  |   3m 25s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 24s |  the patch passed  |
| +1 :green_heart: |  findbugs  |  11m 19s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 41s |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 29s |  hbase-protocol in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  1s |  hbase-client in the patch passed.  |
| -1 :x: |  unit  |  61m 28s |  hbase-server in the patch failed.  |
| +1 :green_heart: |  unit  |   2m 23s |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   3m  6s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 57s |  The patch does not generate ASF License warnings.  |
|  |   | 159m 48s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.http.TestInfoServersACL |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1209 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux f94dc0f6bde7 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1209/out/precommit/personality/provided.sh |
| git revision | branch-2 / 2c3621690d |
| Default Java | 1.8.0_181 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/1/artifact/out/diff-checkstyle-hbase-client.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/1/testReport/ |
| Max. process+thread count | 8023 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-protocol hbase-client hbase-server hbase-thrift hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/1/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 36s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  0s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 7 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 18s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   3m 41s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   3m 20s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   4m 19s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 26s |  branch-2 passed  |
| +0 :ok: |  spotbugs  |   1m 31s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |  11m 11s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 51s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 49s |  the patch passed  |
| +1 :green_heart: |  cc  |   3m 49s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 49s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 11s |  The patch passed checkstyle in hbase-protocol-shaded  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  The patch passed checkstyle in hbase-protocol  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  hbase-client: The patch generated 0 new + 132 unchanged - 26 fixed = 132 total (was 158)  |
| +1 :green_heart: |  checkstyle  |   1m 17s |  hbase-server: The patch generated 0 new + 468 unchanged - 8 fixed = 468 total (was 476)  |
| +1 :green_heart: |  checkstyle  |   0m 37s |  The patch passed checkstyle in hbase-thrift  |
| +1 :green_heart: |  checkstyle  |   0m 19s |  hbase-rest: The patch generated 0 new + 105 unchanged - 1 fixed = 105 total (was 106)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 12s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  15m 38s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  hbaseprotoc  |   3m 27s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 24s |  the patch passed  |
| +1 :green_heart: |  findbugs  |  11m 24s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 42s |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 29s |  hbase-protocol in the patch passed.  |
| +1 :green_heart: |  unit  |   2m  7s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |  61m 39s |  hbase-server in the patch passed.  |
| -1 :x: |  unit  |   2m 24s |  hbase-thrift in the patch failed.  |
| +1 :green_heart: |  unit  |   3m 10s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  asflicense  |   3m  0s |  The patch does not generate ASF License warnings.  |
|  |   | 161m 19s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.thrift.TestThriftHttpServer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1209 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux ad3a5b6da0d2 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1209/out/precommit/personality/provided.sh |
| git revision | branch-2 / 2c3621690d |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/2/artifact/out/patch-unit-hbase-thrift.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/2/testReport/ |
| Max. process+thread count | 7649 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-protocol hbase-client hbase-server hbase-thrift hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/2/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by brfrn169** [comment]
The test failure is unrelated to the patch.

**Comment by Apache9** [comment]
Could you please double check it? I think the thrift client also implements the Table interface and here you changed the table interface?

**Comment by brfrn169** [comment]
> Could you please double check it? I think the thrift client also implements the Table interface and here you changed the table interface?

Thank you for your comment. 

Yes, I changed the table interface for thrift:
https://github.com/apache/hbase/pull/1209/files#diff-a6fb426c873989cb1824233fcf574413

**Comment by ndimiduk** [comment]
Thrift test failure looks like a broken test,

```
2020-02-26 10:24:07,725 INFO  [ThriftServer-httpServer] http.HttpServer (HttpServer.java:start(1063)) - HttpServer.start() threw a non Bind IOException
java.net.BindException: Port in use: 0.0.0.0:54902
	at org.apache.hadoop.hbase.http.HttpServer.openListeners(HttpServer.java:1126)
	at org.apache.hadoop.hbase.http.HttpServer.start(HttpServer.java:1060)
	at org.apache.hadoop.hbase.http.InfoServer.start(InfoServer.java:148)
	at org.apache.hadoop.hbase.thrift.ThriftServer.startInfoServer(ThriftServer.java:308)
	at org.apache.hadoop.hbase.thrift.ThriftServer.run(ThriftServer.java:849)
	at org.apache.hadoop.hbase.thrift.TestThriftHttpServer.lambda$startHttpServerThread$0(TestThriftHttpServer.java:121)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319)
	at org.apache.hadoop.hbase.http.HttpServer.openListeners(HttpServer.java:1120)
	... 6 more
```

**Comment by ndimiduk** [comment]
Filed as https://issues.apache.org/jira/browse/HBASE-23903.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 29s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  prototool  |   0m  0s |  prototool was not available.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 7 new or modified test files.  |
||| _ branch-2 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   5m 51s |  branch-2 passed  |
| +1 :green_heart: |  compile  |   3m 41s |  branch-2 passed  |
| +1 :green_heart: |  checkstyle  |   3m 20s |  branch-2 passed  |
| +1 :green_heart: |  shadedjars  |   4m 45s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 22s |  branch-2 passed  |
| +0 :ok: |  spotbugs  |   1m 38s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |  11m 33s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 28s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 37s |  the patch passed  |
| +1 :green_heart: |  cc  |   3m 37s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m 37s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  The patch passed checkstyle in hbase-protocol-shaded  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  The patch passed checkstyle in hbase-protocol  |
| +1 :green_heart: |  checkstyle  |   0m 37s |  hbase-client: The patch generated 0 new + 132 unchanged - 26 fixed = 132 total (was 158)  |
| +1 :green_heart: |  checkstyle  |   1m 20s |  hbase-server: The patch generated 0 new + 468 unchanged - 8 fixed = 468 total (was 476)  |
| +1 :green_heart: |  checkstyle  |   0m 41s |  The patch passed checkstyle in hbase-thrift  |
| +1 :green_heart: |  checkstyle  |   0m 17s |  hbase-rest: The patch generated 0 new + 105 unchanged - 1 fixed = 105 total (was 106)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedjars  |   4m 41s |  patch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  hadoopcheck  |  17m 15s |  Patch does not cause any errors with Hadoop 2.8.5 2.9.2 or 3.1.2.  |
| +1 :green_heart: |  hbaseprotoc  |   3m 26s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   2m 21s |  the patch passed  |
| +1 :green_heart: |  findbugs  |  12m 16s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 42s |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 27s |  hbase-protocol in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 17s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  |  94m 42s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |   3m  1s |  hbase-thrift in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 23s |  hbase-rest in the patch passed.  |
| +1 :green_heart: |  asflicense  |   2m 19s |  The patch does not generate ASF License warnings.  |
|  |   | 202m  3s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.6 Server=19.03.6 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/1209 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile cc hbaseprotoc prototool |
| uname | Linux 0e8c301af863 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/Base-PreCommit-GitHub-PR_PR-1209/out/precommit/personality/provided.sh |
| git revision | branch-2 / 8b7cdc9781 |
| Default Java | 1.8.0_181 |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/3/testReport/ |
| Max. process+thread count | 5597 (vs. ulimit of 10000) |
| modules | C: hbase-protocol-shaded hbase-protocol hbase-client hbase-server hbase-thrift hbase-rest U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-1209/3/console |
| versions | git=2.11.0 maven=2018-06-17T18:33:14Z) findbugs=3.1.11 |
| Powered by | Apache Yetus 0.11.1 https://yetus.apache.org |


This message was automatically generated.

**Comment by brfrn169** [comment]
Thank you! @ndimiduk 

The last QA looks good.

**Comment by brfrn169** [comment]
@Apache9 @ndimiduk Can I push this to branch-2?

**Comment by brfrn169** [comment]
Ping @Apache9 @ndimiduk. Please take a look at this when you get a chance?

**Comment by brfrn169** [comment]
Merged. Thank you! @Apache9

**Pull request merged**
