### PR TITLE
HBASE-26804 Missing opentelemetry agent in hadoop-two-compat.xml

### PR DESCRIPTION
**Pull request by taklwu**

### CODE REVIEW

**Comment by taklwu** [comment]
see the original commit in master here https://github.com/apache/hbase/commit/8d2a0efb7a9c17e58892369b281b4af49a5f0d7e and this PR is porting the change in [hadoop-three-compat.xml](https://github.com/apache/hbase/commit/8d2a0efb7a9c17e58892369b281b4af49a5f0d7e#diff-3245893b838247ac80130558cebcbbb4d3fb8346c4290a127314be8d965b18ac) to hadoop-two-compat.xml

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 50s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  4s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 51s |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 17s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   2m 19s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 14s |  hbase-assembly in the patch passed.  |
|  |   |   8m 43s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4185/1/artifact/yetus-jdk8-hadoop2-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4185 |
| Optional Tests | javac javadoc unit |
| uname | Linux daecaf97109c 5.4.0-1043-aws #45~18.04.1-Ubuntu SMP Fri Apr 9 23:32:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 98836fb2b4 |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4185/1/testReport/ |
| Max. process+thread count | 44 (vs. ulimit of 12500) |
| modules | C: hbase-assembly U: hbase-assembly |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4185/1/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 22s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  3s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ branch-2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 23s |  branch-2 passed  |
| +1 :green_heart: |  javadoc  |   0m 13s |  branch-2 passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 13s |  the patch passed  |
| +1 :green_heart: |  javadoc  |   0m 12s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 21s |  hbase-assembly in the patch passed.  |
|  |   |   9m 47s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4185/1/artifact/yetus-jdk11-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/4185 |
| Optional Tests | javac javadoc unit |
| uname | Linux b5a4072a3d72 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | branch-2 / 98836fb2b4 |
| Default Java | AdoptOpenJDK-11.0.10+9 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4185/1/testReport/ |
| Max. process+thread count | 59 (vs. ulimit of 12500) |
| modules | C: hbase-assembly U: hbase-assembly |
| Console output | https://ci-hbase.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-4185/1/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ndimiduk — APPROVED** [review]
Looks right to me. I don't have a simple means of testing it, can I assume you've got that covered, @taklwu ?

**Comment by taklwu** [comment]
I had an internal runtime was using but for this PR, I checked if the jar exists within the tar.gz that should be proving the agent has been included as part of the classpath.

```
# build the assembly tar bar with the default hadoop2 profile
% mvn clean install -DskipTests -Dcheckstyle.skip=true site assembly:single -Prelease

# go into the assembly output directory
$ cd hbase-assembly/target
% pwd
/Users/taklwu/workspace/hbase2/hbase-assembly/target

# unzip the tar bin and client ball
% tar -zxvf hbase-2.6.0-SNAPSHOT-bin.tar.gz
% tar -zxvf hbase-2.6.0-SNAPSHOT-client-bin.tar.gz

# verify the client exists
% ls -l hbase-2.6.0-SNAPSHOT/lib/trace/opentelemetry-javaagent-1.0.1-all.jar
-rw-r--r--  1 taklwu  staff  26478003 Jan 22  2020 hbase-2.6.0-SNAPSHOT/lib/trace/opentelemetry-javaagent-1.0.1-all.jar
% ls -l hbase-2.6.0-SNAPSHOT-client/lib/trace/*
-rw-r--r--  1 taklwu  staff  26478003 Jan 22  2020 hbase-2.6.0-SNAPSHOT-client/lib/trace/opentelemetry-javaagent-1.0.1-all.jar
```

**Review by Apache9 — APPROVED** [review]

**Review by ndimiduk — APPROVED** [review]

**Pull request merged**
