### PR TITLE
HBASE-22189 Removed remaining usage of StoreFile.getModificationTimeStamp

### PR DESCRIPTION
**Pull request by HorizonNet**
Moved the remaining usage of `StoreFile.getModificationTimeStamp` to `StoreFile.getModificationTimestamp`.

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 27 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| -0 | test4tests | 0 | The patch doesn't appear to include any new or modified tests.  Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch. |
||| _ master Compile Tests _ |
| +1 | mvninstall | 302 | master passed |
| +1 | javadoc | 34 | master passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 253 | the patch passed |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | javadoc | 30 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 8405 | hbase-server in the patch failed. |
| +1 | asflicense | 22 | The patch does not generate ASF License warnings. |
| | | 9141 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.locking.TestLockManager |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-129/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/129 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  |
| uname | Linux 8fb385828517 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | master / a871d3139a |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-129/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-129/1/testReport/ |
| Max. process+thread count | 4793 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-129/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by HorizonNet** [comment]
The failing test case seems to be unrelated to the actual change.

**Comment by Apache9** [comment]
@HorizonNet Please merge this and also cherry-pick to other branches if necessary? You're a commit so you should have the permission to do so.

**Comment by Apache9** [comment]
And make sure to use 'rebase and merge'...

Thanks.

**Pull request merged**
