### PR TITLE
HBASE-22623 - Add RegionObserver coprocessor hook for preWALAppend

### PR DESCRIPTION
**Pull request by gjacoby126**
This is the branch-1 backport of PR #390 , for HBASE-22623. Since it's a slightly non-trivial backport, opening up a separate PR for ease of review / chance for HBase Robot to pass judgement.

### CODE REVIEW

**Comment by gjacoby126** [comment]
@apurtell @Apache9 @anoopsjohn , fyi. The branch-1 backport.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 73 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 600 | branch-1 passed |
| +1 | compile | 57 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 55 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 126 | branch-1 passed |
| +1 | shadedjars | 217 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 47 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 49 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 220 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 216 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 143 | the patch passed |
| +1 | compile | 51 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 51 | the patch passed |
| +1 | compile | 54 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 54 | the patch passed |
| -1 | checkstyle | 114 | hbase-server: The patch generated 1 new + 636 unchanged - 1 fixed = 637 total (was 637) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 220 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 357 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 40 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 50 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 215 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 9456 | hbase-server in the patch failed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 12423 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.client.TestAdmin1 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/470 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 519955c246bd 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-470/out/precommit/personality/provided.sh |
| git revision | branch-1 / e7114f7 |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/2/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/2/testReport/ |
| Max. process+thread count | 4179 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/2/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 1206 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | dupname | 0 | No case conflicting files found. |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 2 new or modified test files. |
||| _ branch-1 Compile Tests _ |
| +1 | mvninstall | 554 | branch-1 passed |
| +1 | compile | 41 | branch-1 passed with JDK v1.8.0_222 |
| +1 | compile | 45 | branch-1 passed with JDK v1.7.0_232 |
| +1 | checkstyle | 101 | branch-1 passed |
| +1 | shadedjars | 181 | branch has no errors when building our shaded downstream artifacts. |
| +1 | javadoc | 40 | branch-1 passed with JDK v1.8.0_222 |
| +1 | javadoc | 40 | branch-1 passed with JDK v1.7.0_232 |
| 0 | spotbugs | 180 | Used deprecated FindBugs config; considering switching to SpotBugs. |
| +1 | findbugs | 177 | branch-1 passed |
||| _ Patch Compile Tests _ |
| +1 | mvninstall | 110 | the patch passed |
| +1 | compile | 38 | the patch passed with JDK v1.8.0_222 |
| +1 | javac | 38 | the patch passed |
| +1 | compile | 42 | the patch passed with JDK v1.7.0_232 |
| +1 | javac | 42 | the patch passed |
| -1 | checkstyle | 95 | hbase-server: The patch generated 1 new + 636 unchanged - 1 fixed = 637 total (was 637) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 167 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 304 | Patch does not cause any errors with Hadoop 2.8.5 2.9.2. |
| +1 | javadoc | 31 | the patch passed with JDK v1.8.0_222 |
| +1 | javadoc | 40 | the patch passed with JDK v1.7.0_232 |
| +1 | findbugs | 181 | the patch passed |
||| _ Other Tests _ |
| -1 | unit | 9446 | hbase-server in the patch failed. |
| +1 | asflicense | 30 | The patch does not generate ASF License warnings. |
| | | 13097 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.TestMasterBalanceThrottling |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/470 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs shadedjars hadoopcheck hbaseanti checkstyle compile |
| uname | Linux 0eeb20ca9e17 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /home/jenkins/jenkins-slave/workspace/HBase-PreCommit-GitHub-PR_PR-470/out/precommit/personality/provided.sh |
| git revision | branch-1 / e7114f7 |
| Default Java | 1.7.0_232 |
| Multi-JDK versions | /usr/lib/jvm/java-8-openjdk-amd64:1.8.0_222 /usr/lib/jvm/java-7-openjdk-amd64:1.7.0_232 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/1/artifact/out/diff-checkstyle-hbase-server.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/1/testReport/ |
| Max. process+thread count | 4992 (vs. ulimit of 10000) |
| modules | C: hbase-server U: hbase-server |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-470/1/console |
| versions | git=1.9.1 maven=3.0.5 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.10.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by apurtell** [comment]
TestMasterBalanceThrottling is showing up in a couple of PRs, passes locally.

**Pull request merged**
