### PR TITLE
test github vote

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   1m 25s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --jenkins --quick-hadoopcheck --skip-errorprone --skip-dir  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-533/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/533 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-533/1/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
I just tried the master branch, so the vote table is fine but we have something wrong with the flags...

`-quick-hadoopcheck --skip-errorprone` should be introduced by HBase, this means we failed to load the personality?

Ping @busbey

**Comment by busbey** [comment]
The personality has to be updated to say it used those parameters. The release notes for the 0.11.0  RC should have instructions.

**Comment by busbey** [comment]
And the `--jenkins` flag hasn't existed for awhile. Yetus just detects if it is running on Jenkins.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| :blue_heart: |  reexec  |   0m 46s |  Docker mode activated.  |
| :broken_heart: |  yetus  |   0m  6s |  Unprocessed flag(s): --jenkins --quick-hadoopcheck --skip-errorprone --skip-dir  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=19.03.1 Server=19.03.1 base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-533/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/533 |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-533/2/console |
| versions | git=2.11.0 |
| Powered by | Apache Yetus 0.12.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
OK, is it YETUS-873? Let me take a look on how to make use of the `delete_parameter` method.

**Pull request closed without merging**
