### PR TITLE
HBASE-26271: Cleanup the broken store files under data directory

### PR DESCRIPTION
**Pull request by BukrosSzabolcs**
Add new chore to delete lefotver files in case file based storefile
handling is used
Expose the target files of currently running compactions for easier
validation
Store chore metrics on RS and push them for aggregation to Master
Add a new REST endpoint to get chore metrics from Master

### CODE REVIEW

**Comment by Apache9** [comment]
Hi @BukrosSzabolcs , you need to rebase your PR as I have done a force push to HBASE-26067 to include HBASE-26348 so @GeorryHuang could implement HBASE-26263.

Sorry for the inconvenience.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 26s |  Docker mode activated.  |
| -0 :warning: |  yetus  |   0m  5s |  Unprocessed flag(s): --brief-report-file --spotbugs-strict-precheck --whitespace-eol-ignore-list --whitespace-tabs-ignore-list --quick-hadoopcheck  |
||| _ Prechecks _ |
||| _ HBASE-26067 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   4m  1s |  HBASE-26067 passed  |
| +1 :green_heart: |  compile  |   3m  2s |  HBASE-26067 passed  |
| +1 :green_heart: |  shadedjars  |   8m 13s |  branch has no errors when building our shaded downstream artifacts.  |
| +1 :green_heart: |  javadoc  |   1m 57s |  HBASE-26067 passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   3m 50s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  3s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m  4s |  the patch passed  |
| -1 :x: |  shadedjars  |   3m 47s |  patch has 10 errors when building our shaded downstream artifacts.  |
| -0 :warning: |  javadoc  |   0m 24s |  hbase-client generated 1 new + 3 unchanged - 0 fixed = 4 total (was 3)  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 48s |  hbase-protocol-shaded in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 39s |  hbase-hadoop-compat in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 24s |  hbase-client in the patch passed.  |
| +1 :green_heart: |  unit  | 157m 47s |  hbase-server in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 29s |  hbase-rest in the patch passed.  |
|  |   | 199m  3s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3751/2/artifact/yetus-jdk8-hadoop3-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/3751 |
| JIRA Issue | HBASE-26271 |
| Optional Tests | javac javadoc unit shadedjars compile |
| uname | Linux af04fe3e5953 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/hbase-personality.sh |
| git revision | HBASE-26067 / d3556bf41f |
| Default Java | AdoptOpenJDK-1.8.0_282-b08 |
| shadedjars | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3751/2/artifact/yetus-jdk8-hadoop3-check/output/patch-shadedjars.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3751/2/artifact/yetus-jdk8-hadoop3-check/output/diff-javadoc-javadoc-hbase-client.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3751/2/testReport/ |
| Max. process+thread count | 4943 (vs. ulimit of 30000) |
| modules | C: hbase-protocol-shaded hbase-hadoop-compat hbase-client hbase-server hbase-rest U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-PreCommit-GitHub-PR/job/PR-3751/2/console |
| versions | git=2.17.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
HBASE-26386 has been merged so you need to rebase here @BukrosSzabolcs

**Comment by Apache9** [comment]
OK, no problem, no need to rebase then. Let's start with smaller PRs.

Thanks.

**Pull request closed without merging**
