### PR TITLE
HBASE-21937 Make the Compression#decompress can accept ByteBuff as input

### PR DESCRIPTION
**Pull request by openinx**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 48 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ HBASE-21879 Compile Tests _ |
| 0 | mvndep | 26 | Maven dependency ordering for branch |
| +1 | mvninstall | 314 | HBASE-21879 passed |
| +1 | compile | 91 | HBASE-21879 passed |
| +1 | checkstyle | 109 | HBASE-21879 passed |
| +1 | shadedjars | 330 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 242 | HBASE-21879 passed |
| +1 | javadoc | 64 | HBASE-21879 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 18 | Maven dependency ordering for patch |
| +1 | mvninstall | 303 | the patch passed |
| +1 | compile | 91 | the patch passed |
| +1 | javac | 91 | the patch passed |
| -1 | checkstyle | 29 | hbase-common: The patch generated 1 new + 8 unchanged - 1 fixed = 9 total (was 9) |
| +1 | checkstyle | 86 | hbase-server: The patch generated 0 new + 26 unchanged - 1 fixed = 26 total (was 27) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 332 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 649 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 267 | the patch passed |
| +1 | javadoc | 64 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 188 | hbase-common in the patch passed. |
| -1 | unit | 1952 | hbase-server in the patch failed. |
| +1 | asflicense | 32 | The patch does not generate ASF License warnings. |
| | | 5341 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.io.hfile.TestHFileEncryption |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/127 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux c090ace12cf9 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | HBASE-21879 / c70acf9ed4 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/1/artifact/out/diff-checkstyle-hbase-common.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/1/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/1/testReport/ |
| Max. process+thread count | 757 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/1/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
Is the failed UT related?

**Comment by openinx** [comment]
@Apache9  Yes, it's related.  will update the PR.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| 0 | reexec | 43 | Docker mode activated. |
||| _ Prechecks _ |
| +1 | hbaseanti | 0 |  Patch does not have any anti-patterns. |
| +1 | @author | 0 | The patch does not contain any @author tags. |
| +1 | test4tests | 0 | The patch appears to include 3 new or modified test files. |
||| _ HBASE-21879 Compile Tests _ |
| 0 | mvndep | 14 | Maven dependency ordering for branch |
| +1 | mvninstall | 247 | HBASE-21879 passed |
| +1 | compile | 71 | HBASE-21879 passed |
| +1 | checkstyle | 92 | HBASE-21879 passed |
| +1 | shadedjars | 258 | branch has no errors when building our shaded downstream artifacts. |
| +1 | findbugs | 180 | HBASE-21879 passed |
| +1 | javadoc | 52 | HBASE-21879 passed |
||| _ Patch Compile Tests _ |
| 0 | mvndep | 15 | Maven dependency ordering for patch |
| +1 | mvninstall | 256 | the patch passed |
| +1 | compile | 72 | the patch passed |
| +1 | javac | 72 | the patch passed |
| -1 | checkstyle | 22 | hbase-common: The patch generated 1 new + 8 unchanged - 1 fixed = 9 total (was 9) |
| +1 | checkstyle | 69 | hbase-server: The patch generated 0 new + 26 unchanged - 1 fixed = 26 total (was 27) |
| +1 | whitespace | 0 | The patch has no whitespace issues. |
| +1 | shadedjars | 259 | patch has no errors when building our shaded downstream artifacts. |
| +1 | hadoopcheck | 494 | Patch does not cause any errors with Hadoop 2.7.4 or 3.0.0. |
| +1 | findbugs | 203 | the patch passed |
| +1 | javadoc | 54 | the patch passed |
||| _ Other Tests _ |
| +1 | unit | 164 | hbase-common in the patch passed. |
| -1 | unit | 17397 | hbase-server in the patch failed. |
| +1 | asflicense | 59 | The patch does not generate ASF License warnings. |
| | | 20114 | |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.hbase.master.TestSplitWALManager |
|   | hadoop.hbase.client.TestSnapshotTemporaryDirectoryWithRegionReplicas |
|   | hadoop.hbase.client.TestFromClientSide |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicas |
|   | hadoop.hbase.client.TestAdmin1 |
|   | hadoop.hbase.TestSplitMerge |
|   | hadoop.hbase.client.TestFromClientSide3 |
|   | hadoop.hbase.client.TestFromClientSideWithCoprocessor |
|   | hadoop.hbase.client.TestSnapshotDFSTemporaryDirectory |
|   | hadoop.hbase.master.procedure.TestSCPWithReplicasWithoutZKCoordinated |
|   | hadoop.hbase.client.TestAsyncTableGetMultiThreaded |
|   | hadoop.hbase.replication.multiwal.TestReplicationSyncUpToolWithMultipleAsyncWAL |
|   | hadoop.hbase.regionserver.TestSplitTransactionOnCluster |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | Client=17.05.0-ce Server=17.05.0-ce base: https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase/pull/127 |
| Optional Tests |  dupname  asflicense  javac  javadoc  unit  findbugs  shadedjars  hadoopcheck  hbaseanti  checkstyle  compile  |
| uname | Linux 559cb7044fc3 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | /testptch/patchprocess/precommit/personality/provided.sh |
| git revision | HBASE-21879 / c70acf9ed4 |
| maven | version: Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z) |
| Default Java | 1.8.0_181 |
| findbugs | v3.1.11 |
| checkstyle | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/2/artifact/out/diff-checkstyle-hbase-common.txt |
| unit | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/2/artifact/out/patch-unit-hbase-server.txt |
|  Test Results | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/2/testReport/ |
| Max. process+thread count | 5293 (vs. ulimit of 10000) |
| modules | C: hbase-common hbase-server U: . |
| Console output | https://builds.apache.org/job/HBase-PreCommit-GitHub-PR/job/PR-127/2/console |
| Powered by | Apache Yetus 0.9.0 http://yetus.apache.org |


This message was automatically generated.

**Comment by openinx** [comment]
Out of date now, let's see the patch in RB.

**Pull request closed without merging**
